.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.4 */

nonmatching D_80088720

dlabel D_80088720
    /* 22D1E0 80088720 00000000 */ .word 0x00000000
enddlabel D_80088720

nonmatching D_80088724

dlabel D_80088724
    /* 22D1E4 80088724 00000000 */ .float 0
    /* 22D1E8 80088728 00000000 */ .float 0
    /* 22D1EC 8008872C 00000000 */ .float 0
enddlabel D_80088724
