.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.4 */

nonmatching D_80088910

dlabel D_80088910
    /* 22D3D0 80088910 00000000 */ .word 0x00000000
    /* 22D3D4 80088914 C2040000 */ .word 0xC2040000
    /* 22D3D8 80088918 42200000 */ .word 0x42200000
enddlabel D_80088910

nonmatching D_8008891C

dlabel D_8008891C
    /* 22D3DC 8008891C 00000000 */ .word 0x00000000
    /* 22D3E0 80088920 C2940000 */ .word 0xC2940000
    /* 22D3E4 80088924 42C40000 */ .word 0x42C40000
enddlabel D_8008891C

nonmatching D_80088928

dlabel D_80088928
    /* 22D3E8 80088928 0000000F */ .word 0x0000000F
enddlabel D_80088928

nonmatching D_8008892C

dlabel D_8008892C
    /* 22D3EC 8008892C 3DDD2F1B */ .float 0.1080000028
enddlabel D_8008892C
