.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.4 */

nonmatching D_80088B90

dlabel D_80088B90
    /* 22D650 80088B90 */ .byte 0x09
    /* 22D651 80088B91 */ .byte 0x00
    /* 22D652 80088B92 */ .byte 0x00
    /* 22D653 80088B93 */ .byte 0x00
enddlabel D_80088B90

nonmatching D_80088B94

dlabel D_80088B94
    /* 22D654 80088B94 */ .byte 0x09
    /* 22D655 80088B95 */ .byte 0x00
    /* 22D656 80088B96 */ .byte 0x00
    /* 22D657 80088B97 */ .byte 0x00
    /* 22D658 80088B98 */ .byte 0x00
    /* 22D659 80088B99 */ .byte 0x00
    /* 22D65A 80088B9A */ .byte 0x00
    /* 22D65B 80088B9B */ .byte 0x00
    /* 22D65C 80088B9C */ .byte 0x00
    /* 22D65D 80088B9D */ .byte 0x00
    /* 22D65E 80088B9E */ .byte 0x00
    /* 22D65F 80088B9F */ .byte 0x00
enddlabel D_80088B94
