.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.4 */

nonmatching D_80088BA0

dlabel D_80088BA0
    /* 22D660 80088BA0 */ .byte 0x09
    /* 22D661 80088BA1 */ .byte 0x00
    /* 22D662 80088BA2 */ .byte 0x00
    /* 22D663 80088BA3 */ .byte 0x00
    /* 22D664 80088BA4 */ .byte 0x00
    /* 22D665 80088BA5 */ .byte 0x00
    /* 22D666 80088BA6 */ .byte 0x00
    /* 22D667 80088BA7 */ .byte 0x00
    /* 22D668 80088BA8 */ .byte 0x00
    /* 22D669 80088BA9 */ .byte 0x00
    /* 22D66A 80088BAA */ .byte 0x00
    /* 22D66B 80088BAB */ .byte 0x00
    /* 22D66C 80088BAC */ .byte 0x00
    /* 22D66D 80088BAD */ .byte 0x00
    /* 22D66E 80088BAE */ .byte 0x00
    /* 22D66F 80088BAF */ .byte 0x00
enddlabel D_80088BA0
