.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.4 */

nonmatching D_80089260

dlabel D_80089260
    /* 22DD20 80089260 */ .short 0x0000
enddlabel D_80089260

nonmatching D_80089262

dlabel D_80089262
    /* 22DD22 80089262 */ .short 0x0000
enddlabel D_80089262

nonmatching D_80089264

dlabel D_80089264
    /* 22DD24 80089264 */ .short 0x0000
    /* 22DD26 80089266 */ .short 0x0000
enddlabel D_80089264

nonmatching D_80089268

dlabel D_80089268
    /* 22DD28 80089268 */ .short 0x0000
    /* 22DD2A 8008926A */ .short 0x0000
    /* 22DD2C 8008926C */ .short 0x04B5
    /* 22DD2E 8008926E */ .short 0x04B6
    /* 22DD30 80089270 */ .short 0x0000
    /* 22DD32 80089272 */ .short 0x04B7
    /* 22DD34 80089274 */ .short 0x0000
    /* 22DD36 80089276 */ .short 0x0000
    /* 22DD38 80089278 */ .short 0x04B8
    /* 22DD3A 8008927A */ .short 0x04B8
    /* 22DD3C 8008927C */ .short 0x04B9
    /* 22DD3E 8008927E */ .short 0x04B9
    /* 22DD40 80089280 */ .short 0x0000
    /* 22DD42 80089282 */ .short 0x0000
    /* 22DD44 80089284 */ .short 0x04C1
    /* 22DD46 80089286 */ .short 0x04C2
    /* 22DD48 80089288 */ .short 0xFFFF
    /* 22DD4A 8008928A */ .short 0x04C3
    /* 22DD4C 8008928C */ .short 0x0000
    /* 22DD4E 8008928E */ .short 0x0000
    /* 22DD50 80089290 */ .short 0x0361
    /* 22DD52 80089292 */ .short 0x0361
    /* 22DD54 80089294 */ .short 0x04C1
    /* 22DD56 80089296 */ .short 0x04C1
    /* 22DD58 80089298 */ .short 0x0000
    /* 22DD5A 8008929A */ .short 0x0000
    /* 22DD5C 8008929C */ .short 0x04BC
    /* 22DD5E 8008929E */ .short 0x04BC
    /* 22DD60 800892A0 */ .short 0x0000
    /* 22DD62 800892A2 */ .short 0x0000
    /* 22DD64 800892A4 */ .short 0x04BD
    /* 22DD66 800892A6 */ .short 0x001E
    /* 22DD68 800892A8 */ .short 0x0000
    /* 22DD6A 800892AA */ .short 0x0000
    /* 22DD6C 800892AC */ .short 0x0082
    /* 22DD6E 800892AE */ .short 0x0082
    /* 22DD70 800892B0 */ .short 0x0000
    /* 22DD72 800892B2 */ .short 0x0000
    /* 22DD74 800892B4 */ .short 0x04BE
    /* 22DD76 800892B6 */ .short 0x04BF
    /* 22DD78 800892B8 */ .short 0x04C0
    /* 22DD7A 800892BA */ .short 0x0000
    /* 22DD7C 800892BC */ .short 0x0000
    /* 22DD7E 800892BE */ .short 0x0000
    /* 22DD80 800892C0 */ .short 0x04BF
    /* 22DD82 800892C2 */ .short 0x04BF
    /* 22DD84 800892C4 */ .short 0xFFFF
    /* 22DD86 800892C6 */ .short 0x0000
    /* 22DD88 800892C8 */ .short 0x0000
    /* 22DD8A 800892CA */ .short 0x0000
    /* 22DD8C 800892CC */ .short 0x04C2
    /* 22DD8E 800892CE */ .short 0x04C2
    /* 22DD90 800892D0 */ .short 0xFFFF
    /* 22DD92 800892D2 */ .short 0xFFFF
    /* 22DD94 800892D4 */ .short 0x0000
    /* 22DD96 800892D6 */ .short 0x0000
    /* 22DD98 800892D8 */ .short 0x04C4
    /* 22DD9A 800892DA */ .short 0x04C5
    /* 22DD9C 800892DC */ .short 0xFFFF
    /* 22DD9E 800892DE */ .short 0xFFFF
    /* 22DDA0 800892E0 */ .short 0x0000
    /* 22DDA2 800892E2 */ .short 0x0000
    /* 22DDA4 800892E4 */ .short 0x001A
    /* 22DDA6 800892E6 */ .short 0x04C5
    /* 22DDA8 800892E8 */ .short 0xFFFF
    /* 22DDAA 800892EA */ .short 0xFFFF
    /* 22DDAC 800892EC */ .short 0x0000
    /* 22DDAE 800892EE */ .short 0x0000
    /* 22DDB0 800892F0 */ .short 0x04BA
    /* 22DDB2 800892F2 */ .short 0x0000
    /* 22DDB4 800892F4 */ .short 0x04BB
    /* 22DDB6 800892F6 */ .short 0x0000
    /* 22DDB8 800892F8 */ .short 0x0000
    /* 22DDBA 800892FA */ .short 0x0000
    /* 22DDBC 800892FC */ .short 0x004B
    /* 22DDBE 800892FE */ .short 0x004B
    /* 22DDC0 80089300 */ .short 0x04C8
    /* 22DDC2 80089302 */ .short 0x04C8
    /* 22DDC4 80089304 */ .short 0x0000
    /* 22DDC6 80089306 */ .short 0x0000
    /* 22DDC8 80089308 */ .short 0x067B
    /* 22DDCA 8008930A */ .short 0x067B
    /* 22DDCC 8008930C */ .short 0x04C8
    /* 22DDCE 8008930E */ .short 0x04C8
    /* 22DDD0 80089310 */ .short 0x0000
    /* 22DDD2 80089312 */ .short 0x0000
    /* 22DDD4 80089314 */ .short 0x062C
    /* 22DDD6 80089316 */ .short 0x062C
    /* 22DDD8 80089318 */ .short 0x04C2
    /* 22DDDA 8008931A */ .short 0x04C2
    /* 22DDDC 8008931C */ .short 0x0000
    /* 22DDDE 8008931E */ .short 0x0000
enddlabel D_80089268
