.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.4 */

nonmatching D_8008A1D0

dlabel D_8008A1D0
    /* 22EC90 8008A1D0 E7000000 */ .word 0xE7000000
    /* 22EC94 8008A1D4 00000000 */ .word 0x00000000
    /* 22EC98 8008A1D8 DA380003 */ .word 0xDA380003
    /* 22EC9C 8008A1DC 80089470 */ .word D_80089470
    /* 22ECA0 8008A1E0 D7000002 */ .word 0xD7000002
    /* 22ECA4 8008A1E4 80008000 */ .word 0x80008000
    /* 22ECA8 8008A1E8 DF000000 */ .word 0xDF000000
    /* 22ECAC 8008A1EC 00000000 */ .word 0x00000000
enddlabel D_8008A1D0
