.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.4 */

nonmatching D_8008F870

dlabel D_8008F870
    /* 234330 8008F870 151979F8 */ .word func_151979F8
    /* 234334 8008F874 15197A0C */ .word func_15197A0C
    /* 234338 8008F878 15197A68 */ .word func_15197A68
enddlabel D_8008F870

nonmatching D_8008F87C

dlabel D_8008F87C
    /* 23433C 8008F87C 151993E4 */ .word func_151993E4
enddlabel D_8008F87C

nonmatching D_8008F880

dlabel D_8008F880
    /* 234340 8008F880 15198570 */ .word func_15198570
    /* 234344 8008F884 1519897C */ .word func_1519897C
    /* 234348 8008F888 151987CC */ .word func_151987CC
enddlabel D_8008F880

nonmatching D_8008F88C

dlabel D_8008F88C
    /* 23434C 8008F88C 1519944C */ .word func_1519944C
enddlabel D_8008F88C

nonmatching D_8008F890

dlabel D_8008F890
    /* 234350 8008F890 15198C60 */ .word func_15198C60
enddlabel D_8008F890

nonmatching D_8008F894

dlabel D_8008F894
    /* 234354 8008F894 15198C90 */ .word func_15198C90
enddlabel D_8008F894

nonmatching D_8008F898

dlabel D_8008F898
    /* 234358 8008F898 15198D40 */ .word func_15198D40
enddlabel D_8008F898

nonmatching D_8008F89C

dlabel D_8008F89C
    /* 23435C 8008F89C 15198D7C */ .word func_15198D7C
enddlabel D_8008F89C

nonmatching D_8008F8A0

dlabel D_8008F8A0
    /* 234360 8008F8A0 15161700 */ .word 0x15161700
enddlabel D_8008F8A0

nonmatching D_8008F8A4

dlabel D_8008F8A4
    /* 234364 8008F8A4 1519BEB8 */ .word func_1519BEB8
enddlabel D_8008F8A4

nonmatching D_8008F8A8

dlabel D_8008F8A8
    /* 234368 8008F8A8 1519C948 */ .word func_1519C948
    /* 23436C 8008F8AC 1519C970 */ .word func_1519C970
    /* 234370 8008F8B0 1519C998 */ .word func_1519C998
enddlabel D_8008F8A8

nonmatching D_8008F8B4

dlabel D_8008F8B4
    /* 234374 8008F8B4 1519BF20 */ .word func_1519BF20
enddlabel D_8008F8B4

nonmatching D_8008F8B8

dlabel D_8008F8B8
    /* 234378 8008F8B8 1519BF8C */ .word func_1519BF8C
enddlabel D_8008F8B8

nonmatching D_8008F8BC

dlabel D_8008F8BC
    /* 23437C 8008F8BC 1519BFBC */ .word func_1519BFBC
enddlabel D_8008F8BC

nonmatching D_8008F8C0

dlabel D_8008F8C0
    /* 234380 8008F8C0 1519C06C */ .word func_1519C06C
enddlabel D_8008F8C0

nonmatching D_8008F8C4

dlabel D_8008F8C4
    /* 234384 8008F8C4 1519C910 */ .word func_1519C910
    /* 234388 8008F8C8 00000000 */ .word 0x00000000
    /* 23438C 8008F8CC 00000000 */ .word 0x00000000
enddlabel D_8008F8C4
