.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.4 */

nonmatching D_8008F900

dlabel D_8008F900
    /* 2343C0 8008F900 151A5170 */ .word func_151A5170
enddlabel D_8008F900

nonmatching D_8008F904

dlabel D_8008F904
    /* 2343C4 8008F904 00000000 */ .word 0x00000000
    /* 2343C8 8008F908 151CBB6C */ .word func_151CBB6C
    /* 2343CC 8008F90C 00000000 */ .word 0x00000000
enddlabel D_8008F904
