.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.4 */

nonmatching D_8008FBA0

dlabel D_8008FBA0
    /* 234660 8008FBA0 0000002D */ .word 0x0000002D
    /* 234664 8008FBA4 0000002E */ .word 0x0000002E
    /* 234668 8008FBA8 0000002A */ .word 0x0000002A
enddlabel D_8008FBA0

nonmatching D_8008FBAC

dlabel D_8008FBAC
    /* 23466C 8008FBAC 3F800000 */ .word 0x3F800000
    /* 234670 8008FBB0 3F800000 */ .word 0x3F800000
    /* 234674 8008FBB4 3F800000 */ .word 0x3F800000
    /* 234678 8008FBB8 00000000 */ .word 0x00000000
    /* 23467C 8008FBBC 00000000 */ .word 0x00000000
enddlabel D_8008FBAC
