.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.4 */

nonmatching D_8008FBD0

dlabel D_8008FBD0
    /* 234690 8008FBD0 151C2F48 */ .word func_151C2F48
    /* 234694 8008FBD4 150E4010 */ .word func_150E4010
    /* 234698 8008FBD8 150E411C */ .word func_150E411C
    /* 23469C 8008FBDC 150EC45C */ .word func_150EC45C
    /* 2346A0 8008FBE0 150FC368 */ .word func_150FC368
    /* 2346A4 8008FBE4 1510558C */ .word func_1510558C
enddlabel D_8008FBD0

nonmatching D_8008FBE8

dlabel D_8008FBE8
    /* 2346A8 8008FBE8 */ .short 0x0327
    /* 2346AA 8008FBEA */ .short 0x0028
    /* 2346AC 8008FBEC */ .short 0x0328
    /* 2346AE 8008FBEE */ .short 0x001E
    /* 2346B0 8008FBF0 */ .short 0x0329
    /* 2346B2 8008FBF2 */ .short 0x003C
    /* 2346B4 8008FBF4 */ .short 0x032A
    /* 2346B6 8008FBF6 */ .short 0x0014
    /* 2346B8 8008FBF8 */ .short 0x032B
    /* 2346BA 8008FBFA */ .short 0x000F
    /* 2346BC 8008FBFC */ .short 0x0320
    /* 2346BE 8008FBFE */ .short 0x0005
    /* 2346C0 8008FC00 */ .short 0x0321
    /* 2346C2 8008FC02 */ .short 0x0005
    /* 2346C4 8008FC04 */ .short 0x0322
    /* 2346C6 8008FC06 */ .short 0x0005
    /* 2346C8 8008FC08 */ .short 0x0000
    /* 2346CA 8008FC0A */ .short 0x0000
    /* 2346CC 8008FC0C */ .short 0x0000
    /* 2346CE 8008FC0E */ .short 0x0000
enddlabel D_8008FBE8
