.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.4 */

nonmatching D_80096920

dlabel D_80096920
    /* 23B3E0 80096920 */ .byte 0x04
    /* 23B3E1 80096921 */ .byte 0x04
    /* 23B3E2 80096922 */ .byte 0x03
    /* 23B3E3 80096923 */ .byte 0x03
    /* 23B3E4 80096924 */ .byte 0x02
    /* 23B3E5 80096925 */ .byte 0x00
    /* 23B3E6 80096926 */ .byte 0x00
    /* 23B3E7 80096927 */ .byte 0x00
enddlabel D_80096920

nonmatching D_80096928

dlabel D_80096928
    /* 23B3E8 80096928 FF6400FF */ .word 0xFF6400FF
    /* 23B3EC 8009692C 0000FFFF */ .word 0x0000FFFF
    /* 23B3F0 80096930 FFFFFFFF */ .word 0xFFFFFFFF
enddlabel D_80096928

nonmatching D_80096934

dlabel D_80096934
    /* 23B3F4 80096934 FF5A00FF */ .word 0xFF5A00FF
    /* 23B3F8 80096938 1E00FFFF */ .word 0x1E00FFFF
    /* 23B3FC 8009693C FF000000 */ .word 0xFF000000
enddlabel D_80096934

nonmatching D_80096940

dlabel D_80096940
    /* 23B400 80096940 B43C00B4 */ .word 0xB43C00B4
    /* 23B404 80096944 0000FFFF */ .word 0x0000FFFF
    /* 23B408 80096948 FF000000 */ .word 0xFF000000
enddlabel D_80096940

nonmatching D_8009694C

dlabel D_8009694C
    /* 23B40C 8009694C FFFFFFFF */ .word 0xFFFFFFFF
    /* 23B410 80096950 00000000 */ .word 0x00000000
    /* 23B414 80096954 00000000 */ .word 0x00000000
    /* 23B418 80096958 00000000 */ .word 0x00000000
    /* 23B41C 8009695C 00000000 */ .word 0x00000000
enddlabel D_8009694C
