.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.4 */

nonmatching D_800968B0

dlabel D_800968B0
    /* 23B370 800968B0 469C4000 */ .float 20000
    /* 23B374 800968B4 00000000 */ .float 0
    /* 23B378 800968B8 00000000 */ .float 0
    /* 23B37C 800968BC 00000000 */ .float 0
enddlabel D_800968B0
