.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.4 */

nonmatching D_8009CE40

dlabel D_8009CE40
    /* 241900 8009CE40 0D100001 */ .word 0x0D100001
    /* 241904 8009CE44 00000001 */ .word 0x00000001
    /* 241908 8009CE48 00000000 */ .word 0x00000000
    /* 24190C 8009CE4C 00000000 */ .word 0x00000000
enddlabel D_8009CE40
