.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.4 */

nonmatching D_8009D030

dlabel D_8009D030
    /* 241AF0 8009D030 8C000902 */ .word 0x8C000902
    /* 241AF4 8009D034 00000C00 */ .word 0x00000C00
    /* 241AF8 8009D038 00000000 */ .word 0x00000000
    /* 241AFC 8009D03C 00000000 */ .word 0x00000000
enddlabel D_8009D030
