.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.4 */

nonmatching D_8009D000

dlabel D_8009D000
    /* 241AC0 8009D000 89000502 */ .word 0x89000502
    /* 241AC4 8009D004 00000900 */ .word 0x00000900
    /* 241AC8 8009D008 00000000 */ .word 0x00000000
    /* 241ACC 8009D00C 00000000 */ .word 0x00000000
enddlabel D_8009D000
