.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.4 */

nonmatching D_8009D0B0

dlabel D_8009D0B0
    /* 241B70 8009D0B0 32000001 */ .word 0x32000001
    /* 241B74 8009D0B4 00040008 */ .word 0x00040008
    /* 241B78 8009D0B8 00000000 */ .word 0x00000000
    /* 241B7C 8009D0BC 00000000 */ .word 0x00000000
enddlabel D_8009D0B0
