.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.4 */

nonmatching D_8009D1D0

dlabel D_8009D1D0
    /* 241C90 8009D1D0 7C000001 */ .word 0x7C000001
    /* 241C94 8009D1D4 00000000 */ .word 0x00000000
    /* 241C98 8009D1D8 00000000 */ .word 0x00000000
    /* 241C9C 8009D1DC 00000000 */ .word 0x00000000
enddlabel D_8009D1D0
