.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.4 */

nonmatching D_8009D410

dlabel D_8009D410
    /* 241ED0 8009D410 2C040001 */ .word 0x2C040001
    /* 241ED4 8009D414 00000000 */ .word 0x00000000
    /* 241ED8 8009D418 00000000 */ .word 0x00000000
    /* 241EDC 8009D41C 00000000 */ .word 0x00000000
enddlabel D_8009D410
