.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.4 */

nonmatching D_8009D630

dlabel D_8009D630
    /* 2420F0 8009D630 540E0001 */ .word 0x540E0001
    /* 2420F4 8009D634 00000008 */ .word 0x00000008
    /* 2420F8 8009D638 00000000 */ .word 0x00000000
    /* 2420FC 8009D63C 00000000 */ .word 0x00000000
enddlabel D_8009D630
