.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.4 */

nonmatching D_8009D690

dlabel D_8009D690
    /* 242150 8009D690 5D171401 */ .word 0x5D171401
    /* 242154 8009D694 00000000 */ .word 0x00000000
    /* 242158 8009D698 00000000 */ .word 0x00000000
    /* 24215C 8009D69C 00000000 */ .word 0x00000000
enddlabel D_8009D690
