.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.4 */

nonmatching D_8009D6E0

dlabel D_8009D6E0
    /* 2421A0 8009D6E0 570E0001 */ .word 0x570E0001
    /* 2421A4 8009D6E4 00000000 */ .word 0x00000000
    /* 2421A8 8009D6E8 00000000 */ .word 0x00000000
    /* 2421AC 8009D6EC 00000000 */ .word 0x00000000
enddlabel D_8009D6E0
