.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.4 */

nonmatching D_8009D850

dlabel D_8009D850
    /* 242310 8009D850 77040001 */ .word 0x77040001
    /* 242314 8009D854 00000000 */ .word 0x00000000
    /* 242318 8009D858 00000000 */ .word 0x00000000
    /* 24231C 8009D85C 00000000 */ .word 0x00000000
enddlabel D_8009D850
