.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.4 */

nonmatching D_8009D8B0

dlabel D_8009D8B0
    /* 242370 8009D8B0 68090001 */ .word 0x68090001
    /* 242374 8009D8B4 00000000 */ .word 0x00000000
    /* 242378 8009D8B8 00000000 */ .word 0x00000000
    /* 24237C 8009D8BC 00000000 */ .word 0x00000000
enddlabel D_8009D8B0
