.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.4 */

.align 2
nonmatching D_8009FBC0

dlabel D_8009FBC0
    /* 244680 8009FBC0 */ .asciz "Bh"
    /* 42680000 */
.align 2
    /* 244684 8009FBC4 C1F00000 */ .word 0xC1F00000
    /* 244688 8009FBC8 00000000 */ .word 0x00000000
enddlabel D_8009FBC0

nonmatching D_8009FBCC

dlabel D_8009FBCC
    /* 24468C 8009FBCC 3FF9FBE8 */ .float 1.953000069
enddlabel D_8009FBCC

nonmatching D_8009FBD0

dlabel D_8009FBD0
    /* 244690 8009FBD0 406F1AA0 */ .float 3.736000061
enddlabel D_8009FBD0

nonmatching D_8009FBD4

dlabel D_8009FBD4
    /* 244694 8009FBD4 3F70A3D8 */ .float 0.9400000572
enddlabel D_8009FBD4

nonmatching D_8009FBD8

dlabel D_8009FBD8
    /* 244698 8009FBD8 400E45A2 */ .float 2.22300005
enddlabel D_8009FBD8

nonmatching D_8009FBDC

dlabel D_8009FBDC
    /* 24469C 8009FBDC 402A3D70 */ .float 2.659999847
enddlabel D_8009FBDC

nonmatching D_8009FBE0

dlabel D_8009FBE0
    /* 2446A0 8009FBE0 3FECCCCC */ .float 1.849999905
    /* 2446A4 8009FBE4 00000000 */ .float 0
    /* 2446A8 8009FBE8 00000000 */ .float 0
    /* 2446AC 8009FBEC 00000000 */ .float 0
enddlabel D_8009FBE0
