.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.4 */

nonmatching D_800A07F0

dlabel D_800A07F0
    /* 2452B0 800A07F0 00000000 */ .word 0x00000000
    /* 2452B4 800A07F4 C2440000 */ .word 0xC2440000
    /* 2452B8 800A07F8 C0000000 */ .word 0xC0000000
enddlabel D_800A07F0

nonmatching D_800A07FC

dlabel D_800A07FC
    /* 2452BC 800A07FC 46EA6000 */ .float 30000
enddlabel D_800A07FC

nonmatching D_800A0800

dlabel D_800A0800
    /* 2452C0 800A0800 43918000 */ .float 291
    /* 2452C4 800A0804 00000000 */ .float 0
    /* 2452C8 800A0808 00000000 */ .float 0
    /* 2452CC 800A080C */ .byte 0x00
    /* 2452CD 800A080D */ .byte 0x00
    /* 2452CE 800A080E */ .byte 0x00
enddlabel D_800A0800

nonmatching D_800A080F

dlabel D_800A080F
    /* 2452CF 800A080F */ .byte 0x00
    /* 2452D0 800A0810 06012122 */ .float 2.428654555e-35
    /* 2452D4 800A0814 11110000 */ .float 1.143848313e-28
enddlabel D_800A080F

nonmatching D_800A0818

dlabel D_800A0818
    /* 2452D8 800A0818 */ .byte 0x10
    /* 2452D9 800A0819 */ .byte 0x0C
    /* 2452DA 800A081A */ .byte 0x0A
    /* 2452DB 800A081B */ .byte 0x0D
    /* 2452DC 800A081C */ .byte 0x01
    /* 2452DD 800A081D */ .byte 0x19
    /* 2452DE 800A081E */ .byte 0x9C
    /* 2452DF 800A081F */ .byte 0xBE
enddlabel D_800A0818

nonmatching D_800A0820

dlabel D_800A0820
    /* 2452E0 800A0820 43360B61 */ .float 182.0444489
enddlabel D_800A0820

nonmatching D_800A0824

dlabel D_800A0824
    /* 2452E4 800A0824 3BA3D70A */ .float 0.004999999888
enddlabel D_800A0824

nonmatching D_800A0828

dlabel D_800A0828
    /* 2452E8 800A0828 3E19999A */ .float 0.150000006
    /* 2452EC 800A082C 00000000 */ .float 0
enddlabel D_800A0828
