.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.4 */

nonmatching D_800A0890

dlabel D_800A0890
    /* 245350 800A0890 3EB3A29C */ .float 0.3508499861
enddlabel D_800A0890

nonmatching D_800A0894

dlabel D_800A0894
    /* 245354 800A0894 3A83126F */ .float 0.001000000047
enddlabel D_800A0894

nonmatching D_800A0898

dlabel D_800A0898
    /* 245358 800A0898 3F849247 */ .float 1.03571403
enddlabel D_800A0898

nonmatching D_800A089C

dlabel D_800A089C
    /* 24535C 800A089C 3F786CA9 */ .float 0.9704080224
enddlabel D_800A089C

nonmatching D_800A08A0

dlabel D_800A08A0
    /* 245360 800A08A0 3E20C49C */ .float 0.1570000052
enddlabel D_800A08A0

nonmatching D_800A08A4

dlabel D_800A08A4
    /* 245364 800A08A4 BDA3D70B */ .float -0.08000000566
    /* 245368 800A08A8 00000000 */ .float 0
    /* 24536C 800A08AC 00000000 */ .float 0
enddlabel D_800A08A4
