.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.4 */

nonmatching D_800A1980

dlabel D_800A1980
    /* 246440 800A1980 BC23D70A */ .float -0.009999999776
enddlabel D_800A1980

nonmatching D_800A1984

dlabel D_800A1984
    /* 246444 800A1984 3F333333 */ .float 0.6999999881
enddlabel D_800A1984

nonmatching D_800A1988

dlabel D_800A1988
    /* 246448 800A1988 3EB33333 */ .float 0.349999994
enddlabel D_800A1988

nonmatching D_800A198C

dlabel D_800A198C
    /* 24644C 800A198C 45034000 */ .float 2100
enddlabel D_800A198C

nonmatching D_800A1990

dlabel D_800A1990
    /* 246450 800A1990 3E4CCCCD */ .float 0.200000003
enddlabel D_800A1990

nonmatching D_800A1994

dlabel D_800A1994
    /* 246454 800A1994 3D23D70A */ .float 0.03999999911
enddlabel D_800A1994

nonmatching D_800A1998

dlabel D_800A1998
    /* 246458 800A1998 3C75C28F */ .float 0.01499999966
enddlabel D_800A1998

nonmatching D_800A199C

dlabel D_800A199C
    /* 24645C 800A199C 3FA66666 */ .float 1.299999952
enddlabel D_800A199C

nonmatching D_800A19A0

dlabel D_800A19A0
    /* 246460 800A19A0 3FE66666 */ .float 1.799999952
enddlabel D_800A19A0

nonmatching D_800A19A4

dlabel D_800A19A4
    /* 246464 800A19A4 3F19999A */ .float 0.6000000238
enddlabel D_800A19A4

nonmatching D_800A19A8

dlabel D_800A19A8
    /* 246468 800A19A8 3E99999A */ .float 0.3000000119
enddlabel D_800A19A8

nonmatching D_800A19AC

dlabel D_800A19AC
    /* 24646C 800A19AC 3903126F */ .float 0.0001250000059
enddlabel D_800A19AC

nonmatching D_800A19B0

dlabel D_800A19B0
    /* 246470 800A19B0 3ECCCCCD */ .float 0.400000006
enddlabel D_800A19B0

nonmatching D_800A19B4

dlabel D_800A19B4
    /* 246474 800A19B4 3F19999A */ .float 0.6000000238
enddlabel D_800A19B4

nonmatching D_800A19B8

dlabel D_800A19B8
    /* 246478 800A19B8 3FCCCCCD */ .float 1.600000024
enddlabel D_800A19B8

nonmatching D_800A19BC

dlabel D_800A19BC
    /* 24647C 800A19BC BFCCCCCD */ .float -1.600000024
enddlabel D_800A19BC

nonmatching D_800A19C0

dlabel D_800A19C0
    /* 246480 800A19C0 3F99999A */ .float 1.200000048
enddlabel D_800A19C0

nonmatching D_800A19C4

dlabel D_800A19C4
    /* 246484 800A19C4 3E4CCCCD */ .float 0.200000003
enddlabel D_800A19C4

nonmatching D_800A19C8

dlabel D_800A19C8
    /* 246488 800A19C8 3F19999A */ .float 0.6000000238
enddlabel D_800A19C8

nonmatching D_800A19CC

dlabel D_800A19CC
    /* 24648C 800A19CC 3DCCCCCD */ .float 0.1000000015
enddlabel D_800A19CC

nonmatching D_800A19D0

dlabel D_800A19D0
    /* 246490 800A19D0 BEB33333 */ .float -0.349999994
enddlabel D_800A19D0

nonmatching D_800A19D4

dlabel D_800A19D4
    /* 246494 800A19D4 3E4CCCCD */ .float 0.200000003
    /* 246498 800A19D8 00000000 */ .float 0
    /* 24649C 800A19DC 00000000 */ .float 0
enddlabel D_800A19D4
