.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.4 */

nonmatching D_800A3380

dlabel D_800A3380
    /* 247E40 800A3380 3C8EFA35 */ .float 0.01745329238
enddlabel D_800A3380

nonmatching D_800A3384

dlabel D_800A3384
    /* 247E44 800A3384 3F99999A */ .float 1.200000048
enddlabel D_800A3384

nonmatching D_800A3388

dlabel D_800A3388
    /* 247E48 800A3388 3F2AAA9F */ .float 0.6666659713
enddlabel D_800A3388

nonmatching D_800A338C

dlabel D_800A338C
    /* 247E4C 800A338C C61C4000 */ .float -10000
enddlabel D_800A338C

nonmatching D_800A3390

dlabel D_800A3390
    /* 247E50 800A3390 3B3B3EE7 */ .float 0.002857142827
enddlabel D_800A3390

nonmatching D_800A3394

dlabel D_800A3394
    /* 247E54 800A3394 3C8EFA35 */ .float 0.01745329238
enddlabel D_800A3394

nonmatching D_800A3398

dlabel D_800A3398
    /* 247E58 800A3398 3C8EFA35 */ .float 0.01745329238
enddlabel D_800A3398

nonmatching D_800A339C

dlabel D_800A339C
    /* 247E5C 800A339C 3C8EFA35 */ .float 0.01745329238
enddlabel D_800A339C

nonmatching D_800A33A0

dlabel D_800A33A0
    /* 247E60 800A33A0 3C23D70A */ .float 0.009999999776
enddlabel D_800A33A0

nonmatching D_800A33A4

dlabel D_800A33A4
    /* 247E64 800A33A4 3C8EFA35 */ .float 0.01745329238
enddlabel D_800A33A4

nonmatching D_800A33A8

dlabel D_800A33A8
    /* 247E68 800A33A8 3C51B717 */ .float 0.01279999968
enddlabel D_800A33A8

nonmatching D_800A33AC

dlabel D_800A33AC
    /* 247E6C 800A33AC 3CCCCCCD */ .float 0.02500000037
enddlabel D_800A33AC

nonmatching D_800A33B0

dlabel D_800A33B0
    /* 247E70 800A33B0 3C8EFA35 */ .float 0.01745329238
enddlabel D_800A33B0

nonmatching D_800A33B4

dlabel D_800A33B4
    /* 247E74 800A33B4 3EB33333 */ .float 0.349999994
enddlabel D_800A33B4

nonmatching D_800A33B8

dlabel D_800A33B8
    /* 247E78 800A33B8 3F8CA000 */ .float 1.098632812
enddlabel D_800A33B8

nonmatching D_800A33BC

dlabel D_800A33BC
    /* 247E7C 800A33BC 3F8CA000 */ .float 1.098632812
enddlabel D_800A33BC

nonmatching D_800A33C0

dlabel D_800A33C0
    /* 247E80 800A33C0 41035C29 */ .float 8.210000038
enddlabel D_800A33C0

nonmatching D_800A33C4

dlabel D_800A33C4
    /* 247E84 800A33C4 41035C29 */ .float 8.210000038
enddlabel D_800A33C4

nonmatching D_800A33C8

dlabel D_800A33C8
    /* 247E88 800A33C8 41035C29 */ .float 8.210000038
enddlabel D_800A33C8

nonmatching D_800A33CC

dlabel D_800A33CC
    /* 247E8C 800A33CC 41035C29 */ .float 8.210000038
enddlabel D_800A33CC

nonmatching D_800A33D0

dlabel D_800A33D0
    /* 247E90 800A33D0 40E9999A */ .float 7.300000191
enddlabel D_800A33D0

nonmatching D_800A33D4

dlabel D_800A33D4
    /* 247E94 800A33D4 40E9999A */ .float 7.300000191
enddlabel D_800A33D4

nonmatching D_800A33D8

dlabel D_800A33D8
    /* 247E98 800A33D8 3C8EFA35 */ .float 0.01745329238
enddlabel D_800A33D8

nonmatching D_800A33DC

dlabel D_800A33DC
    /* 247E9C 800A33DC 3C8EFA35 */ .float 0.01745329238
enddlabel D_800A33DC

nonmatching D_800A33E0

dlabel D_800A33E0
    /* 247EA0 800A33E0 3C8EFA35 */ .float 0.01745329238
enddlabel D_800A33E0

nonmatching D_800A33E4

dlabel D_800A33E4
    /* 247EA4 800A33E4 40490FDB */ .float 3.141592741
enddlabel D_800A33E4

nonmatching D_800A33E8

dlabel D_800A33E8
    /* 247EA8 800A33E8 3C8EFA35 */ .float 0.01745329238
enddlabel D_800A33E8

nonmatching D_800A33EC

dlabel D_800A33EC
    /* 247EAC 800A33EC 40490FDB */ .float 3.141592741
enddlabel D_800A33EC

nonmatching D_800A33F0

dlabel D_800A33F0
    /* 247EB0 800A33F0 3C8EFA35 */ .float 0.01745329238
enddlabel D_800A33F0

nonmatching D_800A33F4

dlabel D_800A33F4
    /* 247EB4 800A33F4 40490FDB */ .float 3.141592741
enddlabel D_800A33F4

nonmatching D_800A33F8

dlabel D_800A33F8
    /* 247EB8 800A33F8 3D4CCCCD */ .float 0.05000000075
enddlabel D_800A33F8

nonmatching D_800A33FC

dlabel D_800A33FC
    /* 247EBC 800A33FC 3C8EFA35 */ .float 0.01745329238
enddlabel D_800A33FC

nonmatching D_800A3400

dlabel D_800A3400
    /* 247EC0 800A3400 3FC90FDB */ .float 1.570796371
enddlabel D_800A3400

nonmatching D_800A3404

dlabel D_800A3404
    /* 247EC4 800A3404 3FC90FDB */ .float 1.570796371
enddlabel D_800A3404

nonmatching D_800A3408

dlabel D_800A3408
    /* 247EC8 800A3408 3C8EFA35 */ .float 0.01745329238
enddlabel D_800A3408

nonmatching D_800A340C

dlabel D_800A340C
    /* 247ECC 800A340C BC8EFA35 */ .float -0.01745329238
enddlabel D_800A340C

nonmatching D_800A3410

dlabel D_800A3410
    /* 247ED0 800A3410 BC8EFA35 */ .float -0.01745329238
enddlabel D_800A3410

nonmatching D_800A3414

dlabel D_800A3414
    /* 247ED4 800A3414 BC8EFA35 */ .float -0.01745329238
enddlabel D_800A3414

nonmatching D_800A3418

dlabel D_800A3418
    /* 247ED8 800A3418 BC8EFA35 */ .float -0.01745329238
    /* 247EDC 800A341C 00000000 */ .float 0
enddlabel D_800A3418
