.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.4 */

nonmatching D_800A3860

dlabel D_800A3860
    /* 248320 800A3860 00000019 */ .word 0x00000019
    /* 248324 800A3864 00000048 */ .word 0x00000048
enddlabel D_800A3860

nonmatching D_800A3868

dlabel D_800A3868
    /* 248328 800A3868 C61C4000 */ .float -10000
enddlabel D_800A3868

nonmatching D_800A386C

dlabel D_800A386C
    /* 24832C 800A386C C61C4000 */ .float -10000
enddlabel D_800A386C

nonmatching D_800A3870

dlabel D_800A3870
    /* 248330 800A3870 4222F983 */ .float 40.74366379
    /* 248334 800A3874 00000000 */ .float 0
    /* 248338 800A3878 00000000 */ .float 0
    /* 24833C 800A387C 00000000 */ .float 0
enddlabel D_800A3870
