.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.4 */

nonmatching D_800A6E00

dlabel D_800A6E00
    /* 24B8C0 800A6E00 */ .byte 0xFF
    /* 24B8C1 800A6E01 */ .byte 0x28
    /* 24B8C2 800A6E02 */ .byte 0x23
    /* 24B8C3 800A6E03 */ .byte 0x1E
    /* 24B8C4 800A6E04 */ .byte 0x19
    /* 24B8C5 800A6E05 */ .byte 0x14
    /* 24B8C6 800A6E06 */ .byte 0x0F
    /* 24B8C7 800A6E07 */ .byte 0x00
    /* 24B8C8 800A6E08 */ .byte 0xFF
    /* 24B8C9 800A6E09 */ .byte 0x28
    /* 24B8CA 800A6E0A */ .byte 0x00
    /* 24B8CB 800A6E0B */ .byte 0x00
enddlabel D_800A6E00

nonmatching D_800A6E0C

dlabel D_800A6E0C
    /* 24B8CC 800A6E0C */ .byte 0xFF
    /* 24B8CD 800A6E0D */ .byte 0xFF
    /* 24B8CE 800A6E0E */ .byte 0x00
    /* 24B8CF 800A6E0F */ .byte 0xFF
    /* 24B8D0 800A6E10 */ .byte 0xFF
    /* 24B8D1 800A6E11 */ .byte 0x00
    /* 24B8D2 800A6E12 */ .byte 0xFF
    /* 24B8D3 800A6E13 */ .byte 0x80
    /* 24B8D4 800A6E14 */ .byte 0x00
    /* 24B8D5 800A6E15 */ .byte 0xFF
    /* 24B8D6 800A6E16 */ .byte 0x80
    /* 24B8D7 800A6E17 */ .byte 0x00
    /* 24B8D8 800A6E18 */ .byte 0xFF
    /* 24B8D9 800A6E19 */ .byte 0x00
    /* 24B8DA 800A6E1A */ .byte 0x00
    /* 24B8DB 800A6E1B */ .byte 0xFF
    /* 24B8DC 800A6E1C */ .byte 0x00
    /* 24B8DD 800A6E1D */ .byte 0x00
    /* 24B8DE 800A6E1E */ .byte 0xC0
    /* 24B8DF 800A6E1F */ .byte 0x00
    /* 24B8E0 800A6E20 */ .byte 0x00
    /* 24B8E1 800A6E21 */ .byte 0x80
    /* 24B8E2 800A6E22 */ .byte 0x00
    /* 24B8E3 800A6E23 */ .byte 0x00
    /* 24B8E4 800A6E24 */ .byte 0x5A
    /* 24B8E5 800A6E25 */ .byte 0x5A
    /* 24B8E6 800A6E26 */ .byte 0x5A
    /* 24B8E7 800A6E27 */ .byte 0x5A
    /* 24B8E8 800A6E28 */ .byte 0x5A
    /* 24B8E9 800A6E29 */ .byte 0x5A
    /* 24B8EA 800A6E2A */ .byte 0x00
    /* 24B8EB 800A6E2B */ .byte 0x00
    /* 24B8EC 800A6E2C */ .byte 0x00
    /* 24B8ED 800A6E2D */ .byte 0x00
    /* 24B8EE 800A6E2E */ .byte 0x00
    /* 24B8EF 800A6E2F */ .byte 0x00
enddlabel D_800A6E0C
