.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.4 */

nonmatching D_800A7250

dlabel D_800A7250
    /* 24BD10 800A7250 */ .byte 0x80
    /* 24BD11 800A7251 */ .byte 0x40
    /* 24BD12 800A7252 */ .byte 0x80
    /* 24BD13 800A7253 */ .byte 0xFF
    /* 24BD14 800A7254 */ .byte 0x80
    /* 24BD15 800A7255 */ .byte 0x40
    /* 24BD16 800A7256 */ .byte 0x80
    /* 24BD17 800A7257 */ .byte 0x20
    /* 24BD18 800A7258 */ .byte 0x40
    /* 24BD19 800A7259 */ .byte 0x20
    /* 24BD1A 800A725A */ .byte 0x20
    /* 24BD1B 800A725B */ .byte 0x20
    /* 24BD1C 800A725C */ .byte 0x20
    /* 24BD1D 800A725D */ .byte 0x20
    /* 24BD1E 800A725E */ .byte 0x00
    /* 24BD1F 800A725F */ .byte 0x00
enddlabel D_800A7250

nonmatching D_800A7260

dlabel D_800A7260
    /* 24BD20 800A7260 3F4CCCCD */ .float 0.8000000119
    /* 24BD24 800A7264 3F666666 */ .float 0.8999999762
    /* 24BD28 800A7268 3F666666 */ .float 0.8999999762
    /* 24BD2C 800A726C 3F666666 */ .float 0.8999999762
enddlabel D_800A7260

nonmatching D_800A7270

dlabel D_800A7270
    /* 24BD30 800A7270 3F770A3D */ .float 0.9649999738
    /* 24BD34 800A7274 3F770A3D */ .float 0.9649999738
    /* 24BD38 800A7278 3F770A3D */ .float 0.9649999738
    /* 24BD3C 800A727C 3F770A3D */ .float 0.9649999738
enddlabel D_800A7270

nonmatching D_800A7280

dlabel D_800A7280
    /* 24BD40 800A7280 461C4000 */ .float 10000
enddlabel D_800A7280

nonmatching D_800A7284

dlabel D_800A7284
    /* 24BD44 800A7284 C61C4000 */ .float -10000
enddlabel D_800A7284

nonmatching D_800A7288

dlabel D_800A7288
    /* 24BD48 800A7288 C61C4000 */ .float -10000
enddlabel D_800A7288

nonmatching D_800A728C

dlabel D_800A728C
    /* 24BD4C 800A728C 3C23D70A */ .float 0.009999999776
enddlabel D_800A728C

nonmatching D_800A7290

dlabel D_800A7290
    /* 24BD50 800A7290 C3C78000 */ .float -399
enddlabel D_800A7290

nonmatching D_800A7294

dlabel D_800A7294
    /* 24BD54 800A7294 3F666666 */ .float 0.8999999762
enddlabel D_800A7294

nonmatching D_800A7298

dlabel D_800A7298
    /* 24BD58 800A7298 3C23D70A */ .float 0.009999999776
enddlabel D_800A7298

nonmatching D_800A729C

dlabel D_800A729C
    /* 24BD5C 800A729C 3C1374BC */ .float 0.008999999613
enddlabel D_800A729C

nonmatching D_800A72A0

dlabel D_800A72A0
    /* 24BD60 800A72A0 3B83126F */ .float 0.00400000019
enddlabel D_800A72A0

nonmatching D_800A72A4

dlabel D_800A72A4
    /* 24BD64 800A72A4 3D4CCCCD */ .float 0.05000000075
enddlabel D_800A72A4

nonmatching D_800A72A8

dlabel D_800A72A8
    /* 24BD68 800A72A8 BC1374BC */ .float -0.008999999613
enddlabel D_800A72A8

nonmatching D_800A72AC

dlabel D_800A72AC
    /* 24BD6C 800A72AC 3F3AE148 */ .float 0.7300000191
enddlabel D_800A72AC

nonmatching D_800A72B0

dlabel D_800A72B0
    /* 24BD70 800A72B0 3C23D70A */ .float 0.009999999776
enddlabel D_800A72B0

nonmatching D_800A72B4

dlabel D_800A72B4
    /* 24BD74 800A72B4 BB83126F */ .float -0.00400000019
enddlabel D_800A72B4

nonmatching D_800A72B8

dlabel D_800A72B8
    /* 24BD78 800A72B8 3C23D70A */ .float 0.009999999776
enddlabel D_800A72B8

nonmatching D_800A72BC

dlabel D_800A72BC
    /* 24BD7C 800A72BC 3F333333 */ .float 0.6999999881
enddlabel D_800A72BC

nonmatching D_800A72C0

dlabel D_800A72C0
    /* 24BD80 800A72C0 3F333333 */ .float 0.6999999881
    /* 24BD84 800A72C4 00000000 */ .float 0
    /* 24BD88 800A72C8 00000000 */ .float 0
    /* 24BD8C 800A72CC 00000000 */ .float 0
enddlabel D_800A72C0
