.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.4 */

nonmatching D_800A73C0

dlabel D_800A73C0
    /* 24BE80 800A73C0 3F19999A */ .float 0.6000000238
enddlabel D_800A73C0

nonmatching D_800A73C4

dlabel D_800A73C4
    /* 24BE84 800A73C4 3E99999A */ .float 0.3000000119
enddlabel D_800A73C4

nonmatching D_800A73C8

dlabel D_800A73C8
    /* 24BE88 800A73C8 3F19999A */ .float 0.6000000238
    /* 24BE8C 800A73CC 00000000 */ .float 0
enddlabel D_800A73C8
