.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.4 */

nonmatching D_800A7390

dlabel D_800A7390
    /* 24BE50 800A7390 */ .byte 0x3C
    /* 24BE51 800A7391 */ .byte 0x06
    /* 24BE52 800A7392 */ .byte 0x64
    /* 24BE53 800A7393 */ .byte 0x06
    /* 24BE54 800A7394 */ .byte 0x28
    /* 24BE55 800A7395 */ .byte 0x37
    /* 24BE56 800A7396 */ .byte 0x06
    /* 24BE57 800A7397 */ .byte 0x5A
enddlabel D_800A7390

nonmatching D_800A7398

dlabel D_800A7398
    /* 24BE58 800A7398 40C90FDB */ .float 6.283185482
    /* 24BE5C 800A739C 00000000 */ .float 0
enddlabel D_800A7398
