.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.4 */

nonmatching D_800ABA90

dlabel D_800ABA90
    /* 250550 800ABA90 */ .byte 0xFF
    /* 250551 800ABA91 */ .byte 0x00
    /* 250552 800ABA92 */ .byte 0x00
    /* 250553 800ABA93 */ .byte 0xFF
    /* 250554 800ABA94 */ .byte 0x00
    /* 250555 800ABA95 */ .byte 0x00
    /* 250556 800ABA96 */ .byte 0xFF
    /* 250557 800ABA97 */ .byte 0xFF
    /* 250558 800ABA98 */ .byte 0x00
    /* 250559 800ABA99 */ .byte 0xFF
    /* 25055A 800ABA9A */ .byte 0x00
    /* 25055B 800ABA9B */ .byte 0xFF
    /* 25055C 800ABA9C */ .byte 0xFF
    /* 25055D 800ABA9D */ .byte 0xFF
    /* 25055E 800ABA9E */ .byte 0x00
    /* 25055F 800ABA9F */ .byte 0xFF
enddlabel D_800ABA90

.align 2
nonmatching D_800ABAA0

dlabel D_800ABAA0
    /* 250560 800ABAA0 */ .asciz " %d"
    /* 20256400 */
.align 2
enddlabel D_800ABAA0

.align 2
nonmatching D_800ABAA4

dlabel D_800ABAA4
    /* 250564 800ABAA4 */ .asciz " %d"
    /* 20256400 */
.align 2
enddlabel D_800ABAA4

.align 2
nonmatching D_800ABAA8

dlabel D_800ABAA8
    /* 250568 800ABAA8 */ .asciz "%s"
    /* 25730000 */
.align 2
enddlabel D_800ABAA8

.align 2
nonmatching D_800ABAAC

dlabel D_800ABAAC
    /* 25056C 800ABAAC */ .asciz "%d"
    /* 25640000 */
.align 2
enddlabel D_800ABAAC

.align 2
nonmatching D_800ABAB0

dlabel D_800ABAB0
    /* 250570 800ABAB0 */ .asciz "%d%%"
    /* 2564252500000000 */
.align 2
enddlabel D_800ABAB0

.align 2
nonmatching D_800ABAB8

dlabel D_800ABAB8
    /* 250578 800ABAB8 */ .asciz "%d"
    /* 25640000 */
.align 2
enddlabel D_800ABAB8

.align 2
nonmatching D_800ABABC

dlabel D_800ABABC
    /* 25057C 800ABABC */ .asciz "X"
    /* 58000000 */
.align 2
enddlabel D_800ABABC

.align 2
nonmatching D_800ABAC0

dlabel D_800ABAC0
    /* 250580 800ABAC0 */ .asciz "%d"
    /* 25640000 */
.align 2
enddlabel D_800ABAC0

.align 2
nonmatching D_800ABAC4

dlabel D_800ABAC4
    /* 250584 800ABAC4 */ .asciz "%d"
    /* 25640000 */
.align 2
enddlabel D_800ABAC4

.align 2
nonmatching D_800ABAC8

dlabel D_800ABAC8
    /* 250588 800ABAC8 */ .asciz "#"
    /* 23000000 */
.align 2
enddlabel D_800ABAC8

.align 2
nonmatching D_800ABACC

dlabel D_800ABACC
    /* 25058C 800ABACC */ .asciz "#"
    /* 23000000 */
.align 2
enddlabel D_800ABACC

.align 2
nonmatching D_800ABAD0

dlabel D_800ABAD0
    /* 250590 800ABAD0 */ .asciz "%d"
    /* 25640000 */
.align 2
enddlabel D_800ABAD0

.align 2
nonmatching D_800ABAD4

dlabel D_800ABAD4
    /* 250594 800ABAD4 */ .asciz "-"
    /* 2D000000 */
.align 2
enddlabel D_800ABAD4

nonmatching D_800ABAD8

dlabel D_800ABAD8
    /* 250598 800ABAD8 4ABEBC20 */ .float 6250000
enddlabel D_800ABAD8

nonmatching D_800ABADC

dlabel D_800ABADC
    /* 25059C 800ABADC 469C4000 */ .float 20000
enddlabel D_800ABADC

nonmatching D_800ABAE0

dlabel D_800ABAE0
    /* 2505A0 800ABAE0 3E8A3D70 */ .float 0.2699999809
enddlabel D_800ABAE0

nonmatching D_800ABAE4

dlabel D_800ABAE4
    /* 2505A4 800ABAE4 3E99999A */ .float 0.3000000119
enddlabel D_800ABAE4

nonmatching D_800ABAE8

dlabel D_800ABAE8
    /* 2505A8 800ABAE8 3F666666 */ .float 0.8999999762
enddlabel D_800ABAE8

nonmatching D_800ABAEC

dlabel D_800ABAEC
    /* 2505AC 800ABAEC 3F4CCCCD */ .float 0.8000000119
enddlabel D_800ABAEC

nonmatching D_800ABAF0

dlabel D_800ABAF0
    /* 2505B0 800ABAF0 3F20D97C */ .float 0.6283185482
enddlabel D_800ABAF0

nonmatching D_800ABAF4

dlabel D_800ABAF4
    /* 2505B4 800ABAF4 3F20D97C */ .float 0.6283185482
enddlabel D_800ABAF4

nonmatching D_800ABAF8

dlabel D_800ABAF8
    /* 2505B8 800ABAF8 3DC90FD0 */ .float 0.0981746912
enddlabel D_800ABAF8

nonmatching D_800ABAFC

dlabel D_800ABAFC
    /* 2505BC 800ABAFC 3F490FD0 */ .float 0.7853975296
enddlabel D_800ABAFC

nonmatching D_800ABB00

dlabel D_800ABB00
    /* 2505C0 800ABB00 3E124925 */ .float 0.1428571492
enddlabel D_800ABB00

nonmatching D_800ABB04

dlabel D_800ABB04
    /* 2505C4 800ABB04 C4048000 */ .float -530
enddlabel D_800ABB04

nonmatching D_800ABB08

dlabel D_800ABB08
    /* 2505C8 800ABB08 469C4000 */ .float 20000
    /* 2505CC 800ABB0C 00000000 */ .float 0
    /* 2505D0 800ABB10 7F810000 */ .word 0x7F810000
    /* 2505D4 800ABB14 00000000 */ .float 0
    /* 2505D8 800ABB18 00000000 */ .float 0
    /* 2505DC 800ABB1C 00000000 */ .float 0
enddlabel D_800ABB08
