.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching func_150DECC0, 0x674

glabel func_150DECC0
    /* 10C170 150DECC0 27BDFE78 */  addiu      $sp, $sp, -0x188
    /* 10C174 150DECC4 3C013F80 */  lui        $at, (0x3F800000 >> 16)
    /* 10C178 150DECC8 AFB60060 */  sw         $s6, 0x60($sp)
    /* 10C17C 150DECCC 44810000 */  mtc1       $at, $f0
    /* 10C180 150DECD0 44801000 */  mtc1       $zero, $f2
    /* 10C184 150DECD4 0080B025 */  or         $s6, $a0, $zero
    /* 10C188 150DECD8 AFBF006C */  sw         $ra, 0x6C($sp)
    /* 10C18C 150DECDC AFBE0068 */  sw         $fp, 0x68($sp)
    /* 10C190 150DECE0 AFB70064 */  sw         $s7, 0x64($sp)
    /* 10C194 150DECE4 AFB5005C */  sw         $s5, 0x5C($sp)
    /* 10C198 150DECE8 AFB40058 */  sw         $s4, 0x58($sp)
    /* 10C19C 150DECEC AFB30054 */  sw         $s3, 0x54($sp)
    /* 10C1A0 150DECF0 AFB20050 */  sw         $s2, 0x50($sp)
    /* 10C1A4 150DECF4 AFB1004C */  sw         $s1, 0x4C($sp)
    /* 10C1A8 150DECF8 AFB00048 */  sw         $s0, 0x48($sp)
    /* 10C1AC 150DECFC F7B80040 */  sdc1       $f24, 0x40($sp)
    /* 10C1B0 150DED00 F7B60038 */  sdc1       $f22, 0x38($sp)
    /* 10C1B4 150DED04 F7B40030 */  sdc1       $f20, 0x30($sp)
    /* 10C1B8 150DED08 AFA5018C */  sw         $a1, 0x18C($sp)
    /* 10C1BC 150DED0C AFA60190 */  sw         $a2, 0x190($sp)
    /* 10C1C0 150DED10 3C0F8008 */  lui        $t7, %hi(D_80082FA4)
    /* 10C1C4 150DED14 8DEF2FA4 */  lw         $t7, %lo(D_80082FA4)($t7)
    /* 10C1C8 150DED18 3C0E800E */  lui        $t6, %hi(D_800DBFF0)
    /* 10C1CC 150DED1C 8DCEBFF0 */  lw         $t6, %lo(D_800DBFF0)($t6)
    /* 10C1D0 150DED20 000FC080 */  sll        $t8, $t7, 2
    /* 10C1D4 150DED24 030FC021 */  addu       $t8, $t8, $t7
    /* 10C1D8 150DED28 0018C080 */  sll        $t8, $t8, 2
    /* 10C1DC 150DED2C 030FC023 */  subu       $t8, $t8, $t7
    /* 10C1E0 150DED30 0018C080 */  sll        $t8, $t8, 2
    /* 10C1E4 150DED34 030FC021 */  addu       $t8, $t8, $t7
    /* 10C1E8 150DED38 0018C140 */  sll        $t8, $t8, 5
    /* 10C1EC 150DED3C 3C01800A */  lui        $at, %hi(D_800A0F04)
    /* 10C1F0 150DED40 01D8C821 */  addu       $t9, $t6, $t8
    /* 10C1F4 150DED44 C7240380 */  lwc1       $f4, 0x380($t9)
    /* 10C1F8 150DED48 C4260F04 */  lwc1       $f6, %lo(D_800A0F04)($at)
    /* 10C1FC 150DED4C 3C014170 */  lui        $at, (0x41700000 >> 16)
    /* 10C200 150DED50 44818000 */  mtc1       $at, $f16
    /* 10C204 150DED54 46062202 */  mul.s      $f8, $f4, $f6
    /* 10C208 150DED58 3C0B800A */  lui        $t3, %hi(D_800A5480)
    /* 10C20C 150DED5C 3C01800A */  lui        $at, %hi(D_800A0F08)
    /* 10C210 150DED60 256B5480 */  addiu      $t3, $t3, %lo(D_800A5480)
    /* 10C214 150DED64 27AA0114 */  addiu      $t2, $sp, 0x114
    /* 10C218 150DED68 240E29E9 */  addiu      $t6, $zero, 0x29E9
    /* 10C21C 150DED6C 241800FF */  addiu      $t8, $zero, 0xFF
    /* 10C220 150DED70 4600428D */  trunc.w.s  $f10, $f8
    /* 10C224 150DED74 2419000D */  addiu      $t9, $zero, 0xD
    /* 10C228 150DED78 2408000A */  addiu      $t0, $zero, 0xA
    /* 10C22C 150DED7C 240D0002 */  addiu      $t5, $zero, 0x2
    /* 10C230 150DED80 44095000 */  mfc1       $t1, $f10
    /* 10C234 150DED84 240C0023 */  addiu      $t4, $zero, 0x23
    /* 10C238 150DED88 3C13800A */  lui        $s3, %hi(D_800A0EC8)
    /* 10C23C 150DED8C AFA90184 */  sw         $t1, 0x184($sp)
    /* 10C240 150DED90 C4320F08 */  lwc1       $f18, %lo(D_800A0F08)($at)
    /* 10C244 150DED94 E7B00104 */  swc1       $f16, 0x104($sp)
    /* 10C248 150DED98 E7A00110 */  swc1       $f0, 0x110($sp)
    /* 10C24C 150DED9C E7A0010C */  swc1       $f0, 0x10C($sp)
    /* 10C250 150DEDA0 E7B20108 */  swc1       $f18, 0x108($sp)
    /* 10C254 150DEDA4 8D610000 */  lw         $at, 0x0($t3)
    /* 10C258 150DEDA8 8D6F0004 */  lw         $t7, 0x4($t3)
    /* 10C25C 150DEDAC 24090002 */  addiu      $t1, $zero, 0x2
    /* 10C260 150DEDB0 AD410000 */  sw         $at, 0x0($t2)
    /* 10C264 150DEDB4 8D610008 */  lw         $at, 0x8($t3)
    /* 10C268 150DEDB8 AD4F0004 */  sw         $t7, 0x4($t2)
    /* 10C26C 150DEDBC 3C10800A */  lui        $s0, %hi(D_800A0D60)
    /* 10C270 150DEDC0 AD410008 */  sw         $at, 0x8($t2)
    /* 10C274 150DEDC4 3C01800A */  lui        $at, %hi(D_800A0F0C)
    /* 10C278 150DEDC8 C4380F0C */  lwc1       $f24, %lo(D_800A0F0C)($at)
    /* 10C27C 150DEDCC 3C01800A */  lui        $at, %hi(D_800A0F10)
    /* 10C280 150DEDD0 C4360F10 */  lwc1       $f22, %lo(D_800A0F10)($at)
    /* 10C284 150DEDD4 240A0007 */  addiu      $t2, $zero, 0x7
    /* 10C288 150DEDD8 3C01800A */  lui        $at, %hi(D_800A0F14)
    /* 10C28C 150DEDDC 3C14800A */  lui        $s4, %hi(D_800A0E50)
    /* 10C290 150DEDE0 3C15800A */  lui        $s5, %hi(D_800A0E8C)
    /* 10C294 150DEDE4 3C11800A */  lui        $s1, %hi(D_800A0E14)
    /* 10C298 150DEDE8 3C1E8009 */  lui        $fp, %hi(D_80088960)
    /* 10C29C 150DEDEC 3C178009 */  lui        $s7, %hi(D_8008896C)
    /* 10C2A0 150DEDF0 E7A00120 */  swc1       $f0, 0x120($sp)
    /* 10C2A4 150DEDF4 E7A00124 */  swc1       $f0, 0x124($sp)
    /* 10C2A8 150DEDF8 E7A00128 */  swc1       $f0, 0x128($sp)
    /* 10C2AC 150DEDFC E7A20148 */  swc1       $f2, 0x148($sp)
    /* 10C2B0 150DEE00 AFAE0154 */  sw         $t6, 0x154($sp)
    /* 10C2B4 150DEE04 A3A0015C */  sb         $zero, 0x15C($sp)
    /* 10C2B8 150DEE08 AFA00160 */  sw         $zero, 0x160($sp)
    /* 10C2BC 150DEE0C A3B80164 */  sb         $t8, 0x164($sp)
    /* 10C2C0 150DEE10 A3B90165 */  sb         $t9, 0x165($sp)
    /* 10C2C4 150DEE14 A3A00166 */  sb         $zero, 0x166($sp)
    /* 10C2C8 150DEE18 A3A80167 */  sb         $t0, 0x167($sp)
    /* 10C2CC 150DEE1C A3A00168 */  sb         $zero, 0x168($sp)
    /* 10C2D0 150DEE20 A3A00169 */  sb         $zero, 0x169($sp)
    /* 10C2D4 150DEE24 A3A0016A */  sb         $zero, 0x16A($sp)
    /* 10C2D8 150DEE28 A3A0016B */  sb         $zero, 0x16B($sp)
    /* 10C2DC 150DEE2C A3A9016C */  sb         $t1, 0x16C($sp)
    /* 10C2E0 150DEE30 A3AD016E */  sb         $t5, 0x16E($sp)
    /* 10C2E4 150DEE34 AFA00170 */  sw         $zero, 0x170($sp)
    /* 10C2E8 150DEE38 A3A00174 */  sb         $zero, 0x174($sp)
    /* 10C2EC 150DEE3C A7AC0176 */  sh         $t4, 0x176($sp)
    /* 10C2F0 150DEE40 A7AA0178 */  sh         $t2, 0x178($sp)
    /* 10C2F4 150DEE44 AFA0017C */  sw         $zero, 0x17C($sp)
    /* 10C2F8 150DEE48 E7A20138 */  swc1       $f2, 0x138($sp)
    /* 10C2FC 150DEE4C E7A20140 */  swc1       $f2, 0x140($sp)
    /* 10C300 150DEE50 26F7896C */  addiu      $s7, $s7, %lo(D_8008896C)
    /* 10C304 150DEE54 27DE8960 */  addiu      $fp, $fp, %lo(D_80088960)
    /* 10C308 150DEE58 26310E14 */  addiu      $s1, $s1, %lo(D_800A0E14)
    /* 10C30C 150DEE5C 26B50E8C */  addiu      $s5, $s5, %lo(D_800A0E8C)
    /* 10C310 150DEE60 26940E50 */  addiu      $s4, $s4, %lo(D_800A0E50)
    /* 10C314 150DEE64 C4340F14 */  lwc1       $f20, %lo(D_800A0F14)($at)
    /* 10C318 150DEE68 26100D60 */  addiu      $s0, $s0, %lo(D_800A0D60)
    /* 10C31C 150DEE6C 26730EC8 */  addiu      $s3, $s3, %lo(D_800A0EC8)
  .L150DEE70:
    /* 10C320 150DEE70 444BF800 */  cfc1       $t3, $31
    /* 10C324 150DEE74 24120001 */  addiu      $s2, $zero, 0x1
    /* 10C328 150DEE78 44D2F800 */  ctc1       $s2, $31
    /* 10C32C 150DEE7C C6640000 */  lwc1       $f4, 0x0($s3)
    /* 10C330 150DEE80 3C014F00 */  lui        $at, (0x4F000000 >> 16)
    /* 10C334 150DEE84 460021A4 */  cvt.w.s    $f6, $f4
    /* 10C338 150DEE88 4452F800 */  cfc1       $s2, $31
    /* 10C33C 150DEE8C 00000000 */  nop
    /* 10C340 150DEE90 32520078 */  andi       $s2, $s2, 0x78
    /* 10C344 150DEE94 52400013 */  beql       $s2, $zero, .L150DEEE4
    /* 10C348 150DEE98 44123000 */   mfc1      $s2, $f6
    /* 10C34C 150DEE9C 44813000 */  mtc1       $at, $f6
    /* 10C350 150DEEA0 24120001 */  addiu      $s2, $zero, 0x1
    /* 10C354 150DEEA4 46062181 */  sub.s      $f6, $f4, $f6
    /* 10C358 150DEEA8 44D2F800 */  ctc1       $s2, $31
    /* 10C35C 150DEEAC 00000000 */  nop
    /* 10C360 150DEEB0 460031A4 */  cvt.w.s    $f6, $f6
    /* 10C364 150DEEB4 4452F800 */  cfc1       $s2, $31
    /* 10C368 150DEEB8 00000000 */  nop
    /* 10C36C 150DEEBC 32520078 */  andi       $s2, $s2, 0x78
    /* 10C370 150DEEC0 16400005 */  bnez       $s2, .L150DEED8
    /* 10C374 150DEEC4 00000000 */   nop
    /* 10C378 150DEEC8 44123000 */  mfc1       $s2, $f6
    /* 10C37C 150DEECC 3C018000 */  lui        $at, (0x80000000 >> 16)
    /* 10C380 150DEED0 10000007 */  b          .L150DEEF0
    /* 10C384 150DEED4 02419025 */   or        $s2, $s2, $at
  .L150DEED8:
    /* 10C388 150DEED8 10000005 */  b          .L150DEEF0
    /* 10C38C 150DEEDC 2412FFFF */   addiu     $s2, $zero, -0x1
    /* 10C390 150DEEE0 44123000 */  mfc1       $s2, $f6
  .L150DEEE4:
    /* 10C394 150DEEE4 00000000 */  nop
    /* 10C398 150DEEE8 0640FFFB */  bltz       $s2, .L150DEED8
    /* 10C39C 150DEEEC 00000000 */   nop
  .L150DEEF0:
    /* 10C3A0 150DEEF0 44CBF800 */  ctc1       $t3, $31
    /* 10C3A4 150DEEF4 C6080000 */  lwc1       $f8, 0x0($s0)
    /* 10C3A8 150DEEF8 C6CA0000 */  lwc1       $f10, 0x0($s6)
    /* 10C3AC 150DEEFC C6120004 */  lwc1       $f18, 0x4($s0)
    /* 10C3B0 150DEF00 324F00FF */  andi       $t7, $s2, 0xFF
    /* 10C3B4 150DEF04 460A4400 */  add.s      $f16, $f8, $f10
    /* 10C3B8 150DEF08 C6080008 */  lwc1       $f8, 0x8($s0)
    /* 10C3BC 150DEF0C 01E09025 */  or         $s2, $t7, $zero
    /* 10C3C0 150DEF10 E7B0012C */  swc1       $f16, 0x12C($sp)
    /* 10C3C4 150DEF14 C6C40004 */  lwc1       $f4, 0x4($s6)
    /* 10C3C8 150DEF18 46049180 */  add.s      $f6, $f18, $f4
    /* 10C3CC 150DEF1C E7A60130 */  swc1       $f6, 0x130($sp)
    /* 10C3D0 150DEF20 C6CA0008 */  lwc1       $f10, 0x8($s6)
    /* 10C3D4 150DEF24 460A4400 */  add.s      $f16, $f8, $f10
    /* 10C3D8 150DEF28 0D42B69A */  jal        func_150ADA68
    /* 10C3DC 150DEF2C E7B00134 */   swc1      $f16, 0x134($sp)
    /* 10C3E0 150DEF30 00121080 */  sll        $v0, $s2, 2
    /* 10C3E4 150DEF34 02E27021 */  addu       $t6, $s7, $v0
    /* 10C3E8 150DEF38 C5D20000 */  lwc1       $f18, 0x0($t6)
    /* 10C3EC 150DEF3C C6A20000 */  lwc1       $f2, 0x0($s5)
    /* 10C3F0 150DEF40 C68A0000 */  lwc1       $f10, 0x0($s4)
    /* 10C3F4 150DEF44 46009102 */  mul.s      $f4, $f18, $f0
    /* 10C3F8 150DEF48 03C2C021 */  addu       $t8, $fp, $v0
    /* 10C3FC 150DEF4C C7060000 */  lwc1       $f6, 0x0($t8)
    /* 10C400 150DEF50 46025402 */  mul.s      $f16, $f10, $f2
    /* 10C404 150DEF54 46062200 */  add.s      $f8, $f4, $f6
    /* 10C408 150DEF58 C6240000 */  lwc1       $f4, 0x0($s1)
    /* 10C40C 150DEF5C 46148482 */  mul.s      $f18, $f16, $f20
    /* 10C410 150DEF60 E7A8013C */  swc1       $f8, 0x13C($sp)
    /* 10C414 150DEF64 46022182 */  mul.s      $f6, $f4, $f2
    /* 10C418 150DEF68 E7B20144 */  swc1       $f18, 0x144($sp)
    /* 10C41C 150DEF6C 46143202 */  mul.s      $f8, $f6, $f20
    /* 10C420 150DEF70 0D42B69A */  jal        func_150ADA68
    /* 10C424 150DEF74 E7A8014C */   swc1      $f8, 0x14C($sp)
    /* 10C428 150DEF78 46160282 */  mul.s      $f10, $f0, $f22
    /* 10C42C 150DEF7C 46185400 */  add.s      $f16, $f10, $f24
    /* 10C430 150DEF80 0D42B688 */  jal        func_150ADA20
    /* 10C434 150DEF84 E7B00150 */   swc1      $f16, 0x150($sp)
    /* 10C438 150DEF88 2401006F */  addiu      $at, $zero, 0x6F
    /* 10C43C 150DEF8C 0041001B */  divu       $zero, $v0, $at
    /* 10C440 150DEF90 0000C810 */  mfhi       $t9
    /* 10C444 150DEF94 27280082 */  addiu      $t0, $t9, 0x82
    /* 10C448 150DEF98 0D42B688 */  jal        func_150ADA20
    /* 10C44C 150DEF9C A7A80158 */   sh        $t0, 0x158($sp)
    /* 10C450 150DEFA0 30490001 */  andi       $t1, $v0, 0x1
    /* 10C454 150DEFA4 11200004 */  beqz       $t1, .L150DEFB8
    /* 10C458 150DEFA8 27A40104 */   addiu     $a0, $sp, 0x104
    /* 10C45C 150DEFAC 240D00C4 */  addiu      $t5, $zero, 0xC4
    /* 10C460 150DEFB0 10000003 */  b          .L150DEFC0
    /* 10C464 150DEFB4 A7AD015A */   sh        $t5, 0x15A($sp)
  .L150DEFB8:
    /* 10C468 150DEFB8 240C00C5 */  addiu      $t4, $zero, 0xC5
    /* 10C46C 150DEFBC A7AC015A */  sh         $t4, 0x15A($sp)
  .L150DEFC0:
    /* 10C470 150DEFC0 93AA018F */  lbu        $t2, 0x18F($sp)
    /* 10C474 150DEFC4 8FAB0190 */  lw         $t3, 0x190($sp)
    /* 10C478 150DEFC8 24050003 */  addiu      $a1, $zero, 0x3
    /* 10C47C 150DEFCC 240600FF */  addiu      $a2, $zero, 0xFF
    /* 10C480 150DEFD0 00003825 */  or         $a3, $zero, $zero
    /* 10C484 150DEFD4 AFA00010 */  sw         $zero, 0x10($sp)
    /* 10C488 150DEFD8 AFAA0014 */  sw         $t2, 0x14($sp)
    /* 10C48C 150DEFDC 0D44C993 */  jal        func_1513264C
    /* 10C490 150DEFE0 AFAB0018 */   sw        $t3, 0x18($sp)
    /* 10C494 150DEFE4 3C0F800A */  lui        $t7, %hi(D_800A0E50)
    /* 10C498 150DEFE8 25EF0E50 */  addiu      $t7, $t7, %lo(D_800A0E50)
    /* 10C49C 150DEFEC 26310004 */  addiu      $s1, $s1, 0x4
    /* 10C4A0 150DEFF0 26730004 */  addiu      $s3, $s3, 0x4
    /* 10C4A4 150DEFF4 2610000C */  addiu      $s0, $s0, 0xC
    /* 10C4A8 150DEFF8 26940004 */  addiu      $s4, $s4, 0x4
    /* 10C4AC 150DEFFC 162FFF9C */  bne        $s1, $t7, .L150DEE70
    /* 10C4B0 150DF000 26B50004 */   addiu     $s5, $s5, 0x4
    /* 10C4B4 150DF004 C6D20000 */  lwc1       $f18, 0x0($s6)
    /* 10C4B8 150DF008 C6C60004 */  lwc1       $f6, 0x4($s6)
    /* 10C4BC 150DF00C C6CA0008 */  lwc1       $f10, 0x8($s6)
    /* 10C4C0 150DF010 4600910D */  trunc.w.s  $f4, $f18
    /* 10C4C4 150DF014 93AD018F */  lbu        $t5, 0x18F($sp)
    /* 10C4C8 150DF018 8FAC0190 */  lw         $t4, 0x190($sp)
    /* 10C4CC 150DF01C 4600320D */  trunc.w.s  $f8, $f6
    /* 10C4D0 150DF020 44052000 */  mfc1       $a1, $f4
    /* 10C4D4 150DF024 2408001E */  addiu      $t0, $zero, 0x1E
    /* 10C4D8 150DF028 4600540D */  trunc.w.s  $f16, $f10
    /* 10C4DC 150DF02C 44064000 */  mfc1       $a2, $f8
    /* 10C4E0 150DF030 24090032 */  addiu      $t1, $zero, 0x32
    /* 10C4E4 150DF034 AFA90014 */  sw         $t1, 0x14($sp)
    /* 10C4E8 150DF038 44078000 */  mfc1       $a3, $f16
    /* 10C4EC 150DF03C AFA80010 */  sw         $t0, 0x10($sp)
    /* 10C4F0 150DF040 AFA00018 */  sw         $zero, 0x18($sp)
    /* 10C4F4 150DF044 2404FFFF */  addiu      $a0, $zero, -0x1
    /* 10C4F8 150DF048 AFAD001C */  sw         $t5, 0x1C($sp)
    /* 10C4FC 150DF04C 0D4597E0 */  jal        func_15165F80
    /* 10C500 150DF050 AFAC0020 */   sw        $t4, 0x20($sp)
    /* 10C504 150DF054 3C0143FD */  lui        $at, (0x43FD0000 >> 16)
    /* 10C508 150DF058 4481A000 */  mtc1       $at, $f20
    /* 10C50C 150DF05C 3C01800A */  lui        $at, %hi(D_800A0F18)
    /* 10C510 150DF060 C4360F18 */  lwc1       $f22, %lo(D_800A0F18)($at)
    /* 10C514 150DF064 3C01800A */  lui        $at, %hi(D_800A0F1C)
    /* 10C518 150DF068 C4380F1C */  lwc1       $f24, %lo(D_800A0F1C)($at)
    /* 10C51C 150DF06C 93AF018F */  lbu        $t7, 0x18F($sp)
    /* 10C520 150DF070 8FAE0190 */  lw         $t6, 0x190($sp)
    /* 10C524 150DF074 240A000F */  addiu      $t2, $zero, 0xF
    /* 10C528 150DF078 240B0014 */  addiu      $t3, $zero, 0x14
    /* 10C52C 150DF07C 4405A000 */  mfc1       $a1, $f20
    /* 10C530 150DF080 4406B000 */  mfc1       $a2, $f22
    /* 10C534 150DF084 4407C000 */  mfc1       $a3, $f24
    /* 10C538 150DF088 AFAB0014 */  sw         $t3, 0x14($sp)
    /* 10C53C 150DF08C AFAA0010 */  sw         $t2, 0x10($sp)
    /* 10C540 150DF090 02C02025 */  or         $a0, $s6, $zero
    /* 10C544 150DF094 AFAF0018 */  sw         $t7, 0x18($sp)
    /* 10C548 150DF098 0D475501 */  jal        func_151D5404
    /* 10C54C 150DF09C AFAE001C */   sw        $t6, 0x1C($sp)
    /* 10C550 150DF0A0 93B9018F */  lbu        $t9, 0x18F($sp)
    /* 10C554 150DF0A4 8FA80190 */  lw         $t0, 0x190($sp)
    /* 10C558 150DF0A8 4405A000 */  mfc1       $a1, $f20
    /* 10C55C 150DF0AC 4406B000 */  mfc1       $a2, $f22
    /* 10C560 150DF0B0 4407C000 */  mfc1       $a3, $f24
    /* 10C564 150DF0B4 24180005 */  addiu      $t8, $zero, 0x5
    /* 10C568 150DF0B8 AFB80010 */  sw         $t8, 0x10($sp)
    /* 10C56C 150DF0BC 02C02025 */  or         $a0, $s6, $zero
    /* 10C570 150DF0C0 AFB90014 */  sw         $t9, 0x14($sp)
    /* 10C574 150DF0C4 0D4754CD */  jal        func_151D5334
    /* 10C578 150DF0C8 AFA80018 */   sw        $t0, 0x18($sp)
    /* 10C57C 150DF0CC 02C02025 */  or         $a0, $s6, $zero
    /* 10C580 150DF0D0 93A5018F */  lbu        $a1, 0x18F($sp)
    /* 10C584 150DF0D4 0D475545 */  jal        func_151D5514
    /* 10C588 150DF0D8 8FA60190 */   lw        $a2, 0x190($sp)
    /* 10C58C 150DF0DC 02C02025 */  or         $a0, $s6, $zero
    /* 10C590 150DF0E0 93A5018F */  lbu        $a1, 0x18F($sp)
    /* 10C594 150DF0E4 0D474FFD */  jal        func_151D3FF4
    /* 10C598 150DF0E8 8FA60190 */   lw        $a2, 0x190($sp)
    /* 10C59C 150DF0EC 0D42B69A */  jal        func_150ADA68
    /* 10C5A0 150DF0F0 00000000 */   nop
    /* 10C5A4 150DF0F4 0D42B688 */  jal        func_150ADA20
    /* 10C5A8 150DF0F8 46000506 */   mov.s     $f20, $f0
    /* 10C5AC 150DF0FC 3C014080 */  lui        $at, (0x40800000 >> 16)
    /* 10C5B0 150DF100 4481C000 */  mtc1       $at, $f24
    /* 10C5B4 150DF104 3C014140 */  lui        $at, (0x41400000 >> 16)
    /* 10C5B8 150DF108 4481B000 */  mtc1       $at, $f22
    /* 10C5BC 150DF10C 4618A602 */  mul.s      $f24, $f20, $f24
    /* 10C5C0 150DF110 24010038 */  addiu      $at, $zero, 0x38
    /* 10C5C4 150DF114 0041001B */  divu       $zero, $v0, $at
    /* 10C5C8 150DF118 4616C580 */  add.s      $f22, $f24, $f22
    /* 10C5CC 150DF11C 00004810 */  mfhi       $t1
    /* 10C5D0 150DF120 252D00C8 */  addiu      $t5, $t1, 0xC8
    /* 10C5D4 150DF124 448D5000 */  mtc1       $t5, $f10
    /* 10C5D8 150DF128 4405B000 */  mfc1       $a1, $f22
    /* 10C5DC 150DF12C 3C063FD2 */  lui        $a2, (0x3FD20C49 >> 16)
    /* 10C5E0 150DF130 468052A0 */  cvt.s.w    $f10, $f10
    /* 10C5E4 150DF134 02C02025 */  or         $a0, $s6, $zero
    /* 10C5E8 150DF138 05A10005 */  bgez       $t5, .L150DF150
    /* 10C5EC 150DF13C 34C60C49 */   ori       $a2, $a2, (0x3FD20C49 & 0xFFFF)
    /* 10C5F0 150DF140 3C014F80 */  lui        $at, (0x4F800000 >> 16)
    /* 10C5F4 150DF144 44818000 */  mtc1       $at, $f16
    /* 10C5F8 150DF148 00000000 */  nop
    /* 10C5FC 150DF14C 46105280 */  add.s      $f10, $f10, $f16
  .L150DF150:
    /* 10C600 150DF150 44809000 */  mtc1       $zero, $f18
    /* 10C604 150DF154 93AC018F */  lbu        $t4, 0x18F($sp)
    /* 10C608 150DF158 8FAA0190 */  lw         $t2, 0x190($sp)
    /* 10C60C 150DF15C 44075000 */  mfc1       $a3, $f10
    /* 10C610 150DF160 AFAC0014 */  sw         $t4, 0x14($sp)
    /* 10C614 150DF164 E7B20010 */  swc1       $f18, 0x10($sp)
    /* 10C618 150DF168 0D45506E */  jal        func_151541B8
    /* 10C61C 150DF16C AFAA0018 */   sw        $t2, 0x18($sp)
    /* 10C620 150DF170 0D42B688 */  jal        func_150ADA20
    /* 10C624 150DF174 00000000 */   nop
    /* 10C628 150DF178 3C014120 */  lui        $at, (0x41200000 >> 16)
    /* 10C62C 150DF17C 44810000 */  mtc1       $at, $f0
    /* 10C630 150DF180 8FB80184 */  lw         $t8, 0x184($sp)
    /* 10C634 150DF184 3C01437A */  lui        $at, (0x437A0000 >> 16)
    /* 10C638 150DF188 44812000 */  mtc1       $at, $f4
    /* 10C63C 150DF18C 304B0003 */  andi       $t3, $v0, 0x3
    /* 10C640 150DF190 256F0003 */  addiu      $t7, $t3, 0x3
    /* 10C644 150DF194 240E00BE */  addiu      $t6, $zero, 0xBE
    /* 10C648 150DF198 24080080 */  addiu      $t0, $zero, 0x80
    /* 10C64C 150DF19C 2409FFC1 */  addiu      $t1, $zero, -0x3F
    /* 10C650 150DF1A0 240D005A */  addiu      $t5, $zero, 0x5A
    /* 10C654 150DF1A4 2719FFC0 */  addiu      $t9, $t8, -0x40
    /* 10C658 150DF1A8 A7AF00A4 */  sh         $t7, 0xA4($sp)
    /* 10C65C 150DF1AC A7AE00B4 */  sh         $t6, 0xB4($sp)
    /* 10C660 150DF1B0 A7B900BC */  sh         $t9, 0xBC($sp)
    /* 10C664 150DF1B4 A7A800BE */  sh         $t0, 0xBE($sp)
    /* 10C668 150DF1B8 A7A900C0 */  sh         $t1, 0xC0($sp)
    /* 10C66C 150DF1BC A7AD00C2 */  sh         $t5, 0xC2($sp)
    /* 10C670 150DF1C0 E7A400B8 */  swc1       $f4, 0xB8($sp)
    /* 10C674 150DF1C4 8EC10000 */  lw         $at, 0x0($s6)
    /* 10C678 150DF1C8 27AC00A8 */  addiu      $t4, $sp, 0xA8
    /* 10C67C 150DF1CC 44808000 */  mtc1       $zero, $f16
    /* 10C680 150DF1D0 AD810000 */  sw         $at, 0x0($t4)
    /* 10C684 150DF1D4 8ECF0004 */  lw         $t7, 0x4($s6)
    /* 10C688 150DF1D8 44809000 */  mtc1       $zero, $f18
    /* 10C68C 150DF1DC 44802000 */  mtc1       $zero, $f4
    /* 10C690 150DF1E0 AD8F0004 */  sw         $t7, 0x4($t4)
    /* 10C694 150DF1E4 8EC10008 */  lw         $at, 0x8($s6)
    /* 10C698 150DF1E8 240E0001 */  addiu      $t6, $zero, 0x1
    /* 10C69C 150DF1EC 24180001 */  addiu      $t8, $zero, 0x1
    /* 10C6A0 150DF1F0 AD810008 */  sw         $at, 0x8($t4)
    /* 10C6A4 150DF1F4 3C0140A0 */  lui        $at, (0x40A00000 >> 16)
    /* 10C6A8 150DF1F8 44813000 */  mtc1       $at, $f6
    /* 10C6AC 150DF1FC 3C014170 */  lui        $at, (0x41700000 >> 16)
    /* 10C6B0 150DF200 44814000 */  mtc1       $at, $f8
    /* 10C6B4 150DF204 44815000 */  mtc1       $at, $f10
    /* 10C6B8 150DF208 3C013E80 */  lui        $at, (0x3E800000 >> 16)
    /* 10C6BC 150DF20C E7A600C4 */  swc1       $f6, 0xC4($sp)
    /* 10C6C0 150DF210 44813000 */  mtc1       $at, $f6
    /* 10C6C4 150DF214 3C013F00 */  lui        $at, (0x3F000000 >> 16)
    /* 10C6C8 150DF218 E7A800CC */  swc1       $f8, 0xCC($sp)
    /* 10C6CC 150DF21C 44814000 */  mtc1       $at, $f8
    /* 10C6D0 150DF220 3C01800A */  lui        $at, %hi(D_800A0F20)
    /* 10C6D4 150DF224 E7AA00D0 */  swc1       $f10, 0xD0($sp)
    /* 10C6D8 150DF228 C42A0F20 */  lwc1       $f10, %lo(D_800A0F20)($at)
    /* 10C6DC 150DF22C 3C01800A */  lui        $at, %hi(D_800A0F24)
    /* 10C6E0 150DF230 E7B000D4 */  swc1       $f16, 0xD4($sp)
    /* 10C6E4 150DF234 C4300F24 */  lwc1       $f16, %lo(D_800A0F24)($at)
    /* 10C6E8 150DF238 3C01C0A0 */  lui        $at, (0xC0A00000 >> 16)
    /* 10C6EC 150DF23C E7B200D8 */  swc1       $f18, 0xD8($sp)
    /* 10C6F0 150DF240 44819000 */  mtc1       $at, $f18
    /* 10C6F4 150DF244 24190064 */  addiu      $t9, $zero, 0x64
    /* 10C6F8 150DF248 24080032 */  addiu      $t0, $zero, 0x32
    /* 10C6FC 150DF24C A3AE00F8 */  sb         $t6, 0xF8($sp)
    /* 10C700 150DF250 A3B800F9 */  sb         $t8, 0xF9($sp)
    /* 10C704 150DF254 A7B900FA */  sh         $t9, 0xFA($sp)
    /* 10C708 150DF258 A7A800FC */  sh         $t0, 0xFC($sp)
    /* 10C70C 150DF25C 8FA70190 */  lw         $a3, 0x190($sp)
    /* 10C710 150DF260 93A6018F */  lbu        $a2, 0x18F($sp)
    /* 10C714 150DF264 27A400A4 */  addiu      $a0, $sp, 0xA4
    /* 10C718 150DF268 00002825 */  or         $a1, $zero, $zero
    /* 10C71C 150DF26C E7A000C8 */  swc1       $f0, 0xC8($sp)
    /* 10C720 150DF270 E7A000F4 */  swc1       $f0, 0xF4($sp)
    /* 10C724 150DF274 E7A400DC */  swc1       $f4, 0xDC($sp)
    /* 10C728 150DF278 E7A600E0 */  swc1       $f6, 0xE0($sp)
    /* 10C72C 150DF27C E7A800E4 */  swc1       $f8, 0xE4($sp)
    /* 10C730 150DF280 E7AA00E8 */  swc1       $f10, 0xE8($sp)
    /* 10C734 150DF284 E7B000EC */  swc1       $f16, 0xEC($sp)
    /* 10C738 150DF288 0D469BC0 */  jal        func_151A6F00
    /* 10C73C 150DF28C E7B200F0 */   swc1      $f18, 0xF0($sp)
    /* 10C740 150DF290 27B00094 */  addiu      $s0, $sp, 0x94
    /* 10C744 150DF294 8EC10000 */  lw         $at, 0x0($s6)
    /* 10C748 150DF298 240A0001 */  addiu      $t2, $zero, 0x1
    /* 10C74C 150DF29C 240C000C */  addiu      $t4, $zero, 0xC
    /* 10C750 150DF2A0 AE010000 */  sw         $at, 0x0($s0)
    /* 10C754 150DF2A4 8ECB0004 */  lw         $t3, 0x4($s6)
    /* 10C758 150DF2A8 2404000F */  addiu      $a0, $zero, 0xF
    /* 10C75C 150DF2AC 24050008 */  addiu      $a1, $zero, 0x8
    /* 10C760 150DF2B0 AE0B0004 */  sw         $t3, 0x4($s0)
    /* 10C764 150DF2B4 8EC10008 */  lw         $at, 0x8($s6)
    /* 10C768 150DF2B8 2406FFFF */  addiu      $a2, $zero, -0x1
    /* 10C76C 150DF2BC 2407FFFF */  addiu      $a3, $zero, -0x1
    /* 10C770 150DF2C0 AE010008 */  sw         $at, 0x8($s0)
    /* 10C774 150DF2C4 8FAE0190 */  lw         $t6, 0x190($sp)
    /* 10C778 150DF2C8 93AF018F */  lbu        $t7, 0x18F($sp)
    /* 10C77C 150DF2CC AFAC0018 */  sw         $t4, 0x18($sp)
    /* 10C780 150DF2D0 AFA00014 */  sw         $zero, 0x14($sp)
    /* 10C784 150DF2D4 AFAA0010 */  sw         $t2, 0x10($sp)
    /* 10C788 150DF2D8 AFAE0020 */  sw         $t6, 0x20($sp)
    /* 10C78C 150DF2DC 0D45244C */  jal        func_15149130
    /* 10C790 150DF2E0 AFAF001C */   sw        $t7, 0x1C($sp)
    /* 10C794 150DF2E4 10400004 */  beqz       $v0, .L150DF2F8
    /* 10C798 150DF2E8 24440028 */   addiu     $a0, $v0, 0x28
    /* 10C79C 150DF2EC 02002825 */  or         $a1, $s0, $zero
    /* 10C7A0 150DF2F0 0C008BB0 */  jal        memcpy
    /* 10C7A4 150DF2F4 2406000C */   addiu     $a2, $zero, 0xC
  .L150DF2F8:
    /* 10C7A8 150DF2F8 8FBF006C */  lw         $ra, 0x6C($sp)
    /* 10C7AC 150DF2FC D7B40030 */  ldc1       $f20, 0x30($sp)
    /* 10C7B0 150DF300 D7B60038 */  ldc1       $f22, 0x38($sp)
    /* 10C7B4 150DF304 D7B80040 */  ldc1       $f24, 0x40($sp)
    /* 10C7B8 150DF308 8FB00048 */  lw         $s0, 0x48($sp)
    /* 10C7BC 150DF30C 8FB1004C */  lw         $s1, 0x4C($sp)
    /* 10C7C0 150DF310 8FB20050 */  lw         $s2, 0x50($sp)
    /* 10C7C4 150DF314 8FB30054 */  lw         $s3, 0x54($sp)
    /* 10C7C8 150DF318 8FB40058 */  lw         $s4, 0x58($sp)
    /* 10C7CC 150DF31C 8FB5005C */  lw         $s5, 0x5C($sp)
    /* 10C7D0 150DF320 8FB60060 */  lw         $s6, 0x60($sp)
    /* 10C7D4 150DF324 8FB70064 */  lw         $s7, 0x64($sp)
    /* 10C7D8 150DF328 8FBE0068 */  lw         $fp, 0x68($sp)
    /* 10C7DC 150DF32C 03E00008 */  jr         $ra
    /* 10C7E0 150DF330 27BD0188 */   addiu     $sp, $sp, 0x188
endlabel func_150DECC0

nonmatching func_150DF334, 0x184

glabel func_150DF334
    /* 10C7E4 150DF334 27BDFF68 */  addiu      $sp, $sp, -0x98
    /* 10C7E8 150DF338 AFB00030 */  sw         $s0, 0x30($sp)
    /* 10C7EC 150DF33C 00808025 */  or         $s0, $a0, $zero
    /* 10C7F0 150DF340 AFBF0034 */  sw         $ra, 0x34($sp)
    /* 10C7F4 150DF344 A3A0006F */  sb         $zero, 0x6F($sp)
    /* 10C7F8 150DF348 C6040028 */  lwc1       $f4, 0x28($s0)
    /* 10C7FC 150DF34C 3C0143FA */  lui        $at, (0x43FA0000 >> 16)
    /* 10C800 150DF350 44814000 */  mtc1       $at, $f8
    /* 10C804 150DF354 E7A40054 */  swc1       $f4, 0x54($sp)
    /* 10C808 150DF358 C606002C */  lwc1       $f6, 0x2C($s0)
    /* 10C80C 150DF35C 3C01447A */  lui        $at, (0x447A0000 >> 16)
    /* 10C810 150DF360 44812000 */  mtc1       $at, $f4
    /* 10C814 150DF364 46083280 */  add.s      $f10, $f6, $f8
    /* 10C818 150DF368 27A40054 */  addiu      $a0, $sp, 0x54
    /* 10C81C 150DF36C 00002825 */  or         $a1, $zero, $zero
    /* 10C820 150DF370 27A70070 */  addiu      $a3, $sp, 0x70
    /* 10C824 150DF374 E7AA0058 */  swc1       $f10, 0x58($sp)
    /* 10C828 150DF378 C7B20058 */  lwc1       $f18, 0x58($sp)
    /* 10C82C 150DF37C C6100030 */  lwc1       $f16, 0x30($s0)
    /* 10C830 150DF380 46049181 */  sub.s      $f6, $f18, $f4
    /* 10C834 150DF384 E7B0005C */  swc1       $f16, 0x5C($sp)
    /* 10C838 150DF388 44063000 */  mfc1       $a2, $f6
    /* 10C83C 150DF38C 0D411A5F */  jal        func_1504697C
    /* 10C840 150DF390 00000000 */   nop
    /* 10C844 150DF394 1040000A */  beqz       $v0, .L150DF3C0
    /* 10C848 150DF398 26040028 */   addiu     $a0, $s0, 0x28
    /* 10C84C 150DF39C 26020028 */  addiu      $v0, $s0, 0x28
    /* 10C850 150DF3A0 C4480000 */  lwc1       $f8, 0x0($v0)
    /* 10C854 150DF3A4 C7AA0070 */  lwc1       $f10, 0x70($sp)
    /* 10C858 150DF3A8 240E0001 */  addiu      $t6, $zero, 0x1
    /* 10C85C 150DF3AC E7A80060 */  swc1       $f8, 0x60($sp)
    /* 10C860 150DF3B0 E7AA0064 */  swc1       $f10, 0x64($sp)
    /* 10C864 150DF3B4 C4500008 */  lwc1       $f16, 0x8($v0)
    /* 10C868 150DF3B8 A3AE006F */  sb         $t6, 0x6F($sp)
    /* 10C86C 150DF3BC E7B00068 */  swc1       $f16, 0x68($sp)
  .L150DF3C0:
    /* 10C870 150DF3C0 93AF006F */  lbu        $t7, 0x6F($sp)
    /* 10C874 150DF3C4 11E00003 */  beqz       $t7, .L150DF3D4
    /* 10C878 150DF3C8 00000000 */   nop
    /* 10C87C 150DF3CC 10000001 */  b          .L150DF3D4
    /* 10C880 150DF3D0 27A40060 */   addiu     $a0, $sp, 0x60
  .L150DF3D4:
    /* 10C884 150DF3D4 0D42B688 */  jal        func_150ADA20
    /* 10C888 150DF3D8 AFA40040 */   sw        $a0, 0x40($sp)
    /* 10C88C 150DF3DC 2401003E */  addiu      $at, $zero, 0x3E
    /* 10C890 150DF3E0 0041001B */  divu       $zero, $v0, $at
    /* 10C894 150DF3E4 00002810 */  mfhi       $a1
    /* 10C898 150DF3E8 24A50078 */  addiu      $a1, $a1, 0x78
    /* 10C89C 150DF3EC 0005C400 */  sll        $t8, $a1, 16
    /* 10C8A0 150DF3F0 00182C03 */  sra        $a1, $t8, 16
    /* 10C8A4 150DF3F4 8FA40040 */  lw         $a0, 0x40($sp)
    /* 10C8A8 150DF3F8 9206000C */  lbu        $a2, 0xC($s0)
    /* 10C8AC 150DF3FC 0D43A0EB */  jal        func_150E83AC
    /* 10C8B0 150DF400 92070001 */   lbu       $a3, 0x1($s0)
    /* 10C8B4 150DF404 93A8006F */  lbu        $t0, 0x6F($sp)
    /* 10C8B8 150DF408 26020028 */  addiu      $v0, $s0, 0x28
    /* 10C8BC 150DF40C 11000003 */  beqz       $t0, .L150DF41C
    /* 10C8C0 150DF410 00000000 */   nop
    /* 10C8C4 150DF414 10000001 */  b          .L150DF41C
    /* 10C8C8 150DF418 27A20060 */   addiu     $v0, $sp, 0x60
  .L150DF41C:
    /* 10C8CC 150DF41C 8C410000 */  lw         $at, 0x0($v0)
    /* 10C8D0 150DF420 27A90048 */  addiu      $t1, $sp, 0x48
    /* 10C8D4 150DF424 AD210000 */  sw         $at, 0x0($t1)
    /* 10C8D8 150DF428 8C4B0004 */  lw         $t3, 0x4($v0)
    /* 10C8DC 150DF42C AD2B0004 */  sw         $t3, 0x4($t1)
    /* 10C8E0 150DF430 8C410008 */  lw         $at, 0x8($v0)
    /* 10C8E4 150DF434 AD210008 */  sw         $at, 0x8($t1)
    /* 10C8E8 150DF438 3C0143FA */  lui        $at, (0x43FA0000 >> 16)
    /* 10C8EC 150DF43C 44812000 */  mtc1       $at, $f4
    /* 10C8F0 150DF440 C7B2004C */  lwc1       $f18, 0x4C($sp)
    /* 10C8F4 150DF444 46049180 */  add.s      $f6, $f18, $f4
    /* 10C8F8 150DF448 0D42B688 */  jal        func_150ADA20
    /* 10C8FC 150DF44C E7A6004C */   swc1      $f6, 0x4C($sp)
    /* 10C900 150DF450 3C01447A */  lui        $at, (0x447A0000 >> 16)
    /* 10C904 150DF454 44815000 */  mtc1       $at, $f10
    /* 10C908 150DF458 24010003 */  addiu      $at, $zero, 0x3
    /* 10C90C 150DF45C 0041001B */  divu       $zero, $v0, $at
    /* 10C910 150DF460 00006010 */  mfhi       $t4
    /* 10C914 150DF464 C7A8004C */  lwc1       $f8, 0x4C($sp)
    /* 10C918 150DF468 258D0003 */  addiu      $t5, $t4, 0x3
    /* 10C91C 150DF46C 240E0001 */  addiu      $t6, $zero, 0x1
    /* 10C920 150DF470 AFAE0014 */  sw         $t6, 0x14($sp)
    /* 10C924 150DF474 AFAD0010 */  sw         $t5, 0x10($sp)
    /* 10C928 150DF478 AFA00018 */  sw         $zero, 0x18($sp)
    /* 10C92C 150DF47C 920F000C */  lbu        $t7, 0xC($s0)
    /* 10C930 150DF480 460A4401 */  sub.s      $f16, $f8, $f10
    /* 10C934 150DF484 27A40048 */  addiu      $a0, $sp, 0x48
    /* 10C938 150DF488 AFAF001C */  sw         $t7, 0x1C($sp)
    /* 10C93C 150DF48C 92180001 */  lbu        $t8, 0x1($s0)
    /* 10C940 150DF490 44058000 */  mfc1       $a1, $f16
    /* 10C944 150DF494 3C06437A */  lui        $a2, (0x437A0000 >> 16)
    /* 10C948 150DF498 27A70070 */  addiu      $a3, $sp, 0x70
    /* 10C94C 150DF49C 0D46A60D */  jal        func_151A9834
    /* 10C950 150DF4A0 AFB80020 */   sw        $t8, 0x20($sp)
    /* 10C954 150DF4A4 8FBF0034 */  lw         $ra, 0x34($sp)
    /* 10C958 150DF4A8 8FB00030 */  lw         $s0, 0x30($sp)
    /* 10C95C 150DF4AC 27BD0098 */  addiu      $sp, $sp, 0x98
    /* 10C960 150DF4B0 03E00008 */  jr         $ra
    /* 10C964 150DF4B4 00000000 */   nop
endlabel func_150DF334

nonmatching func_150DF4B8, 0x35C

glabel func_150DF4B8
    /* 10C968 150DF4B8 27BDFF30 */  addiu      $sp, $sp, -0xD0
    /* 10C96C 150DF4BC AFB70068 */  sw         $s7, 0x68($sp)
    /* 10C970 150DF4C0 AFB20054 */  sw         $s2, 0x54($sp)
    /* 10C974 150DF4C4 AFB10050 */  sw         $s1, 0x50($sp)
    /* 10C978 150DF4C8 00808825 */  or         $s1, $a0, $zero
    /* 10C97C 150DF4CC 27B20088 */  addiu      $s2, $sp, 0x88
    /* 10C980 150DF4D0 30F700FF */  andi       $s7, $a3, 0xFF
    /* 10C984 150DF4D4 AFBF006C */  sw         $ra, 0x6C($sp)
    /* 10C988 150DF4D8 AFB60064 */  sw         $s6, 0x64($sp)
    /* 10C98C 150DF4DC AFB50060 */  sw         $s5, 0x60($sp)
    /* 10C990 150DF4E0 AFB4005C */  sw         $s4, 0x5C($sp)
    /* 10C994 150DF4E4 AFB30058 */  sw         $s3, 0x58($sp)
    /* 10C998 150DF4E8 AFB0004C */  sw         $s0, 0x4C($sp)
    /* 10C99C 150DF4EC F7BE0040 */  sdc1       $f30, 0x40($sp)
    /* 10C9A0 150DF4F0 F7BC0038 */  sdc1       $f28, 0x38($sp)
    /* 10C9A4 150DF4F4 F7BA0030 */  sdc1       $f26, 0x30($sp)
    /* 10C9A8 150DF4F8 F7B80028 */  sdc1       $f24, 0x28($sp)
    /* 10C9AC 150DF4FC F7B60020 */  sdc1       $f22, 0x20($sp)
    /* 10C9B0 150DF500 F7B40018 */  sdc1       $f20, 0x18($sp)
    /* 10C9B4 150DF504 AFA500D4 */  sw         $a1, 0xD4($sp)
    /* 10C9B8 150DF508 AFA600D8 */  sw         $a2, 0xD8($sp)
    /* 10C9BC 150DF50C AFA700DC */  sw         $a3, 0xDC($sp)
    /* 10C9C0 150DF510 8E210000 */  lw         $at, 0x0($s1)
    /* 10C9C4 150DF514 AE410000 */  sw         $at, 0x0($s2)
    /* 10C9C8 150DF518 8E380004 */  lw         $t8, 0x4($s1)
    /* 10C9CC 150DF51C AE580004 */  sw         $t8, 0x4($s2)
    /* 10C9D0 150DF520 8E210008 */  lw         $at, 0x8($s1)
    /* 10C9D4 150DF524 0D42B69A */  jal        func_150ADA68
    /* 10C9D8 150DF528 AE410008 */   sw        $at, 0x8($s2)
    /* 10C9DC 150DF52C 3C013F80 */  lui        $at, (0x3F800000 >> 16)
    /* 10C9E0 150DF530 4481B000 */  mtc1       $at, $f22
    /* 10C9E4 150DF534 3C013F00 */  lui        $at, (0x3F000000 >> 16)
    /* 10C9E8 150DF538 4481C000 */  mtc1       $at, $f24
    /* 10C9EC 150DF53C 00000000 */  nop
    /* 10C9F0 150DF540 46180102 */  mul.s      $f4, $f0, $f24
    /* 10C9F4 150DF544 0D42B69A */  jal        func_150ADA68
    /* 10C9F8 150DF548 46162500 */   add.s     $f20, $f4, $f22
    /* 10C9FC 150DF54C 3C01800A */  lui        $at, %hi(D_800A0F28)
    /* 10CA00 150DF550 C43C0F28 */  lwc1       $f28, %lo(D_800A0F28)($at)
    /* 10CA04 150DF554 3C01800A */  lui        $at, %hi(D_800A0F2C)
    /* 10CA08 150DF558 C43E0F2C */  lwc1       $f30, %lo(D_800A0F2C)($at)
    /* 10CA0C 150DF55C 4614E182 */  mul.s      $f6, $f28, $f20
    /* 10CA10 150DF560 3C01800A */  lui        $at, %hi(D_800A0F30)
    /* 10CA14 150DF564 C4300F30 */  lwc1       $f16, %lo(D_800A0F30)($at)
    /* 10CA18 150DF568 4614F202 */  mul.s      $f8, $f30, $f20
    /* 10CA1C 150DF56C 3C01800A */  lui        $at, %hi(D_800A0F34)
    /* 10CA20 150DF570 C4240F34 */  lwc1       $f4, %lo(D_800A0F34)($at)
    /* 10CA24 150DF574 46180282 */  mul.s      $f10, $f0, $f24
    /* 10CA28 150DF578 E7A60094 */  swc1       $f6, 0x94($sp)
    /* 10CA2C 150DF57C 3C01800A */  lui        $at, %hi(D_800A0F38)
    /* 10CA30 150DF580 24196231 */  addiu      $t9, $zero, 0x6231
    /* 10CA34 150DF584 E7A8009C */  swc1       $f8, 0x9C($sp)
    /* 10CA38 150DF588 C4280F38 */  lwc1       $f8, %lo(D_800A0F38)($at)
    /* 10CA3C 150DF58C 24081A4D */  addiu      $t0, $zero, 0x1A4D
    /* 10CA40 150DF590 46165080 */  add.s      $f2, $f10, $f22
    /* 10CA44 150DF594 A7A800AA */  sh         $t0, 0xAA($sp)
    /* 10CA48 150DF598 A7B900A8 */  sh         $t9, 0xA8($sp)
    /* 10CA4C 150DF59C 46028482 */  mul.s      $f18, $f16, $f2
    /* 10CA50 150DF5A0 00000000 */  nop
    /* 10CA54 150DF5A4 46022182 */  mul.s      $f6, $f4, $f2
    /* 10CA58 150DF5A8 00000000 */  nop
    /* 10CA5C 150DF5AC 46024282 */  mul.s      $f10, $f8, $f2
    /* 10CA60 150DF5B0 E7B20098 */  swc1       $f18, 0x98($sp)
    /* 10CA64 150DF5B4 E7A600A0 */  swc1       $f6, 0xA0($sp)
    /* 10CA68 150DF5B8 0D42B688 */  jal        func_150ADA20
    /* 10CA6C 150DF5BC E7AA00A4 */   swc1      $f10, 0xA4($sp)
    /* 10CA70 150DF5C0 24150097 */  addiu      $s5, $zero, 0x97
    /* 10CA74 150DF5C4 0055001B */  divu       $zero, $v0, $s5
    /* 10CA78 150DF5C8 00004810 */  mfhi       $t1
    /* 10CA7C 150DF5CC 252A0096 */  addiu      $t2, $t1, 0x96
    /* 10CA80 150DF5D0 16A00002 */  bnez       $s5, .L150DF5DC
    /* 10CA84 150DF5D4 00000000 */   nop
    /* 10CA88 150DF5D8 0007000D */  break      7
  .L150DF5DC:
    /* 10CA8C 150DF5DC 240B00FF */  addiu      $t3, $zero, 0xFF
    /* 10CA90 150DF5E0 240C0001 */  addiu      $t4, $zero, 0x1
    /* 10CA94 150DF5E4 A7AA00AC */  sh         $t2, 0xAC($sp)
    /* 10CA98 150DF5E8 A3A000AE */  sb         $zero, 0xAE($sp)
    /* 10CA9C 150DF5EC A3A000AF */  sb         $zero, 0xAF($sp)
    /* 10CAA0 150DF5F0 A3A000B0 */  sb         $zero, 0xB0($sp)
    /* 10CAA4 150DF5F4 A3AB00B1 */  sb         $t3, 0xB1($sp)
    /* 10CAA8 150DF5F8 0D42B688 */  jal        func_150ADA20
    /* 10CAAC 150DF5FC A7AC00B2 */   sh        $t4, 0xB2($sp)
    /* 10CAB0 150DF600 2416009C */  addiu      $s6, $zero, 0x9C
    /* 10CAB4 150DF604 0056001B */  divu       $zero, $v0, $s6
    /* 10CAB8 150DF608 3C01800A */  lui        $at, %hi(D_800A0F3C)
    /* 10CABC 150DF60C C4320F3C */  lwc1       $f18, %lo(D_800A0F3C)($at)
    /* 10CAC0 150DF610 3C01800A */  lui        $at, %hi(D_800A0F40)
    /* 10CAC4 150DF614 C4240F40 */  lwc1       $f4, %lo(D_800A0F40)($at)
    /* 10CAC8 150DF618 3C01800A */  lui        $at, %hi(D_800A0F44)
    /* 10CACC 150DF61C 8FB400E0 */  lw         $s4, 0xE0($sp)
    /* 10CAD0 150DF620 44808000 */  mtc1       $zero, $f16
    /* 10CAD4 150DF624 C4260F44 */  lwc1       $f6, %lo(D_800A0F44)($at)
    /* 10CAD8 150DF628 00006810 */  mfhi       $t5
    /* 10CADC 150DF62C 25AF0064 */  addiu      $t7, $t5, 0x64
    /* 10CAE0 150DF630 16C00002 */  bnez       $s6, .L150DF63C
    /* 10CAE4 150DF634 00000000 */   nop
    /* 10CAE8 150DF638 0007000D */  break      7
  .L150DF63C:
    /* 10CAEC 150DF63C 240E00FF */  addiu      $t6, $zero, 0xFF
    /* 10CAF0 150DF640 24180001 */  addiu      $t8, $zero, 0x1
    /* 10CAF4 150DF644 2419000F */  addiu      $t9, $zero, 0xF
    /* 10CAF8 150DF648 A3AF00B4 */  sb         $t7, 0xB4($sp)
    /* 10CAFC 150DF64C A3AE00B5 */  sb         $t6, 0xB5($sp)
    /* 10CB00 150DF650 A3A000B6 */  sb         $zero, 0xB6($sp)
    /* 10CB04 150DF654 A3B800B7 */  sb         $t8, 0xB7($sp)
    /* 10CB08 150DF658 AFA000B8 */  sw         $zero, 0xB8($sp)
    /* 10CB0C 150DF65C A3B900BC */  sb         $t9, 0xBC($sp)
    /* 10CB10 150DF660 02402025 */  or         $a0, $s2, $zero
    /* 10CB14 150DF664 2405000A */  addiu      $a1, $zero, 0xA
    /* 10CB18 150DF668 00003025 */  or         $a2, $zero, $zero
    /* 10CB1C 150DF66C 00003825 */  or         $a3, $zero, $zero
    /* 10CB20 150DF670 AFB70010 */  sw         $s7, 0x10($sp)
    /* 10CB24 150DF674 E7B200C4 */  swc1       $f18, 0xC4($sp)
    /* 10CB28 150DF678 E7A400C8 */  swc1       $f4, 0xC8($sp)
    /* 10CB2C 150DF67C AFB40014 */  sw         $s4, 0x14($sp)
    /* 10CB30 150DF680 E7B000C0 */  swc1       $f16, 0xC0($sp)
    /* 10CB34 150DF684 0D452554 */  jal        func_15149550
    /* 10CB38 150DF688 E7A600CC */   swc1      $f6, 0xCC($sp)
    /* 10CB3C 150DF68C 0D42B688 */  jal        func_150ADA20
    /* 10CB40 150DF690 00000000 */   nop
    /* 10CB44 150DF694 24010003 */  addiu      $at, $zero, 0x3
    /* 10CB48 150DF698 0041001B */  divu       $zero, $v0, $at
    /* 10CB4C 150DF69C 00001810 */  mfhi       $v1
    /* 10CB50 150DF6A0 24700001 */  addiu      $s0, $v1, 0x1
    /* 10CB54 150DF6A4 1A00004A */  blez       $s0, .L150DF7D0
    /* 10CB58 150DF6A8 3C0141F0 */   lui       $at, (0x41F00000 >> 16)
    /* 10CB5C 150DF6AC 4481D000 */  mtc1       $at, $f26
    /* 10CB60 150DF6B0 3C013F40 */  lui        $at, (0x3F400000 >> 16)
    /* 10CB64 150DF6B4 4481B000 */  mtc1       $at, $f22
    /* 10CB68 150DF6B8 27B30090 */  addiu      $s3, $sp, 0x90
  .L150DF6BC:
    /* 10CB6C 150DF6BC 0D42B688 */  jal        func_150ADA20
    /* 10CB70 150DF6C0 00000000 */   nop
    /* 10CB74 150DF6C4 304400FF */  andi       $a0, $v0, 0xFF
    /* 10CB78 150DF6C8 00044400 */  sll        $t0, $a0, 16
    /* 10CB7C 150DF6CC 4405D000 */  mfc1       $a1, $f26
    /* 10CB80 150DF6D0 00082403 */  sra        $a0, $t0, 16
    /* 10CB84 150DF6D4 02403025 */  or         $a2, $s2, $zero
    /* 10CB88 150DF6D8 0D450E1D */  jal        func_15143874
    /* 10CB8C 150DF6DC 02603825 */   or        $a3, $s3, $zero
    /* 10CB90 150DF6E0 C7A80088 */  lwc1       $f8, 0x88($sp)
    /* 10CB94 150DF6E4 C62A0000 */  lwc1       $f10, 0x0($s1)
    /* 10CB98 150DF6E8 C7B20090 */  lwc1       $f18, 0x90($sp)
    /* 10CB9C 150DF6EC 460A4400 */  add.s      $f16, $f8, $f10
    /* 10CBA0 150DF6F0 E7B00088 */  swc1       $f16, 0x88($sp)
    /* 10CBA4 150DF6F4 C6240008 */  lwc1       $f4, 0x8($s1)
    /* 10CBA8 150DF6F8 46049180 */  add.s      $f6, $f18, $f4
    /* 10CBAC 150DF6FC 0D42B69A */  jal        func_150ADA68
    /* 10CBB0 150DF700 E7A60090 */   swc1      $f6, 0x90($sp)
    /* 10CBB4 150DF704 46180202 */  mul.s      $f8, $f0, $f24
    /* 10CBB8 150DF708 0D42B69A */  jal        func_150ADA68
    /* 10CBBC 150DF70C 46164500 */   add.s     $f20, $f8, $f22
    /* 10CBC0 150DF710 4614E282 */  mul.s      $f10, $f28, $f20
    /* 10CBC4 150DF714 3C01800A */  lui        $at, %hi(D_800A0F48)
    /* 10CBC8 150DF718 C4240F48 */  lwc1       $f4, %lo(D_800A0F48)($at)
    /* 10CBCC 150DF71C 4614F402 */  mul.s      $f16, $f30, $f20
    /* 10CBD0 150DF720 3C01800A */  lui        $at, %hi(D_800A0F4C)
    /* 10CBD4 150DF724 C4280F4C */  lwc1       $f8, %lo(D_800A0F4C)($at)
    /* 10CBD8 150DF728 46180482 */  mul.s      $f18, $f0, $f24
    /* 10CBDC 150DF72C E7AA0094 */  swc1       $f10, 0x94($sp)
    /* 10CBE0 150DF730 3C01800A */  lui        $at, %hi(D_800A0F50)
    /* 10CBE4 150DF734 E7B0009C */  swc1       $f16, 0x9C($sp)
    /* 10CBE8 150DF738 C4300F50 */  lwc1       $f16, %lo(D_800A0F50)($at)
    /* 10CBEC 150DF73C 46169080 */  add.s      $f2, $f18, $f22
    /* 10CBF0 150DF740 46022182 */  mul.s      $f6, $f4, $f2
    /* 10CBF4 150DF744 00000000 */  nop
    /* 10CBF8 150DF748 46024282 */  mul.s      $f10, $f8, $f2
    /* 10CBFC 150DF74C 00000000 */  nop
    /* 10CC00 150DF750 46028482 */  mul.s      $f18, $f16, $f2
    /* 10CC04 150DF754 E7A60098 */  swc1       $f6, 0x98($sp)
    /* 10CC08 150DF758 E7AA00A0 */  swc1       $f10, 0xA0($sp)
    /* 10CC0C 150DF75C 0D42B688 */  jal        func_150ADA20
    /* 10CC10 150DF760 E7B200A4 */   swc1      $f18, 0xA4($sp)
    /* 10CC14 150DF764 0055001B */  divu       $zero, $v0, $s5
    /* 10CC18 150DF768 00005010 */  mfhi       $t2
    /* 10CC1C 150DF76C 254B0096 */  addiu      $t3, $t2, 0x96
    /* 10CC20 150DF770 16A00002 */  bnez       $s5, .L150DF77C
    /* 10CC24 150DF774 00000000 */   nop
    /* 10CC28 150DF778 0007000D */  break      7
  .L150DF77C:
    /* 10CC2C 150DF77C A7AB00AC */  sh         $t3, 0xAC($sp)
    /* 10CC30 150DF780 0D42B688 */  jal        func_150ADA20
    /* 10CC34 150DF784 00000000 */   nop
    /* 10CC38 150DF788 0056001B */  divu       $zero, $v0, $s6
    /* 10CC3C 150DF78C 00006010 */  mfhi       $t4
    /* 10CC40 150DF790 258D0064 */  addiu      $t5, $t4, 0x64
    /* 10CC44 150DF794 16C00002 */  bnez       $s6, .L150DF7A0
    /* 10CC48 150DF798 00000000 */   nop
    /* 10CC4C 150DF79C 0007000D */  break      7
  .L150DF7A0:
    /* 10CC50 150DF7A0 A3AD00B4 */  sb         $t5, 0xB4($sp)
    /* 10CC54 150DF7A4 A3A000B7 */  sb         $zero, 0xB7($sp)
    /* 10CC58 150DF7A8 02402025 */  or         $a0, $s2, $zero
    /* 10CC5C 150DF7AC 2405000A */  addiu      $a1, $zero, 0xA
    /* 10CC60 150DF7B0 00003025 */  or         $a2, $zero, $zero
    /* 10CC64 150DF7B4 00003825 */  or         $a3, $zero, $zero
    /* 10CC68 150DF7B8 AFB70010 */  sw         $s7, 0x10($sp)
    /* 10CC6C 150DF7BC 0D452554 */  jal        func_15149550
    /* 10CC70 150DF7C0 AFB40014 */   sw        $s4, 0x14($sp)
    /* 10CC74 150DF7C4 2610FFFF */  addiu      $s0, $s0, -0x1
    /* 10CC78 150DF7C8 1600FFBC */  bnez       $s0, .L150DF6BC
    /* 10CC7C 150DF7CC 00000000 */   nop
  .L150DF7D0:
    /* 10CC80 150DF7D0 8FBF006C */  lw         $ra, 0x6C($sp)
    /* 10CC84 150DF7D4 D7B40018 */  ldc1       $f20, 0x18($sp)
    /* 10CC88 150DF7D8 D7B60020 */  ldc1       $f22, 0x20($sp)
    /* 10CC8C 150DF7DC D7B80028 */  ldc1       $f24, 0x28($sp)
    /* 10CC90 150DF7E0 D7BA0030 */  ldc1       $f26, 0x30($sp)
    /* 10CC94 150DF7E4 D7BC0038 */  ldc1       $f28, 0x38($sp)
    /* 10CC98 150DF7E8 D7BE0040 */  ldc1       $f30, 0x40($sp)
    /* 10CC9C 150DF7EC 8FB0004C */  lw         $s0, 0x4C($sp)
    /* 10CCA0 150DF7F0 8FB10050 */  lw         $s1, 0x50($sp)
    /* 10CCA4 150DF7F4 8FB20054 */  lw         $s2, 0x54($sp)
    /* 10CCA8 150DF7F8 8FB30058 */  lw         $s3, 0x58($sp)
    /* 10CCAC 150DF7FC 8FB4005C */  lw         $s4, 0x5C($sp)
    /* 10CCB0 150DF800 8FB50060 */  lw         $s5, 0x60($sp)
    /* 10CCB4 150DF804 8FB60064 */  lw         $s6, 0x64($sp)
    /* 10CCB8 150DF808 8FB70068 */  lw         $s7, 0x68($sp)
    /* 10CCBC 150DF80C 03E00008 */  jr         $ra
    /* 10CCC0 150DF810 27BD00D0 */   addiu     $sp, $sp, 0xD0
endlabel func_150DF4B8
    /* 10CCC4 150DF814 00000000 */  nop
    /* 10CCC8 150DF818 00000000 */  nop
    /* 10CCCC 150DF81C 00000000 */  nop
