.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching func_150E0D90, 0x2D0

glabel func_150E0D90
    /* 10E240 150E0D90 27BDFFD8 */  addiu      $sp, $sp, -0x28
    /* 10E244 150E0D94 AFB00020 */  sw         $s0, 0x20($sp)
    /* 10E248 150E0D98 00808025 */  or         $s0, $a0, $zero
    /* 10E24C 150E0D9C AFBF0024 */  sw         $ra, 0x24($sp)
    /* 10E250 150E0DA0 920E023E */  lbu        $t6, 0x23E($s0)
    /* 10E254 150E0DA4 24010009 */  addiu      $at, $zero, 0x9
    /* 10E258 150E0DA8 3C0F800C */  lui        $t7, %hi(D_800BE9F0)
    /* 10E25C 150E0DAC 55C10034 */  bnel       $t6, $at, .L150E0E80
    /* 10E260 150E0DB0 8E0E002C */   lw        $t6, 0x2C($s0)
    /* 10E264 150E0DB4 8DEFE9F0 */  lw         $t7, %lo(D_800BE9F0)($t7)
    /* 10E268 150E0DB8 2401001E */  addiu      $at, $zero, 0x1E
    /* 10E26C 150E0DBC 00002025 */  or         $a0, $zero, $zero
    /* 10E270 150E0DC0 15E10003 */  bne        $t7, $at, .L150E0DD0
    /* 10E274 150E0DC4 24054044 */   addiu     $a1, $zero, 0x4044
    /* 10E278 150E0DC8 0D426FEC */  jal        func_1509BFB0
    /* 10E27C 150E0DCC 24060001 */   addiu     $a2, $zero, 0x1
  .L150E0DD0:
    /* 10E280 150E0DD0 8E18002C */  lw         $t8, 0x2C($s0)
    /* 10E284 150E0DD4 24010100 */  addiu      $at, $zero, 0x100
    /* 10E288 150E0DD8 53010023 */  beql       $t8, $at, .L150E0E68
    /* 10E28C 150E0DDC 44804000 */   mtc1      $zero, $f8
    /* 10E290 150E0DE0 8E1906C8 */  lw         $t9, 0x6C8($s0)
    /* 10E294 150E0DE4 02002025 */  or         $a0, $s0, $zero
    /* 10E298 150E0DE8 24050008 */  addiu      $a1, $zero, 0x8
    /* 10E29C 150E0DEC 1720001D */  bnez       $t9, .L150E0E64
    /* 10E2A0 150E0DF0 00003025 */   or        $a2, $zero, $zero
    /* 10E2A4 150E0DF4 00003825 */  or         $a3, $zero, $zero
    /* 10E2A8 150E0DF8 0D448E4D */  jal        func_15123934
    /* 10E2AC 150E0DFC AFA00010 */   sw        $zero, 0x10($sp)
    /* 10E2B0 150E0E00 1040000D */  beqz       $v0, .L150E0E38
    /* 10E2B4 150E0E04 3C010030 */   lui       $at, (0x300000 >> 16)
    /* 10E2B8 150E0E08 8E080084 */  lw         $t0, 0x84($s0)
    /* 10E2BC 150E0E0C 240C0001 */  addiu      $t4, $zero, 0x1
    /* 10E2C0 150E0E10 240D0003 */  addiu      $t5, $zero, 0x3
    /* 10E2C4 150E0E14 01014825 */  or         $t1, $t0, $at
    /* 10E2C8 150E0E18 2401FFFB */  addiu      $at, $zero, -0x5
    /* 10E2CC 150E0E1C AE090084 */  sw         $t1, 0x84($s0)
    /* 10E2D0 150E0E20 01215824 */  and        $t3, $t1, $at
    /* 10E2D4 150E0E24 AE0B0084 */  sw         $t3, 0x84($s0)
    /* 10E2D8 150E0E28 A60C01B4 */  sh         $t4, 0x1B4($s0)
    /* 10E2DC 150E0E2C A60D01E0 */  sh         $t5, 0x1E0($s0)
    /* 10E2E0 150E0E30 0D4492C6 */  jal        func_15124B18
    /* 10E2E4 150E0E34 02002025 */   or        $a0, $s0, $zero
  .L150E0E38:
    /* 10E2E8 150E0E38 3C0142FA */  lui        $at, (0x42FA0000 >> 16)
    /* 10E2EC 150E0E3C 44810000 */  mtc1       $at, $f0
    /* 10E2F0 150E0E40 3C01435C */  lui        $at, (0x435C0000 >> 16)
    /* 10E2F4 150E0E44 44812000 */  mtc1       $at, $f4
    /* 10E2F8 150E0E48 3C0141F0 */  lui        $at, (0x41F00000 >> 16)
    /* 10E2FC 150E0E4C 44813000 */  mtc1       $at, $f6
    /* 10E300 150E0E50 E6000348 */  swc1       $f0, 0x348($s0)
    /* 10E304 150E0E54 E600034C */  swc1       $f0, 0x34C($s0)
    /* 10E308 150E0E58 E6040374 */  swc1       $f4, 0x374($s0)
    /* 10E30C 150E0E5C 10000004 */  b          .L150E0E70
    /* 10E310 150E0E60 E6060190 */   swc1      $f6, 0x190($s0)
  .L150E0E64:
    /* 10E314 150E0E64 44804000 */  mtc1       $zero, $f8
  .L150E0E68:
    /* 10E318 150E0E68 00000000 */  nop
    /* 10E31C 150E0E6C E6080190 */  swc1       $f8, 0x190($s0)
  .L150E0E70:
    /* 10E320 150E0E70 3C03800C */  lui        $v1, %hi(D_800BE9F0)
    /* 10E324 150E0E74 1000001D */  b          .L150E0EEC
    /* 10E328 150E0E78 8C63E9F0 */   lw        $v1, %lo(D_800BE9F0)($v1)
    /* 10E32C 150E0E7C 8E0E002C */  lw         $t6, 0x2C($s0)
  .L150E0E80:
    /* 10E330 150E0E80 24010008 */  addiu      $at, $zero, 0x8
    /* 10E334 150E0E84 15C1000F */  bne        $t6, $at, .L150E0EC4
    /* 10E338 150E0E88 00000000 */   nop
    /* 10E33C 150E0E8C 8E0F06C8 */  lw         $t7, 0x6C8($s0)
    /* 10E340 150E0E90 02002025 */  or         $a0, $s0, $zero
    /* 10E344 150E0E94 15E0000B */  bnez       $t7, .L150E0EC4
    /* 10E348 150E0E98 00000000 */   nop
    /* 10E34C 150E0E9C 0D448E73 */  jal        func_151239CC
    /* 10E350 150E0EA0 00002825 */   or        $a1, $zero, $zero
    /* 10E354 150E0EA4 10400007 */  beqz       $v0, .L150E0EC4
    /* 10E358 150E0EA8 3C0142DC */   lui       $at, (0x42DC0000 >> 16)
    /* 10E35C 150E0EAC 44810000 */  mtc1       $at, $f0
    /* 10E360 150E0EB0 3C014396 */  lui        $at, (0x43960000 >> 16)
    /* 10E364 150E0EB4 44815000 */  mtc1       $at, $f10
    /* 10E368 150E0EB8 E600034C */  swc1       $f0, 0x34C($s0)
    /* 10E36C 150E0EBC E6000348 */  swc1       $f0, 0x348($s0)
    /* 10E370 150E0EC0 E60A0374 */  swc1       $f10, 0x374($s0)
  .L150E0EC4:
    /* 10E374 150E0EC4 3C03800C */  lui        $v1, %hi(D_800BE9F0)
    /* 10E378 150E0EC8 8C63E9F0 */  lw         $v1, %lo(D_800BE9F0)($v1)
    /* 10E37C 150E0ECC 2401001E */  addiu      $at, $zero, 0x1E
    /* 10E380 150E0ED0 00002025 */  or         $a0, $zero, $zero
    /* 10E384 150E0ED4 14610005 */  bne        $v1, $at, .L150E0EEC
    /* 10E388 150E0ED8 24054044 */   addiu     $a1, $zero, 0x4044
    /* 10E38C 150E0EDC 0D426FEC */  jal        func_1509BFB0
    /* 10E390 150E0EE0 00003025 */   or        $a2, $zero, $zero
    /* 10E394 150E0EE4 3C03800C */  lui        $v1, %hi(D_800BE9F0)
    /* 10E398 150E0EE8 8C63E9F0 */  lw         $v1, %lo(D_800BE9F0)($v1)
  .L150E0EEC:
    /* 10E39C 150E0EEC 2401002F */  addiu      $at, $zero, 0x2F
    /* 10E3A0 150E0EF0 5461000A */  bnel       $v1, $at, .L150E0F1C
    /* 10E3A4 150E0EF4 2401001E */   addiu     $at, $zero, 0x1E
    /* 10E3A8 150E0EF8 8E180084 */  lw         $t8, 0x84($s0)
    /* 10E3AC 150E0EFC 3C017FFF */  lui        $at, (0x7FFFFFFF >> 16)
    /* 10E3B0 150E0F00 3421FFFF */  ori        $at, $at, (0x7FFFFFFF & 0xFFFF)
    /* 10E3B4 150E0F04 0301C824 */  and        $t9, $t8, $at
    /* 10E3B8 150E0F08 AE190084 */  sw         $t9, 0x84($s0)
    /* 10E3BC 150E0F0C 3C03800C */  lui        $v1, %hi(D_800BE9F0)
    /* 10E3C0 150E0F10 1000002D */  b          .L150E0FC8
    /* 10E3C4 150E0F14 8C63E9F0 */   lw        $v1, %lo(D_800BE9F0)($v1)
    /* 10E3C8 150E0F18 2401001E */  addiu      $at, $zero, 0x1E
  .L150E0F1C:
    /* 10E3CC 150E0F1C 1461002A */  bne        $v1, $at, .L150E0FC8
    /* 10E3D0 150E0F20 24040001 */   addiu     $a0, $zero, 0x1
    /* 10E3D4 150E0F24 24054042 */  addiu      $a1, $zero, 0x4042
    /* 10E3D8 150E0F28 24060006 */  addiu      $a2, $zero, 0x6
    /* 10E3DC 150E0F2C 0D426F90 */  jal        func_1509BE40
    /* 10E3E0 150E0F30 34079000 */   ori       $a3, $zero, 0x9000
    /* 10E3E4 150E0F34 10400007 */  beqz       $v0, .L150E0F54
    /* 10E3E8 150E0F38 24040001 */   addiu     $a0, $zero, 0x1
    /* 10E3EC 150E0F3C 8E080084 */  lw         $t0, 0x84($s0)
    /* 10E3F0 150E0F40 3C017FFF */  lui        $at, (0x7FFFFFFF >> 16)
    /* 10E3F4 150E0F44 3421FFFF */  ori        $at, $at, (0x7FFFFFFF & 0xFFFF)
    /* 10E3F8 150E0F48 01014824 */  and        $t1, $t0, $at
    /* 10E3FC 150E0F4C 10000005 */  b          .L150E0F64
    /* 10E400 150E0F50 AE090084 */   sw        $t1, 0x84($s0)
  .L150E0F54:
    /* 10E404 150E0F54 8E0A0084 */  lw         $t2, 0x84($s0)
    /* 10E408 150E0F58 3C018000 */  lui        $at, (0x80000000 >> 16)
    /* 10E40C 150E0F5C 01415825 */  or         $t3, $t2, $at
    /* 10E410 150E0F60 AE0B0084 */  sw         $t3, 0x84($s0)
  .L150E0F64:
    /* 10E414 150E0F64 24054044 */  addiu      $a1, $zero, 0x4044
    /* 10E418 150E0F68 24060006 */  addiu      $a2, $zero, 0x6
    /* 10E41C 150E0F6C 0D426F90 */  jal        func_1509BE40
    /* 10E420 150E0F70 24072000 */   addiu     $a3, $zero, 0x2000
    /* 10E424 150E0F74 1040000C */  beqz       $v0, .L150E0FA8
    /* 10E428 150E0F78 3C01DFFF */   lui       $at, (0xDFFFEFEF >> 16)
    /* 10E42C 150E0F7C 8E0C0084 */  lw         $t4, 0x84($s0)
    /* 10E430 150E0F80 3C012000 */  lui        $at, (0x20001010 >> 16)
    /* 10E434 150E0F84 34211010 */  ori        $at, $at, (0x20001010 & 0xFFFF)
    /* 10E438 150E0F88 01816825 */  or         $t5, $t4, $at
    /* 10E43C 150E0F8C 2401FFF7 */  addiu      $at, $zero, -0x9
    /* 10E440 150E0F90 AE0D0084 */  sw         $t5, 0x84($s0)
    /* 10E444 150E0F94 01A17824 */  and        $t7, $t5, $at
    /* 10E448 150E0F98 AE0F0084 */  sw         $t7, 0x84($s0)
    /* 10E44C 150E0F9C 3C03800C */  lui        $v1, %hi(D_800BE9F0)
    /* 10E450 150E0FA0 10000009 */  b          .L150E0FC8
    /* 10E454 150E0FA4 8C63E9F0 */   lw        $v1, %lo(D_800BE9F0)($v1)
  .L150E0FA8:
    /* 10E458 150E0FA8 8E180084 */  lw         $t8, 0x84($s0)
    /* 10E45C 150E0FAC 3421EFEF */  ori        $at, $at, (0xDFFFEFEF & 0xFFFF)
    /* 10E460 150E0FB0 3C03800C */  lui        $v1, %hi(D_800BE9F0)
    /* 10E464 150E0FB4 0301C824 */  and        $t9, $t8, $at
    /* 10E468 150E0FB8 AE190084 */  sw         $t9, 0x84($s0)
    /* 10E46C 150E0FBC 37290008 */  ori        $t1, $t9, 0x8
    /* 10E470 150E0FC0 AE090084 */  sw         $t1, 0x84($s0)
    /* 10E474 150E0FC4 8C63E9F0 */  lw         $v1, %lo(D_800BE9F0)($v1)
  .L150E0FC8:
    /* 10E478 150E0FC8 2401001B */  addiu      $at, $zero, 0x1B
    /* 10E47C 150E0FCC 1461001F */  bne        $v1, $at, .L150E104C
    /* 10E480 150E0FD0 24040001 */   addiu     $a0, $zero, 0x1
    /* 10E484 150E0FD4 2405406E */  addiu      $a1, $zero, 0x406E
    /* 10E488 150E0FD8 24060006 */  addiu      $a2, $zero, 0x6
    /* 10E48C 150E0FDC 0D426F90 */  jal        func_1509BE40
    /* 10E490 150E0FE0 34079000 */   ori       $a3, $zero, 0x9000
    /* 10E494 150E0FE4 10400005 */  beqz       $v0, .L150E0FFC
    /* 10E498 150E0FE8 24040001 */   addiu     $a0, $zero, 0x1
    /* 10E49C 150E0FEC 8E0A0084 */  lw         $t2, 0x84($s0)
    /* 10E4A0 150E0FF0 354B0200 */  ori        $t3, $t2, 0x200
    /* 10E4A4 150E0FF4 10000005 */  b          .L150E100C
    /* 10E4A8 150E0FF8 AE0B0084 */   sw        $t3, 0x84($s0)
  .L150E0FFC:
    /* 10E4AC 150E0FFC 8E0C0084 */  lw         $t4, 0x84($s0)
    /* 10E4B0 150E1000 2401FDFF */  addiu      $at, $zero, -0x201
    /* 10E4B4 150E1004 01816824 */  and        $t5, $t4, $at
    /* 10E4B8 150E1008 AE0D0084 */  sw         $t5, 0x84($s0)
  .L150E100C:
    /* 10E4BC 150E100C 2405406F */  addiu      $a1, $zero, 0x406F
    /* 10E4C0 150E1010 24060006 */  addiu      $a2, $zero, 0x6
    /* 10E4C4 150E1014 0D426F90 */  jal        func_1509BE40
    /* 10E4C8 150E1018 34079000 */   ori       $a3, $zero, 0x9000
    /* 10E4CC 150E101C 50400007 */  beql       $v0, $zero, .L150E103C
    /* 10E4D0 150E1020 8E180084 */   lw        $t8, 0x84($s0)
    /* 10E4D4 150E1024 8E0E0084 */  lw         $t6, 0x84($s0)
    /* 10E4D8 150E1028 3C018000 */  lui        $at, (0x80000000 >> 16)
    /* 10E4DC 150E102C 01C17825 */  or         $t7, $t6, $at
    /* 10E4E0 150E1030 10000006 */  b          .L150E104C
    /* 10E4E4 150E1034 AE0F0084 */   sw        $t7, 0x84($s0)
    /* 10E4E8 150E1038 8E180084 */  lw         $t8, 0x84($s0)
  .L150E103C:
    /* 10E4EC 150E103C 3C017FFF */  lui        $at, (0x7FFFFFFF >> 16)
    /* 10E4F0 150E1040 3421FFFF */  ori        $at, $at, (0x7FFFFFFF & 0xFFFF)
    /* 10E4F4 150E1044 0301C824 */  and        $t9, $t8, $at
    /* 10E4F8 150E1048 AE190084 */  sw         $t9, 0x84($s0)
  .L150E104C:
    /* 10E4FC 150E104C 8FBF0024 */  lw         $ra, 0x24($sp)
    /* 10E500 150E1050 8FB00020 */  lw         $s0, 0x20($sp)
    /* 10E504 150E1054 27BD0028 */  addiu      $sp, $sp, 0x28
    /* 10E508 150E1058 03E00008 */  jr         $ra
    /* 10E50C 150E105C 00000000 */   nop
endlabel func_150E0D90

nonmatching func_150E1060, 0xEC

glabel func_150E1060
    /* 10E510 150E1060 27BDFFB8 */  addiu      $sp, $sp, -0x48
    /* 10E514 150E1064 AFBF002C */  sw         $ra, 0x2C($sp)
    /* 10E518 150E1068 AFA40048 */  sw         $a0, 0x48($sp)
    /* 10E51C 150E106C AFA5004C */  sw         $a1, 0x4C($sp)
    /* 10E520 150E1070 AFA60050 */  sw         $a2, 0x50($sp)
    /* 10E524 150E1074 308700FF */  andi       $a3, $a0, 0xFF
    /* 10E528 150E1078 04E10003 */  bgez       $a3, .L150E1088
    /* 10E52C 150E107C 00E01025 */   or        $v0, $a3, $zero
    /* 10E530 150E1080 1000002E */  b          .L150E113C
    /* 10E534 150E1084 00001025 */   or        $v0, $zero, $zero
  .L150E1088:
    /* 10E538 150E1088 28410002 */  slti       $at, $v0, 0x2
    /* 10E53C 150E108C 14200003 */  bnez       $at, .L150E109C
    /* 10E540 150E1090 3C04800A */   lui       $a0, %hi(D_800A0FE0)
    /* 10E544 150E1094 10000029 */  b          .L150E113C
    /* 10E548 150E1098 00001025 */   or        $v0, $zero, $zero
  .L150E109C:
    /* 10E54C 150E109C 00872021 */  addu       $a0, $a0, $a3
    /* 10E550 150E10A0 A3A70034 */  sb         $a3, 0x34($sp)
    /* 10E554 150E10A4 0D44526B */  jal        func_151149AC
    /* 10E558 150E10A8 90840FE0 */   lbu       $a0, %lo(D_800A0FE0)($a0)
    /* 10E55C 150E10AC 14400003 */  bnez       $v0, .L150E10BC
    /* 10E560 150E10B0 AFA20038 */   sw        $v0, 0x38($sp)
    /* 10E564 150E10B4 10000021 */  b          .L150E113C
    /* 10E568 150E10B8 00001025 */   or        $v0, $zero, $zero
  .L150E10BC:
    /* 10E56C 150E10BC 0D443E00 */  jal        func_1510F800
    /* 10E570 150E10C0 00002025 */   or        $a0, $zero, $zero
    /* 10E574 150E10C4 8FAE0038 */  lw         $t6, 0x38($sp)
    /* 10E578 150E10C8 85C40010 */  lh         $a0, 0x10($t6)
    /* 10E57C 150E10CC 0D443F48 */  jal        func_1510FD20
    /* 10E580 150E10D0 85C50014 */   lh        $a1, 0x14($t6)
    /* 10E584 150E10D4 44802000 */  mtc1       $zero, $f4
    /* 10E588 150E10D8 93B9004F */  lbu        $t9, 0x4F($sp)
    /* 10E58C 150E10DC 8FA80050 */  lw         $t0, 0x50($sp)
    /* 10E590 150E10E0 240F001F */  addiu      $t7, $zero, 0x1F
    /* 10E594 150E10E4 24180010 */  addiu      $t8, $zero, 0x10
    /* 10E598 150E10E8 AFA2003C */  sw         $v0, 0x3C($sp)
    /* 10E59C 150E10EC AFB80018 */  sw         $t8, 0x18($sp)
    /* 10E5A0 150E10F0 AFAF0014 */  sw         $t7, 0x14($sp)
    /* 10E5A4 150E10F4 2404012C */  addiu      $a0, $zero, 0x12C
    /* 10E5A8 150E10F8 2405FFFF */  addiu      $a1, $zero, -0x1
    /* 10E5AC 150E10FC 2406001F */  addiu      $a2, $zero, 0x1F
    /* 10E5B0 150E1100 2407FFFF */  addiu      $a3, $zero, -0x1
    /* 10E5B4 150E1104 AFA00010 */  sw         $zero, 0x10($sp)
    /* 10E5B8 150E1108 E7A40040 */  swc1       $f4, 0x40($sp)
    /* 10E5BC 150E110C AFB9001C */  sw         $t9, 0x1C($sp)
    /* 10E5C0 150E1110 0D45244C */  jal        func_15149130
    /* 10E5C4 150E1114 AFA80020 */   sw        $t0, 0x20($sp)
    /* 10E5C8 150E1118 10400007 */  beqz       $v0, .L150E1138
    /* 10E5CC 150E111C 00401825 */   or        $v1, $v0, $zero
    /* 10E5D0 150E1120 24440028 */  addiu      $a0, $v0, 0x28
    /* 10E5D4 150E1124 27A50034 */  addiu      $a1, $sp, 0x34
    /* 10E5D8 150E1128 24060010 */  addiu      $a2, $zero, 0x10
    /* 10E5DC 150E112C 0C008BB0 */  jal        memcpy
    /* 10E5E0 150E1130 AFA20044 */   sw        $v0, 0x44($sp)
    /* 10E5E4 150E1134 8FA30044 */  lw         $v1, 0x44($sp)
  .L150E1138:
    /* 10E5E8 150E1138 00601025 */  or         $v0, $v1, $zero
  .L150E113C:
    /* 10E5EC 150E113C 8FBF002C */  lw         $ra, 0x2C($sp)
    /* 10E5F0 150E1140 27BD0048 */  addiu      $sp, $sp, 0x48
    /* 10E5F4 150E1144 03E00008 */  jr         $ra
    /* 10E5F8 150E1148 00000000 */   nop
endlabel func_150E1060

nonmatching func_150E114C, 0x41C

glabel func_150E114C
    /* 10E5FC 150E114C 27BDFED0 */  addiu      $sp, $sp, -0x130
    /* 10E600 150E1150 AFB20058 */  sw         $s2, 0x58($sp)
    /* 10E604 150E1154 00809025 */  or         $s2, $a0, $zero
    /* 10E608 150E1158 AFBF006C */  sw         $ra, 0x6C($sp)
    /* 10E60C 150E115C AFB60068 */  sw         $s6, 0x68($sp)
    /* 10E610 150E1160 AFB50064 */  sw         $s5, 0x64($sp)
    /* 10E614 150E1164 AFB40060 */  sw         $s4, 0x60($sp)
    /* 10E618 150E1168 AFB3005C */  sw         $s3, 0x5C($sp)
    /* 10E61C 150E116C AFB10054 */  sw         $s1, 0x54($sp)
    /* 10E620 150E1170 AFB00050 */  sw         $s0, 0x50($sp)
    /* 10E624 150E1174 F7BE0048 */  sdc1       $f30, 0x48($sp)
    /* 10E628 150E1178 F7BC0040 */  sdc1       $f28, 0x40($sp)
    /* 10E62C 150E117C F7BA0038 */  sdc1       $f26, 0x38($sp)
    /* 10E630 150E1180 F7B80030 */  sdc1       $f24, 0x30($sp)
    /* 10E634 150E1184 F7B60028 */  sdc1       $f22, 0x28($sp)
    /* 10E638 150E1188 F7B40020 */  sdc1       $f20, 0x20($sp)
    /* 10E63C 150E118C 0D42B69A */  jal        func_150ADA68
    /* 10E640 150E1190 00000000 */   nop
    /* 10E644 150E1194 3C013F80 */  lui        $at, (0x3F800000 >> 16)
    /* 10E648 150E1198 4481A000 */  mtc1       $at, $f20
    /* 10E64C 150E119C 3C01434C */  lui        $at, (0x434C0000 >> 16)
    /* 10E650 150E11A0 44812000 */  mtc1       $at, $f4
    /* 10E654 150E11A4 3C01431F */  lui        $at, (0x431F0000 >> 16)
    /* 10E658 150E11A8 44813000 */  mtc1       $at, $f6
    /* 10E65C 150E11AC 3C01800A */  lui        $at, %hi(D_800A1014)
    /* 10E660 150E11B0 C4301014 */  lwc1       $f16, %lo(D_800A1014)($at)
    /* 10E664 150E11B4 46060202 */  mul.s      $f8, $f0, $f6
    /* 10E668 150E11B8 3C01800C */  lui        $at, %hi(D_800BE9A4)
    /* 10E66C 150E11BC C426E9A4 */  lwc1       $f6, %lo(D_800BE9A4)($at)
    /* 10E670 150E11C0 26510028 */  addiu      $s1, $s2, 0x28
    /* 10E674 150E11C4 3C048008 */  lui        $a0, %hi(D_80082FA0)
    /* 10E678 150E11C8 46082280 */  add.s      $f10, $f4, $f8
    /* 10E67C 150E11CC C628000C */  lwc1       $f8, 0xC($s1)
    /* 10E680 150E11D0 46105482 */  mul.s      $f18, $f10, $f16
    /* 10E684 150E11D4 00000000 */  nop
    /* 10E688 150E11D8 46069102 */  mul.s      $f4, $f18, $f6
    /* 10E68C 150E11DC 46044280 */  add.s      $f10, $f8, $f4
    /* 10E690 150E11E0 E62A000C */  swc1       $f10, 0xC($s1)
    /* 10E694 150E11E4 C622000C */  lwc1       $f2, 0xC($s1)
    /* 10E698 150E11E8 4602A03C */  c.lt.s     $f20, $f2
    /* 10E69C 150E11EC 00000000 */  nop
    /* 10E6A0 150E11F0 450000CD */  bc1f       .L150E1528
    /* 10E6A4 150E11F4 00000000 */   nop
    /* 10E6A8 150E11F8 8C842FA0 */  lw         $a0, %lo(D_80082FA0)($a0)
    /* 10E6AC 150E11FC 00001025 */  or         $v0, $zero, $zero
    /* 10E6B0 150E1200 00001825 */  or         $v1, $zero, $zero
    /* 10E6B4 150E1204 04800009 */  bltz       $a0, .L150E122C
    /* 10E6B8 150E1208 240B0029 */   addiu     $t3, $zero, 0x29
  .L150E120C:
    /* 10E6BC 150E120C 240E0001 */  addiu      $t6, $zero, 0x1
    /* 10E6C0 150E1210 004E7804 */  sllv       $t7, $t6, $v0
    /* 10E6C4 150E1214 24420001 */  addiu      $v0, $v0, 0x1
    /* 10E6C8 150E1218 006F1825 */  or         $v1, $v1, $t7
    /* 10E6CC 150E121C 0082082A */  slt        $at, $a0, $v0
    /* 10E6D0 150E1220 0003C400 */  sll        $t8, $v1, 16
    /* 10E6D4 150E1224 1020FFF9 */  beqz       $at, .L150E120C
    /* 10E6D8 150E1228 00181C03 */   sra       $v1, $t8, 16
  .L150E122C:
    /* 10E6DC 150E122C 8E280008 */  lw         $t0, 0x8($s1)
    /* 10E6E0 150E1230 3C0D0020 */  lui        $t5, (0x200005 >> 16)
    /* 10E6E4 150E1234 240C4403 */  addiu      $t4, $zero, 0x4403
    /* 10E6E8 150E1238 85090002 */  lh         $t1, 0x2($t0)
    /* 10E6EC 150E123C 35AD0005 */  ori        $t5, $t5, (0x200005 & 0xFFFF)
    /* 10E6F0 150E1240 240E0021 */  addiu      $t6, $zero, 0x21
    /* 10E6F4 150E1244 01235024 */  and        $t2, $t1, $v1
    /* 10E6F8 150E1248 1540000A */  bnez       $t2, .L150E1274
    /* 10E6FC 150E124C 240F0007 */   addiu     $t7, $zero, 0x7
    /* 10E700 150E1250 46141401 */  sub.s      $f16, $f2, $f20
  .L150E1254:
    /* 10E704 150E1254 E630000C */  swc1       $f16, 0xC($s1)
    /* 10E708 150E1258 C622000C */  lwc1       $f2, 0xC($s1)
    /* 10E70C 150E125C 4602A03C */  c.lt.s     $f20, $f2
    /* 10E710 150E1260 00000000 */  nop
    /* 10E714 150E1264 4503FFFB */  bc1tl      .L150E1254
    /* 10E718 150E1268 46141401 */   sub.s     $f16, $f2, $f20
    /* 10E71C 150E126C 100000AF */  b          .L150E152C
    /* 10E720 150E1270 8FBF006C */   lw        $ra, 0x6C($sp)
  .L150E1274:
    /* 10E724 150E1274 4480B000 */  mtc1       $zero, $f22
    /* 10E728 150E1278 3C180001 */  lui        $t8, (0x1CE05 >> 16)
    /* 10E72C 150E127C 3C01800A */  lui        $at, %hi(D_800A1018)
    /* 10E730 150E1280 C4321018 */  lwc1       $f18, %lo(D_800A1018)($at)
    /* 10E734 150E1284 3C01800A */  lui        $at, %hi(D_800A101C)
    /* 10E738 150E1288 C426101C */  lwc1       $f6, %lo(D_800A101C)($at)
    /* 10E73C 150E128C 3718CE05 */  ori        $t8, $t8, (0x1CE05 & 0xFFFF)
    /* 10E740 150E1290 24190006 */  addiu      $t9, $zero, 0x6
    /* 10E744 150E1294 24080008 */  addiu      $t0, $zero, 0x8
    /* 10E748 150E1298 24090010 */  addiu      $t1, $zero, 0x10
    /* 10E74C 150E129C 240AFFFF */  addiu      $t2, $zero, -0x1
    /* 10E750 150E12A0 A3AB00D1 */  sb         $t3, 0xD1($sp)
    /* 10E754 150E12A4 A7AC00BC */  sh         $t4, 0xBC($sp)
    /* 10E758 150E12A8 AFAD00B4 */  sw         $t5, 0xB4($sp)
    /* 10E75C 150E12AC A7AE00D2 */  sh         $t6, 0xD2($sp)
    /* 10E760 150E12B0 A7AF00D4 */  sh         $t7, 0xD4($sp)
    /* 10E764 150E12B4 AFB8010C */  sw         $t8, 0x10C($sp)
    /* 10E768 150E12B8 A3B90114 */  sb         $t9, 0x114($sp)
    /* 10E76C 150E12BC A3A80115 */  sb         $t0, 0x115($sp)
    /* 10E770 150E12C0 A3A90116 */  sb         $t1, 0x116($sp)
    /* 10E774 150E12C4 A3AA0117 */  sb         $t2, 0x117($sp)
    /* 10E778 150E12C8 240BFFFF */  addiu      $t3, $zero, -0x1
    /* 10E77C 150E12CC 240C0027 */  addiu      $t4, $zero, 0x27
    /* 10E780 150E12D0 240D00DD */  addiu      $t5, $zero, 0xDD
    /* 10E784 150E12D4 240E00D3 */  addiu      $t6, $zero, 0xD3
    /* 10E788 150E12D8 240F00CD */  addiu      $t7, $zero, 0xCD
    /* 10E78C 150E12DC 241800FF */  addiu      $t8, $zero, 0xFF
    /* 10E790 150E12E0 24190057 */  addiu      $t9, $zero, 0x57
    /* 10E794 150E12E4 24080055 */  addiu      $t0, $zero, 0x55
    /* 10E798 150E12E8 2409005A */  addiu      $t1, $zero, 0x5A
    /* 10E79C 150E12EC 240A00FF */  addiu      $t2, $zero, 0xFF
    /* 10E7A0 150E12F0 AFA000B8 */  sw         $zero, 0xB8($sp)
    /* 10E7A4 150E12F4 AFA000C0 */  sw         $zero, 0xC0($sp)
    /* 10E7A8 150E12F8 AFA000C4 */  sw         $zero, 0xC4($sp)
    /* 10E7AC 150E12FC E7B60108 */  swc1       $f22, 0x108($sp)
    /* 10E7B0 150E1300 A3AB0118 */  sb         $t3, 0x118($sp)
    /* 10E7B4 150E1304 A3A00119 */  sb         $zero, 0x119($sp)
    /* 10E7B8 150E1308 A7AC00D6 */  sh         $t4, 0xD6($sp)
    /* 10E7BC 150E130C A3AD00C8 */  sb         $t5, 0xC8($sp)
    /* 10E7C0 150E1310 A3AE00C9 */  sb         $t6, 0xC9($sp)
    /* 10E7C4 150E1314 A3AF00CA */  sb         $t7, 0xCA($sp)
    /* 10E7C8 150E1318 A3B800CB */  sb         $t8, 0xCB($sp)
    /* 10E7CC 150E131C A3B900CC */  sb         $t9, 0xCC($sp)
    /* 10E7D0 150E1320 A3A800CD */  sb         $t0, 0xCD($sp)
    /* 10E7D4 150E1324 A3A900CE */  sb         $t1, 0xCE($sp)
    /* 10E7D8 150E1328 A3AA00D0 */  sb         $t2, 0xD0($sp)
    /* 10E7DC 150E132C E7B200B0 */  swc1       $f18, 0xB0($sp)
    /* 10E7E0 150E1330 E7A600D8 */  swc1       $f6, 0xD8($sp)
    /* 10E7E4 150E1334 922B0000 */  lbu        $t3, 0x0($s1)
    /* 10E7E8 150E1338 3C0D800A */  lui        $t5, %hi(D_800A0FE4)
    /* 10E7EC 150E133C 25AD0FE4 */  addiu      $t5, $t5, %lo(D_800A0FE4)
    /* 10E7F0 150E1340 000B6080 */  sll        $t4, $t3, 2
    /* 10E7F4 150E1344 018B6023 */  subu       $t4, $t4, $t3
    /* 10E7F8 150E1348 000C6080 */  sll        $t4, $t4, 2
    /* 10E7FC 150E134C 018D7021 */  addu       $t6, $t4, $t5
    /* 10E800 150E1350 AFAE009C */  sw         $t6, 0x9C($sp)
    /* 10E804 150E1354 922F0000 */  lbu        $t7, 0x0($s1)
    /* 10E808 150E1358 3C19800A */  lui        $t9, %hi(D_800A0FFC)
    /* 10E80C 150E135C 27390FFC */  addiu      $t9, $t9, %lo(D_800A0FFC)
    /* 10E810 150E1360 000FC080 */  sll        $t8, $t7, 2
    /* 10E814 150E1364 030FC023 */  subu       $t8, $t8, $t7
    /* 10E818 150E1368 0018C080 */  sll        $t8, $t8, 2
    /* 10E81C 150E136C 03194021 */  addu       $t0, $t8, $t9
    /* 10E820 150E1370 27A900E4 */  addiu      $t1, $sp, 0xE4
    /* 10E824 150E1374 27AA00A4 */  addiu      $t2, $sp, 0xA4
    /* 10E828 150E1378 AFA800A0 */  sw         $t0, 0xA0($sp)
    /* 10E82C 150E137C AFA90094 */  sw         $t1, 0x94($sp)
    /* 10E830 150E1380 AFAA0098 */  sw         $t2, 0x98($sp)
    /* 10E834 150E1384 8E240004 */  lw         $a0, 0x4($s1)
    /* 10E838 150E1388 27A5009C */  addiu      $a1, $sp, 0x9C
    /* 10E83C 150E138C 27A60094 */  addiu      $a2, $sp, 0x94
    /* 10E840 150E1390 0D451734 */  jal        func_15145CD0
    /* 10E844 150E1394 24070002 */   addiu     $a3, $zero, 0x2
    /* 10E848 150E1398 C7A800A4 */  lwc1       $f8, 0xA4($sp)
    /* 10E84C 150E139C C7A400E4 */  lwc1       $f4, 0xE4($sp)
    /* 10E850 150E13A0 C7B000A8 */  lwc1       $f16, 0xA8($sp)
    /* 10E854 150E13A4 C7B200E8 */  lwc1       $f18, 0xE8($sp)
    /* 10E858 150E13A8 46044281 */  sub.s      $f10, $f8, $f4
    /* 10E85C 150E13AC C7A400EC */  lwc1       $f4, 0xEC($sp)
    /* 10E860 150E13B0 C7A800AC */  lwc1       $f8, 0xAC($sp)
    /* 10E864 150E13B4 46128181 */  sub.s      $f6, $f16, $f18
    /* 10E868 150E13B8 E7AA00A4 */  swc1       $f10, 0xA4($sp)
    /* 10E86C 150E13BC 3C0143B2 */  lui        $at, (0x43B20000 >> 16)
    /* 10E870 150E13C0 46044281 */  sub.s      $f10, $f8, $f4
    /* 10E874 150E13C4 4481F000 */  mtc1       $at, $f30
    /* 10E878 150E13C8 E7A600A8 */  swc1       $f6, 0xA8($sp)
    /* 10E87C 150E13CC 3C014343 */  lui        $at, (0x43430000 >> 16)
    /* 10E880 150E13D0 E7AA00AC */  swc1       $f10, 0xAC($sp)
    /* 10E884 150E13D4 4481E000 */  mtc1       $at, $f28
    /* 10E888 150E13D8 3C01800A */  lui        $at, %hi(D_800A1020)
    /* 10E88C 150E13DC C43A1020 */  lwc1       $f26, %lo(D_800A1020)($at)
    /* 10E890 150E13E0 3C014325 */  lui        $at, (0x43250000 >> 16)
    /* 10E894 150E13E4 4481C000 */  mtc1       $at, $f24
    /* 10E898 150E13E8 27B600B0 */  addiu      $s6, $sp, 0xB0
    /* 10E89C 150E13EC 27B500B4 */  addiu      $s5, $sp, 0xB4
    /* 10E8A0 150E13F0 24140011 */  addiu      $s4, $zero, 0x11
    /* 10E8A4 150E13F4 2413FF3F */  addiu      $s3, $zero, -0xC1
    /* 10E8A8 150E13F8 8FAB010C */  lw         $t3, 0x10C($sp)
  .L150E13FC:
    /* 10E8AC 150E13FC 01736024 */  and        $t4, $t3, $s3
    /* 10E8B0 150E1400 0D42B688 */  jal        func_150ADA20
    /* 10E8B4 150E1404 AFAC010C */   sw        $t4, 0x10C($sp)
    /* 10E8B8 150E1408 304D0001 */  andi       $t5, $v0, 0x1
    /* 10E8BC 150E140C 11A00003 */  beqz       $t5, .L150E141C
    /* 10E8C0 150E1410 00008025 */   or        $s0, $zero, $zero
    /* 10E8C4 150E1414 10000001 */  b          .L150E141C
    /* 10E8C8 150E1418 24100080 */   addiu     $s0, $zero, 0x80
  .L150E141C:
    /* 10E8CC 150E141C 0D42B688 */  jal        func_150ADA20
    /* 10E8D0 150E1420 00000000 */   nop
    /* 10E8D4 150E1424 304E0001 */  andi       $t6, $v0, 0x1
    /* 10E8D8 150E1428 11C00003 */  beqz       $t6, .L150E1438
    /* 10E8DC 150E142C 8FAF010C */   lw        $t7, 0x10C($sp)
    /* 10E8E0 150E1430 10000002 */  b          .L150E143C
    /* 10E8E4 150E1434 24020040 */   addiu     $v0, $zero, 0x40
  .L150E1438:
    /* 10E8E8 150E1438 00001025 */  or         $v0, $zero, $zero
  .L150E143C:
    /* 10E8EC 150E143C 0050C025 */  or         $t8, $v0, $s0
    /* 10E8F0 150E1440 01F8C825 */  or         $t9, $t7, $t8
    /* 10E8F4 150E1444 240800FF */  addiu      $t0, $zero, 0xFF
    /* 10E8F8 150E1448 AFB9010C */  sw         $t9, 0x10C($sp)
    /* 10E8FC 150E144C E7B600F0 */  swc1       $f22, 0xF0($sp)
    /* 10E900 150E1450 E7B600F4 */  swc1       $f22, 0xF4($sp)
    /* 10E904 150E1454 E7B600F8 */  swc1       $f22, 0xF8($sp)
    /* 10E908 150E1458 0D42B688 */  jal        func_150ADA20
    /* 10E90C 150E145C A3A800CF */   sb        $t0, 0xCF($sp)
    /* 10E910 150E1460 0054001B */  divu       $zero, $v0, $s4
    /* 10E914 150E1464 00004810 */  mfhi       $t1
    /* 10E918 150E1468 252A0032 */  addiu      $t2, $t1, 0x32
    /* 10E91C 150E146C 16800002 */  bnez       $s4, .L150E1478
    /* 10E920 150E1470 00000000 */   nop
    /* 10E924 150E1474 0007000D */  break      7
  .L150E1478:
    /* 10E928 150E1478 A7AA00BE */  sh         $t2, 0xBE($sp)
    /* 10E92C 150E147C 0D42B69A */  jal        func_150ADA68
    /* 10E930 150E1480 00000000 */   nop
    /* 10E934 150E1484 46180402 */  mul.s      $f16, $f0, $f24
    /* 10E938 150E1488 461A8080 */  add.s      $f2, $f16, $f26
    /* 10E93C 150E148C E7A200DC */  swc1       $f2, 0xDC($sp)
    /* 10E940 150E1490 0D42B69A */  jal        func_150ADA68
    /* 10E944 150E1494 E7A200E0 */   swc1      $f2, 0xE0($sp)
    /* 10E948 150E1498 461C0482 */  mul.s      $f18, $f0, $f28
    /* 10E94C 150E149C 3C01800A */  lui        $at, %hi(D_800A1024)
    /* 10E950 150E14A0 C4281024 */  lwc1       $f8, %lo(D_800A1024)($at)
    /* 10E954 150E14A4 C7A400A4 */  lwc1       $f4, 0xA4($sp)
    /* 10E958 150E14A8 C7B000A8 */  lwc1       $f16, 0xA8($sp)
    /* 10E95C 150E14AC 02A02025 */  or         $a0, $s5, $zero
    /* 10E960 150E14B0 24050001 */  addiu      $a1, $zero, 0x1
    /* 10E964 150E14B4 461E9180 */  add.s      $f6, $f18, $f30
    /* 10E968 150E14B8 24060004 */  addiu      $a2, $zero, 0x4
    /* 10E96C 150E14BC 46083082 */  mul.s      $f2, $f6, $f8
    /* 10E970 150E14C0 C7A600AC */  lwc1       $f6, 0xAC($sp)
    /* 10E974 150E14C4 46022282 */  mul.s      $f10, $f4, $f2
    /* 10E978 150E14C8 00000000 */  nop
    /* 10E97C 150E14CC 46028482 */  mul.s      $f18, $f16, $f2
    /* 10E980 150E14D0 00000000 */  nop
    /* 10E984 150E14D4 46023202 */  mul.s      $f8, $f6, $f2
    /* 10E988 150E14D8 E7AA00FC */  swc1       $f10, 0xFC($sp)
    /* 10E98C 150E14DC E7B20100 */  swc1       $f18, 0x100($sp)
    /* 10E990 150E14E0 E7A80104 */  swc1       $f8, 0x104($sp)
    /* 10E994 150E14E4 924B0001 */  lbu        $t3, 0x1($s2)
    /* 10E998 150E14E8 9247000C */  lbu        $a3, 0xC($s2)
    /* 10E99C 150E14EC 0D44C0DD */  jal        func_15130374
    /* 10E9A0 150E14F0 AFAB0010 */   sw        $t3, 0x10($sp)
    /* 10E9A4 150E14F4 10400004 */  beqz       $v0, .L150E1508
    /* 10E9A8 150E14F8 244400A8 */   addiu     $a0, $v0, 0xA8
    /* 10E9AC 150E14FC 02C02825 */  or         $a1, $s6, $zero
    /* 10E9B0 150E1500 0C008BB0 */  jal        memcpy
    /* 10E9B4 150E1504 24060004 */   addiu     $a2, $zero, 0x4
  .L150E1508:
    /* 10E9B8 150E1508 C624000C */  lwc1       $f4, 0xC($s1)
    /* 10E9BC 150E150C 46142281 */  sub.s      $f10, $f4, $f20
    /* 10E9C0 150E1510 E62A000C */  swc1       $f10, 0xC($s1)
    /* 10E9C4 150E1514 C630000C */  lwc1       $f16, 0xC($s1)
    /* 10E9C8 150E1518 4610A03C */  c.lt.s     $f20, $f16
    /* 10E9CC 150E151C 00000000 */  nop
    /* 10E9D0 150E1520 4503FFB6 */  bc1tl      .L150E13FC
    /* 10E9D4 150E1524 8FAB010C */   lw        $t3, 0x10C($sp)
  .L150E1528:
    /* 10E9D8 150E1528 8FBF006C */  lw         $ra, 0x6C($sp)
  .L150E152C:
    /* 10E9DC 150E152C D7B40020 */  ldc1       $f20, 0x20($sp)
    /* 10E9E0 150E1530 D7B60028 */  ldc1       $f22, 0x28($sp)
    /* 10E9E4 150E1534 D7B80030 */  ldc1       $f24, 0x30($sp)
    /* 10E9E8 150E1538 D7BA0038 */  ldc1       $f26, 0x38($sp)
    /* 10E9EC 150E153C D7BC0040 */  ldc1       $f28, 0x40($sp)
    /* 10E9F0 150E1540 D7BE0048 */  ldc1       $f30, 0x48($sp)
    /* 10E9F4 150E1544 8FB00050 */  lw         $s0, 0x50($sp)
    /* 10E9F8 150E1548 8FB10054 */  lw         $s1, 0x54($sp)
    /* 10E9FC 150E154C 8FB20058 */  lw         $s2, 0x58($sp)
    /* 10EA00 150E1550 8FB3005C */  lw         $s3, 0x5C($sp)
    /* 10EA04 150E1554 8FB40060 */  lw         $s4, 0x60($sp)
    /* 10EA08 150E1558 8FB50064 */  lw         $s5, 0x64($sp)
    /* 10EA0C 150E155C 8FB60068 */  lw         $s6, 0x68($sp)
    /* 10EA10 150E1560 03E00008 */  jr         $ra
    /* 10EA14 150E1564 27BD0130 */   addiu     $sp, $sp, 0x130
endlabel func_150E114C
    /* 10EA18 150E1568 00000000 */  nop
    /* 10EA1C 150E156C 00000000 */  nop
