.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching func_150EBEC0, 0x514

glabel func_150EBEC0
    /* 119370 150EBEC0 27BDFEF0 */  addiu      $sp, $sp, -0x110
    /* 119374 150EBEC4 AFBF0074 */  sw         $ra, 0x74($sp)
    /* 119378 150EBEC8 AFA40110 */  sw         $a0, 0x110($sp)
    /* 11937C 150EBECC AFA50114 */  sw         $a1, 0x114($sp)
    /* 119380 150EBED0 AFA60118 */  sw         $a2, 0x118($sp)
    /* 119384 150EBED4 AFA7011C */  sw         $a3, 0x11C($sp)
    /* 119388 150EBED8 8FAE0110 */  lw         $t6, 0x110($sp)
    /* 11938C 150EBEDC 93AF0117 */  lbu        $t7, 0x117($sp)
    /* 119390 150EBEE0 15C00003 */  bnez       $t6, .L150EBEF0
    /* 119394 150EBEE4 29E10002 */   slti      $at, $t7, 0x2
    /* 119398 150EBEE8 10000136 */  b          .L150EC3C4
    /* 11939C 150EBEEC 00001025 */   or        $v0, $zero, $zero
  .L150EBEF0:
    /* 1193A0 150EBEF0 14200003 */  bnez       $at, .L150EBF00
    /* 1193A4 150EBEF4 8FB80110 */   lw        $t8, 0x110($sp)
    /* 1193A8 150EBEF8 10000132 */  b          .L150EC3C4
    /* 1193AC 150EBEFC 00001025 */   or        $v0, $zero, $zero
  .L150EBF00:
    /* 1193B0 150EBF00 8F1901D4 */  lw         $t9, 0x1D4($t8)
    /* 1193B4 150EBF04 3C08800A */  lui        $t0, %hi(D_800A1500)
    /* 1193B8 150EBF08 25081500 */  addiu      $t0, $t0, %lo(D_800A1500)
    /* 1193BC 150EBF0C 17200003 */  bnez       $t9, .L150EBF1C
    /* 1193C0 150EBF10 3C09800A */   lui       $t1, %hi(D_800A150C)
    /* 1193C4 150EBF14 1000012B */  b          .L150EC3C4
    /* 1193C8 150EBF18 00001025 */   or        $v0, $zero, $zero
  .L150EBF1C:
    /* 1193CC 150EBF1C 8FAC0110 */  lw         $t4, 0x110($sp)
    /* 1193D0 150EBF20 2529150C */  addiu      $t1, $t1, %lo(D_800A150C)
    /* 1193D4 150EBF24 27AA0100 */  addiu      $t2, $sp, 0x100
    /* 1193D8 150EBF28 27AB00F4 */  addiu      $t3, $sp, 0xF4
    /* 1193DC 150EBF2C AFA800D0 */  sw         $t0, 0xD0($sp)
    /* 1193E0 150EBF30 AFA900D4 */  sw         $t1, 0xD4($sp)
    /* 1193E4 150EBF34 AFAA00C8 */  sw         $t2, 0xC8($sp)
    /* 1193E8 150EBF38 AFAB00CC */  sw         $t3, 0xCC($sp)
    /* 1193EC 150EBF3C 8D8601D4 */  lw         $a2, 0x1D4($t4)
    /* 1193F0 150EBF40 27A400D0 */  addiu      $a0, $sp, 0xD0
    /* 1193F4 150EBF44 27A500C8 */  addiu      $a1, $sp, 0xC8
    /* 1193F8 150EBF48 24070002 */  addiu      $a3, $zero, 0x2
    /* 1193FC 150EBF4C 0D4517A9 */  jal        func_15145EA4
    /* 119400 150EBF50 24C60080 */   addiu     $a2, $a2, 0x80
    /* 119404 150EBF54 C7A400F4 */  lwc1       $f4, 0xF4($sp)
    /* 119408 150EBF58 C7A60100 */  lwc1       $f6, 0x100($sp)
    /* 11940C 150EBF5C C7AA00F8 */  lwc1       $f10, 0xF8($sp)
    /* 119410 150EBF60 C7B00104 */  lwc1       $f16, 0x104($sp)
    /* 119414 150EBF64 46062201 */  sub.s      $f8, $f4, $f6
    /* 119418 150EBF68 C7A60108 */  lwc1       $f6, 0x108($sp)
    /* 11941C 150EBF6C C7A400FC */  lwc1       $f4, 0xFC($sp)
    /* 119420 150EBF70 46105481 */  sub.s      $f18, $f10, $f16
    /* 119424 150EBF74 E7A800F4 */  swc1       $f8, 0xF4($sp)
    /* 119428 150EBF78 93A30117 */  lbu        $v1, 0x117($sp)
    /* 11942C 150EBF7C 46062201 */  sub.s      $f8, $f4, $f6
    /* 119430 150EBF80 E7B200F8 */  swc1       $f18, 0xF8($sp)
    /* 119434 150EBF84 00036880 */  sll        $t5, $v1, 2
    /* 119438 150EBF88 01A36823 */  subu       $t5, $t5, $v1
    /* 11943C 150EBF8C E7A800FC */  swc1       $f8, 0xFC($sp)
    /* 119440 150EBF90 3C19800A */  lui        $t9, %hi(D_800A1548)
    /* 119444 150EBF94 3C0E800A */  lui        $t6, %hi(D_800A1518)
    /* 119448 150EBF98 27391548 */  addiu      $t9, $t9, %lo(D_800A1548)
    /* 11944C 150EBF9C 8FAA0110 */  lw         $t2, 0x110($sp)
    /* 119450 150EBFA0 25CE1518 */  addiu      $t6, $t6, %lo(D_800A1518)
    /* 119454 150EBFA4 000D6880 */  sll        $t5, $t5, 2
    /* 119458 150EBFA8 00791021 */  addu       $v0, $v1, $t9
    /* 11945C 150EBFAC 90480000 */  lbu        $t0, 0x0($v0)
    /* 119460 150EBFB0 01AE7821 */  addu       $t7, $t5, $t6
    /* 119464 150EBFB4 27B800E8 */  addiu      $t8, $sp, 0xE8
    /* 119468 150EBFB8 AFAF00C4 */  sw         $t7, 0xC4($sp)
    /* 11946C 150EBFBC AFB800C0 */  sw         $t8, 0xC0($sp)
    /* 119470 150EBFC0 8D4B01D4 */  lw         $t3, 0x1D4($t2)
    /* 119474 150EBFC4 00084980 */  sll        $t1, $t0, 6
    /* 119478 150EBFC8 AFA2007C */  sw         $v0, 0x7C($sp)
    /* 11947C 150EBFCC 27A400C4 */  addiu      $a0, $sp, 0xC4
    /* 119480 150EBFD0 27A500C0 */  addiu      $a1, $sp, 0xC0
    /* 119484 150EBFD4 24070001 */  addiu      $a3, $zero, 0x1
    /* 119488 150EBFD8 0D4517A9 */  jal        func_15145EA4
    /* 11948C 150EBFDC 012B3021 */   addu      $a2, $t1, $t3
    /* 119490 150EBFE0 C7AA00F8 */  lwc1       $f10, 0xF8($sp)
    /* 119494 150EBFE4 C7B000FC */  lwc1       $f16, 0xFC($sp)
    /* 119498 150EBFE8 44809000 */  mtc1       $zero, $f18
    /* 11949C 150EBFEC 27AC00B4 */  addiu      $t4, $sp, 0xB4
    /* 1194A0 150EBFF0 27AD00B8 */  addiu      $t5, $sp, 0xB8
    /* 1194A4 150EBFF4 27AE00BC */  addiu      $t6, $sp, 0xBC
    /* 1194A8 150EBFF8 AFAE0028 */  sw         $t6, 0x28($sp)
    /* 1194AC 150EBFFC AFAD0024 */  sw         $t5, 0x24($sp)
    /* 1194B0 150EC000 AFAC0020 */  sw         $t4, 0x20($sp)
    /* 1194B4 150EC004 C7AC0100 */  lwc1       $f12, 0x100($sp)
    /* 1194B8 150EC008 C7AE0104 */  lwc1       $f14, 0x104($sp)
    /* 1194BC 150EC00C 8FA60108 */  lw         $a2, 0x108($sp)
    /* 1194C0 150EC010 8FA700F4 */  lw         $a3, 0xF4($sp)
    /* 1194C4 150EC014 AFA00018 */  sw         $zero, 0x18($sp)
    /* 1194C8 150EC018 AFA0001C */  sw         $zero, 0x1C($sp)
    /* 1194CC 150EC01C AFA0002C */  sw         $zero, 0x2C($sp)
    /* 1194D0 150EC020 AFA00030 */  sw         $zero, 0x30($sp)
    /* 1194D4 150EC024 AFA00034 */  sw         $zero, 0x34($sp)
    /* 1194D8 150EC028 E7AA0010 */  swc1       $f10, 0x10($sp)
    /* 1194DC 150EC02C E7B00014 */  swc1       $f16, 0x14($sp)
    /* 1194E0 150EC030 0D42B270 */  jal        func_150AC9C0
    /* 1194E4 150EC034 E7B20038 */   swc1      $f18, 0x38($sp)
    /* 1194E8 150EC038 50400027 */  beql       $v0, $zero, .L150EC0D8
    /* 1194EC 150EC03C 27AA00F4 */   addiu     $t2, $sp, 0xF4
    /* 1194F0 150EC040 0D42B688 */  jal        func_150ADA20
    /* 1194F4 150EC044 00000000 */   nop
    /* 1194F8 150EC048 0D42B69A */  jal        func_150ADA68
    /* 1194FC 150EC04C AFA20088 */   sw        $v0, 0x88($sp)
    /* 119500 150EC050 3C0142A0 */  lui        $at, (0x42A00000 >> 16)
    /* 119504 150EC054 44812000 */  mtc1       $at, $f4
    /* 119508 150EC058 8FA40088 */  lw         $a0, 0x88($sp)
    /* 11950C 150EC05C 27A600AC */  addiu      $a2, $sp, 0xAC
    /* 119510 150EC060 46040182 */  mul.s      $f6, $f0, $f4
    /* 119514 150EC064 308F00FF */  andi       $t7, $a0, 0xFF
    /* 119518 150EC068 000FC400 */  sll        $t8, $t7, 16
    /* 11951C 150EC06C 00182403 */  sra        $a0, $t8, 16
    /* 119520 150EC070 27A700B0 */  addiu      $a3, $sp, 0xB0
    /* 119524 150EC074 44053000 */  mfc1       $a1, $f6
    /* 119528 150EC078 0D450E1D */  jal        func_15143874
    /* 11952C 150EC07C 00000000 */   nop
    /* 119530 150EC080 C7A000B4 */  lwc1       $f0, 0xB4($sp)
    /* 119534 150EC084 C7A200BC */  lwc1       $f2, 0xBC($sp)
    /* 119538 150EC088 C7A800AC */  lwc1       $f8, 0xAC($sp)
    /* 11953C 150EC08C C7AA00B0 */  lwc1       $f10, 0xB0($sp)
    /* 119540 150EC090 C7B000E8 */  lwc1       $f16, 0xE8($sp)
    /* 119544 150EC094 46080000 */  add.s      $f0, $f0, $f8
    /* 119548 150EC098 C7A400B8 */  lwc1       $f4, 0xB8($sp)
    /* 11954C 150EC09C C7A600EC */  lwc1       $f6, 0xEC($sp)
    /* 119550 150EC0A0 460A1080 */  add.s      $f2, $f2, $f10
    /* 119554 150EC0A4 C7AA00F0 */  lwc1       $f10, 0xF0($sp)
    /* 119558 150EC0A8 27A800D8 */  addiu      $t0, $sp, 0xD8
    /* 11955C 150EC0AC 46100481 */  sub.s      $f18, $f0, $f16
    /* 119560 150EC0B0 AFA800E4 */  sw         $t0, 0xE4($sp)
    /* 119564 150EC0B4 46062201 */  sub.s      $f8, $f4, $f6
    /* 119568 150EC0B8 E7B200D8 */  swc1       $f18, 0xD8($sp)
    /* 11956C 150EC0BC 460A1401 */  sub.s      $f16, $f2, $f10
    /* 119570 150EC0C0 E7A800DC */  swc1       $f8, 0xDC($sp)
    /* 119574 150EC0C4 E7B000E0 */  swc1       $f16, 0xE0($sp)
    /* 119578 150EC0C8 E7A000B4 */  swc1       $f0, 0xB4($sp)
    /* 11957C 150EC0CC 10000003 */  b          .L150EC0DC
    /* 119580 150EC0D0 E7A200BC */   swc1      $f2, 0xBC($sp)
    /* 119584 150EC0D4 27AA00F4 */  addiu      $t2, $sp, 0xF4
  .L150EC0D8:
    /* 119588 150EC0D8 AFAA00E4 */  sw         $t2, 0xE4($sp)
  .L150EC0DC:
    /* 11958C 150EC0DC 0D42B69A */  jal        func_150ADA68
    /* 119590 150EC0E0 00000000 */   nop
    /* 119594 150EC0E4 0D42B69A */  jal        func_150ADA68
    /* 119598 150EC0E8 E7A00084 */   swc1      $f0, 0x84($sp)
    /* 11959C 150EC0EC 0D42B688 */  jal        func_150ADA20
    /* 1195A0 150EC0F0 E7A0008C */   swc1      $f0, 0x8C($sp)
    /* 1195A4 150EC0F4 3C014302 */  lui        $at, (0x43020000 >> 16)
    /* 1195A8 150EC0F8 44819000 */  mtc1       $at, $f18
    /* 1195AC 150EC0FC 3C01800A */  lui        $at, %hi(D_800A154C)
    /* 1195B0 150EC100 C424154C */  lwc1       $f4, %lo(D_800A154C)($at)
    /* 1195B4 150EC104 3C014190 */  lui        $at, (0x41900000 >> 16)
    /* 1195B8 150EC108 44814000 */  mtc1       $at, $f8
    /* 1195BC 150EC10C C7A60084 */  lwc1       $f6, 0x84($sp)
    /* 1195C0 150EC110 3C0141E8 */  lui        $at, (0x41E80000 >> 16)
    /* 1195C4 150EC114 44818000 */  mtc1       $at, $f16
    /* 1195C8 150EC118 46083282 */  mul.s      $f10, $f6, $f8
    /* 1195CC 150EC11C 3C0143C8 */  lui        $at, (0x43C80000 >> 16)
    /* 1195D0 150EC120 E7A4001C */  swc1       $f4, 0x1C($sp)
    /* 1195D4 150EC124 C7A4008C */  lwc1       $f4, 0x8C($sp)
    /* 1195D8 150EC128 44813000 */  mtc1       $at, $f6
    /* 1195DC 150EC12C E7B20018 */  swc1       $f18, 0x18($sp)
    /* 1195E0 150EC130 3C014383 */  lui        $at, (0x43830000 >> 16)
    /* 1195E4 150EC134 46062202 */  mul.s      $f8, $f4, $f6
    /* 1195E8 150EC138 46105480 */  add.s      $f18, $f10, $f16
    /* 1195EC 150EC13C 44815000 */  mtc1       $at, $f10
    /* 1195F0 150EC140 240900FF */  addiu      $t1, $zero, 0xFF
    /* 1195F4 150EC144 AFA9002C */  sw         $t1, 0x2C($sp)
    /* 1195F8 150EC148 3C0142C8 */  lui        $at, (0x42C80000 >> 16)
    /* 1195FC 150EC14C E7B20020 */  swc1       $f18, 0x20($sp)
    /* 119600 150EC150 460A4400 */  add.s      $f16, $f8, $f10
    /* 119604 150EC154 44819000 */  mtc1       $at, $f18
    /* 119608 150EC158 8FA9011C */  lw         $t1, 0x11C($sp)
    /* 11960C 150EC15C 44802000 */  mtc1       $zero, $f4
    /* 119610 150EC160 8FAB0110 */  lw         $t3, 0x110($sp)
    /* 119614 150EC164 93AA011B */  lbu        $t2, 0x11B($sp)
    /* 119618 150EC168 240C0001 */  addiu      $t4, $zero, 0x1
    /* 11961C 150EC16C 240D0001 */  addiu      $t5, $zero, 0x1
    /* 119620 150EC170 240E0001 */  addiu      $t6, $zero, 0x1
    /* 119624 150EC174 240F0003 */  addiu      $t7, $zero, 0x3
    /* 119628 150EC178 2418001A */  addiu      $t8, $zero, 0x1A
    /* 11962C 150EC17C 241900FF */  addiu      $t9, $zero, 0xFF
    /* 119630 150EC180 2408FFFF */  addiu      $t0, $zero, -0x1
    /* 119634 150EC184 AFA8005C */  sw         $t0, 0x5C($sp)
    /* 119638 150EC188 AFB90058 */  sw         $t9, 0x58($sp)
    /* 11963C 150EC18C AFB80050 */  sw         $t8, 0x50($sp)
    /* 119640 150EC190 AFAF004C */  sw         $t7, 0x4C($sp)
    /* 119644 150EC194 AFAE0048 */  sw         $t6, 0x48($sp)
    /* 119648 150EC198 AFAD0038 */  sw         $t5, 0x38($sp)
    /* 11964C 150EC19C AFAC0034 */  sw         $t4, 0x34($sp)
    /* 119650 150EC1A0 E7B00024 */  swc1       $f16, 0x24($sp)
    /* 119654 150EC1A4 27A400E8 */  addiu      $a0, $sp, 0xE8
    /* 119658 150EC1A8 8FA500E4 */  lw         $a1, 0xE4($sp)
    /* 11965C 150EC1AC 00003025 */  or         $a2, $zero, $zero
    /* 119660 150EC1B0 00003825 */  or         $a3, $zero, $zero
    /* 119664 150EC1B4 AFA00010 */  sw         $zero, 0x10($sp)
    /* 119668 150EC1B8 AFA00014 */  sw         $zero, 0x14($sp)
    /* 11966C 150EC1BC AFA0003C */  sw         $zero, 0x3C($sp)
    /* 119670 150EC1C0 AFA00040 */  sw         $zero, 0x40($sp)
    /* 119674 150EC1C4 AFA00044 */  sw         $zero, 0x44($sp)
    /* 119678 150EC1C8 AFA00060 */  sw         $zero, 0x60($sp)
    /* 11967C 150EC1CC AFA90068 */  sw         $t1, 0x68($sp)
    /* 119680 150EC1D0 E7B20028 */  swc1       $f18, 0x28($sp)
    /* 119684 150EC1D4 AFAB0030 */  sw         $t3, 0x30($sp)
    /* 119688 150EC1D8 E7A40054 */  swc1       $f4, 0x54($sp)
    /* 11968C 150EC1DC 0D4708A7 */  jal        func_151C229C
    /* 119690 150EC1E0 AFAA0064 */   sw        $t2, 0x64($sp)
    /* 119694 150EC1E4 AFA2010C */  sw         $v0, 0x10C($sp)
    /* 119698 150EC1E8 240B0003 */  addiu      $t3, $zero, 0x3
    /* 11969C 150EC1EC 240CFFFF */  addiu      $t4, $zero, -0x1
    /* 1196A0 150EC1F0 A3AB00A4 */  sb         $t3, 0xA4($sp)
    /* 1196A4 150EC1F4 0D42B688 */  jal        func_150ADA20
    /* 1196A8 150EC1F8 A3AC00A5 */   sb        $t4, 0xA5($sp)
    /* 1196AC 150EC1FC 24010003 */  addiu      $at, $zero, 0x3
    /* 1196B0 150EC200 0041001B */  divu       $zero, $v0, $at
    /* 1196B4 150EC204 C7A600E8 */  lwc1       $f6, 0xE8($sp)
    /* 1196B8 150EC208 C7AA00EC */  lwc1       $f10, 0xEC($sp)
    /* 1196BC 150EC20C C7B200F0 */  lwc1       $f18, 0xF0($sp)
    /* 1196C0 150EC210 4600320D */  trunc.w.s  $f8, $f6
    /* 1196C4 150EC214 00006810 */  mfhi       $t5
    /* 1196C8 150EC218 25AE0003 */  addiu      $t6, $t5, 0x3
    /* 1196CC 150EC21C 4600540D */  trunc.w.s  $f16, $f10
    /* 1196D0 150EC220 44184000 */  mfc1       $t8, $f8
    /* 1196D4 150EC224 A7AE00A6 */  sh         $t6, 0xA6($sp)
    /* 1196D8 150EC228 4600910D */  trunc.w.s  $f4, $f18
    /* 1196DC 150EC22C 44088000 */  mfc1       $t0, $f16
    /* 1196E0 150EC230 A3A000A8 */  sb         $zero, 0xA8($sp)
    /* 1196E4 150EC234 AFB80098 */  sw         $t8, 0x98($sp)
    /* 1196E8 150EC238 44092000 */  mfc1       $t1, $f4
    /* 1196EC 150EC23C AFA8009C */  sw         $t0, 0x9C($sp)
    /* 1196F0 150EC240 0D42B688 */  jal        func_150ADA20
    /* 1196F4 150EC244 AFA900A0 */   sw        $t1, 0xA0($sp)
    /* 1196F8 150EC248 2401000D */  addiu      $at, $zero, 0xD
    /* 1196FC 150EC24C 0041001B */  divu       $zero, $v0, $at
    /* 119700 150EC250 93AE011B */  lbu        $t6, 0x11B($sp)
    /* 119704 150EC254 8FAF011C */  lw         $t7, 0x11C($sp)
    /* 119708 150EC258 00003010 */  mfhi       $a2
    /* 11970C 150EC25C 240B00FF */  addiu      $t3, $zero, 0xFF
    /* 119710 150EC260 240C00FF */  addiu      $t4, $zero, 0xFF
    /* 119714 150EC264 240D00FF */  addiu      $t5, $zero, 0xFF
    /* 119718 150EC268 AFAD0018 */  sw         $t5, 0x18($sp)
    /* 11971C 150EC26C AFAC0014 */  sw         $t4, 0x14($sp)
    /* 119720 150EC270 AFAB0010 */  sw         $t3, 0x10($sp)
    /* 119724 150EC274 24C6005A */  addiu      $a2, $a2, 0x5A
    /* 119728 150EC278 27A400A4 */  addiu      $a0, $sp, 0xA4
    /* 11972C 150EC27C 27A50098 */  addiu      $a1, $sp, 0x98
    /* 119730 150EC280 240700FF */  addiu      $a3, $zero, 0xFF
    /* 119734 150EC284 AFA0001C */  sw         $zero, 0x1C($sp)
    /* 119738 150EC288 AFA00020 */  sw         $zero, 0x20($sp)
    /* 11973C 150EC28C AFAE0024 */  sw         $t6, 0x24($sp)
    /* 119740 150EC290 0D4580B0 */  jal        func_151602C0
    /* 119744 150EC294 AFAF0028 */   sw        $t7, 0x28($sp)
    /* 119748 150EC298 0D42B69A */  jal        func_150ADA68
    /* 11974C 150EC29C 00000000 */   nop
    /* 119750 150EC2A0 3C01800A */  lui        $at, %hi(D_800A1550)
    /* 119754 150EC2A4 C4261550 */  lwc1       $f6, %lo(D_800A1550)($at)
    /* 119758 150EC2A8 3C01800A */  lui        $at, %hi(D_800A1554)
    /* 11975C 150EC2AC C42A1554 */  lwc1       $f10, %lo(D_800A1554)($at)
    /* 119760 150EC2B0 46060202 */  mul.s      $f8, $f0, $f6
    /* 119764 150EC2B4 3C01800A */  lui        $at, %hi(D_800A1558)
    /* 119768 150EC2B8 C4321558 */  lwc1       $f18, %lo(D_800A1558)($at)
    /* 11976C 150EC2BC 460A4400 */  add.s      $f16, $f8, $f10
    /* 119770 150EC2C0 46128102 */  mul.s      $f4, $f16, $f18
    /* 119774 150EC2C4 0D42B69A */  jal        func_150ADA68
    /* 119778 150EC2C8 E7A40094 */   swc1      $f4, 0x94($sp)
    /* 11977C 150EC2CC 3C01800A */  lui        $at, %hi(D_800A155C)
    /* 119780 150EC2D0 C426155C */  lwc1       $f6, %lo(D_800A155C)($at)
    /* 119784 150EC2D4 3C014472 */  lui        $at, (0x44720000 >> 16)
    /* 119788 150EC2D8 44815000 */  mtc1       $at, $f10
    /* 11978C 150EC2DC 46060202 */  mul.s      $f8, $f0, $f6
    /* 119790 150EC2E0 3C01800A */  lui        $at, %hi(D_800A1560)
    /* 119794 150EC2E4 C4321560 */  lwc1       $f18, %lo(D_800A1560)($at)
    /* 119798 150EC2E8 460A4400 */  add.s      $f16, $f8, $f10
    /* 11979C 150EC2EC 46128102 */  mul.s      $f4, $f16, $f18
    /* 1197A0 150EC2F0 0D42B688 */  jal        func_150ADA20
    /* 1197A4 150EC2F4 E7A40090 */   swc1      $f4, 0x90($sp)
    /* 1197A8 150EC2F8 0D42B688 */  jal        func_150ADA20
    /* 1197AC 150EC2FC AFA20080 */   sw        $v0, 0x80($sp)
    /* 1197B0 150EC300 0D42B69A */  jal        func_150ADA68
    /* 1197B4 150EC304 AFA20088 */   sw        $v0, 0x88($sp)
    /* 1197B8 150EC308 8FAB0080 */  lw         $t3, 0x80($sp)
    /* 1197BC 150EC30C 24010006 */  addiu      $at, $zero, 0x6
    /* 1197C0 150EC310 8FAE0088 */  lw         $t6, 0x88($sp)
    /* 1197C4 150EC314 0161001B */  divu       $zero, $t3, $at
    /* 1197C8 150EC318 24010034 */  addiu      $at, $zero, 0x34
    /* 1197CC 150EC31C 00006010 */  mfhi       $t4
    /* 1197D0 150EC320 8FB8007C */  lw         $t8, 0x7C($sp)
    /* 1197D4 150EC324 93A20117 */  lbu        $v0, 0x117($sp)
    /* 1197D8 150EC328 01C1001B */  divu       $zero, $t6, $at
    /* 1197DC 150EC32C 3C01800A */  lui        $at, %hi(D_800A1564)
    /* 1197E0 150EC330 C4261564 */  lwc1       $f6, %lo(D_800A1564)($at)
    /* 1197E4 150EC334 93050000 */  lbu        $a1, 0x0($t8)
    /* 1197E8 150EC338 3C01457A */  lui        $at, (0x457A0000 >> 16)
    /* 1197EC 150EC33C 46060202 */  mul.s      $f8, $f0, $f6
    /* 1197F0 150EC340 44815000 */  mtc1       $at, $f10
    /* 1197F4 150EC344 0002C880 */  sll        $t9, $v0, 2
    /* 1197F8 150EC348 0322C823 */  subu       $t9, $t9, $v0
    /* 1197FC 150EC34C 00191080 */  sll        $v0, $t9, 2
    /* 119800 150EC350 3C08800A */  lui        $t0, %hi(D_800A1518)
    /* 119804 150EC354 3C0A800A */  lui        $t2, %hi(D_800A1530)
    /* 119808 150EC358 27A90090 */  addiu      $t1, $sp, 0x90
    /* 11980C 150EC35C 460A4400 */  add.s      $f16, $f8, $f10
    /* 119810 150EC360 AFA90010 */  sw         $t1, 0x10($sp)
    /* 119814 150EC364 254A1530 */  addiu      $t2, $t2, %lo(D_800A1530)
    /* 119818 150EC368 25081518 */  addiu      $t0, $t0, %lo(D_800A1518)
    /* 11981C 150EC36C 93A9011B */  lbu        $t1, 0x11B($sp)
    /* 119820 150EC370 8FAB011C */  lw         $t3, 0x11C($sp)
    /* 119824 150EC374 00483021 */  addu       $a2, $v0, $t0
    /* 119828 150EC378 004A3821 */  addu       $a3, $v0, $t2
    /* 11982C 150EC37C 00007810 */  mfhi       $t7
    /* 119830 150EC380 25F800C1 */  addiu      $t8, $t7, 0xC1
    /* 119834 150EC384 240AFFFF */  addiu      $t2, $zero, -0x1
    /* 119838 150EC388 240800FF */  addiu      $t0, $zero, 0xFF
    /* 11983C 150EC38C 27B900E8 */  addiu      $t9, $sp, 0xE8
    /* 119840 150EC390 258D0006 */  addiu      $t5, $t4, 0x6
    /* 119844 150EC394 AFAD0014 */  sw         $t5, 0x14($sp)
    /* 119848 150EC398 AFB90020 */  sw         $t9, 0x20($sp)
    /* 11984C 150EC39C AFA80024 */  sw         $t0, 0x24($sp)
    /* 119850 150EC3A0 AFAA002C */  sw         $t2, 0x2C($sp)
    /* 119854 150EC3A4 AFB80018 */  sw         $t8, 0x18($sp)
    /* 119858 150EC3A8 E7B0001C */  swc1       $f16, 0x1C($sp)
    /* 11985C 150EC3AC AFA00028 */  sw         $zero, 0x28($sp)
    /* 119860 150EC3B0 8FA40110 */  lw         $a0, 0x110($sp)
    /* 119864 150EC3B4 AFA90030 */  sw         $t1, 0x30($sp)
    /* 119868 150EC3B8 0D440ACE */  jal        func_15102B38
    /* 11986C 150EC3BC AFAB0034 */   sw        $t3, 0x34($sp)
    /* 119870 150EC3C0 8FA2010C */  lw         $v0, 0x10C($sp)
  .L150EC3C4:
    /* 119874 150EC3C4 8FBF0074 */  lw         $ra, 0x74($sp)
    /* 119878 150EC3C8 27BD0110 */  addiu      $sp, $sp, 0x110
    /* 11987C 150EC3CC 03E00008 */  jr         $ra
    /* 119880 150EC3D0 00000000 */   nop
endlabel func_150EBEC0

nonmatching func_150EC3D4, 0x88

glabel func_150EC3D4
    /* 119884 150EC3D4 54850004 */  bnel       $a0, $a1, .L150EC3E8
    /* 119888 150EC3D8 8C8E0000 */   lw        $t6, 0x0($a0)
    /* 11988C 150EC3DC 03E00008 */  jr         $ra
    /* 119890 150EC3E0 00001025 */   or        $v0, $zero, $zero
    /* 119894 150EC3E4 8C8E0000 */  lw         $t6, 0x0($a0)
  .L150EC3E8:
    /* 119898 150EC3E8 55C00004 */  bnel       $t6, $zero, .L150EC3FC
    /* 11989C 150EC3EC 90820004 */   lbu       $v0, 0x4($a0)
    /* 1198A0 150EC3F0 03E00008 */  jr         $ra
    /* 1198A4 150EC3F4 00001025 */   or        $v0, $zero, $zero
    /* 1198A8 150EC3F8 90820004 */  lbu        $v0, 0x4($a0)
  .L150EC3FC:
    /* 1198AC 150EC3FC 240100FF */  addiu      $at, $zero, 0xFF
    /* 1198B0 150EC400 14410003 */  bne        $v0, $at, .L150EC410
    /* 1198B4 150EC404 00000000 */   nop
    /* 1198B8 150EC408 03E00008 */  jr         $ra
    /* 1198BC 150EC40C 00001025 */   or        $v0, $zero, $zero
  .L150EC410:
    /* 1198C0 150EC410 1040000D */  beqz       $v0, .L150EC448
    /* 1198C4 150EC414 24010001 */   addiu     $at, $zero, 0x1
    /* 1198C8 150EC418 1041000B */  beq        $v0, $at, .L150EC448
    /* 1198CC 150EC41C 24010002 */   addiu     $at, $zero, 0x2
    /* 1198D0 150EC420 10410009 */  beq        $v0, $at, .L150EC448
    /* 1198D4 150EC424 24010003 */   addiu     $at, $zero, 0x3
    /* 1198D8 150EC428 10410007 */  beq        $v0, $at, .L150EC448
    /* 1198DC 150EC42C 24010004 */   addiu     $at, $zero, 0x4
    /* 1198E0 150EC430 10410005 */  beq        $v0, $at, .L150EC448
    /* 1198E4 150EC434 24010028 */   addiu     $at, $zero, 0x28
    /* 1198E8 150EC438 10410003 */  beq        $v0, $at, .L150EC448
    /* 1198EC 150EC43C 24010077 */   addiu     $at, $zero, 0x77
    /* 1198F0 150EC440 54410004 */  bnel       $v0, $at, .L150EC454
    /* 1198F4 150EC444 00001025 */   or        $v0, $zero, $zero
  .L150EC448:
    /* 1198F8 150EC448 03E00008 */  jr         $ra
    /* 1198FC 150EC44C 24020001 */   addiu     $v0, $zero, 0x1
    /* 119900 150EC450 00001025 */  or         $v0, $zero, $zero
  .L150EC454:
    /* 119904 150EC454 03E00008 */  jr         $ra
    /* 119908 150EC458 00000000 */   nop
endlabel func_150EC3D4

nonmatching func_150EC45C, 0x50

glabel func_150EC45C
    /* 11990C 150EC45C 3C013F80 */  lui        $at, (0x3F800000 >> 16)
    /* 119910 150EC460 27BDFFD8 */  addiu      $sp, $sp, -0x28
    /* 119914 150EC464 44810000 */  mtc1       $at, $f0
    /* 119918 150EC468 AFBF0024 */  sw         $ra, 0x24($sp)
    /* 11991C 150EC46C 44802000 */  mtc1       $zero, $f4
    /* 119920 150EC470 44050000 */  mfc1       $a1, $f0
    /* 119924 150EC474 44060000 */  mfc1       $a2, $f0
    /* 119928 150EC478 44070000 */  mfc1       $a3, $f0
    /* 11992C 150EC47C 240E00FF */  addiu      $t6, $zero, 0xFF
    /* 119930 150EC480 240F00FF */  addiu      $t7, $zero, 0xFF
    /* 119934 150EC484 241800FF */  addiu      $t8, $zero, 0xFF
    /* 119938 150EC488 AFB8001C */  sw         $t8, 0x1C($sp)
    /* 11993C 150EC48C AFAF0018 */  sw         $t7, 0x18($sp)
    /* 119940 150EC490 AFAE0014 */  sw         $t6, 0x14($sp)
    /* 119944 150EC494 0D470EC3 */  jal        func_151C3B0C
    /* 119948 150EC498 E7A40010 */   swc1      $f4, 0x10($sp)
    /* 11994C 150EC49C 8FBF0024 */  lw         $ra, 0x24($sp)
    /* 119950 150EC4A0 27BD0028 */  addiu      $sp, $sp, 0x28
    /* 119954 150EC4A4 03E00008 */  jr         $ra
    /* 119958 150EC4A8 00000000 */   nop
endlabel func_150EC45C
    /* 11995C 150EC4AC 00000000 */  nop
