.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching func_1512E5F0, 0x2E8

glabel func_1512E5F0
    /* 15BAA0 1512E5F0 27BDFFE0 */  addiu      $sp, $sp, -0x20
    /* 15BAA4 1512E5F4 AFBF001C */  sw         $ra, 0x1C($sp)
    /* 15BAA8 1512E5F8 3C09800C */  lui        $t1, %hi(D_800BE620)
    /* 15BAAC 1512E5FC 2529E620 */  addiu      $t1, $t1, %lo(D_800BE620)
    /* 15BAB0 1512E600 3C1F0700 */  lui        $ra, (0x7000000 >> 16)
    /* 15BAB4 1512E604 AFA50024 */  sw         $a1, 0x24($sp)
    /* 15BAB8 1512E608 3C0CE700 */  lui        $t4, (0xE7000000 >> 16)
    /* 15BABC 1512E60C 3C0DF510 */  lui        $t5, (0xF5100000 >> 16)
    /* 15BAC0 1512E610 00801025 */  or         $v0, $a0, $zero
    /* 15BAC4 1512E614 AC4C0000 */  sw         $t4, 0x0($v0)
    /* 15BAC8 1512E618 AC400004 */  sw         $zero, 0x4($v0)
    /* 15BACC 1512E61C 24840008 */  addiu      $a0, $a0, 0x8
    /* 15BAD0 1512E620 00801825 */  or         $v1, $a0, $zero
    /* 15BAD4 1512E624 3C0EEF20 */  lui        $t6, (0xEF202CFF >> 16)
    /* 15BAD8 1512E628 35CE2CFF */  ori        $t6, $t6, (0xEF202CFF & 0xFFFF)
    /* 15BADC 1512E62C AC6E0000 */  sw         $t6, 0x0($v1)
    /* 15BAE0 1512E630 AC600004 */  sw         $zero, 0x4($v1)
    /* 15BAE4 1512E634 24840008 */  addiu      $a0, $a0, 0x8
    /* 15BAE8 1512E638 00803025 */  or         $a2, $a0, $zero
    /* 15BAEC 1512E63C 3C0FFD10 */  lui        $t7, (0xFD100000 >> 16)
    /* 15BAF0 1512E640 ACCF0000 */  sw         $t7, 0x0($a2)
    /* 15BAF4 1512E644 8FB80024 */  lw         $t8, 0x24($sp)
    /* 15BAF8 1512E648 8D2E0000 */  lw         $t6, 0x0($t1)
    /* 15BAFC 1512E64C 24840008 */  addiu      $a0, $a0, 0x8
    /* 15BB00 1512E650 971908BA */  lhu        $t9, 0x8BA($t8)
    /* 15BB04 1512E654 00803825 */  or         $a3, $a0, $zero
    /* 15BB08 1512E658 24840008 */  addiu      $a0, $a0, 0x8
    /* 15BB0C 1512E65C 032E0019 */  multu      $t9, $t6
    /* 15BB10 1512E660 3C19800C */  lui        $t9, %hi(D_800BE9C4)
    /* 15BB14 1512E664 8F39E9C4 */  lw         $t9, %lo(D_800BE9C4)($t9)
    /* 15BB18 1512E668 00804025 */  or         $t0, $a0, $zero
    /* 15BB1C 1512E66C 24840008 */  addiu      $a0, $a0, 0x8
    /* 15BB20 1512E670 00805825 */  or         $t3, $a0, $zero
    /* 15BB24 1512E674 00007812 */  mflo       $t7
    /* 15BB28 1512E678 000FC040 */  sll        $t8, $t7, 1
    /* 15BB2C 1512E67C 03197021 */  addu       $t6, $t8, $t9
    /* 15BB30 1512E680 ACCE0004 */  sw         $t6, 0x4($a2)
    /* 15BB34 1512E684 ACED0000 */  sw         $t5, 0x0($a3)
    /* 15BB38 1512E688 ACFF0004 */  sw         $ra, 0x4($a3)
    /* 15BB3C 1512E68C 3C0FE600 */  lui        $t7, (0xE6000000 >> 16)
    /* 15BB40 1512E690 AD0F0000 */  sw         $t7, 0x0($t0)
    /* 15BB44 1512E694 AD000004 */  sw         $zero, 0x4($t0)
    /* 15BB48 1512E698 3C18F300 */  lui        $t8, (0xF3000000 >> 16)
    /* 15BB4C 1512E69C AD780000 */  sw         $t8, 0x0($t3)
    /* 15BB50 1512E6A0 8D230000 */  lw         $v1, 0x0($t1)
    /* 15BB54 1512E6A4 24840008 */  addiu      $a0, $a0, 0x8
    /* 15BB58 1512E6A8 2462FFFF */  addiu      $v0, $v1, -0x1
    /* 15BB5C 1512E6AC 284107FF */  slti       $at, $v0, 0x7FF
    /* 15BB60 1512E6B0 50200004 */  beql       $at, $zero, .L1512E6C4
    /* 15BB64 1512E6B4 240807FF */   addiu     $t0, $zero, 0x7FF
    /* 15BB68 1512E6B8 10000002 */  b          .L1512E6C4
    /* 15BB6C 1512E6BC 00404025 */   or        $t0, $v0, $zero
    /* 15BB70 1512E6C0 240807FF */  addiu      $t0, $zero, 0x7FF
  .L1512E6C4:
    /* 15BB74 1512E6C4 00031040 */  sll        $v0, $v1, 1
    /* 15BB78 1512E6C8 04410003 */  bgez       $v0, .L1512E6D8
    /* 15BB7C 1512E6CC 0002C8C3 */   sra       $t9, $v0, 3
    /* 15BB80 1512E6D0 24410007 */  addiu      $at, $v0, 0x7
    /* 15BB84 1512E6D4 0001C8C3 */  sra        $t9, $at, 3
  .L1512E6D8:
    /* 15BB88 1512E6D8 1F200003 */  bgtz       $t9, .L1512E6E8
    /* 15BB8C 1512E6DC 03201025 */   or        $v0, $t9, $zero
    /* 15BB90 1512E6E0 10000002 */  b          .L1512E6EC
    /* 15BB94 1512E6E4 240A0001 */   addiu     $t2, $zero, 0x1
  .L1512E6E8:
    /* 15BB98 1512E6E8 00405025 */  or         $t2, $v0, $zero
  .L1512E6EC:
    /* 15BB9C 1512E6EC 1C400003 */  bgtz       $v0, .L1512E6FC
    /* 15BBA0 1512E6F0 254E07FF */   addiu     $t6, $t2, 0x7FF
    /* 15BBA4 1512E6F4 10000002 */  b          .L1512E700
    /* 15BBA8 1512E6F8 24070001 */   addiu     $a3, $zero, 0x1
  .L1512E6FC:
    /* 15BBAC 1512E6FC 00403825 */  or         $a3, $v0, $zero
  .L1512E700:
    /* 15BBB0 1512E700 01C7001A */  div        $zero, $t6, $a3
    /* 15BBB4 1512E704 00007812 */  mflo       $t7
    /* 15BBB8 1512E708 31F80FFF */  andi       $t8, $t7, 0xFFF
    /* 15BBBC 1512E70C 14E00002 */  bnez       $a3, .L1512E718
    /* 15BBC0 1512E710 00000000 */   nop
    /* 15BBC4 1512E714 0007000D */  break      7
  .L1512E718:
    /* 15BBC8 1512E718 2401FFFF */  addiu      $at, $zero, -0x1
    /* 15BBCC 1512E71C 14E10004 */  bne        $a3, $at, .L1512E730
    /* 15BBD0 1512E720 3C018000 */   lui       $at, (0x80000000 >> 16)
    /* 15BBD4 1512E724 15C10002 */  bne        $t6, $at, .L1512E730
    /* 15BBD8 1512E728 00000000 */   nop
    /* 15BBDC 1512E72C 0006000D */  break      6
  .L1512E730:
    /* 15BBE0 1512E730 310E0FFF */  andi       $t6, $t0, 0xFFF
    /* 15BBE4 1512E734 000E7B00 */  sll        $t7, $t6, 12
    /* 15BBE8 1512E738 031FC825 */  or         $t9, $t8, $ra
    /* 15BBEC 1512E73C 032FC025 */  or         $t8, $t9, $t7
    /* 15BBF0 1512E740 AD780004 */  sw         $t8, 0x4($t3)
    /* 15BBF4 1512E744 00801025 */  or         $v0, $a0, $zero
    /* 15BBF8 1512E748 AC4C0000 */  sw         $t4, 0x0($v0)
    /* 15BBFC 1512E74C AC400004 */  sw         $zero, 0x4($v0)
    /* 15BC00 1512E750 24840008 */  addiu      $a0, $a0, 0x8
    /* 15BC04 1512E754 8D2E0000 */  lw         $t6, 0x0($t1)
    /* 15BC08 1512E758 00801825 */  or         $v1, $a0, $zero
    /* 15BC0C 1512E75C AC600004 */  sw         $zero, 0x4($v1)
    /* 15BC10 1512E760 000EC840 */  sll        $t9, $t6, 1
    /* 15BC14 1512E764 272F0007 */  addiu      $t7, $t9, 0x7
    /* 15BC18 1512E768 000FC0C3 */  sra        $t8, $t7, 3
    /* 15BC1C 1512E76C 330E01FF */  andi       $t6, $t8, 0x1FF
    /* 15BC20 1512E770 000ECA40 */  sll        $t9, $t6, 9
    /* 15BC24 1512E774 032D7825 */  or         $t7, $t9, $t5
    /* 15BC28 1512E778 AC6F0000 */  sw         $t7, 0x0($v1)
    /* 15BC2C 1512E77C 24840008 */  addiu      $a0, $a0, 0x8
    /* 15BC30 1512E780 00802825 */  or         $a1, $a0, $zero
    /* 15BC34 1512E784 3C18F200 */  lui        $t8, (0xF2000000 >> 16)
    /* 15BC38 1512E788 ACB80000 */  sw         $t8, 0x0($a1)
    /* 15BC3C 1512E78C 8D2E0000 */  lw         $t6, 0x0($t1)
    /* 15BC40 1512E790 24840008 */  addiu      $a0, $a0, 0x8
    /* 15BC44 1512E794 25D9FFFF */  addiu      $t9, $t6, -0x1
    /* 15BC48 1512E798 00197880 */  sll        $t7, $t9, 2
    /* 15BC4C 1512E79C 31F80FFF */  andi       $t8, $t7, 0xFFF
    /* 15BC50 1512E7A0 00187300 */  sll        $t6, $t8, 12
    /* 15BC54 1512E7A4 ACAE0004 */  sw         $t6, 0x4($a1)
    /* 15BC58 1512E7A8 8D390000 */  lw         $t9, 0x0($t1)
    /* 15BC5C 1512E7AC 3C01FF10 */  lui        $at, (0xFF100000 >> 16)
    /* 15BC60 1512E7B0 00803025 */  or         $a2, $a0, $zero
    /* 15BC64 1512E7B4 272FFFFF */  addiu      $t7, $t9, -0x1
    /* 15BC68 1512E7B8 31F80FFF */  andi       $t8, $t7, 0xFFF
    /* 15BC6C 1512E7BC 03017025 */  or         $t6, $t8, $at
    /* 15BC70 1512E7C0 ACCE0000 */  sw         $t6, 0x0($a2)
    /* 15BC74 1512E7C4 8FB90024 */  lw         $t9, 0x24($sp)
    /* 15BC78 1512E7C8 24840008 */  addiu      $a0, $a0, 0x8
    /* 15BC7C 1512E7CC 00801025 */  or         $v0, $a0, $zero
    /* 15BC80 1512E7D0 8F2F08BC */  lw         $t7, 0x8BC($t9)
    /* 15BC84 1512E7D4 3C18ED00 */  lui        $t8, (0xED000000 >> 16)
    /* 15BC88 1512E7D8 ACCF0004 */  sw         $t7, 0x4($a2)
    /* 15BC8C 1512E7DC AC580000 */  sw         $t8, 0x0($v0)
    /* 15BC90 1512E7E0 8D2E0000 */  lw         $t6, 0x0($t1)
    /* 15BC94 1512E7E4 3C014080 */  lui        $at, (0x40800000 >> 16)
    /* 15BC98 1512E7E8 44814000 */  mtc1       $at, $f8
    /* 15BC9C 1512E7EC 448E2000 */  mtc1       $t6, $f4
    /* 15BCA0 1512E7F0 24840008 */  addiu      $a0, $a0, 0x8
    /* 15BCA4 1512E7F4 00801825 */  or         $v1, $a0, $zero
    /* 15BCA8 1512E7F8 468021A0 */  cvt.s.w    $f6, $f4
    /* 15BCAC 1512E7FC 24840008 */  addiu      $a0, $a0, 0x8
    /* 15BCB0 1512E800 00802825 */  or         $a1, $a0, $zero
    /* 15BCB4 1512E804 24840008 */  addiu      $a0, $a0, 0x8
    /* 15BCB8 1512E808 00803025 */  or         $a2, $a0, $zero
    /* 15BCBC 1512E80C 24840008 */  addiu      $a0, $a0, 0x8
    /* 15BCC0 1512E810 46083282 */  mul.s      $f10, $f6, $f8
    /* 15BCC4 1512E814 00803825 */  or         $a3, $a0, $zero
    /* 15BCC8 1512E818 24840008 */  addiu      $a0, $a0, 0x8
    /* 15BCCC 1512E81C 4600540D */  trunc.w.s  $f16, $f10
    /* 15BCD0 1512E820 440F8000 */  mfc1       $t7, $f16
    /* 15BCD4 1512E824 00000000 */  nop
    /* 15BCD8 1512E828 31F80FFF */  andi       $t8, $t7, 0xFFF
    /* 15BCDC 1512E82C 00187300 */  sll        $t6, $t8, 12
    /* 15BCE0 1512E830 35D90004 */  ori        $t9, $t6, 0x4
    /* 15BCE4 1512E834 AC590004 */  sw         $t9, 0x4($v0)
    /* 15BCE8 1512E838 8D2F0000 */  lw         $t7, 0x0($t1)
    /* 15BCEC 1512E83C 3C01E400 */  lui        $at, (0xE4000004 >> 16)
    /* 15BCF0 1512E840 AC600004 */  sw         $zero, 0x4($v1)
    /* 15BCF4 1512E844 000FC080 */  sll        $t8, $t7, 2
    /* 15BCF8 1512E848 330E0FFF */  andi       $t6, $t8, 0xFFF
    /* 15BCFC 1512E84C 000ECB00 */  sll        $t9, $t6, 12
    /* 15BD00 1512E850 03217825 */  or         $t7, $t9, $at
    /* 15BD04 1512E854 35F80004 */  ori        $t8, $t7, (0xE4000004 & 0xFFFF)
    /* 15BD08 1512E858 AC780000 */  sw         $t8, 0x0($v1)
    /* 15BD0C 1512E85C 3C0EE100 */  lui        $t6, (0xE1000000 >> 16)
    /* 15BD10 1512E860 ACAE0000 */  sw         $t6, 0x0($a1)
    /* 15BD14 1512E864 ACA00004 */  sw         $zero, 0x4($a1)
    /* 15BD18 1512E868 3C0F1000 */  lui        $t7, (0x10000400 >> 16)
    /* 15BD1C 1512E86C 35EF0400 */  ori        $t7, $t7, (0x10000400 & 0xFFFF)
    /* 15BD20 1512E870 3C19F100 */  lui        $t9, (0xF1000000 >> 16)
    /* 15BD24 1512E874 ACD90000 */  sw         $t9, 0x0($a2)
    /* 15BD28 1512E878 ACCF0004 */  sw         $t7, 0x4($a2)
    /* 15BD2C 1512E87C ACEC0000 */  sw         $t4, 0x0($a3)
    /* 15BD30 1512E880 ACE00004 */  sw         $zero, 0x4($a3)
    /* 15BD34 1512E884 0D4069A0 */  jal        func_1501A680
    /* 15BD38 1512E888 00000000 */   nop
    /* 15BD3C 1512E88C 3C058008 */  lui        $a1, %hi(D_80082FA6)
    /* 15BD40 1512E890 84A52FA6 */  lh         $a1, %lo(D_80082FA6)($a1)
    /* 15BD44 1512E894 00402025 */  or         $a0, $v0, $zero
    /* 15BD48 1512E898 00003025 */  or         $a2, $zero, $zero
    /* 15BD4C 1512E89C 00003825 */  or         $a3, $zero, $zero
    /* 15BD50 1512E8A0 AFA00010 */  sw         $zero, 0x10($sp)
    /* 15BD54 1512E8A4 0D406924 */  jal        func_1501A490
    /* 15BD58 1512E8A8 AFA00014 */   sw        $zero, 0x14($sp)
    /* 15BD5C 1512E8AC 3C18EF08 */  lui        $t8, (0xEF082C3F >> 16)
    /* 15BD60 1512E8B0 3C0E0055 */  lui        $t6, (0x552230 >> 16)
    /* 15BD64 1512E8B4 35CE2230 */  ori        $t6, $t6, (0x552230 & 0xFFFF)
    /* 15BD68 1512E8B8 37182C3F */  ori        $t8, $t8, (0xEF082C3F & 0xFFFF)
    /* 15BD6C 1512E8BC AC580000 */  sw         $t8, 0x0($v0)
    /* 15BD70 1512E8C0 AC4E0004 */  sw         $t6, 0x4($v0)
    /* 15BD74 1512E8C4 24420008 */  addiu      $v0, $v0, 0x8
    /* 15BD78 1512E8C8 8FBF001C */  lw         $ra, 0x1C($sp)
    /* 15BD7C 1512E8CC 27BD0020 */  addiu      $sp, $sp, 0x20
    /* 15BD80 1512E8D0 03E00008 */  jr         $ra
    /* 15BD84 1512E8D4 00000000 */   nop
endlabel func_1512E5F0
    /* 15BD88 1512E8D8 00000000 */  nop
    /* 15BD8C 1512E8DC 00000000 */  nop
