.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching func_151DD3A0, 0xB4

glabel func_151DD3A0
    /* 20A850 151DD3A0 27BDFFD0 */  addiu      $sp, $sp, -0x30
    /* 20A854 151DD3A4 AFB40028 */  sw         $s4, 0x28($sp)
    /* 20A858 151DD3A8 AFB20020 */  sw         $s2, 0x20($sp)
    /* 20A85C 151DD3AC AFB1001C */  sw         $s1, 0x1C($sp)
    /* 20A860 151DD3B0 AFB00018 */  sw         $s0, 0x18($sp)
    /* 20A864 151DD3B4 00E08025 */  or         $s0, $a3, $zero
    /* 20A868 151DD3B8 30B100FF */  andi       $s1, $a1, 0xFF
    /* 20A86C 151DD3BC 00C09025 */  or         $s2, $a2, $zero
    /* 20A870 151DD3C0 0080A025 */  or         $s4, $a0, $zero
    /* 20A874 151DD3C4 AFBF002C */  sw         $ra, 0x2C($sp)
    /* 20A878 151DD3C8 AFB30024 */  sw         $s3, 0x24($sp)
    /* 20A87C 151DD3CC AFA50034 */  sw         $a1, 0x34($sp)
    /* 20A880 151DD3D0 00009825 */  or         $s3, $zero, $zero
    /* 20A884 151DD3D4 0D4773F6 */  jal        func_151DCFD8
    /* 20A888 151DD3D8 24040001 */   addiu     $a0, $zero, 0x1
    /* 20A88C 151DD3DC 10400005 */  beqz       $v0, .L151DD3F4
    /* 20A890 151DD3E0 00000000 */   nop
  .L151DD3E4:
    /* 20A894 151DD3E4 0D4773F6 */  jal        func_151DCFD8
    /* 20A898 151DD3E8 24040001 */   addiu     $a0, $zero, 0x1
    /* 20A89C 151DD3EC 1440FFFD */  bnez       $v0, .L151DD3E4
    /* 20A8A0 151DD3F0 00000000 */   nop
  .L151DD3F4:
    /* 20A8A4 151DD3F4 1A00000E */  blez       $s0, .L151DD430
  .L151DD3F8:
    /* 20A8A8 151DD3F8 02802025 */   or        $a0, $s4, $zero
    /* 20A8AC 151DD3FC 322500FF */  andi       $a1, $s1, 0xFF
    /* 20A8B0 151DD400 0D477450 */  jal        func_151DD140
    /* 20A8B4 151DD404 02403025 */   or        $a2, $s2, $zero
    /* 20A8B8 151DD408 10400003 */  beqz       $v0, .L151DD418
    /* 20A8BC 151DD40C 00409825 */   or        $s3, $v0, $zero
    /* 20A8C0 151DD410 10000009 */  b          .L151DD438
    /* 20A8C4 151DD414 8FBF002C */   lw        $ra, 0x2C($sp)
  .L151DD418:
    /* 20A8C8 151DD418 26310001 */  addiu      $s1, $s1, 0x1
    /* 20A8CC 151DD41C 2610FFF8 */  addiu      $s0, $s0, -0x8
    /* 20A8D0 151DD420 322E00FF */  andi       $t6, $s1, 0xFF
    /* 20A8D4 151DD424 01C08825 */  or         $s1, $t6, $zero
    /* 20A8D8 151DD428 1E00FFF3 */  bgtz       $s0, .L151DD3F8
    /* 20A8DC 151DD42C 26520008 */   addiu     $s2, $s2, 0x8
  .L151DD430:
    /* 20A8E0 151DD430 02601025 */  or         $v0, $s3, $zero
    /* 20A8E4 151DD434 8FBF002C */  lw         $ra, 0x2C($sp)
  .L151DD438:
    /* 20A8E8 151DD438 8FB00018 */  lw         $s0, 0x18($sp)
    /* 20A8EC 151DD43C 8FB1001C */  lw         $s1, 0x1C($sp)
    /* 20A8F0 151DD440 8FB20020 */  lw         $s2, 0x20($sp)
    /* 20A8F4 151DD444 8FB30024 */  lw         $s3, 0x24($sp)
    /* 20A8F8 151DD448 8FB40028 */  lw         $s4, 0x28($sp)
    /* 20A8FC 151DD44C 03E00008 */  jr         $ra
    /* 20A900 151DD450 27BD0030 */   addiu     $sp, $sp, 0x30
endlabel func_151DD3A0
    /* 20A904 151DD454 00000000 */  nop
    /* 20A908 151DD458 00000000 */  nop
    /* 20A90C 151DD45C 00000000 */  nop
