.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching func_1500F9D0, 0x94

glabel func_1500F9D0
    /* 3CE80 1500F9D0 27BDFFD8 */  addiu      $sp, $sp, -0x28
    /* 3CE84 1500F9D4 AFBF0024 */  sw         $ra, 0x24($sp)
    /* 3CE88 1500F9D8 AFA40028 */  sw         $a0, 0x28($sp)
    /* 3CE8C 1500F9DC AFA5002C */  sw         $a1, 0x2C($sp)
    /* 3CE90 1500F9E0 AFA60030 */  sw         $a2, 0x30($sp)
    /* 3CE94 1500F9E4 AFA70034 */  sw         $a3, 0x34($sp)
    /* 3CE98 1500F9E8 0D42B688 */  jal        func_150ADA20
    /* 3CE9C 1500F9EC 00000000 */   nop
    /* 3CEA0 1500F9F0 3044007F */  andi       $a0, $v0, 0x7F
    /* 3CEA4 1500F9F4 2484000A */  addiu      $a0, $a0, 0xA
    /* 3CEA8 1500F9F8 00047400 */  sll        $t6, $a0, 16
    /* 3CEAC 1500F9FC 2418000A */  addiu      $t8, $zero, 0xA
    /* 3CEB0 1500FA00 241900FF */  addiu      $t9, $zero, 0xFF
    /* 3CEB4 1500FA04 AFB90018 */  sw         $t9, 0x18($sp)
    /* 3CEB8 1500FA08 AFB80014 */  sw         $t8, 0x14($sp)
    /* 3CEBC 1500FA0C 000E2403 */  sra        $a0, $t6, 16
    /* 3CEC0 1500FA10 24050001 */  addiu      $a1, $zero, 0x1
    /* 3CEC4 1500FA14 2406FFFF */  addiu      $a2, $zero, -0x1
    /* 3CEC8 1500FA18 24070001 */  addiu      $a3, $zero, 0x1
    /* 3CECC 1500FA1C AFA00010 */  sw         $zero, 0x10($sp)
    /* 3CED0 1500FA20 0D45247D */  jal        func_151491F4
    /* 3CED4 1500FA24 AFA0001C */   sw        $zero, 0x1C($sp)
    /* 3CED8 1500FA28 1040000A */  beqz       $v0, .L1500FA54
    /* 3CEDC 1500FA2C 8FA80028 */   lw        $t0, 0x28($sp)
    /* 3CEE0 1500FA30 A4480028 */  sh         $t0, 0x28($v0)
    /* 3CEE4 1500FA34 8FA9002C */  lw         $t1, 0x2C($sp)
    /* 3CEE8 1500FA38 A449002A */  sh         $t1, 0x2A($v0)
    /* 3CEEC 1500FA3C 8FAA0030 */  lw         $t2, 0x30($sp)
    /* 3CEF0 1500FA40 A44A002C */  sh         $t2, 0x2C($v0)
    /* 3CEF4 1500FA44 8FAB0034 */  lw         $t3, 0x34($sp)
    /* 3CEF8 1500FA48 A44B002E */  sh         $t3, 0x2E($v0)
    /* 3CEFC 1500FA4C 8FAC0038 */  lw         $t4, 0x38($sp)
    /* 3CF00 1500FA50 A04C0030 */  sb         $t4, 0x30($v0)
  .L1500FA54:
    /* 3CF04 1500FA54 8FBF0024 */  lw         $ra, 0x24($sp)
    /* 3CF08 1500FA58 27BD0028 */  addiu      $sp, $sp, 0x28
    /* 3CF0C 1500FA5C 03E00008 */  jr         $ra
    /* 3CF10 1500FA60 00000000 */   nop
endlabel func_1500F9D0

nonmatching func_1500FA64, 0x3C8

glabel func_1500FA64
    /* 3CF14 1500FA64 27BDFFB8 */  addiu      $sp, $sp, -0x48
    /* 3CF18 1500FA68 AFBF001C */  sw         $ra, 0x1C($sp)
    /* 3CF1C 1500FA6C 3C0F8009 */  lui        $t7, %hi(D_80096320)
    /* 3CF20 1500FA70 A3A00044 */  sb         $zero, 0x44($sp)
    /* 3CF24 1500FA74 25EF6320 */  addiu      $t7, $t7, %lo(D_80096320)
    /* 3CF28 1500FA78 8DE10000 */  lw         $at, 0x0($t7)
    /* 3CF2C 1500FA7C 8DE80004 */  lw         $t0, 0x4($t7)
    /* 3CF30 1500FA80 27AE0028 */  addiu      $t6, $sp, 0x28
    /* 3CF34 1500FA84 ADC10000 */  sw         $at, 0x0($t6)
    /* 3CF38 1500FA88 ADC80004 */  sw         $t0, 0x4($t6)
    /* 3CF3C 1500FA8C 8DE8000C */  lw         $t0, 0xC($t7)
    /* 3CF40 1500FA90 8DE10008 */  lw         $at, 0x8($t7)
    /* 3CF44 1500FA94 24090001 */  addiu      $t1, $zero, 0x1
    /* 3CF48 1500FA98 ADC8000C */  sw         $t0, 0xC($t6)
    /* 3CF4C 1500FA9C ADC10008 */  sw         $at, 0x8($t6)
    /* 3CF50 1500FAA0 8DE10010 */  lw         $at, 0x10($t7)
    /* 3CF54 1500FAA4 8DE80014 */  lw         $t0, 0x14($t7)
    /* 3CF58 1500FAA8 27A40024 */  addiu      $a0, $sp, 0x24
    /* 3CF5C 1500FAAC ADC10010 */  sw         $at, 0x10($t6)
    /* 3CF60 1500FAB0 ADC80014 */  sw         $t0, 0x14($t6)
    /* 3CF64 1500FAB4 C7A60038 */  lwc1       $f6, 0x38($sp)
    /* 3CF68 1500FAB8 C7A4002C */  lwc1       $f4, 0x2C($sp)
    /* 3CF6C 1500FABC A3A90024 */  sb         $t1, 0x24($sp)
    /* 3CF70 1500FAC0 00002825 */  or         $a1, $zero, $zero
    /* 3CF74 1500FAC4 46062001 */  sub.s      $f0, $f4, $f6
    /* 3CF78 1500FAC8 46000005 */  abs.s      $f0, $f0
    /* 3CF7C 1500FACC 0D46B2F5 */  jal        func_151ACBD4
    /* 3CF80 1500FAD0 E7A00040 */   swc1      $f0, 0x40($sp)
    /* 3CF84 1500FAD4 3C0B8009 */  lui        $t3, %hi(D_80096338)
    /* 3CF88 1500FAD8 256B6338 */  addiu      $t3, $t3, %lo(D_80096338)
    /* 3CF8C 1500FADC 8D610000 */  lw         $at, 0x0($t3)
    /* 3CF90 1500FAE0 8D790004 */  lw         $t9, 0x4($t3)
    /* 3CF94 1500FAE4 27AA0028 */  addiu      $t2, $sp, 0x28
    /* 3CF98 1500FAE8 AD410000 */  sw         $at, 0x0($t2)
    /* 3CF9C 1500FAEC AD590004 */  sw         $t9, 0x4($t2)
    /* 3CFA0 1500FAF0 8D79000C */  lw         $t9, 0xC($t3)
    /* 3CFA4 1500FAF4 8D610008 */  lw         $at, 0x8($t3)
    /* 3CFA8 1500FAF8 24180002 */  addiu      $t8, $zero, 0x2
    /* 3CFAC 1500FAFC AD59000C */  sw         $t9, 0xC($t2)
    /* 3CFB0 1500FB00 AD410008 */  sw         $at, 0x8($t2)
    /* 3CFB4 1500FB04 8D610010 */  lw         $at, 0x10($t3)
    /* 3CFB8 1500FB08 8D790014 */  lw         $t9, 0x14($t3)
    /* 3CFBC 1500FB0C 27A40024 */  addiu      $a0, $sp, 0x24
    /* 3CFC0 1500FB10 AD410010 */  sw         $at, 0x10($t2)
    /* 3CFC4 1500FB14 AD590014 */  sw         $t9, 0x14($t2)
    /* 3CFC8 1500FB18 C7AA0038 */  lwc1       $f10, 0x38($sp)
    /* 3CFCC 1500FB1C C7A8002C */  lwc1       $f8, 0x2C($sp)
    /* 3CFD0 1500FB20 A3B80024 */  sb         $t8, 0x24($sp)
    /* 3CFD4 1500FB24 00002825 */  or         $a1, $zero, $zero
    /* 3CFD8 1500FB28 460A4001 */  sub.s      $f0, $f8, $f10
    /* 3CFDC 1500FB2C 46000005 */  abs.s      $f0, $f0
    /* 3CFE0 1500FB30 0D46B2F5 */  jal        func_151ACBD4
    /* 3CFE4 1500FB34 E7A00040 */   swc1      $f0, 0x40($sp)
    /* 3CFE8 1500FB38 3C0F8009 */  lui        $t7, %hi(D_80096350)
    /* 3CFEC 1500FB3C 25EF6350 */  addiu      $t7, $t7, %lo(D_80096350)
    /* 3CFF0 1500FB40 8DE10000 */  lw         $at, 0x0($t7)
    /* 3CFF4 1500FB44 8DED0004 */  lw         $t5, 0x4($t7)
    /* 3CFF8 1500FB48 27AE0028 */  addiu      $t6, $sp, 0x28
    /* 3CFFC 1500FB4C ADC10000 */  sw         $at, 0x0($t6)
    /* 3D000 1500FB50 ADCD0004 */  sw         $t5, 0x4($t6)
    /* 3D004 1500FB54 8DED000C */  lw         $t5, 0xC($t7)
    /* 3D008 1500FB58 8DE10008 */  lw         $at, 0x8($t7)
    /* 3D00C 1500FB5C 240C0003 */  addiu      $t4, $zero, 0x3
    /* 3D010 1500FB60 ADCD000C */  sw         $t5, 0xC($t6)
    /* 3D014 1500FB64 ADC10008 */  sw         $at, 0x8($t6)
    /* 3D018 1500FB68 8DE10010 */  lw         $at, 0x10($t7)
    /* 3D01C 1500FB6C 8DED0014 */  lw         $t5, 0x14($t7)
    /* 3D020 1500FB70 27A40024 */  addiu      $a0, $sp, 0x24
    /* 3D024 1500FB74 ADC10010 */  sw         $at, 0x10($t6)
    /* 3D028 1500FB78 ADCD0014 */  sw         $t5, 0x14($t6)
    /* 3D02C 1500FB7C C7B20038 */  lwc1       $f18, 0x38($sp)
    /* 3D030 1500FB80 C7B0002C */  lwc1       $f16, 0x2C($sp)
    /* 3D034 1500FB84 A3AC0024 */  sb         $t4, 0x24($sp)
    /* 3D038 1500FB88 00002825 */  or         $a1, $zero, $zero
    /* 3D03C 1500FB8C 46128001 */  sub.s      $f0, $f16, $f18
    /* 3D040 1500FB90 46000005 */  abs.s      $f0, $f0
    /* 3D044 1500FB94 0D46B2F5 */  jal        func_151ACBD4
    /* 3D048 1500FB98 E7A00040 */   swc1      $f0, 0x40($sp)
    /* 3D04C 1500FB9C 3C0A8009 */  lui        $t2, %hi(D_80096368)
    /* 3D050 1500FBA0 254A6368 */  addiu      $t2, $t2, %lo(D_80096368)
    /* 3D054 1500FBA4 8D410000 */  lw         $at, 0x0($t2)
    /* 3D058 1500FBA8 27A20028 */  addiu      $v0, $sp, 0x28
    /* 3D05C 1500FBAC 3C098009 */  lui        $t1, %hi(D_80096380)
    /* 3D060 1500FBB0 AC410000 */  sw         $at, 0x0($v0)
    /* 3D064 1500FBB4 8D580004 */  lw         $t8, 0x4($t2)
    /* 3D068 1500FBB8 25296380 */  addiu      $t1, $t1, %lo(D_80096380)
    /* 3D06C 1500FBBC 240D0005 */  addiu      $t5, $zero, 0x5
    /* 3D070 1500FBC0 AC580004 */  sw         $t8, 0x4($v0)
    /* 3D074 1500FBC4 8D410008 */  lw         $at, 0x8($t2)
    /* 3D078 1500FBC8 27A40024 */  addiu      $a0, $sp, 0x24
    /* 3D07C 1500FBCC 00002825 */  or         $a1, $zero, $zero
    /* 3D080 1500FBD0 AC410008 */  sw         $at, 0x8($v0)
    /* 3D084 1500FBD4 8D58000C */  lw         $t8, 0xC($t2)
    /* 3D088 1500FBD8 AC58000C */  sw         $t8, 0xC($v0)
    /* 3D08C 1500FBDC 8D410010 */  lw         $at, 0x10($t2)
    /* 3D090 1500FBE0 AC410010 */  sw         $at, 0x10($v0)
    /* 3D094 1500FBE4 8D580014 */  lw         $t8, 0x14($t2)
    /* 3D098 1500FBE8 AC580014 */  sw         $t8, 0x14($v0)
    /* 3D09C 1500FBEC 8D210000 */  lw         $at, 0x0($t1)
    /* 3D0A0 1500FBF0 AC410000 */  sw         $at, 0x0($v0)
    /* 3D0A4 1500FBF4 8D2F0004 */  lw         $t7, 0x4($t1)
    /* 3D0A8 1500FBF8 AC4F0004 */  sw         $t7, 0x4($v0)
    /* 3D0AC 1500FBFC 8D210008 */  lw         $at, 0x8($t1)
    /* 3D0B0 1500FC00 AC410008 */  sw         $at, 0x8($v0)
    /* 3D0B4 1500FC04 8D2F000C */  lw         $t7, 0xC($t1)
    /* 3D0B8 1500FC08 AC4F000C */  sw         $t7, 0xC($v0)
    /* 3D0BC 1500FC0C 8D210010 */  lw         $at, 0x10($t1)
    /* 3D0C0 1500FC10 AC410010 */  sw         $at, 0x10($v0)
    /* 3D0C4 1500FC14 8D2F0014 */  lw         $t7, 0x14($t1)
    /* 3D0C8 1500FC18 AC4F0014 */  sw         $t7, 0x14($v0)
    /* 3D0CC 1500FC1C C7AA0038 */  lwc1       $f10, 0x38($sp)
    /* 3D0D0 1500FC20 C7A8002C */  lwc1       $f8, 0x2C($sp)
    /* 3D0D4 1500FC24 A3AD0024 */  sb         $t5, 0x24($sp)
    /* 3D0D8 1500FC28 460A4001 */  sub.s      $f0, $f8, $f10
    /* 3D0DC 1500FC2C 46000005 */  abs.s      $f0, $f0
    /* 3D0E0 1500FC30 0D46B2F5 */  jal        func_151ACBD4
    /* 3D0E4 1500FC34 E7A00040 */   swc1      $f0, 0x40($sp)
    /* 3D0E8 1500FC38 240C0001 */  addiu      $t4, $zero, 0x1
    /* 3D0EC 1500FC3C AFAC0010 */  sw         $t4, 0x10($sp)
    /* 3D0F0 1500FC40 2404F919 */  addiu      $a0, $zero, -0x6E7
    /* 3D0F4 1500FC44 2405FB96 */  addiu      $a1, $zero, -0x46A
    /* 3D0F8 1500FC48 24060421 */  addiu      $a2, $zero, 0x421
    /* 3D0FC 1500FC4C 0D403E74 */  jal        func_1500F9D0
    /* 3D100 1500FC50 2407F9B8 */   addiu     $a3, $zero, -0x648
    /* 3D104 1500FC54 24190002 */  addiu      $t9, $zero, 0x2
    /* 3D108 1500FC58 AFB90010 */  sw         $t9, 0x10($sp)
    /* 3D10C 1500FC5C 2404F58F */  addiu      $a0, $zero, -0xA71
    /* 3D110 1500FC60 2405071B */  addiu      $a1, $zero, 0x71B
    /* 3D114 1500FC64 2406082B */  addiu      $a2, $zero, 0x82B
    /* 3D118 1500FC68 0D403E74 */  jal        func_1500F9D0
    /* 3D11C 1500FC6C 2407F9FE */   addiu     $a3, $zero, -0x602
    /* 3D120 1500FC70 240B0002 */  addiu      $t3, $zero, 0x2
    /* 3D124 1500FC74 AFAB0010 */  sw         $t3, 0x10($sp)
    /* 3D128 1500FC78 2404F790 */  addiu      $a0, $zero, -0x870
    /* 3D12C 1500FC7C 2405036E */  addiu      $a1, $zero, 0x36E
    /* 3D130 1500FC80 240604E1 */  addiu      $a2, $zero, 0x4E1
    /* 3D134 1500FC84 0D403E74 */  jal        func_1500F9D0
    /* 3D138 1500FC88 2407F9FE */   addiu     $a3, $zero, -0x602
    /* 3D13C 1500FC8C 240A0002 */  addiu      $t2, $zero, 0x2
    /* 3D140 1500FC90 AFAA0010 */  sw         $t2, 0x10($sp)
    /* 3D144 1500FC94 2404F42B */  addiu      $a0, $zero, -0xBD5
    /* 3D148 1500FC98 240503F1 */  addiu      $a1, $zero, 0x3F1
    /* 3D14C 1500FC9C 24060659 */  addiu      $a2, $zero, 0x659
    /* 3D150 1500FCA0 0D403E74 */  jal        func_1500F9D0
    /* 3D154 1500FCA4 2407F9FE */   addiu     $a3, $zero, -0x602
    /* 3D158 1500FCA8 24180001 */  addiu      $t8, $zero, 0x1
    /* 3D15C 1500FCAC AFB80010 */  sw         $t8, 0x10($sp)
    /* 3D160 1500FCB0 2404F195 */  addiu      $a0, $zero, -0xE6B
    /* 3D164 1500FCB4 2405FD9D */  addiu      $a1, $zero, -0x263
    /* 3D168 1500FCB8 2406FBD9 */  addiu      $a2, $zero, -0x427
    /* 3D16C 1500FCBC 0D403E74 */  jal        func_1500F9D0
    /* 3D170 1500FCC0 2407F9B9 */   addiu     $a3, $zero, -0x647
    /* 3D174 1500FCC4 3C02800E */  lui        $v0, %hi(D_800DCD20)
    /* 3D178 1500FCC8 2442CD20 */  addiu      $v0, $v0, %lo(D_800DCD20)
    /* 3D17C 1500FCCC 904E0000 */  lbu        $t6, 0x0($v0)
    /* 3D180 1500FCD0 3C03800E */  lui        $v1, %hi(D_800DCD28)
    /* 3D184 1500FCD4 2463CD28 */  addiu      $v1, $v1, %lo(D_800DCD28)
    /* 3D188 1500FCD8 448E8000 */  mtc1       $t6, $f16
    /* 3D18C 1500FCDC 3C19800E */  lui        $t9, %hi(D_800DCD3C)
    /* 3D190 1500FCE0 05C10005 */  bgez       $t6, .L1500FCF8
    /* 3D194 1500FCE4 468084A0 */   cvt.s.w   $f18, $f16
    /* 3D198 1500FCE8 3C014F80 */  lui        $at, (0x4F800000 >> 16)
    /* 3D19C 1500FCEC 44812000 */  mtc1       $at, $f4
    /* 3D1A0 1500FCF0 00000000 */  nop
    /* 3D1A4 1500FCF4 46049480 */  add.s      $f18, $f18, $f4
  .L1500FCF8:
    /* 3D1A8 1500FCF8 3C01800E */  lui        $at, %hi(D_800DCDA4)
    /* 3D1AC 1500FCFC E432CDA4 */  swc1       $f18, %lo(D_800DCDA4)($at)
    /* 3D1B0 1500FD00 90480001 */  lbu        $t0, 0x1($v0)
    /* 3D1B4 1500FD04 3C014F80 */  lui        $at, (0x4F800000 >> 16)
    /* 3D1B8 1500FD08 3C0B800E */  lui        $t3, %hi(D_800DCD3D)
    /* 3D1BC 1500FD0C 44883000 */  mtc1       $t0, $f6
    /* 3D1C0 1500FD10 05010004 */  bgez       $t0, .L1500FD24
    /* 3D1C4 1500FD14 46803220 */   cvt.s.w   $f8, $f6
    /* 3D1C8 1500FD18 44815000 */  mtc1       $at, $f10
    /* 3D1CC 1500FD1C 00000000 */  nop
    /* 3D1D0 1500FD20 460A4200 */  add.s      $f8, $f8, $f10
  .L1500FD24:
    /* 3D1D4 1500FD24 3C01800E */  lui        $at, %hi(D_800DCDA8)
    /* 3D1D8 1500FD28 E428CDA8 */  swc1       $f8, %lo(D_800DCDA8)($at)
    /* 3D1DC 1500FD2C 90490002 */  lbu        $t1, 0x2($v0)
    /* 3D1E0 1500FD30 3C014F80 */  lui        $at, (0x4F800000 >> 16)
    /* 3D1E4 1500FD34 44898000 */  mtc1       $t1, $f16
    /* 3D1E8 1500FD38 05210004 */  bgez       $t1, .L1500FD4C
    /* 3D1EC 1500FD3C 46808120 */   cvt.s.w   $f4, $f16
    /* 3D1F0 1500FD40 44819000 */  mtc1       $at, $f18
    /* 3D1F4 1500FD44 00000000 */  nop
    /* 3D1F8 1500FD48 46122100 */  add.s      $f4, $f4, $f18
  .L1500FD4C:
    /* 3D1FC 1500FD4C 3C01800E */  lui        $at, %hi(D_800DCDAC)
    /* 3D200 1500FD50 E424CDAC */  swc1       $f4, %lo(D_800DCDAC)($at)
    /* 3D204 1500FD54 906F0000 */  lbu        $t7, 0x0($v1)
    /* 3D208 1500FD58 3C014F80 */  lui        $at, (0x4F800000 >> 16)
    /* 3D20C 1500FD5C 448F3000 */  mtc1       $t7, $f6
    /* 3D210 1500FD60 05E10004 */  bgez       $t7, .L1500FD74
    /* 3D214 1500FD64 468032A0 */   cvt.s.w   $f10, $f6
    /* 3D218 1500FD68 44814000 */  mtc1       $at, $f8
    /* 3D21C 1500FD6C 00000000 */  nop
    /* 3D220 1500FD70 46085280 */  add.s      $f10, $f10, $f8
  .L1500FD74:
    /* 3D224 1500FD74 3C01800E */  lui        $at, %hi(D_800DCDB0)
    /* 3D228 1500FD78 E42ACDB0 */  swc1       $f10, %lo(D_800DCDB0)($at)
    /* 3D22C 1500FD7C 906D0001 */  lbu        $t5, 0x1($v1)
    /* 3D230 1500FD80 3C014F80 */  lui        $at, (0x4F800000 >> 16)
    /* 3D234 1500FD84 448D8000 */  mtc1       $t5, $f16
    /* 3D238 1500FD88 05A10004 */  bgez       $t5, .L1500FD9C
    /* 3D23C 1500FD8C 468084A0 */   cvt.s.w   $f18, $f16
    /* 3D240 1500FD90 44812000 */  mtc1       $at, $f4
    /* 3D244 1500FD94 00000000 */  nop
    /* 3D248 1500FD98 46049480 */  add.s      $f18, $f18, $f4
  .L1500FD9C:
    /* 3D24C 1500FD9C 3C01800E */  lui        $at, %hi(D_800DCDB4)
    /* 3D250 1500FDA0 E432CDB4 */  swc1       $f18, %lo(D_800DCDB4)($at)
    /* 3D254 1500FDA4 906C0002 */  lbu        $t4, 0x2($v1)
    /* 3D258 1500FDA8 3C014F80 */  lui        $at, (0x4F800000 >> 16)
    /* 3D25C 1500FDAC 448C3000 */  mtc1       $t4, $f6
    /* 3D260 1500FDB0 05810004 */  bgez       $t4, .L1500FDC4
    /* 3D264 1500FDB4 46803220 */   cvt.s.w   $f8, $f6
    /* 3D268 1500FDB8 44815000 */  mtc1       $at, $f10
    /* 3D26C 1500FDBC 00000000 */  nop
    /* 3D270 1500FDC0 460A4200 */  add.s      $f8, $f8, $f10
  .L1500FDC4:
    /* 3D274 1500FDC4 9339CD3C */  lbu        $t9, %lo(D_800DCD3C)($t9)
    /* 3D278 1500FDC8 3C01800E */  lui        $at, %hi(D_800DCDB8)
    /* 3D27C 1500FDCC E428CDB8 */  swc1       $f8, %lo(D_800DCDB8)($at)
    /* 3D280 1500FDD0 44998000 */  mtc1       $t9, $f16
    /* 3D284 1500FDD4 3C014F80 */  lui        $at, (0x4F800000 >> 16)
    /* 3D288 1500FDD8 07210004 */  bgez       $t9, .L1500FDEC
    /* 3D28C 1500FDDC 46808120 */   cvt.s.w   $f4, $f16
    /* 3D290 1500FDE0 44819000 */  mtc1       $at, $f18
    /* 3D294 1500FDE4 00000000 */  nop
    /* 3D298 1500FDE8 46122100 */  add.s      $f4, $f4, $f18
  .L1500FDEC:
    /* 3D29C 1500FDEC 916BCD3D */  lbu        $t3, %lo(D_800DCD3D)($t3)
    /* 3D2A0 1500FDF0 3C01800E */  lui        $at, %hi(D_800DCDBC)
    /* 3D2A4 1500FDF4 E424CDBC */  swc1       $f4, %lo(D_800DCDBC)($at)
    /* 3D2A8 1500FDF8 448B3000 */  mtc1       $t3, $f6
    /* 3D2AC 1500FDFC 3C014F80 */  lui        $at, (0x4F800000 >> 16)
    /* 3D2B0 1500FE00 05610004 */  bgez       $t3, .L1500FE14
    /* 3D2B4 1500FE04 468032A0 */   cvt.s.w   $f10, $f6
    /* 3D2B8 1500FE08 44814000 */  mtc1       $at, $f8
    /* 3D2BC 1500FE0C 00000000 */  nop
    /* 3D2C0 1500FE10 46085280 */  add.s      $f10, $f10, $f8
  .L1500FE14:
    /* 3D2C4 1500FE14 3C01800E */  lui        $at, %hi(D_800DCDC0)
    /* 3D2C8 1500FE18 E42ACDC0 */  swc1       $f10, %lo(D_800DCDC0)($at)
    /* 3D2CC 1500FE1C 8FBF001C */  lw         $ra, 0x1C($sp)
    /* 3D2D0 1500FE20 27BD0048 */  addiu      $sp, $sp, 0x48
    /* 3D2D4 1500FE24 03E00008 */  jr         $ra
    /* 3D2D8 1500FE28 00000000 */   nop
endlabel func_1500FA64
    /* 3D2DC 1500FE2C 00000000 */  nop
