.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching func_1503DDD0, 0x94

glabel func_1503DDD0
    /* 6B280 1503DDD0 04800022 */  bltz       $a0, .L1503DE5C
    /* 6B284 1503DDD4 3C05800C */   lui       $a1, %hi(D_800C6654)
    /* 6B288 1503DDD8 24A56654 */  addiu      $a1, $a1, %lo(D_800C6654)
    /* 6B28C 1503DDDC 8CAE0000 */  lw         $t6, 0x0($a1)
    /* 6B290 1503DDE0 24070014 */  addiu      $a3, $zero, 0x14
    /* 6B294 1503DDE4 008E082B */  sltu       $at, $a0, $t6
    /* 6B298 1503DDE8 1020001C */  beqz       $at, .L1503DE5C
    /* 6B29C 1503DDEC 00000000 */   nop
    /* 6B2A0 1503DDF0 00870019 */  multu      $a0, $a3
    /* 6B2A4 1503DDF4 3C06800C */  lui        $a2, %hi(D_800C6650)
    /* 6B2A8 1503DDF8 24C66650 */  addiu      $a2, $a2, %lo(D_800C6650)
    /* 6B2AC 1503DDFC 8CD80000 */  lw         $t8, 0x0($a2)
    /* 6B2B0 1503DE00 240F0002 */  addiu      $t7, $zero, 0x2
    /* 6B2B4 1503DE04 0000C812 */  mflo       $t9
    /* 6B2B8 1503DE08 03194021 */  addu       $t0, $t8, $t9
    /* 6B2BC 1503DE0C A50F0006 */  sh         $t7, 0x6($t0)
    /* 6B2C0 1503DE10 8CA20000 */  lw         $v0, 0x0($a1)
    /* 6B2C4 1503DE14 10400011 */  beqz       $v0, .L1503DE5C
    /* 6B2C8 1503DE18 2444FFFF */   addiu     $a0, $v0, -0x1
    /* 6B2CC 1503DE1C 00870019 */  multu      $a0, $a3
    /* 6B2D0 1503DE20 8CC90000 */  lw         $t1, 0x0($a2)
    /* 6B2D4 1503DE24 00005012 */  mflo       $t2
    /* 6B2D8 1503DE28 012A1821 */  addu       $v1, $t1, $t2
    /* 6B2DC 1503DE2C 946B0006 */  lhu        $t3, 0x6($v1)
    /* 6B2E0 1503DE30 316C0002 */  andi       $t4, $t3, 0x2
    /* 6B2E4 1503DE34 11800009 */  beqz       $t4, .L1503DE5C
    /* 6B2E8 1503DE38 244DFFFF */   addiu     $t5, $v0, -0x1
  .L1503DE3C:
    /* 6B2EC 1503DE3C ACAD0000 */  sw         $t5, 0x0($a1)
    /* 6B2F0 1503DE40 01A01025 */  or         $v0, $t5, $zero
    /* 6B2F4 1503DE44 11A00005 */  beqz       $t5, .L1503DE5C
    /* 6B2F8 1503DE48 2463FFEC */   addiu     $v1, $v1, -0x14
    /* 6B2FC 1503DE4C 946E0006 */  lhu        $t6, 0x6($v1)
    /* 6B300 1503DE50 31D80002 */  andi       $t8, $t6, 0x2
    /* 6B304 1503DE54 5700FFF9 */  bnel       $t8, $zero, .L1503DE3C
    /* 6B308 1503DE58 244DFFFF */   addiu     $t5, $v0, -0x1
  .L1503DE5C:
    /* 6B30C 1503DE5C 03E00008 */  jr         $ra
    /* 6B310 1503DE60 00000000 */   nop
endlabel func_1503DDD0
    /* 6B314 1503DE64 00000000 */  nop
    /* 6B318 1503DE68 00000000 */  nop
    /* 6B31C 1503DE6C 00000000 */  nop
