.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching func_15080D20, 0x36C

glabel func_15080D20
    /* AE1D0 15080D20 27BDFF30 */  addiu      $sp, $sp, -0xD0
    /* AE1D4 15080D24 AFB70058 */  sw         $s7, 0x58($sp)
    /* AE1D8 15080D28 AFB4004C */  sw         $s4, 0x4C($sp)
    /* AE1DC 15080D2C AFB0003C */  sw         $s0, 0x3C($sp)
    /* AE1E0 15080D30 F7B60028 */  sdc1       $f22, 0x28($sp)
    /* AE1E4 15080D34 44877000 */  mtc1       $a3, $f14
    /* AE1E8 15080D38 C7B600E0 */  lwc1       $f22, 0xE0($sp)
    /* AE1EC 15080D3C 00C08025 */  or         $s0, $a2, $zero
    /* AE1F0 15080D40 00A0A025 */  or         $s4, $a1, $zero
    /* AE1F4 15080D44 0080B825 */  or         $s7, $a0, $zero
    /* AE1F8 15080D48 AFBF005C */  sw         $ra, 0x5C($sp)
    /* AE1FC 15080D4C AFB60054 */  sw         $s6, 0x54($sp)
    /* AE200 15080D50 AFB50050 */  sw         $s5, 0x50($sp)
    /* AE204 15080D54 AFB30048 */  sw         $s3, 0x48($sp)
    /* AE208 15080D58 AFB20044 */  sw         $s2, 0x44($sp)
    /* AE20C 15080D5C AFB10040 */  sw         $s1, 0x40($sp)
    /* AE210 15080D60 F7B80030 */  sdc1       $f24, 0x30($sp)
    /* AE214 15080D64 F7B40020 */  sdc1       $f20, 0x20($sp)
    /* AE218 15080D68 C6E0014C */  lwc1       $f0, 0x14C($s7)
    /* AE21C 15080D6C 3C01800A */  lui        $at, %hi(D_8009CBD8)
    /* AE220 15080D70 C42ACBD8 */  lwc1       $f10, %lo(D_8009CBD8)($at)
    /* AE224 15080D74 46007382 */  mul.s      $f14, $f14, $f0
    /* AE228 15080D78 C6E400B8 */  lwc1       $f4, 0xB8($s7)
    /* AE22C 15080D7C 4600B582 */  mul.s      $f22, $f22, $f0
    /* AE230 15080D80 00000000 */  nop
    /* AE234 15080D84 460A2502 */  mul.s      $f20, $f4, $f10
    /* AE238 15080D88 E7AE00DC */  swc1       $f14, 0xDC($sp)
    /* AE23C 15080D8C 0D411F58 */  jal        sinf
    /* AE240 15080D90 4600A306 */   mov.s     $f12, $f20
    /* AE244 15080D94 46000606 */  mov.s      $f24, $f0
    /* AE248 15080D98 0D411F00 */  jal        cosf
    /* AE24C 15080D9C 4600A306 */   mov.s     $f12, $f20
    /* AE250 15080DA0 C7AE00DC */  lwc1       $f14, 0xDC($sp)
    /* AE254 15080DA4 44803000 */  mtc1       $zero, $f6
    /* AE258 15080DA8 3C01800A */  lui        $at, %hi(D_8009CBDC)
    /* AE25C 15080DAC 46007207 */  neg.s      $f8, $f14
    /* AE260 15080DB0 E7A600A0 */  swc1       $f6, 0xA0($sp)
    /* AE264 15080DB4 46184102 */  mul.s      $f4, $f8, $f24
    /* AE268 15080DB8 C428CBDC */  lwc1       $f8, %lo(D_8009CBDC)($at)
    /* AE26C 15080DBC 46007282 */  mul.s      $f10, $f14, $f0
    /* AE270 15080DC0 E7A400A4 */  swc1       $f4, 0xA4($sp)
    /* AE274 15080DC4 E7AA00A8 */  swc1       $f10, 0xA8($sp)
    /* AE278 15080DC8 C6E60040 */  lwc1       $f6, 0x40($s7)
    /* AE27C 15080DCC 46083502 */  mul.s      $f20, $f6, $f8
    /* AE280 15080DD0 0D411F58 */  jal        sinf
    /* AE284 15080DD4 4600A306 */   mov.s     $f12, $f20
    /* AE288 15080DD8 46000606 */  mov.s      $f24, $f0
    /* AE28C 15080DDC 0D411F00 */  jal        cosf
    /* AE290 15080DE0 4600A306 */   mov.s     $f12, $f20
    /* AE294 15080DE4 C7A400A8 */  lwc1       $f4, 0xA8($sp)
    /* AE298 15080DE8 C7A600A0 */  lwc1       $f6, 0xA0($sp)
    /* AE29C 15080DEC 3C02800D */  lui        $v0, %hi(D_800D1C90)
    /* AE2A0 15080DF0 46182282 */  mul.s      $f10, $f4, $f24
    /* AE2A4 15080DF4 3C15800A */  lui        $s5, %hi(D_8009CBCC)
    /* AE2A8 15080DF8 3C014F80 */  lui        $at, (0x4F800000 >> 16)
    /* AE2AC 15080DFC 46003202 */  mul.s      $f8, $f6, $f0
    /* AE2B0 15080E00 00105880 */  sll        $t3, $s0, 2
    /* AE2B4 15080E04 02B0A821 */  addu       $s5, $s5, $s0
    /* AE2B8 15080E08 00008825 */  or         $s1, $zero, $zero
    /* AE2BC 15080E0C 46085400 */  add.s      $f16, $f10, $f8
    /* AE2C0 15080E10 46002282 */  mul.s      $f10, $f4, $f0
    /* AE2C4 15080E14 46003207 */  neg.s      $f8, $f6
    /* AE2C8 15080E18 E7B000A0 */  swc1       $f16, 0xA0($sp)
    /* AE2CC 15080E1C 46184102 */  mul.s      $f4, $f8, $f24
    /* AE2D0 15080E20 C7A800A0 */  lwc1       $f8, 0xA0($sp)
    /* AE2D4 15080E24 46045180 */  add.s      $f6, $f10, $f4
    /* AE2D8 15080E28 E7A600A8 */  swc1       $f6, 0xA8($sp)
    /* AE2DC 15080E2C C6EA0014 */  lwc1       $f10, 0x14($s7)
    /* AE2E0 15080E30 C7A600A4 */  lwc1       $f6, 0xA4($sp)
    /* AE2E4 15080E34 460A4100 */  add.s      $f4, $f8, $f10
    /* AE2E8 15080E38 E7A400A0 */  swc1       $f4, 0xA0($sp)
    /* AE2EC 15080E3C C6E80018 */  lwc1       $f8, 0x18($s7)
    /* AE2F0 15080E40 46083280 */  add.s      $f10, $f6, $f8
    /* AE2F4 15080E44 C7A600A8 */  lwc1       $f6, 0xA8($sp)
    /* AE2F8 15080E48 E7AA00A4 */  swc1       $f10, 0xA4($sp)
    /* AE2FC 15080E4C C6E8001C */  lwc1       $f8, 0x1C($s7)
    /* AE300 15080E50 46083180 */  add.s      $f6, $f6, $f8
    /* AE304 15080E54 E7A600A8 */  swc1       $f6, 0xA8($sp)
    /* AE308 15080E58 92830004 */  lbu        $v1, 0x4($s4)
    /* AE30C 15080E5C 00034080 */  sll        $t0, $v1, 2
    /* AE310 15080E60 00481021 */  addu       $v0, $v0, $t0
    /* AE314 15080E64 8C421C90 */  lw         $v0, %lo(D_800D1C90)($v0)
    /* AE318 15080E68 9449000E */  lhu        $t1, 0xE($v0)
    /* AE31C 15080E6C E7A40060 */  swc1       $f4, 0x60($sp)
    /* AE320 15080E70 44894000 */  mtc1       $t1, $f8
    /* AE324 15080E74 05210004 */  bgez       $t1, .L15080E88
    /* AE328 15080E78 46804220 */   cvt.s.w   $f8, $f8
    /* AE32C 15080E7C 44812000 */  mtc1       $at, $f4
    /* AE330 15080E80 00000000 */  nop
    /* AE334 15080E84 46044200 */  add.s      $f8, $f8, $f4
  .L15080E88:
    /* AE338 15080E88 C684014C */  lwc1       $f4, 0x14C($s4)
    /* AE33C 15080E8C 844A0010 */  lh         $t2, 0x10($v0)
    /* AE340 15080E90 3C028008 */  lui        $v0, %hi(D_80086C60)
    /* AE344 15080E94 46044502 */  mul.s      $f20, $f8, $f4
    /* AE348 15080E98 448A4000 */  mtc1       $t2, $f8
    /* AE34C 15080E9C 00000000 */  nop
    /* AE350 15080EA0 46804120 */  cvt.s.w    $f4, $f8
    /* AE354 15080EA4 C6880150 */  lwc1       $f8, 0x150($s4)
    /* AE358 15080EA8 46082482 */  mul.s      $f18, $f4, $f8
    /* AE35C 15080EAC C6880014 */  lwc1       $f8, 0x14($s4)
    /* AE360 15080EB0 C7A40060 */  lwc1       $f4, 0x60($sp)
    /* AE364 15080EB4 46082081 */  sub.s      $f2, $f4, $f8
    /* AE368 15080EB8 C6840018 */  lwc1       $f4, 0x18($s4)
    /* AE36C 15080EBC 46122200 */  add.s      $f8, $f4, $f18
    /* AE370 15080EC0 C684001C */  lwc1       $f4, 0x1C($s4)
    /* AE374 15080EC4 46085301 */  sub.s      $f12, $f10, $f8
    /* AE378 15080EC8 4614A282 */  mul.s      $f10, $f20, $f20
    /* AE37C 15080ECC 46043381 */  sub.s      $f14, $f6, $f4
    /* AE380 15080ED0 46021202 */  mul.s      $f8, $f2, $f2
    /* AE384 15080ED4 00000000 */  nop
    /* AE388 15080ED8 460C6182 */  mul.s      $f6, $f12, $f12
    /* AE38C 15080EDC 46064100 */  add.s      $f4, $f8, $f6
    /* AE390 15080EE0 460E7202 */  mul.s      $f8, $f14, $f14
    /* AE394 15080EE4 46082180 */  add.s      $f6, $f4, $f8
    /* AE398 15080EE8 4606503C */  c.lt.s     $f10, $f6
    /* AE39C 15080EEC 00000000 */  nop
    /* AE3A0 15080EF0 45000003 */  bc1f       .L15080F00
    /* AE3A4 15080EF4 00000000 */   nop
    /* AE3A8 15080EF8 10000056 */  b          .L15081054
    /* AE3AC 15080EFC 00001025 */   or        $v0, $zero, $zero
  .L15080F00:
    /* AE3B0 15080F00 92B5CBCC */  lbu        $s5, %lo(D_8009CBCC)($s5)
    /* AE3B4 15080F04 004B1021 */  addu       $v0, $v0, $t3
    /* AE3B8 15080F08 8C426C60 */  lw         $v0, %lo(D_80086C60)($v0)
    /* AE3BC 15080F0C 1AA00050 */  blez       $s5, .L15081050
    /* AE3C0 15080F10 8E9601D4 */   lw        $s6, 0x1D4($s4)
    /* AE3C4 15080F14 00408025 */  or         $s0, $v0, $zero
    /* AE3C8 15080F18 27B30078 */  addiu      $s3, $sp, 0x78
    /* AE3CC 15080F1C 27B20084 */  addiu      $s2, $sp, 0x84
  .L15080F20:
    /* AE3D0 15080F20 860C0004 */  lh         $t4, 0x4($s0)
    /* AE3D4 15080F24 02402025 */  or         $a0, $s2, $zero
    /* AE3D8 15080F28 02602825 */  or         $a1, $s3, $zero
    /* AE3DC 15080F2C 448C2000 */  mtc1       $t4, $f4
    /* AE3E0 15080F30 00000000 */  nop
    /* AE3E4 15080F34 46802220 */  cvt.s.w    $f8, $f4
    /* AE3E8 15080F38 E7A80084 */  swc1       $f8, 0x84($sp)
    /* AE3EC 15080F3C 860D0006 */  lh         $t5, 0x6($s0)
    /* AE3F0 15080F40 448D5000 */  mtc1       $t5, $f10
    /* AE3F4 15080F44 00000000 */  nop
    /* AE3F8 15080F48 468051A0 */  cvt.s.w    $f6, $f10
    /* AE3FC 15080F4C E7A60088 */  swc1       $f6, 0x88($sp)
    /* AE400 15080F50 860E0008 */  lh         $t6, 0x8($s0)
    /* AE404 15080F54 448E2000 */  mtc1       $t6, $f4
    /* AE408 15080F58 00000000 */  nop
    /* AE40C 15080F5C 46802220 */  cvt.s.w    $f8, $f4
    /* AE410 15080F60 E7A8008C */  swc1       $f8, 0x8C($sp)
    /* AE414 15080F64 920F0000 */  lbu        $t7, 0x0($s0)
    /* AE418 15080F68 000FC180 */  sll        $t8, $t7, 6
    /* AE41C 15080F6C 0D450C4D */  jal        func_15143134
    /* AE420 15080F70 02D83021 */   addu      $a2, $s6, $t8
    /* AE424 15080F74 C7AA00A0 */  lwc1       $f10, 0xA0($sp)
    /* AE428 15080F78 C7A60078 */  lwc1       $f6, 0x78($sp)
    /* AE42C 15080F7C C7A400A4 */  lwc1       $f4, 0xA4($sp)
    /* AE430 15080F80 C7A8007C */  lwc1       $f8, 0x7C($sp)
    /* AE434 15080F84 96190002 */  lhu        $t9, 0x2($s0)
    /* AE438 15080F88 46065081 */  sub.s      $f2, $f10, $f6
    /* AE43C 15080F8C C7A60080 */  lwc1       $f6, 0x80($sp)
    /* AE440 15080F90 C7AA00A8 */  lwc1       $f10, 0xA8($sp)
    /* AE444 15080F94 46082301 */  sub.s      $f12, $f4, $f8
    /* AE448 15080F98 44992000 */  mtc1       $t9, $f4
    /* AE44C 15080F9C 26310001 */  addiu      $s1, $s1, 0x1
    /* AE450 15080FA0 46065381 */  sub.s      $f14, $f10, $f6
    /* AE454 15080FA4 07210005 */  bgez       $t9, .L15080FBC
    /* AE458 15080FA8 46802220 */   cvt.s.w   $f8, $f4
    /* AE45C 15080FAC 3C014F80 */  lui        $at, (0x4F800000 >> 16)
    /* AE460 15080FB0 44815000 */  mtc1       $at, $f10
    /* AE464 15080FB4 00000000 */  nop
    /* AE468 15080FB8 460A4200 */  add.s      $f8, $f8, $f10
  .L15080FBC:
    /* AE46C 15080FBC C686014C */  lwc1       $f6, 0x14C($s4)
    /* AE470 15080FC0 46064102 */  mul.s      $f4, $f8, $f6
    /* AE474 15080FC4 46162000 */  add.s      $f0, $f4, $f22
    /* AE478 15080FC8 46000282 */  mul.s      $f10, $f0, $f0
    /* AE47C 15080FCC 00000000 */  nop
    /* AE480 15080FD0 46021202 */  mul.s      $f8, $f2, $f2
    /* AE484 15080FD4 00000000 */  nop
    /* AE488 15080FD8 460C6182 */  mul.s      $f6, $f12, $f12
    /* AE48C 15080FDC 46064100 */  add.s      $f4, $f8, $f6
    /* AE490 15080FE0 460E7202 */  mul.s      $f8, $f14, $f14
    /* AE494 15080FE4 46082180 */  add.s      $f6, $f4, $f8
    /* AE498 15080FE8 4606503C */  c.lt.s     $f10, $f6
    /* AE49C 15080FEC 00000000 */  nop
    /* AE4A0 15080FF0 45010015 */  bc1t       .L15081048
    /* AE4A4 15080FF4 00000000 */   nop
    /* AE4A8 15080FF8 92880125 */  lbu        $t0, 0x125($s4)
    /* AE4AC 15080FFC 3C09800D */  lui        $t1, %hi(D_800CC2D0)
    /* AE4B0 15081000 2529C2D0 */  addiu      $t1, $t1, %lo(D_800CC2D0)
    /* AE4B4 15081004 1500000D */  bnez       $t0, .L1508103C
    /* AE4B8 15081008 8FA700E4 */   lw        $a3, 0xE4($sp)
    /* AE4BC 1508100C 02E95023 */  subu       $t2, $s7, $t1
    /* AE4C0 15081010 2401032C */  addiu      $at, $zero, 0x32C
    /* AE4C4 15081014 0141001A */  div        $zero, $t2, $at
    /* AE4C8 15081018 C68C0014 */  lwc1       $f12, 0x14($s4)
    /* AE4CC 1508101C C68E0018 */  lwc1       $f14, 0x18($s4)
    /* AE4D0 15081020 8E86001C */  lw         $a2, 0x1C($s4)
    /* AE4D4 15081024 00005812 */  mflo       $t3
    /* AE4D8 15081028 AFAB0010 */  sw         $t3, 0x10($sp)
    /* AE4DC 1508102C AFA0001C */  sw         $zero, 0x1C($sp)
    /* AE4E0 15081030 AFA00018 */  sw         $zero, 0x18($sp)
    /* AE4E4 15081034 0D417471 */  jal        func_1505D1C4
    /* AE4E8 15081038 AFA00014 */   sw        $zero, 0x14($sp)
  .L1508103C:
    /* AE4EC 1508103C 92020000 */  lbu        $v0, 0x0($s0)
    /* AE4F0 15081040 10000004 */  b          .L15081054
    /* AE4F4 15081044 24420001 */   addiu     $v0, $v0, 0x1
  .L15081048:
    /* AE4F8 15081048 1635FFB5 */  bne        $s1, $s5, .L15080F20
    /* AE4FC 1508104C 2610000A */   addiu     $s0, $s0, 0xA
  .L15081050:
    /* AE500 15081050 00001025 */  or         $v0, $zero, $zero
  .L15081054:
    /* AE504 15081054 8FBF005C */  lw         $ra, 0x5C($sp)
    /* AE508 15081058 D7B40020 */  ldc1       $f20, 0x20($sp)
    /* AE50C 1508105C D7B60028 */  ldc1       $f22, 0x28($sp)
    /* AE510 15081060 D7B80030 */  ldc1       $f24, 0x30($sp)
    /* AE514 15081064 8FB0003C */  lw         $s0, 0x3C($sp)
    /* AE518 15081068 8FB10040 */  lw         $s1, 0x40($sp)
    /* AE51C 1508106C 8FB20044 */  lw         $s2, 0x44($sp)
    /* AE520 15081070 8FB30048 */  lw         $s3, 0x48($sp)
    /* AE524 15081074 8FB4004C */  lw         $s4, 0x4C($sp)
    /* AE528 15081078 8FB50050 */  lw         $s5, 0x50($sp)
    /* AE52C 1508107C 8FB60054 */  lw         $s6, 0x54($sp)
    /* AE530 15081080 8FB70058 */  lw         $s7, 0x58($sp)
    /* AE534 15081084 03E00008 */  jr         $ra
    /* AE538 15081088 27BD00D0 */   addiu     $sp, $sp, 0xD0
endlabel func_15080D20

nonmatching func_1508108C, 0xC0

glabel func_1508108C
    /* AE53C 1508108C 3C0E800A */  lui        $t6, %hi(D_8009BD30)
    /* AE540 15081090 95CEBD30 */  lhu        $t6, %lo(D_8009BD30)($t6)
    /* AE544 15081094 90820004 */  lbu        $v0, 0x4($a0)
    /* AE548 15081098 3C0F800A */  lui        $t7, %hi(D_8009BD34)
    /* AE54C 1508109C 144E0003 */  bne        $v0, $t6, .L150810AC
    /* AE550 150810A0 00000000 */   nop
    /* AE554 150810A4 03E00008 */  jr         $ra
    /* AE558 150810A8 00001025 */   or        $v0, $zero, $zero
  .L150810AC:
    /* AE55C 150810AC 95EFBD34 */  lhu        $t7, %lo(D_8009BD34)($t7)
    /* AE560 150810B0 3C18800A */  lui        $t8, %hi(D_8009BD38)
    /* AE564 150810B4 144F0003 */  bne        $v0, $t7, .L150810C4
    /* AE568 150810B8 00000000 */   nop
    /* AE56C 150810BC 03E00008 */  jr         $ra
    /* AE570 150810C0 24020001 */   addiu     $v0, $zero, 0x1
  .L150810C4:
    /* AE574 150810C4 9718BD38 */  lhu        $t8, %lo(D_8009BD38)($t8)
    /* AE578 150810C8 3C04800A */  lui        $a0, %hi(D_8009BD3C)
    /* AE57C 150810CC 2484BD3C */  addiu      $a0, $a0, %lo(D_8009BD3C)
    /* AE580 150810D0 14580003 */  bne        $v0, $t8, .L150810E0
    /* AE584 150810D4 24030003 */   addiu     $v1, $zero, 0x3
    /* AE588 150810D8 03E00008 */  jr         $ra
    /* AE58C 150810DC 24020002 */   addiu     $v0, $zero, 0x2
  .L150810E0:
    /* AE590 150810E0 24050017 */  addiu      $a1, $zero, 0x17
  .L150810E4:
    /* AE594 150810E4 94990000 */  lhu        $t9, 0x0($a0)
    /* AE598 150810E8 54590004 */  bnel       $v0, $t9, .L150810FC
    /* AE59C 150810EC 94880004 */   lhu       $t0, 0x4($a0)
    /* AE5A0 150810F0 03E00008 */  jr         $ra
    /* AE5A4 150810F4 00601025 */   or        $v0, $v1, $zero
    /* AE5A8 150810F8 94880004 */  lhu        $t0, 0x4($a0)
  .L150810FC:
    /* AE5AC 150810FC 54480004 */  bnel       $v0, $t0, .L15081110
    /* AE5B0 15081100 94890008 */   lhu       $t1, 0x8($a0)
    /* AE5B4 15081104 03E00008 */  jr         $ra
    /* AE5B8 15081108 24620001 */   addiu     $v0, $v1, 0x1
    /* AE5BC 1508110C 94890008 */  lhu        $t1, 0x8($a0)
  .L15081110:
    /* AE5C0 15081110 54490004 */  bnel       $v0, $t1, .L15081124
    /* AE5C4 15081114 948A000C */   lhu       $t2, 0xC($a0)
    /* AE5C8 15081118 03E00008 */  jr         $ra
    /* AE5CC 1508111C 24620002 */   addiu     $v0, $v1, 0x2
    /* AE5D0 15081120 948A000C */  lhu        $t2, 0xC($a0)
  .L15081124:
    /* AE5D4 15081124 544A0004 */  bnel       $v0, $t2, .L15081138
    /* AE5D8 15081128 24630004 */   addiu     $v1, $v1, 0x4
    /* AE5DC 1508112C 03E00008 */  jr         $ra
    /* AE5E0 15081130 24620003 */   addiu     $v0, $v1, 0x3
    /* AE5E4 15081134 24630004 */  addiu      $v1, $v1, 0x4
  .L15081138:
    /* AE5E8 15081138 1465FFEA */  bne        $v1, $a1, .L150810E4
    /* AE5EC 1508113C 24840010 */   addiu     $a0, $a0, 0x10
    /* AE5F0 15081140 2402FFFF */  addiu      $v0, $zero, -0x1
    /* AE5F4 15081144 03E00008 */  jr         $ra
    /* AE5F8 15081148 00000000 */   nop
endlabel func_1508108C

nonmatching func_1508114C, 0x428

glabel func_1508114C
    /* AE5FC 1508114C 27BDFF20 */  addiu      $sp, $sp, -0xE0
    /* AE600 15081150 AFB20038 */  sw         $s2, 0x38($sp)
    /* AE604 15081154 00809025 */  or         $s2, $a0, $zero
    /* AE608 15081158 AFBF0054 */  sw         $ra, 0x54($sp)
    /* AE60C 1508115C AFBE0050 */  sw         $fp, 0x50($sp)
    /* AE610 15081160 AFB7004C */  sw         $s7, 0x4C($sp)
    /* AE614 15081164 AFB60048 */  sw         $s6, 0x48($sp)
    /* AE618 15081168 AFB50044 */  sw         $s5, 0x44($sp)
    /* AE61C 1508116C AFB40040 */  sw         $s4, 0x40($sp)
    /* AE620 15081170 AFB3003C */  sw         $s3, 0x3C($sp)
    /* AE624 15081174 AFB10034 */  sw         $s1, 0x34($sp)
    /* AE628 15081178 AFB00030 */  sw         $s0, 0x30($sp)
    /* AE62C 1508117C F7B40028 */  sdc1       $f20, 0x28($sp)
    /* AE630 15081180 AFA500E4 */  sw         $a1, 0xE4($sp)
    /* AE634 15081184 AFA600E8 */  sw         $a2, 0xE8($sp)
    /* AE638 15081188 AFA700EC */  sw         $a3, 0xEC($sp)
    /* AE63C 1508118C 8E4E01D4 */  lw         $t6, 0x1D4($s2)
    /* AE640 15081190 15C00003 */  bnez       $t6, .L150811A0
    /* AE644 15081194 00000000 */   nop
    /* AE648 15081198 100000E9 */  b          .L15081540
    /* AE64C 1508119C 2402FFFF */   addiu     $v0, $zero, -0x1
  .L150811A0:
    /* AE650 150811A0 0D420423 */  jal        func_1508108C
    /* AE654 150811A4 02402025 */   or        $a0, $s2, $zero
    /* AE658 150811A8 2401FFFF */  addiu      $at, $zero, -0x1
    /* AE65C 150811AC 14410003 */  bne        $v0, $at, .L150811BC
    /* AE660 150811B0 00401825 */   or        $v1, $v0, $zero
    /* AE664 150811B4 100000E2 */  b          .L15081540
    /* AE668 150811B8 2402FFFF */   addiu     $v0, $zero, -0x1
  .L150811BC:
    /* AE66C 150811BC 00037880 */  sll        $t7, $v1, 2
    /* AE670 150811C0 3C02800A */  lui        $v0, %hi(D_8009BD32)
    /* AE674 150811C4 004F1021 */  addu       $v0, $v0, $t7
    /* AE678 150811C8 9042BD32 */  lbu        $v0, %lo(D_8009BD32)($v0)
    /* AE67C 150811CC 3C198008 */  lui        $t9, %hi(D_80086C60)
    /* AE680 150811D0 3C09800A */  lui        $t1, %hi(D_8009CBCC)
    /* AE684 150811D4 0002C080 */  sll        $t8, $v0, 2
    /* AE688 150811D8 0338C821 */  addu       $t9, $t9, $t8
    /* AE68C 150811DC 01224821 */  addu       $t1, $t1, $v0
    /* AE690 150811E0 8F396C60 */  lw         $t9, %lo(D_80086C60)($t9)
    /* AE694 150811E4 9129CBCC */  lbu        $t1, %lo(D_8009CBCC)($t1)
    /* AE698 150811E8 3C01BF80 */  lui        $at, (0xBF800000 >> 16)
    /* AE69C 150811EC 4481A000 */  mtc1       $at, $f20
    /* AE6A0 150811F0 8FB700F8 */  lw         $s7, 0xF8($sp)
    /* AE6A4 150811F4 AFB900D8 */  sw         $t9, 0xD8($sp)
    /* AE6A8 150811F8 AFA900D4 */  sw         $t1, 0xD4($sp)
    /* AE6AC 150811FC E6F40000 */  swc1       $f20, 0x0($s7)
    /* AE6B0 15081200 C6440014 */  lwc1       $f4, 0x14($s2)
    /* AE6B4 15081204 3C08800D */  lui        $t0, %hi(D_800D1C90)
    /* AE6B8 15081208 25081C90 */  addiu      $t0, $t0, %lo(D_800D1C90)
    /* AE6BC 1508120C E7A400B4 */  swc1       $f4, 0xB4($sp)
    /* AE6C0 15081210 924A0004 */  lbu        $t2, 0x4($s2)
    /* AE6C4 15081214 C64A0150 */  lwc1       $f10, 0x150($s2)
    /* AE6C8 15081218 C6520018 */  lwc1       $f18, 0x18($s2)
    /* AE6CC 1508121C 000A5880 */  sll        $t3, $t2, 2
    /* AE6D0 15081220 010B6021 */  addu       $t4, $t0, $t3
    /* AE6D4 15081224 8D8D0000 */  lw         $t5, 0x0($t4)
    /* AE6D8 15081228 27B300B4 */  addiu      $s3, $sp, 0xB4
    /* AE6DC 1508122C 27B5009C */  addiu      $s5, $sp, 0x9C
    /* AE6E0 15081230 85AE0010 */  lh         $t6, 0x10($t5)
    /* AE6E4 15081234 27B60090 */  addiu      $s6, $sp, 0x90
    /* AE6E8 15081238 3C014F80 */  lui        $at, (0x4F800000 >> 16)
    /* AE6EC 1508123C 448E3000 */  mtc1       $t6, $f6
    /* AE6F0 15081240 00000000 */  nop
    /* AE6F4 15081244 46803220 */  cvt.s.w    $f8, $f6
    /* AE6F8 15081248 460A4402 */  mul.s      $f16, $f8, $f10
    /* AE6FC 1508124C 46128100 */  add.s      $f4, $f16, $f18
    /* AE700 15081250 E7A400B8 */  swc1       $f4, 0xB8($sp)
    /* AE704 15081254 C646001C */  lwc1       $f6, 0x1C($s2)
    /* AE708 15081258 E7A600BC */  swc1       $f6, 0xBC($sp)
    /* AE70C 1508125C 924F0004 */  lbu        $t7, 0x4($s2)
    /* AE710 15081260 000FC080 */  sll        $t8, $t7, 2
    /* AE714 15081264 0118C821 */  addu       $t9, $t0, $t8
    /* AE718 15081268 8F290000 */  lw         $t1, 0x0($t9)
    /* AE71C 1508126C 952A000E */  lhu        $t2, 0xE($t1)
    /* AE720 15081270 448A4000 */  mtc1       $t2, $f8
    /* AE724 15081274 05410004 */  bgez       $t2, .L15081288
    /* AE728 15081278 468042A0 */   cvt.s.w   $f10, $f8
    /* AE72C 1508127C 44818000 */  mtc1       $at, $f16
    /* AE730 15081280 00000000 */  nop
    /* AE734 15081284 46105280 */  add.s      $f10, $f10, $f16
  .L15081288:
    /* AE738 15081288 C6520150 */  lwc1       $f18, 0x150($s2)
    /* AE73C 1508128C 27AB00C8 */  addiu      $t3, $sp, 0xC8
    /* AE740 15081290 27AC00C4 */  addiu      $t4, $sp, 0xC4
    /* AE744 15081294 46125002 */  mul.s      $f0, $f10, $f18
    /* AE748 15081298 AFAC001C */  sw         $t4, 0x1C($sp)
    /* AE74C 1508129C AFAB0018 */  sw         $t3, 0x18($sp)
    /* AE750 150812A0 AFB60014 */  sw         $s6, 0x14($sp)
    /* AE754 150812A4 AFB50010 */  sw         $s5, 0x10($sp)
    /* AE758 150812A8 8FA400E4 */  lw         $a0, 0xE4($sp)
    /* AE75C 150812AC 8FA500E8 */  lw         $a1, 0xE8($sp)
    /* AE760 150812B0 44070000 */  mfc1       $a3, $f0
    /* AE764 150812B4 0D4514B1 */  jal        func_151452C4
    /* AE768 150812B8 02603025 */   or        $a2, $s3, $zero
    /* AE76C 150812BC 14400003 */  bnez       $v0, .L150812CC
    /* AE770 150812C0 8FAD00D4 */   lw        $t5, 0xD4($sp)
    /* AE774 150812C4 1000009E */  b          .L15081540
    /* AE778 150812C8 00001025 */   or        $v0, $zero, $zero
  .L150812CC:
    /* AE77C 150812CC 2414FFFF */  addiu      $s4, $zero, -0x1
    /* AE780 150812D0 19A00063 */  blez       $t5, .L15081460
    /* AE784 150812D4 00008825 */   or        $s1, $zero, $zero
    /* AE788 150812D8 8FB000D8 */  lw         $s0, 0xD8($sp)
    /* AE78C 150812DC 27BE0084 */  addiu      $fp, $sp, 0x84
    /* AE790 150812E0 920E0000 */  lbu        $t6, 0x0($s0)
  .L150812E4:
    /* AE794 150812E4 8E59009C */  lw         $t9, 0x9C($s2)
    /* AE798 150812E8 240F0001 */  addiu      $t7, $zero, 0x1
    /* AE79C 150812EC 01CFC004 */  sllv       $t8, $t7, $t6
    /* AE7A0 150812F0 03194824 */  and        $t1, $t8, $t9
    /* AE7A4 150812F4 55200056 */  bnel       $t1, $zero, .L15081450
    /* AE7A8 150812F8 8FAB00D4 */   lw        $t3, 0xD4($sp)
    /* AE7AC 150812FC 860A0004 */  lh         $t2, 0x4($s0)
    /* AE7B0 15081300 8E4201D4 */  lw         $v0, 0x1D4($s2)
    /* AE7B4 15081304 03C02025 */  or         $a0, $fp, $zero
    /* AE7B8 15081308 448A2000 */  mtc1       $t2, $f4
    /* AE7BC 1508130C 02602825 */  or         $a1, $s3, $zero
    /* AE7C0 15081310 468021A0 */  cvt.s.w    $f6, $f4
    /* AE7C4 15081314 E7A60084 */  swc1       $f6, 0x84($sp)
    /* AE7C8 15081318 860B0006 */  lh         $t3, 0x6($s0)
    /* AE7CC 1508131C 448B4000 */  mtc1       $t3, $f8
    /* AE7D0 15081320 00000000 */  nop
    /* AE7D4 15081324 46804420 */  cvt.s.w    $f16, $f8
    /* AE7D8 15081328 E7B00088 */  swc1       $f16, 0x88($sp)
    /* AE7DC 1508132C 860C0008 */  lh         $t4, 0x8($s0)
    /* AE7E0 15081330 448C5000 */  mtc1       $t4, $f10
    /* AE7E4 15081334 00000000 */  nop
    /* AE7E8 15081338 468054A0 */  cvt.s.w    $f18, $f10
    /* AE7EC 1508133C E7B2008C */  swc1       $f18, 0x8C($sp)
    /* AE7F0 15081340 920D0000 */  lbu        $t5, 0x0($s0)
    /* AE7F4 15081344 000D7980 */  sll        $t7, $t5, 6
    /* AE7F8 15081348 0D450C4D */  jal        func_15143134
    /* AE7FC 1508134C 004F3021 */   addu      $a2, $v0, $t7
    /* AE800 15081350 960E0002 */  lhu        $t6, 0x2($s0)
    /* AE804 15081354 8FA400E4 */  lw         $a0, 0xE4($sp)
    /* AE808 15081358 8FA500E8 */  lw         $a1, 0xE8($sp)
    /* AE80C 1508135C 448E2000 */  mtc1       $t6, $f4
    /* AE810 15081360 02603025 */  or         $a2, $s3, $zero
    /* AE814 15081364 05C10005 */  bgez       $t6, .L1508137C
    /* AE818 15081368 468021A0 */   cvt.s.w   $f6, $f4
    /* AE81C 1508136C 3C014F80 */  lui        $at, (0x4F800000 >> 16)
    /* AE820 15081370 44814000 */  mtc1       $at, $f8
    /* AE824 15081374 00000000 */  nop
    /* AE828 15081378 46083180 */  add.s      $f6, $f6, $f8
  .L1508137C:
    /* AE82C 1508137C C650014C */  lwc1       $f16, 0x14C($s2)
    /* AE830 15081380 27B800C8 */  addiu      $t8, $sp, 0xC8
    /* AE834 15081384 27B900C4 */  addiu      $t9, $sp, 0xC4
    /* AE838 15081388 46103282 */  mul.s      $f10, $f6, $f16
    /* AE83C 1508138C AFB9001C */  sw         $t9, 0x1C($sp)
    /* AE840 15081390 AFB80018 */  sw         $t8, 0x18($sp)
    /* AE844 15081394 AFB60014 */  sw         $s6, 0x14($sp)
    /* AE848 15081398 AFB50010 */  sw         $s5, 0x10($sp)
    /* AE84C 1508139C 44075000 */  mfc1       $a3, $f10
    /* AE850 150813A0 0D4514B1 */  jal        func_151452C4
    /* AE854 150813A4 00000000 */   nop
    /* AE858 150813A8 50400029 */  beql       $v0, $zero, .L15081450
    /* AE85C 150813AC 8FAB00D4 */   lw        $t3, 0xD4($sp)
    /* AE860 150813B0 C6E00000 */  lwc1       $f0, 0x0($s7)
    /* AE864 150813B4 C7B200C8 */  lwc1       $f18, 0xC8($sp)
    /* AE868 150813B8 C7A400C8 */  lwc1       $f4, 0xC8($sp)
    /* AE86C 150813BC 4600A032 */  c.eq.s     $f20, $f0
    /* AE870 150813C0 00000000 */  nop
    /* AE874 150813C4 4503000A */  bc1tl      .L150813F0
    /* AE878 150813C8 E6E40000 */   swc1      $f4, 0x0($s7)
    /* AE87C 150813CC 4600903C */  c.lt.s     $f18, $f0
    /* AE880 150813D0 00000000 */  nop
    /* AE884 150813D4 4502001E */  bc1fl      .L15081450
    /* AE888 150813D8 8FAB00D4 */   lw        $t3, 0xD4($sp)
    /* AE88C 150813DC 92090001 */  lbu        $t1, 0x1($s0)
    /* AE890 150813E0 0134082A */  slt        $at, $t1, $s4
    /* AE894 150813E4 5420001A */  bnel       $at, $zero, .L15081450
    /* AE898 150813E8 8FAB00D4 */   lw        $t3, 0xD4($sp)
    /* AE89C 150813EC E6E40000 */  swc1       $f4, 0x0($s7)
  .L150813F0:
    /* AE8A0 150813F0 8EA10000 */  lw         $at, 0x0($s5)
    /* AE8A4 150813F4 27AA0078 */  addiu      $t2, $sp, 0x78
    /* AE8A8 150813F8 27AD006C */  addiu      $t5, $sp, 0x6C
    /* AE8AC 150813FC AD410000 */  sw         $at, 0x0($t2)
    /* AE8B0 15081400 8EAC0004 */  lw         $t4, 0x4($s5)
    /* AE8B4 15081404 27B800A8 */  addiu      $t8, $sp, 0xA8
    /* AE8B8 15081408 AD4C0004 */  sw         $t4, 0x4($t2)
    /* AE8BC 1508140C 8EA10008 */  lw         $at, 0x8($s5)
    /* AE8C0 15081410 AD410008 */  sw         $at, 0x8($t2)
    /* AE8C4 15081414 8EC10000 */  lw         $at, 0x0($s6)
    /* AE8C8 15081418 ADA10000 */  sw         $at, 0x0($t5)
    /* AE8CC 1508141C 8ECE0004 */  lw         $t6, 0x4($s6)
    /* AE8D0 15081420 ADAE0004 */  sw         $t6, 0x4($t5)
    /* AE8D4 15081424 8EC10008 */  lw         $at, 0x8($s6)
    /* AE8D8 15081428 ADA10008 */  sw         $at, 0x8($t5)
    /* AE8DC 1508142C 8E610000 */  lw         $at, 0x0($s3)
    /* AE8E0 15081430 AF010000 */  sw         $at, 0x0($t8)
    /* AE8E4 15081434 8E690004 */  lw         $t1, 0x4($s3)
    /* AE8E8 15081438 AF090004 */  sw         $t1, 0x4($t8)
    /* AE8EC 1508143C 8E610008 */  lw         $at, 0x8($s3)
    /* AE8F0 15081440 AF010008 */  sw         $at, 0x8($t8)
    /* AE8F4 15081444 AFB100CC */  sw         $s1, 0xCC($sp)
    /* AE8F8 15081448 92140001 */  lbu        $s4, 0x1($s0)
    /* AE8FC 1508144C 8FAB00D4 */  lw         $t3, 0xD4($sp)
  .L15081450:
    /* AE900 15081450 26310001 */  addiu      $s1, $s1, 0x1
    /* AE904 15081454 2610000A */  addiu      $s0, $s0, 0xA
    /* AE908 15081458 562BFFA2 */  bnel       $s1, $t3, .L150812E4
    /* AE90C 1508145C 920E0000 */   lbu       $t6, 0x0($s0)
  .L15081460:
    /* AE910 15081460 C6E80000 */  lwc1       $f8, 0x0($s7)
    /* AE914 15081464 C7A600C8 */  lwc1       $f6, 0xC8($sp)
    /* AE918 15081468 4608A032 */  c.eq.s     $f20, $f8
    /* AE91C 1508146C 00000000 */  nop
    /* AE920 15081470 45020004 */  bc1fl      .L15081484
    /* AE924 15081474 8FA30108 */   lw        $v1, 0x108($sp)
    /* AE928 15081478 10000031 */  b          .L15081540
    /* AE92C 1508147C 00001025 */   or        $v0, $zero, $zero
    /* AE930 15081480 8FA30108 */  lw         $v1, 0x108($sp)
  .L15081484:
    /* AE934 15081484 E6E60000 */  swc1       $f6, 0x0($s7)
    /* AE938 15081488 8FAC00FC */  lw         $t4, 0xFC($sp)
    /* AE93C 1508148C 8FAA00CC */  lw         $t2, 0xCC($sp)
    /* AE940 15081490 AD8A0000 */  sw         $t2, 0x0($t4)
    /* AE944 15081494 8FAF00D8 */  lw         $t7, 0xD8($sp)
    /* AE948 15081498 000A6880 */  sll        $t5, $t2, 2
    /* AE94C 1508149C 01AA6821 */  addu       $t5, $t5, $t2
    /* AE950 150814A0 000D6840 */  sll        $t5, $t5, 1
    /* AE954 150814A4 01ED1021 */  addu       $v0, $t7, $t5
    /* AE958 150814A8 904E0001 */  lbu        $t6, 0x1($v0)
    /* AE95C 150814AC 8FB90104 */  lw         $t9, 0x104($sp)
    /* AE960 150814B0 27AD0078 */  addiu      $t5, $sp, 0x78
    /* AE964 150814B4 AF2E0000 */  sw         $t6, 0x0($t9)
    /* AE968 150814B8 8FA90100 */  lw         $t1, 0x100($sp)
    /* AE96C 150814BC 90580000 */  lbu        $t8, 0x0($v0)
    /* AE970 150814C0 AD380000 */  sw         $t8, 0x0($t1)
    /* AE974 150814C4 844B0004 */  lh         $t3, 0x4($v0)
    /* AE978 150814C8 27A9006C */  addiu      $t1, $sp, 0x6C
    /* AE97C 150814CC A46B0000 */  sh         $t3, 0x0($v1)
    /* AE980 150814D0 844C0006 */  lh         $t4, 0x6($v0)
    /* AE984 150814D4 A46C0002 */  sh         $t4, 0x2($v1)
    /* AE988 150814D8 844A0008 */  lh         $t2, 0x8($v0)
    /* AE98C 150814DC A46A0004 */  sh         $t2, 0x4($v1)
    /* AE990 150814E0 8DA10000 */  lw         $at, 0x0($t5)
    /* AE994 150814E4 8FAF00EC */  lw         $t7, 0xEC($sp)
    /* AE998 150814E8 27AA00A8 */  addiu      $t2, $sp, 0xA8
    /* AE99C 150814EC ADE10000 */  sw         $at, 0x0($t7)
    /* AE9A0 150814F0 8DB90004 */  lw         $t9, 0x4($t5)
    /* AE9A4 150814F4 ADF90004 */  sw         $t9, 0x4($t7)
    /* AE9A8 150814F8 8DA10008 */  lw         $at, 0x8($t5)
    /* AE9AC 150814FC ADE10008 */  sw         $at, 0x8($t7)
    /* AE9B0 15081500 8D210000 */  lw         $at, 0x0($t1)
    /* AE9B4 15081504 8FB800F0 */  lw         $t8, 0xF0($sp)
    /* AE9B8 15081508 8FA200F4 */  lw         $v0, 0xF4($sp)
    /* AE9BC 1508150C AF010000 */  sw         $at, 0x0($t8)
    /* AE9C0 15081510 8D2C0004 */  lw         $t4, 0x4($t1)
    /* AE9C4 15081514 AF0C0004 */  sw         $t4, 0x4($t8)
    /* AE9C8 15081518 8D210008 */  lw         $at, 0x8($t1)
    /* AE9CC 1508151C 10400007 */  beqz       $v0, .L1508153C
    /* AE9D0 15081520 AF010008 */   sw        $at, 0x8($t8)
    /* AE9D4 15081524 8D410000 */  lw         $at, 0x0($t2)
    /* AE9D8 15081528 AC410000 */  sw         $at, 0x0($v0)
    /* AE9DC 1508152C 8D4F0004 */  lw         $t7, 0x4($t2)
    /* AE9E0 15081530 AC4F0004 */  sw         $t7, 0x4($v0)
    /* AE9E4 15081534 8D410008 */  lw         $at, 0x8($t2)
    /* AE9E8 15081538 AC410008 */  sw         $at, 0x8($v0)
  .L1508153C:
    /* AE9EC 1508153C 24020001 */  addiu      $v0, $zero, 0x1
  .L15081540:
    /* AE9F0 15081540 8FBF0054 */  lw         $ra, 0x54($sp)
    /* AE9F4 15081544 D7B40028 */  ldc1       $f20, 0x28($sp)
    /* AE9F8 15081548 8FB00030 */  lw         $s0, 0x30($sp)
    /* AE9FC 1508154C 8FB10034 */  lw         $s1, 0x34($sp)
    /* AEA00 15081550 8FB20038 */  lw         $s2, 0x38($sp)
    /* AEA04 15081554 8FB3003C */  lw         $s3, 0x3C($sp)
    /* AEA08 15081558 8FB40040 */  lw         $s4, 0x40($sp)
    /* AEA0C 1508155C 8FB50044 */  lw         $s5, 0x44($sp)
    /* AEA10 15081560 8FB60048 */  lw         $s6, 0x48($sp)
    /* AEA14 15081564 8FB7004C */  lw         $s7, 0x4C($sp)
    /* AEA18 15081568 8FBE0050 */  lw         $fp, 0x50($sp)
    /* AEA1C 1508156C 03E00008 */  jr         $ra
    /* AEA20 15081570 27BD00E0 */   addiu     $sp, $sp, 0xE0
endlabel func_1508114C

nonmatching func_15081574, 0x110

glabel func_15081574
    /* AEA24 15081574 27BDFFB0 */  addiu      $sp, $sp, -0x50
    /* AEA28 15081578 F7B60028 */  sdc1       $f22, 0x28($sp)
    /* AEA2C 1508157C F7B40020 */  sdc1       $f20, 0x20($sp)
    /* AEA30 15081580 AFB20038 */  sw         $s2, 0x38($sp)
    /* AEA34 15081584 4485A000 */  mtc1       $a1, $f20
    /* AEA38 15081588 4486B000 */  mtc1       $a2, $f22
    /* AEA3C 1508158C 00809025 */  or         $s2, $a0, $zero
    /* AEA40 15081590 AFBF004C */  sw         $ra, 0x4C($sp)
    /* AEA44 15081594 AFB60048 */  sw         $s6, 0x48($sp)
    /* AEA48 15081598 AFB50044 */  sw         $s5, 0x44($sp)
    /* AEA4C 1508159C AFB40040 */  sw         $s4, 0x40($sp)
    /* AEA50 150815A0 AFB3003C */  sw         $s3, 0x3C($sp)
    /* AEA54 150815A4 AFB10034 */  sw         $s1, 0x34($sp)
    /* AEA58 150815A8 AFB00030 */  sw         $s0, 0x30($sp)
    /* AEA5C 150815AC AFA7005C */  sw         $a3, 0x5C($sp)
    /* AEA60 150815B0 8FAE005C */  lw         $t6, 0x5C($sp)
    /* AEA64 150815B4 3C10800D */  lui        $s0, %hi(D_800CC2D0)
    /* AEA68 150815B8 3C16800A */  lui        $s6, %hi(D_8009BD30)
    /* AEA6C 150815BC ADC00000 */  sw         $zero, 0x0($t6)
    /* AEA70 150815C0 3C14800D */  lui        $s4, %hi(D_800D121C)
    /* AEA74 150815C4 2694121C */  addiu      $s4, $s4, %lo(D_800D121C)
    /* AEA78 150815C8 8FB10064 */  lw         $s1, 0x64($sp)
    /* AEA7C 150815CC 8FB30060 */  lw         $s3, 0x60($sp)
    /* AEA80 150815D0 26D6BD30 */  addiu      $s6, $s6, %lo(D_8009BD30)
    /* AEA84 150815D4 2610C2D0 */  addiu      $s0, $s0, %lo(D_800CC2D0)
    /* AEA88 150815D8 2415FFFF */  addiu      $s5, $zero, -0x1
    /* AEA8C 150815DC 8E0F0000 */  lw         $t7, 0x0($s0)
  .L150815E0:
    /* AEA90 150815E0 51E00019 */  beql       $t7, $zero, .L15081648
    /* AEA94 150815E4 2610032C */   addiu     $s0, $s0, 0x32C
    /* AEA98 150815E8 8E1801D4 */  lw         $t8, 0x1D4($s0)
    /* AEA9C 150815EC 53000016 */  beql       $t8, $zero, .L15081648
    /* AEAA0 150815F0 2610032C */   addiu     $s0, $s0, 0x32C
    /* AEAA4 150815F4 92190004 */  lbu        $t9, 0x4($s0)
    /* AEAA8 150815F8 56390013 */  bnel       $s1, $t9, .L15081648
    /* AEAAC 150815FC 2610032C */   addiu     $s0, $s0, 0x32C
    /* AEAB0 15081600 0D420423 */  jal        func_1508108C
    /* AEAB4 15081604 02002025 */   or        $a0, $s0, $zero
    /* AEAB8 15081608 1055000E */  beq        $v0, $s5, .L15081644
    /* AEABC 1508160C 02402025 */   or        $a0, $s2, $zero
    /* AEAC0 15081610 00024080 */  sll        $t0, $v0, 2
    /* AEAC4 15081614 02C84821 */  addu       $t1, $s6, $t0
    /* AEAC8 15081618 91260002 */  lbu        $a2, 0x2($t1)
    /* AEACC 1508161C 4407A000 */  mfc1       $a3, $f20
    /* AEAD0 15081620 AFB30014 */  sw         $s3, 0x14($sp)
    /* AEAD4 15081624 E7B60010 */  swc1       $f22, 0x10($sp)
    /* AEAD8 15081628 0D420348 */  jal        func_15080D20
    /* AEADC 1508162C 02002825 */   or        $a1, $s0, $zero
    /* AEAE0 15081630 50400005 */  beql       $v0, $zero, .L15081648
    /* AEAE4 15081634 2610032C */   addiu     $s0, $s0, 0x32C
    /* AEAE8 15081638 8FAA005C */  lw         $t2, 0x5C($sp)
    /* AEAEC 1508163C 10000005 */  b          .L15081654
    /* AEAF0 15081640 AD500000 */   sw        $s0, 0x0($t2)
  .L15081644:
    /* AEAF4 15081644 2610032C */  addiu      $s0, $s0, 0x32C
  .L15081648:
    /* AEAF8 15081648 5614FFE5 */  bnel       $s0, $s4, .L150815E0
    /* AEAFC 1508164C 8E0F0000 */   lw        $t7, 0x0($s0)
    /* AEB00 15081650 00001025 */  or         $v0, $zero, $zero
  .L15081654:
    /* AEB04 15081654 8FBF004C */  lw         $ra, 0x4C($sp)
    /* AEB08 15081658 D7B40020 */  ldc1       $f20, 0x20($sp)
    /* AEB0C 1508165C D7B60028 */  ldc1       $f22, 0x28($sp)
    /* AEB10 15081660 8FB00030 */  lw         $s0, 0x30($sp)
    /* AEB14 15081664 8FB10034 */  lw         $s1, 0x34($sp)
    /* AEB18 15081668 8FB20038 */  lw         $s2, 0x38($sp)
    /* AEB1C 1508166C 8FB3003C */  lw         $s3, 0x3C($sp)
    /* AEB20 15081670 8FB40040 */  lw         $s4, 0x40($sp)
    /* AEB24 15081674 8FB50044 */  lw         $s5, 0x44($sp)
    /* AEB28 15081678 8FB60048 */  lw         $s6, 0x48($sp)
    /* AEB2C 1508167C 03E00008 */  jr         $ra
    /* AEB30 15081680 27BD0050 */   addiu     $sp, $sp, 0x50
endlabel func_15081574
    /* AEB34 15081684 00000000 */  nop
    /* AEB38 15081688 00000000 */  nop
    /* AEB3C 1508168C 00000000 */  nop
