.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching func_1509DF20, 0x94

glabel func_1509DF20
    /* CB3D0 1509DF20 AFA40000 */  sw         $a0, 0x0($sp)
    /* CB3D4 1509DF24 8CAE0004 */  lw         $t6, 0x4($a1)
    /* CB3D8 1509DF28 24010001 */  addiu      $at, $zero, 0x1
    /* CB3DC 1509DF2C 3C0F800D */  lui        $t7, %hi(D_800D3840)
    /* CB3E0 1509DF30 15C1001E */  bne        $t6, $at, .L1509DFAC
    /* CB3E4 1509DF34 00000000 */   nop
    /* CB3E8 1509DF38 8DEF3840 */  lw         $t7, %lo(D_800D3840)($t7)
    /* CB3EC 1509DF3C 24010003 */  addiu      $at, $zero, 0x3
    /* CB3F0 1509DF40 15E1001A */  bne        $t7, $at, .L1509DFAC
    /* CB3F4 1509DF44 00000000 */   nop
    /* CB3F8 1509DF48 8CB8000C */  lw         $t8, 0xC($a1)
    /* CB3FC 1509DF4C 3C013780 */  lui        $at, (0x37800000 >> 16)
    /* CB400 1509DF50 44810000 */  mtc1       $at, $f0
    /* CB404 1509DF54 44982000 */  mtc1       $t8, $f4
    /* CB408 1509DF58 8CB90008 */  lw         $t9, 0x8($a1)
    /* CB40C 1509DF5C 3C01800D */  lui        $at, %hi(D_800D2FC0)
    /* CB410 1509DF60 468021A0 */  cvt.s.w    $f6, $f4
    /* CB414 1509DF64 00194080 */  sll        $t0, $t9, 2
    /* CB418 1509DF68 00280821 */  addu       $at, $at, $t0
    /* CB41C 1509DF6C 240C0001 */  addiu      $t4, $zero, 0x1
    /* CB420 1509DF70 46003202 */  mul.s      $f8, $f6, $f0
    /* CB424 1509DF74 E4282FC0 */  swc1       $f8, %lo(D_800D2FC0)($at)
    /* CB428 1509DF78 8CA9000C */  lw         $t1, 0xC($a1)
    /* CB42C 1509DF7C 8CAA0008 */  lw         $t2, 0x8($a1)
    /* CB430 1509DF80 3C01800D */  lui        $at, %hi(D_800D2FD8)
    /* CB434 1509DF84 44895000 */  mtc1       $t1, $f10
    /* CB438 1509DF88 000A5880 */  sll        $t3, $t2, 2
    /* CB43C 1509DF8C 002B0821 */  addu       $at, $at, $t3
    /* CB440 1509DF90 46805420 */  cvt.s.w    $f16, $f10
    /* CB444 1509DF94 46008482 */  mul.s      $f18, $f16, $f0
    /* CB448 1509DF98 E4322FD8 */  swc1       $f18, %lo(D_800D2FD8)($at)
    /* CB44C 1509DF9C 8CAD0008 */  lw         $t5, 0x8($a1)
    /* CB450 1509DFA0 3C01800D */  lui        $at, %hi(D_800D2FEC)
    /* CB454 1509DFA4 002D0821 */  addu       $at, $at, $t5
    /* CB458 1509DFA8 A02C2FEC */  sb         $t4, %lo(D_800D2FEC)($at)
  .L1509DFAC:
    /* CB45C 1509DFAC 03E00008 */  jr         $ra
    /* CB460 1509DFB0 00000000 */   nop
endlabel func_1509DF20

nonmatching func_1509DFB4, 0x10

glabel func_1509DFB4
    /* CB464 1509DFB4 AFA40000 */  sw         $a0, 0x0($sp)
    /* CB468 1509DFB8 AFA50004 */  sw         $a1, 0x4($sp)
    /* CB46C 1509DFBC 03E00008 */  jr         $ra
    /* CB470 1509DFC0 00000000 */   nop
endlabel func_1509DFB4

nonmatching func_1509DFC4, 0x418

glabel func_1509DFC4
    /* CB474 1509DFC4 27BDFFB8 */  addiu      $sp, $sp, -0x48
    /* CB478 1509DFC8 AFB00020 */  sw         $s0, 0x20($sp)
    /* CB47C 1509DFCC 00C08025 */  or         $s0, $a2, $zero
    /* CB480 1509DFD0 AFBF0024 */  sw         $ra, 0x24($sp)
    /* CB484 1509DFD4 AFA40048 */  sw         $a0, 0x48($sp)
    /* CB488 1509DFD8 2CA1001B */  sltiu      $at, $a1, 0x1B
    /* CB48C 1509DFDC 102000F9 */  beqz       $at, .L1509E3C4
    /* CB490 1509DFE0 00057080 */   sll       $t6, $a1, 2
    /* CB494 1509DFE4 3C01800A */  lui        $at, %hi(jtbl_8009F304)
    /* CB498 1509DFE8 002E0821 */  addu       $at, $at, $t6
    /* CB49C 1509DFEC 8C2EF304 */  lw         $t6, %lo(jtbl_8009F304)($at)
    /* CB4A0 1509DFF0 01C00008 */  jr         $t6
    /* CB4A4 1509DFF4 00000000 */   nop
  jlabel .L1509DFF8
    /* CB4A8 1509DFF8 0D460786 */  jal        func_15181E18
    /* CB4AC 1509DFFC 00002025 */   or        $a0, $zero, $zero
    /* CB4B0 1509E000 100000F1 */  b          .L1509E3C8
    /* CB4B4 1509E004 00001025 */   or        $v0, $zero, $zero
  jlabel .L1509E008
    /* CB4B8 1509E008 240400FF */  addiu      $a0, $zero, 0xFF
    /* CB4BC 1509E00C 240500FF */  addiu      $a1, $zero, 0xFF
    /* CB4C0 1509E010 240600FF */  addiu      $a2, $zero, 0xFF
    /* CB4C4 1509E014 0D410CCB */  jal        func_1504332C
    /* CB4C8 1509E018 240700FF */   addiu     $a3, $zero, 0xFF
    /* CB4CC 1509E01C 8E0F0008 */  lw         $t7, 0x8($s0)
    /* CB4D0 1509E020 2401003C */  addiu      $at, $zero, 0x3C
    /* CB4D4 1509E024 3C07800A */  lui        $a3, %hi(D_8009F300)
    /* CB4D8 1509E028 25F8003B */  addiu      $t8, $t7, 0x3B
    /* CB4DC 1509E02C 0301001A */  div        $zero, $t8, $at
    /* CB4E0 1509E030 0000C812 */  mflo       $t9
    /* CB4E4 1509E034 AFB90010 */  sw         $t9, 0x10($sp)
    /* CB4E8 1509E038 24E7F300 */  addiu      $a3, $a3, %lo(D_8009F300)
    /* CB4EC 1509E03C 24040096 */  addiu      $a0, $zero, 0x96
    /* CB4F0 1509E040 24050056 */  addiu      $a1, $zero, 0x56
    /* CB4F4 1509E044 0D410B65 */  jal        func_15042D94
    /* CB4F8 1509E048 24060001 */   addiu     $a2, $zero, 0x1
    /* CB4FC 1509E04C 3C028009 */  lui        $v0, %hi(D_8008FDBC)
    /* CB500 1509E050 2442FDBC */  addiu      $v0, $v0, %lo(D_8008FDBC)
    /* CB504 1509E054 94480000 */  lhu        $t0, 0x0($v0)
    /* CB508 1509E058 35090080 */  ori        $t1, $t0, 0x80
    /* CB50C 1509E05C 100000D9 */  b          .L1509E3C4
    /* CB510 1509E060 A4490000 */   sh        $t1, 0x0($v0)
  jlabel .L1509E064
    /* CB514 1509E064 8E0A0008 */  lw         $t2, 0x8($s0)
    /* CB518 1509E068 3C01800D */  lui        $at, %hi(D_800D2450)
    /* CB51C 1509E06C 100000D5 */  b          .L1509E3C4
    /* CB520 1509E070 AC2A2450 */   sw        $t2, %lo(D_800D2450)($at)
  jlabel .L1509E074
    /* CB524 1509E074 0D424E06 */  jal        func_15093818
    /* CB528 1509E078 8E040008 */   lw        $a0, 0x8($s0)
    /* CB52C 1509E07C 100000D2 */  b          .L1509E3C8
    /* CB530 1509E080 00001025 */   or        $v0, $zero, $zero
  jlabel .L1509E084
    /* CB534 1509E084 0D4226F0 */  jal        func_15089BC0
    /* CB538 1509E088 00000000 */   nop
    /* CB53C 1509E08C 100000CF */  b          .L1509E3CC
    /* CB540 1509E090 8FBF0024 */   lw        $ra, 0x24($sp)
  jlabel .L1509E094
    /* CB544 1509E094 0D42286F */  jal        func_1508A1BC
    /* CB548 1509E098 00000000 */   nop
    /* CB54C 1509E09C 100000CB */  b          .L1509E3CC
    /* CB550 1509E0A0 8FBF0024 */   lw        $ra, 0x24($sp)
  jlabel .L1509E0A4
    /* CB554 1509E0A4 0D4229BF */  jal        func_1508A6FC
    /* CB558 1509E0A8 00000000 */   nop
    /* CB55C 1509E0AC 100000C7 */  b          .L1509E3CC
    /* CB560 1509E0B0 8FBF0024 */   lw        $ra, 0x24($sp)
  jlabel .L1509E0B4
    /* CB564 1509E0B4 0D422FC5 */  jal        func_1508BF14
    /* CB568 1509E0B8 00000000 */   nop
    /* CB56C 1509E0BC 100000C3 */  b          .L1509E3CC
    /* CB570 1509E0C0 8FBF0024 */   lw        $ra, 0x24($sp)
  jlabel .L1509E0C4
    /* CB574 1509E0C4 0D423065 */  jal        func_1508C194
    /* CB578 1509E0C8 8E040008 */   lw        $a0, 0x8($s0)
    /* CB57C 1509E0CC 100000BF */  b          .L1509E3CC
    /* CB580 1509E0D0 8FBF0024 */   lw        $ra, 0x24($sp)
  jlabel .L1509E0D4
    /* CB584 1509E0D4 8E040008 */  lw         $a0, 0x8($s0)
    /* CB588 1509E0D8 8E05000C */  lw         $a1, 0xC($s0)
    /* CB58C 1509E0DC 8E060010 */  lw         $a2, 0x10($s0)
    /* CB590 1509E0E0 8E070014 */  lw         $a3, 0x14($s0)
    /* CB594 1509E0E4 AFA00014 */  sw         $zero, 0x14($sp)
    /* CB598 1509E0E8 0D4232B6 */  jal        func_1508CAD8
    /* CB59C 1509E0EC AFA00010 */   sw        $zero, 0x10($sp)
    /* CB5A0 1509E0F0 100000B6 */  b          .L1509E3CC
    /* CB5A4 1509E0F4 8FBF0024 */   lw        $ra, 0x24($sp)
  jlabel .L1509E0F8
    /* CB5A8 1509E0F8 0D423687 */  jal        func_1508DA1C
    /* CB5AC 1509E0FC 00000000 */   nop
    /* CB5B0 1509E100 100000B2 */  b          .L1509E3CC
    /* CB5B4 1509E104 8FBF0024 */   lw        $ra, 0x24($sp)
  jlabel .L1509E108
    /* CB5B8 1509E108 0D423709 */  jal        func_1508DC24
    /* CB5BC 1509E10C 00000000 */   nop
    /* CB5C0 1509E110 100000AE */  b          .L1509E3CC
    /* CB5C4 1509E114 8FBF0024 */   lw        $ra, 0x24($sp)
  jlabel .L1509E118
    /* CB5C8 1509E118 8E040008 */  lw         $a0, 0x8($s0)
    /* CB5CC 1509E11C 0D4236BB */  jal        func_1508DAEC
    /* CB5D0 1509E120 8E05000C */   lw        $a1, 0xC($s0)
    /* CB5D4 1509E124 100000A9 */  b          .L1509E3CC
    /* CB5D8 1509E128 8FBF0024 */   lw        $ra, 0x24($sp)
  jlabel .L1509E12C
    /* CB5DC 1509E12C 0D422E6F */  jal        func_1508B9BC
    /* CB5E0 1509E130 00000000 */   nop
    /* CB5E4 1509E134 100000A5 */  b          .L1509E3CC
    /* CB5E8 1509E138 8FBF0024 */   lw        $ra, 0x24($sp)
  jlabel .L1509E13C
    /* CB5EC 1509E13C 0D423614 */  jal        func_1508D850
    /* CB5F0 1509E140 8E040008 */   lw        $a0, 0x8($s0)
    /* CB5F4 1509E144 100000A1 */  b          .L1509E3CC
    /* CB5F8 1509E148 8FBF0024 */   lw        $ra, 0x24($sp)
  jlabel .L1509E14C
    /* CB5FC 1509E14C 8E040008 */  lw         $a0, 0x8($s0)
    /* CB600 1509E150 0D423A27 */  jal        func_1508E89C
    /* CB604 1509E154 8E05000C */   lw        $a1, 0xC($s0)
    /* CB608 1509E158 1000009C */  b          .L1509E3CC
    /* CB60C 1509E15C 8FBF0024 */   lw        $ra, 0x24($sp)
  jlabel .L1509E160
    /* CB610 1509E160 0D421B52 */  jal        func_15086D48
    /* CB614 1509E164 8E040008 */   lw        $a0, 0x8($s0)
    /* CB618 1509E168 240100FF */  addiu      $at, $zero, 0xFF
    /* CB61C 1509E16C 10410095 */  beq        $v0, $at, .L1509E3C4
    /* CB620 1509E170 00402025 */   or        $a0, $v0, $zero
    /* CB624 1509E174 27A50040 */  addiu      $a1, $sp, 0x40
    /* CB628 1509E178 27A6003C */  addiu      $a2, $sp, 0x3C
    /* CB62C 1509E17C 0D421B2F */  jal        func_15086CBC
    /* CB630 1509E180 27A70038 */   addiu     $a3, $sp, 0x38
    /* CB634 1509E184 8E0B000C */  lw         $t3, 0xC($s0)
    /* CB638 1509E188 C7AC0040 */  lwc1       $f12, 0x40($sp)
    /* CB63C 1509E18C C7AE003C */  lwc1       $f14, 0x3C($sp)
    /* CB640 1509E190 448B2000 */  mtc1       $t3, $f4
    /* CB644 1509E194 8FA60038 */  lw         $a2, 0x38($sp)
    /* CB648 1509E198 46802120 */  cvt.s.w    $f4, $f4
    /* CB64C 1509E19C 44072000 */  mfc1       $a3, $f4
    /* CB650 1509E1A0 0D422C83 */  jal        func_1508B20C
    /* CB654 1509E1A4 00000000 */   nop
    /* CB658 1509E1A8 10000087 */  b          .L1509E3C8
    /* CB65C 1509E1AC 00001025 */   or        $v0, $zero, $zero
  jlabel .L1509E1B0
    /* CB660 1509E1B0 8E040008 */  lw         $a0, 0x8($s0)
    /* CB664 1509E1B4 8E05000C */  lw         $a1, 0xC($s0)
    /* CB668 1509E1B8 0D421C34 */  jal        func_150870D0
    /* CB66C 1509E1BC 8E060010 */   lw        $a2, 0x10($s0)
    /* CB670 1509E1C0 10000081 */  b          .L1509E3C8
    /* CB674 1509E1C4 00001025 */   or        $v0, $zero, $zero
  jlabel .L1509E1C8
    /* CB678 1509E1C8 3C063DCC */  lui        $a2, (0x3DCCCCCD >> 16)
    /* CB67C 1509E1CC 34C6CCCD */  ori        $a2, $a2, (0x3DCCCCCD & 0xFFFF)
    /* CB680 1509E1D0 8E040008 */  lw         $a0, 0x8($s0)
    /* CB684 1509E1D4 0D421CD4 */  jal        func_15087350
    /* CB688 1509E1D8 8E05000C */   lw        $a1, 0xC($s0)
    /* CB68C 1509E1DC 1000007A */  b          .L1509E3C8
    /* CB690 1509E1E0 00001025 */   or        $v0, $zero, $zero
  jlabel .L1509E1E4
    /* CB694 1509E1E4 8E040008 */  lw         $a0, 0x8($s0)
    /* CB698 1509E1E8 0D421F73 */  jal        func_15087DCC
    /* CB69C 1509E1EC 8E05000C */   lw        $a1, 0xC($s0)
    /* CB6A0 1509E1F0 10000075 */  b          .L1509E3C8
    /* CB6A4 1509E1F4 00001025 */   or        $v0, $zero, $zero
  jlabel .L1509E1F8
    /* CB6A8 1509E1F8 8E040008 */  lw         $a0, 0x8($s0)
    /* CB6AC 1509E1FC 0D421FFB */  jal        func_15087FEC
    /* CB6B0 1509E200 8E05000C */   lw        $a1, 0xC($s0)
    /* CB6B4 1509E204 10000070 */  b          .L1509E3C8
    /* CB6B8 1509E208 00001025 */   or        $v0, $zero, $zero
  jlabel .L1509E20C
    /* CB6BC 1509E20C 8E040008 */  lw         $a0, 0x8($s0)
    /* CB6C0 1509E210 0D421FF1 */  jal        func_15087FC4
    /* CB6C4 1509E214 8E05000C */   lw        $a1, 0xC($s0)
    /* CB6C8 1509E218 1000006B */  b          .L1509E3C8
    /* CB6CC 1509E21C 00001025 */   or        $v0, $zero, $zero
  jlabel .L1509E220
    /* CB6D0 1509E220 8E040008 */  lw         $a0, 0x8($s0)
    /* CB6D4 1509E224 0D42203E */  jal        func_150880F8
    /* CB6D8 1509E228 8E05000C */   lw        $a1, 0xC($s0)
    /* CB6DC 1509E22C 10000067 */  b          .L1509E3CC
    /* CB6E0 1509E230 8FBF0024 */   lw        $ra, 0x24($sp)
  jlabel .L1509E234
    /* CB6E4 1509E234 0D422C75 */  jal        func_1508B1D4
    /* CB6E8 1509E238 8E040008 */   lw        $a0, 0x8($s0)
    /* CB6EC 1509E23C 10000062 */  b          .L1509E3C8
    /* CB6F0 1509E240 00001025 */   or        $v0, $zero, $zero
  jlabel .L1509E244
    /* CB6F4 1509E244 3C013780 */  lui        $at, (0x37800000 >> 16)
    /* CB6F8 1509E248 44810000 */  mtc1       $at, $f0
    /* CB6FC 1509E24C 00000000 */  nop
    /* CB700 1509E250 8E0E000C */  lw         $t6, 0xC($s0)
    /* CB704 1509E254 8E180010 */  lw         $t8, 0x10($s0)
    /* CB708 1509E258 8E190014 */  lw         $t9, 0x14($s0)
    /* CB70C 1509E25C 448E3000 */  mtc1       $t6, $f6
    /* CB710 1509E260 44988000 */  mtc1       $t8, $f16
    /* CB714 1509E264 3C03800E */  lui        $v1, %hi(D_800DBFF0)
    /* CB718 1509E268 46803220 */  cvt.s.w    $f8, $f6
    /* CB71C 1509E26C 44993000 */  mtc1       $t9, $f6
    /* CB720 1509E270 8C63BFF0 */  lw         $v1, %lo(D_800DBFF0)($v1)
    /* CB724 1509E274 8E020008 */  lw         $v0, 0x8($s0)
    /* CB728 1509E278 3C0D800D */  lui        $t5, %hi(D_800D2FD8)
    /* CB72C 1509E27C 468084A0 */  cvt.s.w    $f18, $f16
    /* CB730 1509E280 46004282 */  mul.s      $f10, $f8, $f0
    /* CB734 1509E284 3C0F800D */  lui        $t7, %hi(D_800D2FC0)
    /* CB738 1509E288 00026080 */  sll        $t4, $v0, 2
    /* CB73C 1509E28C 25EF2FC0 */  addiu      $t7, $t7, %lo(D_800D2FC0)
    /* CB740 1509E290 25AD2FD8 */  addiu      $t5, $t5, %lo(D_800D2FD8)
    /* CB744 1509E294 46009102 */  mul.s      $f4, $f18, $f0
    /* CB748 1509E298 018D2021 */  addu       $a0, $t4, $t5
    /* CB74C 1509E29C 44055000 */  mfc1       $a1, $f10
    /* CB750 1509E2A0 018F3021 */  addu       $a2, $t4, $t7
    /* CB754 1509E2A4 01801025 */  or         $v0, $t4, $zero
    /* CB758 1509E2A8 46803220 */  cvt.s.w    $f8, $f6
    /* CB75C 1509E2AC 44072000 */  mfc1       $a3, $f4
    /* CB760 1509E2B0 46004282 */  mul.s      $f10, $f8, $f0
    /* CB764 1509E2B4 E7AA0010 */  swc1       $f10, 0x10($sp)
    /* CB768 1509E2B8 C47007B4 */  lwc1       $f16, 0x7B4($v1)
    /* CB76C 1509E2BC 0D41256C */  jal        func_150495B0
    /* CB770 1509E2C0 E7B00014 */   swc1      $f16, 0x14($sp)
    /* CB774 1509E2C4 8E080008 */  lw         $t0, 0x8($s0)
    /* CB778 1509E2C8 3C01800D */  lui        $at, %hi(D_800D2FD8)
    /* CB77C 1509E2CC 00084880 */  sll        $t1, $t0, 2
    /* CB780 1509E2D0 00290821 */  addu       $at, $at, $t1
    /* CB784 1509E2D4 C4322FD8 */  lwc1       $f18, %lo(D_800D2FD8)($at)
    /* CB788 1509E2D8 3C014780 */  lui        $at, (0x47800000 >> 16)
    /* CB78C 1509E2DC 44812000 */  mtc1       $at, $f4
    /* CB790 1509E2E0 00000000 */  nop
    /* CB794 1509E2E4 46049182 */  mul.s      $f6, $f18, $f4
    /* CB798 1509E2E8 4600320D */  trunc.w.s  $f8, $f6
    /* CB79C 1509E2EC 44024000 */  mfc1       $v0, $f8
    /* CB7A0 1509E2F0 10000036 */  b          .L1509E3CC
    /* CB7A4 1509E2F4 8FBF0024 */   lw        $ra, 0x24($sp)
  jlabel .L1509E2F8
    /* CB7A8 1509E2F8 3C013780 */  lui        $at, (0x37800000 >> 16)
    /* CB7AC 1509E2FC 44810000 */  mtc1       $at, $f0
    /* CB7B0 1509E300 00000000 */  nop
    /* CB7B4 1509E304 8E0D000C */  lw         $t5, 0xC($s0)
    /* CB7B8 1509E308 8E0F0010 */  lw         $t7, 0x10($s0)
    /* CB7BC 1509E30C 8E180014 */  lw         $t8, 0x14($s0)
    /* CB7C0 1509E310 448D5000 */  mtc1       $t5, $f10
    /* CB7C4 1509E314 448F2000 */  mtc1       $t7, $f4
    /* CB7C8 1509E318 3C03800E */  lui        $v1, %hi(D_800DBFF0)
    /* CB7CC 1509E31C 46805420 */  cvt.s.w    $f16, $f10
    /* CB7D0 1509E320 44985000 */  mtc1       $t8, $f10
    /* CB7D4 1509E324 8C63BFF0 */  lw         $v1, %lo(D_800DBFF0)($v1)
    /* CB7D8 1509E328 8E020008 */  lw         $v0, 0x8($s0)
    /* CB7DC 1509E32C 3C0C800D */  lui        $t4, %hi(D_800D2FD8)
    /* CB7E0 1509E330 468021A0 */  cvt.s.w    $f6, $f4
    /* CB7E4 1509E334 46008482 */  mul.s      $f18, $f16, $f0
    /* CB7E8 1509E338 3C0E800D */  lui        $t6, %hi(D_800D2FC0)
    /* CB7EC 1509E33C 00025880 */  sll        $t3, $v0, 2
    /* CB7F0 1509E340 25CE2FC0 */  addiu      $t6, $t6, %lo(D_800D2FC0)
    /* CB7F4 1509E344 258C2FD8 */  addiu      $t4, $t4, %lo(D_800D2FD8)
    /* CB7F8 1509E348 46003202 */  mul.s      $f8, $f6, $f0
    /* CB7FC 1509E34C 016C2021 */  addu       $a0, $t3, $t4
    /* CB800 1509E350 44059000 */  mfc1       $a1, $f18
    /* CB804 1509E354 016E3021 */  addu       $a2, $t3, $t6
    /* CB808 1509E358 01601025 */  or         $v0, $t3, $zero
    /* CB80C 1509E35C 46805420 */  cvt.s.w    $f16, $f10
    /* CB810 1509E360 44074000 */  mfc1       $a3, $f8
    /* CB814 1509E364 46008482 */  mul.s      $f18, $f16, $f0
    /* CB818 1509E368 E7B20010 */  swc1       $f18, 0x10($sp)
    /* CB81C 1509E36C C46407B4 */  lwc1       $f4, 0x7B4($v1)
    /* CB820 1509E370 0D4125A2 */  jal        func_15049688
    /* CB824 1509E374 E7A40014 */   swc1      $f4, 0x14($sp)
    /* CB828 1509E378 8E190008 */  lw         $t9, 0x8($s0)
    /* CB82C 1509E37C 3C01800D */  lui        $at, %hi(D_800D2FD8)
    /* CB830 1509E380 00194080 */  sll        $t0, $t9, 2
    /* CB834 1509E384 00280821 */  addu       $at, $at, $t0
    /* CB838 1509E388 C4262FD8 */  lwc1       $f6, %lo(D_800D2FD8)($at)
    /* CB83C 1509E38C 3C014780 */  lui        $at, (0x47800000 >> 16)
    /* CB840 1509E390 44814000 */  mtc1       $at, $f8
    /* CB844 1509E394 00000000 */  nop
    /* CB848 1509E398 46083282 */  mul.s      $f10, $f6, $f8
    /* CB84C 1509E39C 4600540D */  trunc.w.s  $f16, $f10
    /* CB850 1509E3A0 44028000 */  mfc1       $v0, $f16
    /* CB854 1509E3A4 10000009 */  b          .L1509E3CC
    /* CB858 1509E3A8 8FBF0024 */   lw        $ra, 0x24($sp)
  jlabel .L1509E3AC
    /* CB85C 1509E3AC 0D420FA4 */  jal        func_15083E90
    /* CB860 1509E3B0 9204000B */   lbu       $a0, 0xB($s0)
    /* CB864 1509E3B4 10400003 */  beqz       $v0, .L1509E3C4
    /* CB868 1509E3B8 00402025 */   or        $a0, $v0, $zero
    /* CB86C 1509E3BC 0D4183CA */  jal        func_15060F28
    /* CB870 1509E3C0 00002825 */   or        $a1, $zero, $zero
  .L1509E3C4:
    /* CB874 1509E3C4 00001025 */  or         $v0, $zero, $zero
  .L1509E3C8:
    /* CB878 1509E3C8 8FBF0024 */  lw         $ra, 0x24($sp)
  .L1509E3CC:
    /* CB87C 1509E3CC 8FB00020 */  lw         $s0, 0x20($sp)
    /* CB880 1509E3D0 27BD0048 */  addiu      $sp, $sp, 0x48
    /* CB884 1509E3D4 03E00008 */  jr         $ra
    /* CB888 1509E3D8 00000000 */   nop
endlabel func_1509DFC4

nonmatching func_1509E3DC, 0x25C

glabel func_1509E3DC
    /* CB88C 1509E3DC 27BDFFE8 */  addiu      $sp, $sp, -0x18
    /* CB890 1509E3E0 AFBF0014 */  sw         $ra, 0x14($sp)
    /* CB894 1509E3E4 AFA40018 */  sw         $a0, 0x18($sp)
    /* CB898 1509E3E8 2CA10016 */  sltiu      $at, $a1, 0x16
    /* CB89C 1509E3EC 1020008D */  beqz       $at, .L1509E624
    /* CB8A0 1509E3F0 00057080 */   sll       $t6, $a1, 2
    /* CB8A4 1509E3F4 3C01800A */  lui        $at, %hi(jtbl_8009F370)
    /* CB8A8 1509E3F8 002E0821 */  addu       $at, $at, $t6
    /* CB8AC 1509E3FC 8C2EF370 */  lw         $t6, %lo(jtbl_8009F370)($at)
    /* CB8B0 1509E400 01C00008 */  jr         $t6
    /* CB8B4 1509E404 00000000 */   nop
  jlabel .L1509E408
    /* CB8B8 1509E408 8CC40008 */  lw         $a0, 0x8($a2)
    /* CB8BC 1509E40C 0D433C10 */  jal        func_150CF040
    /* CB8C0 1509E410 8CC5000C */   lw        $a1, 0xC($a2)
    /* CB8C4 1509E414 4600010D */  trunc.w.s  $f4, $f0
    /* CB8C8 1509E418 44022000 */  mfc1       $v0, $f4
    /* CB8CC 1509E41C 10000083 */  b          .L1509E62C
    /* CB8D0 1509E420 8FBF0014 */   lw        $ra, 0x14($sp)
  jlabel .L1509E424
    /* CB8D4 1509E424 8CD80008 */  lw         $t8, 0x8($a2)
    /* CB8D8 1509E428 8CD90010 */  lw         $t9, 0x10($a2)
    /* CB8DC 1509E42C 8CC8000C */  lw         $t0, 0xC($a2)
    /* CB8E0 1509E430 8CC90014 */  lw         $t1, 0x14($a2)
    /* CB8E4 1509E434 03191823 */  subu       $v1, $t8, $t9
    /* CB8E8 1509E438 00630019 */  multu      $v1, $v1
    /* CB8EC 1509E43C 01092023 */  subu       $a0, $t0, $t1
    /* CB8F0 1509E440 00005012 */  mflo       $t2
    /* CB8F4 1509E444 00000000 */  nop
    /* CB8F8 1509E448 00000000 */  nop
    /* CB8FC 1509E44C 00840019 */  multu      $a0, $a0
    /* CB900 1509E450 00005812 */  mflo       $t3
    /* CB904 1509E454 014B6021 */  addu       $t4, $t2, $t3
    /* CB908 1509E458 448C3000 */  mtc1       $t4, $f6
    /* CB90C 1509E45C 00000000 */  nop
    /* CB910 1509E460 46803020 */  cvt.s.w    $f0, $f6
    /* CB914 1509E464 46000004 */  sqrt.s     $f0, $f0
    /* CB918 1509E468 4600020D */  trunc.w.s  $f8, $f0
    /* CB91C 1509E46C 44024000 */  mfc1       $v0, $f8
    /* CB920 1509E470 1000006E */  b          .L1509E62C
    /* CB924 1509E474 8FBF0014 */   lw        $ra, 0x14($sp)
  jlabel .L1509E478
    /* CB928 1509E478 0D4232A2 */  jal        func_1508CA88
    /* CB92C 1509E47C 00000000 */   nop
    /* CB930 1509E480 1000006A */  b          .L1509E62C
    /* CB934 1509E484 8FBF0014 */   lw        $ra, 0x14($sp)
  jlabel .L1509E488
    /* CB938 1509E488 0D423273 */  jal        func_1508C9CC
    /* CB93C 1509E48C 00000000 */   nop
    /* CB940 1509E490 10000066 */  b          .L1509E62C
    /* CB944 1509E494 8FBF0014 */   lw        $ra, 0x14($sp)
  jlabel .L1509E498
    /* CB948 1509E498 8CC40008 */  lw         $a0, 0x8($a2)
    /* CB94C 1509E49C 0D42316E */  jal        func_1508C5B8
    /* CB950 1509E4A0 8CC5000C */   lw        $a1, 0xC($a2)
    /* CB954 1509E4A4 10000061 */  b          .L1509E62C
    /* CB958 1509E4A8 8FBF0014 */   lw        $ra, 0x14($sp)
  jlabel .L1509E4AC
    /* CB95C 1509E4AC 3C02800E */  lui        $v0, %hi(D_800E0BD0)
    /* CB960 1509E4B0 1000005D */  b          .L1509E628
    /* CB964 1509E4B4 80420BD0 */   lb        $v0, %lo(D_800E0BD0)($v0)
  jlabel .L1509E4B8
    /* CB968 1509E4B8 0D4227E7 */  jal        func_15089F9C
    /* CB96C 1509E4BC 8CC40008 */   lw        $a0, 0x8($a2)
    /* CB970 1509E4C0 1000005A */  b          .L1509E62C
    /* CB974 1509E4C4 8FBF0014 */   lw        $ra, 0x14($sp)
  jlabel .L1509E4C8
    /* CB978 1509E4C8 0D4239B4 */  jal        func_1508E6D0
    /* CB97C 1509E4CC 8CC40008 */   lw        $a0, 0x8($a2)
    /* CB980 1509E4D0 10000056 */  b          .L1509E62C
    /* CB984 1509E4D4 8FBF0014 */   lw        $ra, 0x14($sp)
  jlabel .L1509E4D8
    /* CB988 1509E4D8 10000053 */  b          .L1509E628
    /* CB98C 1509E4DC 00001025 */   or        $v0, $zero, $zero
  jlabel .L1509E4E0
    /* CB990 1509E4E0 0D422073 */  jal        func_150881CC
    /* CB994 1509E4E4 8CC40008 */   lw        $a0, 0x8($a2)
    /* CB998 1509E4E8 10000050 */  b          .L1509E62C
    /* CB99C 1509E4EC 8FBF0014 */   lw        $ra, 0x14($sp)
  jlabel .L1509E4F0
    /* CB9A0 1509E4F0 0D422086 */  jal        func_15088218
    /* CB9A4 1509E4F4 8CC40008 */   lw        $a0, 0x8($a2)
    /* CB9A8 1509E4F8 1000004C */  b          .L1509E62C
    /* CB9AC 1509E4FC 8FBF0014 */   lw        $ra, 0x14($sp)
  jlabel .L1509E500
    /* CB9B0 1509E500 0D42209C */  jal        func_15088270
    /* CB9B4 1509E504 8CC40008 */   lw        $a0, 0x8($a2)
    /* CB9B8 1509E508 10000048 */  b          .L1509E62C
    /* CB9BC 1509E50C 8FBF0014 */   lw        $ra, 0x14($sp)
  jlabel .L1509E510
    /* CB9C0 1509E510 0D4220AC */  jal        func_150882B0
    /* CB9C4 1509E514 8CC40008 */   lw        $a0, 0x8($a2)
    /* CB9C8 1509E518 10000044 */  b          .L1509E62C
    /* CB9CC 1509E51C 8FBF0014 */   lw        $ra, 0x14($sp)
  jlabel .L1509E520
    /* CB9D0 1509E520 8CC40008 */  lw         $a0, 0x8($a2)
    /* CB9D4 1509E524 0D4220B9 */  jal        func_150882E4
    /* CB9D8 1509E528 8CC5000C */   lw        $a1, 0xC($a2)
    /* CB9DC 1509E52C 1000003F */  b          .L1509E62C
    /* CB9E0 1509E530 8FBF0014 */   lw        $ra, 0x14($sp)
  jlabel .L1509E534
    /* CB9E4 1509E534 0D4221FE */  jal        func_150887F8
    /* CB9E8 1509E538 00000000 */   nop
    /* CB9EC 1509E53C 1000003B */  b          .L1509E62C
    /* CB9F0 1509E540 8FBF0014 */   lw        $ra, 0x14($sp)
  jlabel .L1509E544
    /* CB9F4 1509E544 3C028009 */  lui        $v0, %hi(D_8008FDBC)
    /* CB9F8 1509E548 9442FDBC */  lhu        $v0, %lo(D_8008FDBC)($v0)
    /* CB9FC 1509E54C 304E0040 */  andi       $t6, $v0, 0x40
    /* CBA00 1509E550 10000035 */  b          .L1509E628
    /* CBA04 1509E554 01C01025 */   or        $v0, $t6, $zero
  jlabel .L1509E558
    /* CBA08 1509E558 8CCF0008 */  lw         $t7, 0x8($a2)
    /* CBA0C 1509E55C 3C02800E */  lui        $v0, %hi(D_800E0BE0)
    /* CBA10 1509E560 004F1021 */  addu       $v0, $v0, $t7
    /* CBA14 1509E564 10000030 */  b          .L1509E628
    /* CBA18 1509E568 80420BE0 */   lb        $v0, %lo(D_800E0BE0)($v0)
  jlabel .L1509E56C
    /* CBA1C 1509E56C 0D422C65 */  jal        func_1508B194
    /* CBA20 1509E570 8CC40008 */   lw        $a0, 0x8($a2)
    /* CBA24 1509E574 1000002D */  b          .L1509E62C
    /* CBA28 1509E578 8FBF0014 */   lw        $ra, 0x14($sp)
  jlabel .L1509E57C
    /* CBA2C 1509E57C 8CD80008 */  lw         $t8, 0x8($a2)
    /* CBA30 1509E580 3C01800D */  lui        $at, %hi(D_800D2FD8)
    /* CBA34 1509E584 0018C880 */  sll        $t9, $t8, 2
    /* CBA38 1509E588 00390821 */  addu       $at, $at, $t9
    /* CBA3C 1509E58C C42A2FD8 */  lwc1       $f10, %lo(D_800D2FD8)($at)
    /* CBA40 1509E590 3C014780 */  lui        $at, (0x47800000 >> 16)
    /* CBA44 1509E594 44818000 */  mtc1       $at, $f16
    /* CBA48 1509E598 00000000 */  nop
    /* CBA4C 1509E59C 46105482 */  mul.s      $f18, $f10, $f16
    /* CBA50 1509E5A0 4600910D */  trunc.w.s  $f4, $f18
    /* CBA54 1509E5A4 44022000 */  mfc1       $v0, $f4
    /* CBA58 1509E5A8 10000020 */  b          .L1509E62C
    /* CBA5C 1509E5AC 8FBF0014 */   lw        $ra, 0x14($sp)
  jlabel .L1509E5B0
    /* CBA60 1509E5B0 0D420FA4 */  jal        func_15083E90
    /* CBA64 1509E5B4 90C4000B */   lbu       $a0, 0xB($a2)
    /* CBA68 1509E5B8 1040000B */  beqz       $v0, .L1509E5E8
    /* CBA6C 1509E5BC 00000000 */   nop
    /* CBA70 1509E5C0 C4460014 */  lwc1       $f6, 0x14($v0)
    /* CBA74 1509E5C4 C44A001C */  lwc1       $f10, 0x1C($v0)
    /* CBA78 1509E5C8 4600320D */  trunc.w.s  $f8, $f6
    /* CBA7C 1509E5CC 4600540D */  trunc.w.s  $f16, $f10
    /* CBA80 1509E5D0 44034000 */  mfc1       $v1, $f8
    /* CBA84 1509E5D4 44048000 */  mfc1       $a0, $f16
    /* CBA88 1509E5D8 00035C00 */  sll        $t3, $v1, 16
    /* CBA8C 1509E5DC 308CFFFF */  andi       $t4, $a0, 0xFFFF
    /* CBA90 1509E5E0 10000011 */  b          .L1509E628
    /* CBA94 1509E5E4 016C1025 */   or        $v0, $t3, $t4
  .L1509E5E8:
    /* CBA98 1509E5E8 1000000F */  b          .L1509E628
    /* CBA9C 1509E5EC 00001025 */   or        $v0, $zero, $zero
  jlabel .L1509E5F0
    /* CBAA0 1509E5F0 0D420FA4 */  jal        func_15083E90
    /* CBAA4 1509E5F4 90C4000B */   lbu       $a0, 0xB($a2)
    /* CBAA8 1509E5F8 10400008 */  beqz       $v0, .L1509E61C
    /* CBAAC 1509E5FC 00000000 */   nop
    /* CBAB0 1509E600 C4520018 */  lwc1       $f18, 0x18($v0)
    /* CBAB4 1509E604 4600910D */  trunc.w.s  $f4, $f18
    /* CBAB8 1509E608 44022000 */  mfc1       $v0, $f4
    /* CBABC 1509E60C 00000000 */  nop
    /* CBAC0 1509E610 00027400 */  sll        $t6, $v0, 16
    /* CBAC4 1509E614 10000004 */  b          .L1509E628
    /* CBAC8 1509E618 000E1403 */   sra       $v0, $t6, 16
  .L1509E61C:
    /* CBACC 1509E61C 10000002 */  b          .L1509E628
    /* CBAD0 1509E620 00001025 */   or        $v0, $zero, $zero
  .L1509E624:
    /* CBAD4 1509E624 00001025 */  or         $v0, $zero, $zero
  .L1509E628:
    /* CBAD8 1509E628 8FBF0014 */  lw         $ra, 0x14($sp)
  .L1509E62C:
    /* CBADC 1509E62C 27BD0018 */  addiu      $sp, $sp, 0x18
    /* CBAE0 1509E630 03E00008 */  jr         $ra
    /* CBAE4 1509E634 00000000 */   nop
endlabel func_1509E3DC
    /* CBAE8 1509E638 00000000 */  nop
    /* CBAEC 1509E63C 00000000 */  nop
