.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching func_150B53D0, 0xD8

glabel func_150B53D0
    /* E2880 150B53D0 27BDFFB0 */  addiu      $sp, $sp, -0x50
    /* E2884 150B53D4 AFA50054 */  sw         $a1, 0x54($sp)
    /* E2888 150B53D8 00057400 */  sll        $t6, $a1, 16
    /* E288C 150B53DC 000E2C03 */  sra        $a1, $t6, 16
    /* E2890 150B53E0 AFBF002C */  sw         $ra, 0x2C($sp)
    /* E2894 150B53E4 AFA60058 */  sw         $a2, 0x58($sp)
    /* E2898 150B53E8 AFA7005C */  sw         $a3, 0x5C($sp)
    /* E289C 150B53EC 14800003 */  bnez       $a0, .L150B53FC
    /* E28A0 150B53F0 2402FFFF */   addiu     $v0, $zero, -0x1
    /* E28A4 150B53F4 10000028 */  b          .L150B5498
    /* E28A8 150B53F8 00001025 */   or        $v0, $zero, $zero
  .L150B53FC:
    /* E28AC 150B53FC 44800000 */  mtc1       $zero, $f0
    /* E28B0 150B5400 AFA4003C */  sw         $a0, 0x3C($sp)
    /* E28B4 150B5404 9098003B */  lbu        $t8, 0x3B($a0)
    /* E28B8 150B5408 E7A00044 */  swc1       $f0, 0x44($sp)
    /* E28BC 150B540C E7A00048 */  swc1       $f0, 0x48($sp)
    /* E28C0 150B5410 14A20003 */  bne        $a1, $v0, .L150B5420
    /* E28C4 150B5414 A3B80040 */   sb        $t8, 0x40($sp)
    /* E28C8 150B5418 10000002 */  b          .L150B5424
    /* E28CC 150B541C 2403012C */   addiu     $v1, $zero, 0x12C
  .L150B5420:
    /* E28D0 150B5420 00A01825 */  or         $v1, $a1, $zero
  .L150B5424:
    /* E28D4 150B5424 14A20003 */  bne        $a1, $v0, .L150B5434
    /* E28D8 150B5428 00032400 */   sll       $a0, $v1, 16
    /* E28DC 150B542C 10000002 */  b          .L150B5438
    /* E28E0 150B5430 00001025 */   or        $v0, $zero, $zero
  .L150B5434:
    /* E28E4 150B5434 24020001 */  addiu      $v0, $zero, 0x1
  .L150B5438:
    /* E28E8 150B5438 93AA005B */  lbu        $t2, 0x5B($sp)
    /* E28EC 150B543C 8FAB005C */  lw         $t3, 0x5C($sp)
    /* E28F0 150B5440 0004CC03 */  sra        $t9, $a0, 16
    /* E28F4 150B5444 24080023 */  addiu      $t0, $zero, 0x23
    /* E28F8 150B5448 24090010 */  addiu      $t1, $zero, 0x10
    /* E28FC 150B544C AFA90018 */  sw         $t1, 0x18($sp)
    /* E2900 150B5450 AFA80014 */  sw         $t0, 0x14($sp)
    /* E2904 150B5454 03202025 */  or         $a0, $t9, $zero
    /* E2908 150B5458 2405FFFF */  addiu      $a1, $zero, -0x1
    /* E290C 150B545C 24060024 */  addiu      $a2, $zero, 0x24
    /* E2910 150B5460 2407FFFF */  addiu      $a3, $zero, -0x1
    /* E2914 150B5464 AFA20010 */  sw         $v0, 0x10($sp)
    /* E2918 150B5468 AFAA001C */  sw         $t2, 0x1C($sp)
    /* E291C 150B546C 0D45244C */  jal        func_15149130
    /* E2920 150B5470 AFAB0020 */   sw        $t3, 0x20($sp)
    /* E2924 150B5474 10400007 */  beqz       $v0, .L150B5494
    /* E2928 150B5478 AFA2004C */   sw        $v0, 0x4C($sp)
    /* E292C 150B547C 24440028 */  addiu      $a0, $v0, 0x28
    /* E2930 150B5480 27A5003C */  addiu      $a1, $sp, 0x3C
    /* E2934 150B5484 0C008BB0 */  jal        memcpy
    /* E2938 150B5488 24060010 */   addiu     $a2, $zero, 0x10
    /* E293C 150B548C 0D474AAC */  jal        func_151D2AB0
    /* E2940 150B5490 24040006 */   addiu     $a0, $zero, 0x6
  .L150B5494:
    /* E2944 150B5494 8FA2004C */  lw         $v0, 0x4C($sp)
  .L150B5498:
    /* E2948 150B5498 8FBF002C */  lw         $ra, 0x2C($sp)
    /* E294C 150B549C 27BD0050 */  addiu      $sp, $sp, 0x50
    /* E2950 150B54A0 03E00008 */  jr         $ra
    /* E2954 150B54A4 00000000 */   nop
endlabel func_150B53D0

nonmatching func_150B54A8, 0x31C

glabel func_150B54A8
    /* E2958 150B54A8 27BDFF60 */  addiu      $sp, $sp, -0xA0
    /* E295C 150B54AC AFB40068 */  sw         $s4, 0x68($sp)
    /* E2960 150B54B0 0080A025 */  or         $s4, $a0, $zero
    /* E2964 150B54B4 AFBF007C */  sw         $ra, 0x7C($sp)
    /* E2968 150B54B8 AFBE0078 */  sw         $fp, 0x78($sp)
    /* E296C 150B54BC AFB70074 */  sw         $s7, 0x74($sp)
    /* E2970 150B54C0 AFB60070 */  sw         $s6, 0x70($sp)
    /* E2974 150B54C4 AFB5006C */  sw         $s5, 0x6C($sp)
    /* E2978 150B54C8 AFB30064 */  sw         $s3, 0x64($sp)
    /* E297C 150B54CC AFB20060 */  sw         $s2, 0x60($sp)
    /* E2980 150B54D0 AFB1005C */  sw         $s1, 0x5C($sp)
    /* E2984 150B54D4 AFB00058 */  sw         $s0, 0x58($sp)
    /* E2988 150B54D8 F7BA0050 */  sdc1       $f26, 0x50($sp)
    /* E298C 150B54DC F7B80048 */  sdc1       $f24, 0x48($sp)
    /* E2990 150B54E0 F7B60040 */  sdc1       $f22, 0x40($sp)
    /* E2994 150B54E4 F7B40038 */  sdc1       $f20, 0x38($sp)
    /* E2998 150B54E8 8E960028 */  lw         $s6, 0x28($s4)
    /* E299C 150B54EC 26910028 */  addiu      $s1, $s4, 0x28
    /* E29A0 150B54F0 2408FFFF */  addiu      $t0, $zero, -0x1
    /* E29A4 150B54F4 8ECE0000 */  lw         $t6, 0x0($s6)
    /* E29A8 150B54F8 11C0000A */  beqz       $t6, .L150B5524
    /* E29AC 150B54FC 00000000 */   nop
    /* E29B0 150B5500 922F0004 */  lbu        $t7, 0x4($s1)
    /* E29B4 150B5504 92D8003B */  lbu        $t8, 0x3B($s6)
    /* E29B8 150B5508 15F80006 */  bne        $t7, $t8, .L150B5524
    /* E29BC 150B550C 00000000 */   nop
    /* E29C0 150B5510 92D90004 */  lbu        $t9, 0x4($s6)
    /* E29C4 150B5514 240100FF */  addiu      $at, $zero, 0xFF
    /* E29C8 150B5518 02C02025 */  or         $a0, $s6, $zero
    /* E29CC 150B551C 17210003 */  bne        $t9, $at, .L150B552C
    /* E29D0 150B5520 240500FF */   addiu     $a1, $zero, 0xFF
  .L150B5524:
    /* E29D4 150B5524 10000097 */  b          .L150B5784
    /* E29D8 150B5528 A688000E */   sh        $t0, 0xE($s4)
  .L150B552C:
    /* E29DC 150B552C 2409001E */  addiu      $t1, $zero, 0x1E
    /* E29E0 150B5530 240A000A */  addiu      $t2, $zero, 0xA
    /* E29E4 150B5534 AFAA0018 */  sw         $t2, 0x18($sp)
    /* E29E8 150B5538 AFA90010 */  sw         $t1, 0x10($sp)
    /* E29EC 150B553C 240600FF */  addiu      $a2, $zero, 0xFF
    /* E29F0 150B5540 240700FF */  addiu      $a3, $zero, 0xFF
    /* E29F4 150B5544 0D40BAA6 */  jal        func_1502EA98
    /* E29F8 150B5548 AFA00014 */   sw        $zero, 0x14($sp)
    /* E29FC 150B554C 0D42B69A */  jal        func_150ADA68
    /* E2A00 150B5550 00000000 */   nop
    /* E2A04 150B5554 3C013F80 */  lui        $at, (0x3F800000 >> 16)
    /* E2A08 150B5558 4481A000 */  mtc1       $at, $f20
    /* E2A0C 150B555C 3C01800A */  lui        $at, %hi(D_8009FC20)
    /* E2A10 150B5560 C424FC20 */  lwc1       $f4, %lo(D_8009FC20)($at)
    /* E2A14 150B5564 3C01800A */  lui        $at, %hi(D_8009FC24)
    /* E2A18 150B5568 C426FC24 */  lwc1       $f6, %lo(D_8009FC24)($at)
    /* E2A1C 150B556C 3C01800C */  lui        $at, %hi(D_800BE9A4)
    /* E2A20 150B5570 C430E9A4 */  lwc1       $f16, %lo(D_800BE9A4)($at)
    /* E2A24 150B5574 46060202 */  mul.s      $f8, $f0, $f6
    /* E2A28 150B5578 C6260008 */  lwc1       $f6, 0x8($s1)
    /* E2A2C 150B557C 3C01420C */  lui        $at, (0x420C0000 >> 16)
    /* E2A30 150B5580 24150065 */  addiu      $s5, $zero, 0x65
    /* E2A34 150B5584 46082280 */  add.s      $f10, $f4, $f8
    /* E2A38 150B5588 46105482 */  mul.s      $f18, $f10, $f16
    /* E2A3C 150B558C 46123100 */  add.s      $f4, $f6, $f18
    /* E2A40 150B5590 E6240008 */  swc1       $f4, 0x8($s1)
    /* E2A44 150B5594 C6280008 */  lwc1       $f8, 0x8($s1)
    /* E2A48 150B5598 4608A03C */  c.lt.s     $f20, $f8
    /* E2A4C 150B559C 00000000 */  nop
    /* E2A50 150B55A0 45000047 */  bc1f       .L150B56C0
    /* E2A54 150B55A4 00000000 */   nop
    /* E2A58 150B55A8 4481D000 */  mtc1       $at, $f26
    /* E2A5C 150B55AC 3C014296 */  lui        $at, (0x42960000 >> 16)
    /* E2A60 150B55B0 4481C000 */  mtc1       $at, $f24
    /* E2A64 150B55B4 3C014301 */  lui        $at, (0x43010000 >> 16)
    /* E2A68 150B55B8 4481B000 */  mtc1       $at, $f22
    /* E2A6C 150B55BC 27BE0094 */  addiu      $fp, $sp, 0x94
    /* E2A70 150B55C0 2417007E */  addiu      $s7, $zero, 0x7E
    /* E2A74 150B55C4 240B00BA */  addiu      $t3, $zero, 0xBA
  .L150B55C8:
    /* E2A78 150B55C8 240C00D2 */  addiu      $t4, $zero, 0xD2
    /* E2A7C 150B55CC 240D00FF */  addiu      $t5, $zero, 0xFF
    /* E2A80 150B55D0 A3AB0094 */  sb         $t3, 0x94($sp)
    /* E2A84 150B55D4 A3AC0095 */  sb         $t4, 0x95($sp)
    /* E2A88 150B55D8 0D42B688 */  jal        func_150ADA20
    /* E2A8C 150B55DC A3AD0096 */   sb        $t5, 0x96($sp)
    /* E2A90 150B55E0 0057001B */  divu       $zero, $v0, $s7
    /* E2A94 150B55E4 00007010 */  mfhi       $t6
    /* E2A98 150B55E8 25CF0082 */  addiu      $t7, $t6, 0x82
    /* E2A9C 150B55EC 16E00002 */  bnez       $s7, .L150B55F8
    /* E2AA0 150B55F0 00000000 */   nop
    /* E2AA4 150B55F4 0007000D */  break      7
  .L150B55F8:
    /* E2AA8 150B55F8 A3AF0097 */  sb         $t7, 0x97($sp)
    /* E2AAC 150B55FC 0D42B688 */  jal        func_150ADA20
    /* E2AB0 150B5600 00000000 */   nop
    /* E2AB4 150B5604 0D42B688 */  jal        func_150ADA20
    /* E2AB8 150B5608 00409025 */   or        $s2, $v0, $zero
    /* E2ABC 150B560C 0D42B688 */  jal        func_150ADA20
    /* E2AC0 150B5610 00408025 */   or        $s0, $v0, $zero
    /* E2AC4 150B5614 0D42B69A */  jal        func_150ADA68
    /* E2AC8 150B5618 00409825 */   or        $s3, $v0, $zero
    /* E2ACC 150B561C 0215001B */  divu       $zero, $s0, $s5
    /* E2AD0 150B5620 46180282 */  mul.s      $f10, $f0, $f24
    /* E2AD4 150B5624 240C0004 */  addiu      $t4, $zero, 0x4
    /* E2AD8 150B5628 240D0001 */  addiu      $t5, $zero, 0x1
    /* E2ADC 150B562C AFAD0020 */  sw         $t5, 0x20($sp)
    /* E2AE0 150B5630 AFAC0010 */  sw         $t4, 0x10($sp)
    /* E2AE4 150B5634 E7B60014 */  swc1       $f22, 0x14($sp)
    /* E2AE8 150B5638 AFA0001C */  sw         $zero, 0x1C($sp)
    /* E2AEC 150B563C 461A5400 */  add.s      $f16, $f10, $f26
    /* E2AF0 150B5640 AFBE0024 */  sw         $fp, 0x24($sp)
    /* E2AF4 150B5644 00003010 */  mfhi       $a2
    /* E2AF8 150B5648 324500FF */  andi       $a1, $s2, 0xFF
    /* E2AFC 150B564C E7B00018 */  swc1       $f16, 0x18($sp)
    /* E2B00 150B5650 928E000C */  lbu        $t6, 0xC($s4)
    /* E2B04 150B5654 3267000F */  andi       $a3, $s3, 0xF
    /* E2B08 150B5658 24E7000F */  addiu      $a3, $a3, 0xF
    /* E2B0C 150B565C AFAE0028 */  sw         $t6, 0x28($sp)
    /* E2B10 150B5660 928F0001 */  lbu        $t7, 0x1($s4)
    /* E2B14 150B5664 0005C400 */  sll        $t8, $a1, 16
    /* E2B18 150B5668 24C6FFC1 */  addiu      $a2, $a2, -0x3F
    /* E2B1C 150B566C 00064400 */  sll        $t0, $a2, 16
    /* E2B20 150B5670 0018CC03 */  sra        $t9, $t8, 16
    /* E2B24 150B5674 00075400 */  sll        $t2, $a3, 16
    /* E2B28 150B5678 000A3C03 */  sra        $a3, $t2, 16
    /* E2B2C 150B567C 03202825 */  or         $a1, $t9, $zero
    /* E2B30 150B5680 00083403 */  sra        $a2, $t0, 16
    /* E2B34 150B5684 02C02025 */  or         $a0, $s6, $zero
    /* E2B38 150B5688 16A00002 */  bnez       $s5, .L150B5694
    /* E2B3C 150B568C 00000000 */   nop
    /* E2B40 150B5690 0007000D */  break      7
  .L150B5694:
    /* E2B44 150B5694 AFAF002C */  sw         $t7, 0x2C($sp)
    /* E2B48 150B5698 0D441DC0 */  jal        func_15107700
    /* E2B4C 150B569C 00000000 */   nop
    /* E2B50 150B56A0 C6260008 */  lwc1       $f6, 0x8($s1)
    /* E2B54 150B56A4 46143481 */  sub.s      $f18, $f6, $f20
    /* E2B58 150B56A8 E6320008 */  swc1       $f18, 0x8($s1)
    /* E2B5C 150B56AC C6240008 */  lwc1       $f4, 0x8($s1)
    /* E2B60 150B56B0 4604A03C */  c.lt.s     $f20, $f4
    /* E2B64 150B56B4 00000000 */  nop
    /* E2B68 150B56B8 4503FFC3 */  bc1tl      .L150B55C8
    /* E2B6C 150B56BC 240B00BA */   addiu     $t3, $zero, 0xBA
  .L150B56C0:
    /* E2B70 150B56C0 0D42B69A */  jal        func_150ADA68
    /* E2B74 150B56C4 24150065 */   addiu     $s5, $zero, 0x65
    /* E2B78 150B56C8 3C01800A */  lui        $at, %hi(D_8009FC28)
    /* E2B7C 150B56CC C428FC28 */  lwc1       $f8, %lo(D_8009FC28)($at)
    /* E2B80 150B56D0 3C01800A */  lui        $at, %hi(D_8009FC2C)
    /* E2B84 150B56D4 C42AFC2C */  lwc1       $f10, %lo(D_8009FC2C)($at)
    /* E2B88 150B56D8 3C01800C */  lui        $at, %hi(D_800BE9A4)
    /* E2B8C 150B56DC C432E9A4 */  lwc1       $f18, %lo(D_800BE9A4)($at)
    /* E2B90 150B56E0 460A0402 */  mul.s      $f16, $f0, $f10
    /* E2B94 150B56E4 C62A000C */  lwc1       $f10, 0xC($s1)
    /* E2B98 150B56E8 46104180 */  add.s      $f6, $f8, $f16
    /* E2B9C 150B56EC 46123102 */  mul.s      $f4, $f6, $f18
    /* E2BA0 150B56F0 46045200 */  add.s      $f8, $f10, $f4
    /* E2BA4 150B56F4 E628000C */  swc1       $f8, 0xC($s1)
    /* E2BA8 150B56F8 C630000C */  lwc1       $f16, 0xC($s1)
    /* E2BAC 150B56FC 4610A03C */  c.lt.s     $f20, $f16
    /* E2BB0 150B5700 00000000 */  nop
    /* E2BB4 150B5704 45020020 */  bc1fl      .L150B5788
    /* E2BB8 150B5708 8FBF007C */   lw        $ra, 0x7C($sp)
  .L150B570C:
    /* E2BBC 150B570C 0D42B688 */  jal        func_150ADA20
    /* E2BC0 150B5710 00000000 */   nop
    /* E2BC4 150B5714 0D42B688 */  jal        func_150ADA20
    /* E2BC8 150B5718 00408025 */   or        $s0, $v0, $zero
    /* E2BCC 150B571C 0055001B */  divu       $zero, $v0, $s5
    /* E2BD0 150B5720 00003010 */  mfhi       $a2
    /* E2BD4 150B5724 320500FF */  andi       $a1, $s0, 0xFF
    /* E2BD8 150B5728 928A0001 */  lbu        $t2, 0x1($s4)
    /* E2BDC 150B572C 0005C400 */  sll        $t8, $a1, 16
    /* E2BE0 150B5730 24C6FFC1 */  addiu      $a2, $a2, -0x3F
    /* E2BE4 150B5734 00064400 */  sll        $t0, $a2, 16
    /* E2BE8 150B5738 0018CC03 */  sra        $t9, $t8, 16
    /* E2BEC 150B573C 9287000C */  lbu        $a3, 0xC($s4)
    /* E2BF0 150B5740 03202825 */  or         $a1, $t9, $zero
    /* E2BF4 150B5744 00083403 */  sra        $a2, $t0, 16
    /* E2BF8 150B5748 02C02025 */  or         $a0, $s6, $zero
    /* E2BFC 150B574C 16A00002 */  bnez       $s5, .L150B5758
    /* E2C00 150B5750 00000000 */   nop
    /* E2C04 150B5754 0007000D */  break      7
  .L150B5758:
    /* E2C08 150B5758 AFAA0010 */  sw         $t2, 0x10($sp)
    /* E2C0C 150B575C 0D441EDE */  jal        func_15107B78
    /* E2C10 150B5760 00000000 */   nop
    /* E2C14 150B5764 C626000C */  lwc1       $f6, 0xC($s1)
    /* E2C18 150B5768 46143481 */  sub.s      $f18, $f6, $f20
    /* E2C1C 150B576C E632000C */  swc1       $f18, 0xC($s1)
    /* E2C20 150B5770 C62A000C */  lwc1       $f10, 0xC($s1)
    /* E2C24 150B5774 460AA03C */  c.lt.s     $f20, $f10
    /* E2C28 150B5778 00000000 */  nop
    /* E2C2C 150B577C 4501FFE3 */  bc1t       .L150B570C
    /* E2C30 150B5780 00000000 */   nop
  .L150B5784:
    /* E2C34 150B5784 8FBF007C */  lw         $ra, 0x7C($sp)
  .L150B5788:
    /* E2C38 150B5788 D7B40038 */  ldc1       $f20, 0x38($sp)
    /* E2C3C 150B578C D7B60040 */  ldc1       $f22, 0x40($sp)
    /* E2C40 150B5790 D7B80048 */  ldc1       $f24, 0x48($sp)
    /* E2C44 150B5794 D7BA0050 */  ldc1       $f26, 0x50($sp)
    /* E2C48 150B5798 8FB00058 */  lw         $s0, 0x58($sp)
    /* E2C4C 150B579C 8FB1005C */  lw         $s1, 0x5C($sp)
    /* E2C50 150B57A0 8FB20060 */  lw         $s2, 0x60($sp)
    /* E2C54 150B57A4 8FB30064 */  lw         $s3, 0x64($sp)
    /* E2C58 150B57A8 8FB40068 */  lw         $s4, 0x68($sp)
    /* E2C5C 150B57AC 8FB5006C */  lw         $s5, 0x6C($sp)
    /* E2C60 150B57B0 8FB60070 */  lw         $s6, 0x70($sp)
    /* E2C64 150B57B4 8FB70074 */  lw         $s7, 0x74($sp)
    /* E2C68 150B57B8 8FBE0078 */  lw         $fp, 0x78($sp)
    /* E2C6C 150B57BC 03E00008 */  jr         $ra
    /* E2C70 150B57C0 27BD00A0 */   addiu     $sp, $sp, 0xA0
endlabel func_150B54A8

nonmatching func_150B57C4, 0x24

glabel func_150B57C4
    /* E2C74 150B57C4 27BDFFE8 */  addiu      $sp, $sp, -0x18
    /* E2C78 150B57C8 AFBF0014 */  sw         $ra, 0x14($sp)
    /* E2C7C 150B57CC AFA40018 */  sw         $a0, 0x18($sp)
    /* E2C80 150B57D0 0D474AD3 */  jal        func_151D2B4C
    /* E2C84 150B57D4 24040006 */   addiu     $a0, $zero, 0x6
    /* E2C88 150B57D8 8FBF0014 */  lw         $ra, 0x14($sp)
    /* E2C8C 150B57DC 27BD0018 */  addiu      $sp, $sp, 0x18
    /* E2C90 150B57E0 03E00008 */  jr         $ra
    /* E2C94 150B57E4 00000000 */   nop
endlabel func_150B57C4

nonmatching func_150B57E8, 0x2C

glabel func_150B57E8
    /* E2C98 150B57E8 27BDFFE8 */  addiu      $sp, $sp, -0x18
    /* E2C9C 150B57EC AFBF0014 */  sw         $ra, 0x14($sp)
    /* E2CA0 150B57F0 AFA40018 */  sw         $a0, 0x18($sp)
    /* E2CA4 150B57F4 0D42D5F1 */  jal        func_150B57C4
    /* E2CA8 150B57F8 8FA40018 */   lw        $a0, 0x18($sp)
    /* E2CAC 150B57FC 0D4524CF */  jal        func_1514933C
    /* E2CB0 150B5800 8FA40018 */   lw        $a0, 0x18($sp)
    /* E2CB4 150B5804 8FBF0014 */  lw         $ra, 0x14($sp)
    /* E2CB8 150B5808 27BD0018 */  addiu      $sp, $sp, 0x18
    /* E2CBC 150B580C 03E00008 */  jr         $ra
    /* E2CC0 150B5810 00000000 */   nop
endlabel func_150B57E8

nonmatching func_150B5814, 0x2C

glabel func_150B5814
    /* E2CC4 150B5814 27BDFFE8 */  addiu      $sp, $sp, -0x18
    /* E2CC8 150B5818 AFBF0014 */  sw         $ra, 0x14($sp)
    /* E2CCC 150B581C AFA40018 */  sw         $a0, 0x18($sp)
    /* E2CD0 150B5820 0D42D5F1 */  jal        func_150B57C4
    /* E2CD4 150B5824 8FA40018 */   lw        $a0, 0x18($sp)
    /* E2CD8 150B5828 0D4524DA */  jal        func_15149368
    /* E2CDC 150B582C 8FA40018 */   lw        $a0, 0x18($sp)
    /* E2CE0 150B5830 8FBF0014 */  lw         $ra, 0x14($sp)
    /* E2CE4 150B5834 27BD0018 */  addiu      $sp, $sp, 0x18
    /* E2CE8 150B5838 03E00008 */  jr         $ra
    /* E2CEC 150B583C 00000000 */   nop
endlabel func_150B5814

nonmatching func_150B5840, 0xAC

glabel func_150B5840
    /* E2CF0 150B5840 27BDFFE8 */  addiu      $sp, $sp, -0x18
    /* E2CF4 150B5844 AFA60020 */  sw         $a2, 0x20($sp)
    /* E2CF8 150B5848 30CE00FF */  andi       $t6, $a2, 0xFF
    /* E2CFC 150B584C 01C03025 */  or         $a2, $t6, $zero
    /* E2D00 150B5850 AFBF0014 */  sw         $ra, 0x14($sp)
    /* E2D04 150B5854 00803825 */  or         $a3, $a0, $zero
    /* E2D08 150B5858 14C0000E */  bnez       $a2, .L150B5894
    /* E2D0C 150B585C 00C01025 */   or        $v0, $a2, $zero
    /* E2D10 150B5860 24E20028 */  addiu      $v0, $a3, 0x28
    /* E2D14 150B5864 8CA30000 */  lw         $v1, 0x0($a1)
    /* E2D18 150B5868 8C4F0000 */  lw         $t7, 0x0($v0)
    /* E2D1C 150B586C 106F0005 */  beq        $v1, $t7, .L150B5884
    /* E2D20 150B5870 00000000 */   nop
    /* E2D24 150B5874 90580004 */  lbu        $t8, 0x4($v0)
    /* E2D28 150B5878 90B90004 */  lbu        $t9, 0x4($a1)
    /* E2D2C 150B587C 57190018 */  bnel       $t8, $t9, .L150B58E0
    /* E2D30 150B5880 8FBF0014 */   lw        $ra, 0x14($sp)
  .L150B5884:
    /* E2D34 150B5884 0D45A5CB */  jal        func_1516972C
    /* E2D38 150B5888 00E02025 */   or        $a0, $a3, $zero
    /* E2D3C 150B588C 10000014 */  b          .L150B58E0
    /* E2D40 150B5890 8FBF0014 */   lw        $ra, 0x14($sp)
  .L150B5894:
    /* E2D44 150B5894 2401002D */  addiu      $at, $zero, 0x2D
    /* E2D48 150B5898 14410010 */  bne        $v0, $at, .L150B58DC
    /* E2D4C 150B589C 24E20028 */   addiu     $v0, $a3, 0x28
    /* E2D50 150B58A0 8C440000 */  lw         $a0, 0x0($v0)
    /* E2D54 150B58A4 8CA30000 */  lw         $v1, 0x0($a1)
    /* E2D58 150B58A8 54640007 */  bnel       $v1, $a0, .L150B58C8
    /* E2D5C 150B58AC 8CAA0004 */   lw        $t2, 0x4($a1)
    /* E2D60 150B58B0 8CA80004 */  lw         $t0, 0x4($a1)
    /* E2D64 150B58B4 AC480000 */  sw         $t0, 0x0($v0)
    /* E2D68 150B58B8 90A90009 */  lbu        $t1, 0x9($a1)
    /* E2D6C 150B58BC 10000007 */  b          .L150B58DC
    /* E2D70 150B58C0 A0490004 */   sb        $t1, 0x4($v0)
    /* E2D74 150B58C4 8CAA0004 */  lw         $t2, 0x4($a1)
  .L150B58C8:
    /* E2D78 150B58C8 55440005 */  bnel       $t2, $a0, .L150B58E0
    /* E2D7C 150B58CC 8FBF0014 */   lw        $ra, 0x14($sp)
    /* E2D80 150B58D0 AC430000 */  sw         $v1, 0x0($v0)
    /* E2D84 150B58D4 90AB0008 */  lbu        $t3, 0x8($a1)
    /* E2D88 150B58D8 A04B0004 */  sb         $t3, 0x4($v0)
  .L150B58DC:
    /* E2D8C 150B58DC 8FBF0014 */  lw         $ra, 0x14($sp)
  .L150B58E0:
    /* E2D90 150B58E0 27BD0018 */  addiu      $sp, $sp, 0x18
    /* E2D94 150B58E4 03E00008 */  jr         $ra
    /* E2D98 150B58E8 00000000 */   nop
endlabel func_150B5840
    /* E2D9C 150B58EC 00000000 */  nop
