.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching func_150B58F0, 0x60

glabel func_150B58F0
    /* E2DA0 150B58F0 3C0E800C */  lui        $t6, %hi(D_800C35EA)
    /* E2DA4 150B58F4 91CE35EA */  lbu        $t6, %lo(D_800C35EA)($t6)
    /* E2DA8 150B58F8 24010001 */  addiu      $at, $zero, 0x1
    /* E2DAC 150B58FC 240F001A */  addiu      $t7, $zero, 0x1A
    /* E2DB0 150B5900 15C10003 */  bne        $t6, $at, .L150B5910
    /* E2DB4 150B5904 0005C080 */   sll       $t8, $a1, 2
    /* E2DB8 150B5908 03E00008 */  jr         $ra
    /* E2DBC 150B590C 00801025 */   or        $v0, $a0, $zero
  .L150B5910:
    /* E2DC0 150B5910 0305C023 */  subu       $t8, $t8, $a1
    /* E2DC4 150B5914 0018C080 */  sll        $t8, $t8, 2
    /* E2DC8 150B5918 0305C021 */  addu       $t8, $t8, $a1
    /* E2DCC 150B591C 0018C080 */  sll        $t8, $t8, 2
    /* E2DD0 150B5920 0305C023 */  subu       $t8, $t8, $a1
    /* E2DD4 150B5924 0018C080 */  sll        $t8, $t8, 2
    /* E2DD8 150B5928 0305C023 */  subu       $t8, $t8, $a1
    /* E2DDC 150B592C 0018C080 */  sll        $t8, $t8, 2
    /* E2DE0 150B5930 3C19800D */  lui        $t9, %hi(D_800CC34A)
    /* E2DE4 150B5934 A48F0000 */  sh         $t7, 0x0($a0)
    /* E2DE8 150B5938 0338C821 */  addu       $t9, $t9, $t8
    /* E2DEC 150B593C 9739C34A */  lhu        $t9, %lo(D_800CC34A)($t9)
    /* E2DF0 150B5940 24820004 */  addiu      $v0, $a0, 0x4
    /* E2DF4 150B5944 A4990002 */  sh         $t9, 0x2($a0)
    /* E2DF8 150B5948 03E00008 */  jr         $ra
    /* E2DFC 150B594C 00000000 */   nop
endlabel func_150B58F0

nonmatching func_150B5950, 0xEC

glabel func_150B5950
    /* E2E00 150B5950 27BDFFC8 */  addiu      $sp, $sp, -0x38
    /* E2E04 150B5954 AFB00018 */  sw         $s0, 0x18($sp)
    /* E2E08 150B5958 00808025 */  or         $s0, $a0, $zero
    /* E2E0C 150B595C AFBF001C */  sw         $ra, 0x1C($sp)
    /* E2E10 150B5960 8E070028 */  lw         $a3, 0x28($s0)
    /* E2E14 150B5964 2419FFFF */  addiu      $t9, $zero, -0x1
    /* E2E18 150B5968 8CEE0000 */  lw         $t6, 0x0($a3)
    /* E2E1C 150B596C 11C00005 */  beqz       $t6, .L150B5984
    /* E2E20 150B5970 00000000 */   nop
    /* E2E24 150B5974 920F002C */  lbu        $t7, 0x2C($s0)
    /* E2E28 150B5978 90F8003B */  lbu        $t8, 0x3B($a3)
    /* E2E2C 150B597C 51F80004 */  beql       $t7, $t8, .L150B5990
    /* E2E30 150B5980 8CE801D4 */   lw        $t0, 0x1D4($a3)
  .L150B5984:
    /* E2E34 150B5984 10000028 */  b          .L150B5A28
    /* E2E38 150B5988 A619000E */   sh        $t9, 0xE($s0)
    /* E2E3C 150B598C 8CE801D4 */  lw         $t0, 0x1D4($a3)
  .L150B5990:
    /* E2E40 150B5990 51000026 */  beql       $t0, $zero, .L150B5A2C
    /* E2E44 150B5994 8FBF001C */   lw        $ra, 0x1C($sp)
    /* E2E48 150B5998 0D42B69A */  jal        func_150ADA68
    /* E2E4C 150B599C AFA70024 */   sw        $a3, 0x24($sp)
    /* E2E50 150B59A0 3C01800A */  lui        $at, %hi(D_8009FC98)
    /* E2E54 150B59A4 C424FC98 */  lwc1       $f4, %lo(D_8009FC98)($at)
    /* E2E58 150B59A8 8FA70024 */  lw         $a3, 0x24($sp)
    /* E2E5C 150B59AC 4604003C */  c.lt.s     $f0, $f4
    /* E2E60 150B59B0 00000000 */  nop
    /* E2E64 150B59B4 4500000D */  bc1f       .L150B59EC
    /* E2E68 150B59B8 00000000 */   nop
    /* E2E6C 150B59BC C4E60014 */  lwc1       $f6, 0x14($a3)
    /* E2E70 150B59C0 27A40028 */  addiu      $a0, $sp, 0x28
    /* E2E74 150B59C4 E7A60028 */  swc1       $f6, 0x28($sp)
    /* E2E78 150B59C8 C4E80018 */  lwc1       $f8, 0x18($a3)
    /* E2E7C 150B59CC E7A8002C */  swc1       $f8, 0x2C($sp)
    /* E2E80 150B59D0 C4EA001C */  lwc1       $f10, 0x1C($a3)
    /* E2E84 150B59D4 E7AA0030 */  swc1       $f10, 0x30($sp)
    /* E2E88 150B59D8 92060001 */  lbu        $a2, 0x1($s0)
    /* E2E8C 150B59DC 9205000C */  lbu        $a1, 0xC($s0)
    /* E2E90 150B59E0 0D42D68F */  jal        func_150B5A3C
    /* E2E94 150B59E4 AFA70024 */   sw        $a3, 0x24($sp)
    /* E2E98 150B59E8 8FA70024 */  lw         $a3, 0x24($sp)
  .L150B59EC:
    /* E2E9C 150B59EC 0D42B69A */  jal        func_150ADA68
    /* E2EA0 150B59F0 AFA70024 */   sw        $a3, 0x24($sp)
    /* E2EA4 150B59F4 3C01800A */  lui        $at, %hi(D_8009FC9C)
    /* E2EA8 150B59F8 C430FC9C */  lwc1       $f16, %lo(D_8009FC9C)($at)
    /* E2EAC 150B59FC 8FA70024 */  lw         $a3, 0x24($sp)
    /* E2EB0 150B5A00 4610003C */  c.lt.s     $f0, $f16
    /* E2EB4 150B5A04 00E02025 */  or         $a0, $a3, $zero
    /* E2EB8 150B5A08 45020008 */  bc1fl      .L150B5A2C
    /* E2EBC 150B5A0C 8FBF001C */   lw        $ra, 0x1C($sp)
    /* E2EC0 150B5A10 0D42D838 */  jal        func_150B60E0
    /* E2EC4 150B5A14 27A50028 */   addiu     $a1, $sp, 0x28
    /* E2EC8 150B5A18 27A40028 */  addiu      $a0, $sp, 0x28
    /* E2ECC 150B5A1C 9205000C */  lbu        $a1, 0xC($s0)
    /* E2ED0 150B5A20 0D42D68F */  jal        func_150B5A3C
    /* E2ED4 150B5A24 92060001 */   lbu       $a2, 0x1($s0)
  .L150B5A28:
    /* E2ED8 150B5A28 8FBF001C */  lw         $ra, 0x1C($sp)
  .L150B5A2C:
    /* E2EDC 150B5A2C 8FB00018 */  lw         $s0, 0x18($sp)
    /* E2EE0 150B5A30 27BD0038 */  addiu      $sp, $sp, 0x38
    /* E2EE4 150B5A34 03E00008 */  jr         $ra
    /* E2EE8 150B5A38 00000000 */   nop
endlabel func_150B5950

nonmatching func_150B5A3C, 0x1FC

glabel func_150B5A3C
    /* E2EEC 150B5A3C 27BDFF70 */  addiu      $sp, $sp, -0x90
    /* E2EF0 150B5A40 AFBF0014 */  sw         $ra, 0x14($sp)
    /* E2EF4 150B5A44 AFA40090 */  sw         $a0, 0x90($sp)
    /* E2EF8 150B5A48 AFA50094 */  sw         $a1, 0x94($sp)
    /* E2EFC 150B5A4C AFA60098 */  sw         $a2, 0x98($sp)
    /* E2F00 150B5A50 8FB90090 */  lw         $t9, 0x90($sp)
    /* E2F04 150B5A54 240E0005 */  addiu      $t6, $zero, 0x5
    /* E2F08 150B5A58 240F0005 */  addiu      $t7, $zero, 0x5
    /* E2F0C 150B5A5C AFAE001C */  sw         $t6, 0x1C($sp)
    /* E2F10 150B5A60 AFAF0020 */  sw         $t7, 0x20($sp)
    /* E2F14 150B5A64 8F210000 */  lw         $at, 0x0($t9)
    /* E2F18 150B5A68 27B80024 */  addiu      $t8, $sp, 0x24
    /* E2F1C 150B5A6C 240D0050 */  addiu      $t5, $zero, 0x50
    /* E2F20 150B5A70 AF010000 */  sw         $at, 0x0($t8)
    /* E2F24 150B5A74 8F2A0004 */  lw         $t2, 0x4($t9)
    /* E2F28 150B5A78 240E0003 */  addiu      $t6, $zero, 0x3
    /* E2F2C 150B5A7C 240CFFE1 */  addiu      $t4, $zero, -0x1F
    /* E2F30 150B5A80 AF0A0004 */  sw         $t2, 0x4($t8)
    /* E2F34 150B5A84 8F210008 */  lw         $at, 0x8($t9)
    /* E2F38 150B5A88 240F0002 */  addiu      $t7, $zero, 0x2
    /* E2F3C 150B5A8C 24090014 */  addiu      $t1, $zero, 0x14
    /* E2F40 150B5A90 AF010008 */  sw         $at, 0x8($t8)
    /* E2F44 150B5A94 3C0141A0 */  lui        $at, (0x41A00000 >> 16)
    /* E2F48 150B5A98 44812000 */  mtc1       $at, $f4
    /* E2F4C 150B5A9C 3C01800A */  lui        $at, %hi(D_8009FCA0)
    /* E2F50 150B5AA0 C426FCA0 */  lwc1       $f6, %lo(D_8009FCA0)($at)
    /* E2F54 150B5AA4 3C01800A */  lui        $at, %hi(D_8009FCA4)
    /* E2F58 150B5AA8 C428FCA4 */  lwc1       $f8, %lo(D_8009FCA4)($at)
    /* E2F5C 150B5AAC 3C01800A */  lui        $at, %hi(D_8009FCA8)
    /* E2F60 150B5AB0 C42AFCA8 */  lwc1       $f10, %lo(D_8009FCA8)($at)
    /* E2F64 150B5AB4 3C01421C */  lui        $at, (0x421C0000 >> 16)
    /* E2F68 150B5AB8 44818000 */  mtc1       $at, $f16
    /* E2F6C 150B5ABC 3C01420C */  lui        $at, (0x420C0000 >> 16)
    /* E2F70 150B5AC0 A7AD004E */  sh         $t5, 0x4E($sp)
    /* E2F74 150B5AC4 AFAE0050 */  sw         $t6, 0x50($sp)
    /* E2F78 150B5AC8 2408001E */  addiu      $t0, $zero, 0x1E
    /* E2F7C 150B5ACC 24180001 */  addiu      $t8, $zero, 0x1
    /* E2F80 150B5AD0 24190004 */  addiu      $t9, $zero, 0x4
    /* E2F84 150B5AD4 240A0002 */  addiu      $t2, $zero, 0x2
    /* E2F88 150B5AD8 44819000 */  mtc1       $at, $f18
    /* E2F8C 150B5ADC A7AC004C */  sh         $t4, 0x4C($sp)
    /* E2F90 150B5AE0 AFAF0054 */  sw         $t7, 0x54($sp)
    /* E2F94 150B5AE4 A7A90058 */  sh         $t1, 0x58($sp)
    /* E2F98 150B5AE8 A7A8005A */  sh         $t0, 0x5A($sp)
    /* E2F9C 150B5AEC A7B8005C */  sh         $t8, 0x5C($sp)
    /* E2FA0 150B5AF0 A3B9005E */  sb         $t9, 0x5E($sp)
    /* E2FA4 150B5AF4 A3AA005F */  sb         $t2, 0x5F($sp)
    /* E2FA8 150B5AF8 240D00FF */  addiu      $t5, $zero, 0xFF
    /* E2FAC 150B5AFC 240E00FF */  addiu      $t6, $zero, 0xFF
    /* E2FB0 150B5B00 240B00FF */  addiu      $t3, $zero, 0xFF
    /* E2FB4 150B5B04 240C00FF */  addiu      $t4, $zero, 0xFF
    /* E2FB8 150B5B08 A3AD0062 */  sb         $t5, 0x62($sp)
    /* E2FBC 150B5B0C A3AE0063 */  sb         $t6, 0x63($sp)
    /* E2FC0 150B5B10 240F00FF */  addiu      $t7, $zero, 0xFF
    /* E2FC4 150B5B14 240900FF */  addiu      $t1, $zero, 0xFF
    /* E2FC8 150B5B18 240800FF */  addiu      $t0, $zero, 0xFF
    /* E2FCC 150B5B1C 241800FF */  addiu      $t8, $zero, 0xFF
    /* E2FD0 150B5B20 241900FF */  addiu      $t9, $zero, 0xFF
    /* E2FD4 150B5B24 240A00FF */  addiu      $t2, $zero, 0xFF
    /* E2FD8 150B5B28 3C013F80 */  lui        $at, (0x3F800000 >> 16)
    /* E2FDC 150B5B2C E7A40030 */  swc1       $f4, 0x30($sp)
    /* E2FE0 150B5B30 44812000 */  mtc1       $at, $f4
    /* E2FE4 150B5B34 A7AB004A */  sh         $t3, 0x4A($sp)
    /* E2FE8 150B5B38 A3AC0061 */  sb         $t4, 0x61($sp)
    /* E2FEC 150B5B3C A3AF0064 */  sb         $t7, 0x64($sp)
    /* E2FF0 150B5B40 A3A90069 */  sb         $t1, 0x69($sp)
    /* E2FF4 150B5B44 A3A8006A */  sb         $t0, 0x6A($sp)
    /* E2FF8 150B5B48 A3B8006B */  sb         $t8, 0x6B($sp)
    /* E2FFC 150B5B4C A3B9006C */  sb         $t9, 0x6C($sp)
    /* E3000 150B5B50 A3AA0071 */  sb         $t2, 0x71($sp)
    /* E3004 150B5B54 3C0D0020 */  lui        $t5, (0x200005 >> 16)
    /* E3008 150B5B58 3C0E0006 */  lui        $t6, (0x60600 >> 16)
    /* E300C 150B5B5C 240B0003 */  addiu      $t3, $zero, 0x3
    /* E3010 150B5B60 240C0024 */  addiu      $t4, $zero, 0x24
    /* E3014 150B5B64 35AD0005 */  ori        $t5, $t5, (0x200005 & 0xFFFF)
    /* E3018 150B5B68 35CE0600 */  ori        $t6, $t6, (0x60600 & 0xFFFF)
    /* E301C 150B5B6C 240F0008 */  addiu      $t7, $zero, 0x8
    /* E3020 150B5B70 2409001F */  addiu      $t1, $zero, 0x1F
    /* E3024 150B5B74 24080001 */  addiu      $t0, $zero, 0x1
    /* E3028 150B5B78 2418FFFF */  addiu      $t8, $zero, -0x1
    /* E302C 150B5B7C 2419FFFF */  addiu      $t9, $zero, -0x1
    /* E3030 150B5B80 240AFFFF */  addiu      $t2, $zero, -0x1
    /* E3034 150B5B84 A7A00048 */  sh         $zero, 0x48($sp)
    /* E3038 150B5B88 A3AB0060 */  sb         $t3, 0x60($sp)
    /* E303C 150B5B8C A3A00065 */  sb         $zero, 0x65($sp)
    /* E3040 150B5B90 A3A00066 */  sb         $zero, 0x66($sp)
    /* E3044 150B5B94 A3A00067 */  sb         $zero, 0x67($sp)
    /* E3048 150B5B98 A3A00068 */  sb         $zero, 0x68($sp)
    /* E304C 150B5B9C A3A0006D */  sb         $zero, 0x6D($sp)
    /* E3050 150B5BA0 A3A0006E */  sb         $zero, 0x6E($sp)
    /* E3054 150B5BA4 A3A0006F */  sb         $zero, 0x6F($sp)
    /* E3058 150B5BA8 A3A00070 */  sb         $zero, 0x70($sp)
    /* E305C 150B5BAC A3A00072 */  sb         $zero, 0x72($sp)
    /* E3060 150B5BB0 A3AB0073 */  sb         $t3, 0x73($sp)
    /* E3064 150B5BB4 A3AC0074 */  sb         $t4, 0x74($sp)
    /* E3068 150B5BB8 AFAD0078 */  sw         $t5, 0x78($sp)
    /* E306C 150B5BBC AFAE007C */  sw         $t6, 0x7C($sp)
    /* E3070 150B5BC0 A7AF0080 */  sh         $t7, 0x80($sp)
    /* E3074 150B5BC4 A7A90082 */  sh         $t1, 0x82($sp)
    /* E3078 150B5BC8 A7A80084 */  sh         $t0, 0x84($sp)
    /* E307C 150B5BCC A3A00086 */  sb         $zero, 0x86($sp)
    /* E3080 150B5BD0 A3B8008C */  sb         $t8, 0x8C($sp)
    /* E3084 150B5BD4 A3A0008D */  sb         $zero, 0x8D($sp)
    /* E3088 150B5BD8 A3B9008E */  sb         $t9, 0x8E($sp)
    /* E308C 150B5BDC A3AA008F */  sb         $t2, 0x8F($sp)
    /* E3090 150B5BE0 8FA60098 */  lw         $a2, 0x98($sp)
    /* E3094 150B5BE4 93A50097 */  lbu        $a1, 0x97($sp)
    /* E3098 150B5BE8 27A4001C */  addiu      $a0, $sp, 0x1C
    /* E309C 150B5BEC E7A60034 */  swc1       $f6, 0x34($sp)
    /* E30A0 150B5BF0 E7A80038 */  swc1       $f8, 0x38($sp)
    /* E30A4 150B5BF4 E7AA003C */  swc1       $f10, 0x3C($sp)
    /* E30A8 150B5BF8 E7B00040 */  swc1       $f16, 0x40($sp)
    /* E30AC 150B5BFC E7B20044 */  swc1       $f18, 0x44($sp)
    /* E30B0 150B5C00 0D454ACE */  jal        func_15152B38
    /* E30B4 150B5C04 E7A40088 */   swc1      $f4, 0x88($sp)
    /* E30B8 150B5C08 8FA40090 */  lw         $a0, 0x90($sp)
    /* E30BC 150B5C0C 93A50097 */  lbu        $a1, 0x97($sp)
    /* E30C0 150B5C10 0D42D78D */  jal        func_150B5E34
    /* E30C4 150B5C14 8FA60098 */   lw        $a2, 0x98($sp)
    /* E30C8 150B5C18 8FA40090 */  lw         $a0, 0x90($sp)
    /* E30CC 150B5C1C 93A50097 */  lbu        $a1, 0x97($sp)
    /* E30D0 150B5C20 0D42D800 */  jal        func_150B6000
    /* E30D4 150B5C24 8FA60098 */   lw        $a2, 0x98($sp)
    /* E30D8 150B5C28 8FBF0014 */  lw         $ra, 0x14($sp)
    /* E30DC 150B5C2C 27BD0090 */  addiu      $sp, $sp, 0x90
    /* E30E0 150B5C30 03E00008 */  jr         $ra
    /* E30E4 150B5C34 00000000 */   nop
endlabel func_150B5A3C

nonmatching func_150B5C38, 0x1FC

glabel func_150B5C38
    /* E30E8 150B5C38 27BDFF70 */  addiu      $sp, $sp, -0x90
    /* E30EC 150B5C3C AFBF0014 */  sw         $ra, 0x14($sp)
    /* E30F0 150B5C40 AFA40090 */  sw         $a0, 0x90($sp)
    /* E30F4 150B5C44 AFA50094 */  sw         $a1, 0x94($sp)
    /* E30F8 150B5C48 AFA60098 */  sw         $a2, 0x98($sp)
    /* E30FC 150B5C4C 8FB90090 */  lw         $t9, 0x90($sp)
    /* E3100 150B5C50 240E000D */  addiu      $t6, $zero, 0xD
    /* E3104 150B5C54 240F0008 */  addiu      $t7, $zero, 0x8
    /* E3108 150B5C58 AFAE001C */  sw         $t6, 0x1C($sp)
    /* E310C 150B5C5C AFAF0020 */  sw         $t7, 0x20($sp)
    /* E3110 150B5C60 8F210000 */  lw         $at, 0x0($t9)
    /* E3114 150B5C64 27B80024 */  addiu      $t8, $sp, 0x24
    /* E3118 150B5C68 240D0032 */  addiu      $t5, $zero, 0x32
    /* E311C 150B5C6C AF010000 */  sw         $at, 0x0($t8)
    /* E3120 150B5C70 8F2A0004 */  lw         $t2, 0x4($t9)
    /* E3124 150B5C74 240E0003 */  addiu      $t6, $zero, 0x3
    /* E3128 150B5C78 240CFFEC */  addiu      $t4, $zero, -0x14
    /* E312C 150B5C7C AF0A0004 */  sw         $t2, 0x4($t8)
    /* E3130 150B5C80 8F210008 */  lw         $at, 0x8($t9)
    /* E3134 150B5C84 240F0002 */  addiu      $t7, $zero, 0x2
    /* E3138 150B5C88 24090014 */  addiu      $t1, $zero, 0x14
    /* E313C 150B5C8C AF010008 */  sw         $at, 0x8($t8)
    /* E3140 150B5C90 3C01800A */  lui        $at, %hi(D_8009FCAC)
    /* E3144 150B5C94 C424FCAC */  lwc1       $f4, %lo(D_8009FCAC)($at)
    /* E3148 150B5C98 3C01800A */  lui        $at, %hi(D_8009FCB0)
    /* E314C 150B5C9C C426FCB0 */  lwc1       $f6, %lo(D_8009FCB0)($at)
    /* E3150 150B5CA0 3C01800A */  lui        $at, %hi(D_8009FCB4)
    /* E3154 150B5CA4 C428FCB4 */  lwc1       $f8, %lo(D_8009FCB4)($at)
    /* E3158 150B5CA8 3C01800A */  lui        $at, %hi(D_8009FCB8)
    /* E315C 150B5CAC C42AFCB8 */  lwc1       $f10, %lo(D_8009FCB8)($at)
    /* E3160 150B5CB0 3C014318 */  lui        $at, (0x43180000 >> 16)
    /* E3164 150B5CB4 44818000 */  mtc1       $at, $f16
    /* E3168 150B5CB8 3C0142C8 */  lui        $at, (0x42C80000 >> 16)
    /* E316C 150B5CBC A7AD004E */  sh         $t5, 0x4E($sp)
    /* E3170 150B5CC0 AFAE0050 */  sw         $t6, 0x50($sp)
    /* E3174 150B5CC4 2408000F */  addiu      $t0, $zero, 0xF
    /* E3178 150B5CC8 24180001 */  addiu      $t8, $zero, 0x1
    /* E317C 150B5CCC 24190004 */  addiu      $t9, $zero, 0x4
    /* E3180 150B5CD0 240A0002 */  addiu      $t2, $zero, 0x2
    /* E3184 150B5CD4 44819000 */  mtc1       $at, $f18
    /* E3188 150B5CD8 A7AC004C */  sh         $t4, 0x4C($sp)
    /* E318C 150B5CDC AFAF0054 */  sw         $t7, 0x54($sp)
    /* E3190 150B5CE0 A7A90058 */  sh         $t1, 0x58($sp)
    /* E3194 150B5CE4 A7A8005A */  sh         $t0, 0x5A($sp)
    /* E3198 150B5CE8 A7B8005C */  sh         $t8, 0x5C($sp)
    /* E319C 150B5CEC A3B9005E */  sb         $t9, 0x5E($sp)
    /* E31A0 150B5CF0 A3AA005F */  sb         $t2, 0x5F($sp)
    /* E31A4 150B5CF4 240D00FF */  addiu      $t5, $zero, 0xFF
    /* E31A8 150B5CF8 240E00B4 */  addiu      $t6, $zero, 0xB4
    /* E31AC 150B5CFC 240B00FF */  addiu      $t3, $zero, 0xFF
    /* E31B0 150B5D00 240C00FF */  addiu      $t4, $zero, 0xFF
    /* E31B4 150B5D04 A3AD0062 */  sb         $t5, 0x62($sp)
    /* E31B8 150B5D08 A3AE0063 */  sb         $t6, 0x63($sp)
    /* E31BC 150B5D0C 240F00FF */  addiu      $t7, $zero, 0xFF
    /* E31C0 150B5D10 240900FF */  addiu      $t1, $zero, 0xFF
    /* E31C4 150B5D14 240800FF */  addiu      $t0, $zero, 0xFF
    /* E31C8 150B5D18 241800B4 */  addiu      $t8, $zero, 0xB4
    /* E31CC 150B5D1C 241900FF */  addiu      $t9, $zero, 0xFF
    /* E31D0 150B5D20 240A00FF */  addiu      $t2, $zero, 0xFF
    /* E31D4 150B5D24 3C013F80 */  lui        $at, (0x3F800000 >> 16)
    /* E31D8 150B5D28 E7A40030 */  swc1       $f4, 0x30($sp)
    /* E31DC 150B5D2C 44812000 */  mtc1       $at, $f4
    /* E31E0 150B5D30 A7AB004A */  sh         $t3, 0x4A($sp)
    /* E31E4 150B5D34 A3AC0061 */  sb         $t4, 0x61($sp)
    /* E31E8 150B5D38 A3AF0064 */  sb         $t7, 0x64($sp)
    /* E31EC 150B5D3C A3A90069 */  sb         $t1, 0x69($sp)
    /* E31F0 150B5D40 A3A8006A */  sb         $t0, 0x6A($sp)
    /* E31F4 150B5D44 A3B8006B */  sb         $t8, 0x6B($sp)
    /* E31F8 150B5D48 A3B9006C */  sb         $t9, 0x6C($sp)
    /* E31FC 150B5D4C A3AA0071 */  sb         $t2, 0x71($sp)
    /* E3200 150B5D50 3C0D0020 */  lui        $t5, (0x200005 >> 16)
    /* E3204 150B5D54 3C0E0006 */  lui        $t6, (0x60600 >> 16)
    /* E3208 150B5D58 240B0003 */  addiu      $t3, $zero, 0x3
    /* E320C 150B5D5C 240C0024 */  addiu      $t4, $zero, 0x24
    /* E3210 150B5D60 35AD0005 */  ori        $t5, $t5, (0x200005 & 0xFFFF)
    /* E3214 150B5D64 35CE0600 */  ori        $t6, $t6, (0x60600 & 0xFFFF)
    /* E3218 150B5D68 240F0008 */  addiu      $t7, $zero, 0x8
    /* E321C 150B5D6C 2409001F */  addiu      $t1, $zero, 0x1F
    /* E3220 150B5D70 24080001 */  addiu      $t0, $zero, 0x1
    /* E3224 150B5D74 2418FFFF */  addiu      $t8, $zero, -0x1
    /* E3228 150B5D78 2419FFFF */  addiu      $t9, $zero, -0x1
    /* E322C 150B5D7C 240AFFFF */  addiu      $t2, $zero, -0x1
    /* E3230 150B5D80 A7A00048 */  sh         $zero, 0x48($sp)
    /* E3234 150B5D84 A3AB0060 */  sb         $t3, 0x60($sp)
    /* E3238 150B5D88 A3A00065 */  sb         $zero, 0x65($sp)
    /* E323C 150B5D8C A3A00066 */  sb         $zero, 0x66($sp)
    /* E3240 150B5D90 A3A00067 */  sb         $zero, 0x67($sp)
    /* E3244 150B5D94 A3A00068 */  sb         $zero, 0x68($sp)
    /* E3248 150B5D98 A3A0006D */  sb         $zero, 0x6D($sp)
    /* E324C 150B5D9C A3A0006E */  sb         $zero, 0x6E($sp)
    /* E3250 150B5DA0 A3A0006F */  sb         $zero, 0x6F($sp)
    /* E3254 150B5DA4 A3A00070 */  sb         $zero, 0x70($sp)
    /* E3258 150B5DA8 A3A00072 */  sb         $zero, 0x72($sp)
    /* E325C 150B5DAC A3AB0073 */  sb         $t3, 0x73($sp)
    /* E3260 150B5DB0 A3AC0074 */  sb         $t4, 0x74($sp)
    /* E3264 150B5DB4 AFAD0078 */  sw         $t5, 0x78($sp)
    /* E3268 150B5DB8 AFAE007C */  sw         $t6, 0x7C($sp)
    /* E326C 150B5DBC A7AF0080 */  sh         $t7, 0x80($sp)
    /* E3270 150B5DC0 A7A90082 */  sh         $t1, 0x82($sp)
    /* E3274 150B5DC4 A7A80084 */  sh         $t0, 0x84($sp)
    /* E3278 150B5DC8 A3A00086 */  sb         $zero, 0x86($sp)
    /* E327C 150B5DCC A3B8008C */  sb         $t8, 0x8C($sp)
    /* E3280 150B5DD0 A3A0008D */  sb         $zero, 0x8D($sp)
    /* E3284 150B5DD4 A3B9008E */  sb         $t9, 0x8E($sp)
    /* E3288 150B5DD8 A3AA008F */  sb         $t2, 0x8F($sp)
    /* E328C 150B5DDC 8FA60098 */  lw         $a2, 0x98($sp)
    /* E3290 150B5DE0 93A50097 */  lbu        $a1, 0x97($sp)
    /* E3294 150B5DE4 27A4001C */  addiu      $a0, $sp, 0x1C
    /* E3298 150B5DE8 E7A60034 */  swc1       $f6, 0x34($sp)
    /* E329C 150B5DEC E7A80038 */  swc1       $f8, 0x38($sp)
    /* E32A0 150B5DF0 E7AA003C */  swc1       $f10, 0x3C($sp)
    /* E32A4 150B5DF4 E7B00040 */  swc1       $f16, 0x40($sp)
    /* E32A8 150B5DF8 E7B20044 */  swc1       $f18, 0x44($sp)
    /* E32AC 150B5DFC 0D454ACE */  jal        func_15152B38
    /* E32B0 150B5E00 E7A40088 */   swc1      $f4, 0x88($sp)
    /* E32B4 150B5E04 8FA40090 */  lw         $a0, 0x90($sp)
    /* E32B8 150B5E08 93A50097 */  lbu        $a1, 0x97($sp)
    /* E32BC 150B5E0C 0D42D78D */  jal        func_150B5E34
    /* E32C0 150B5E10 8FA60098 */   lw        $a2, 0x98($sp)
    /* E32C4 150B5E14 8FA40090 */  lw         $a0, 0x90($sp)
    /* E32C8 150B5E18 93A50097 */  lbu        $a1, 0x97($sp)
    /* E32CC 150B5E1C 0D42D800 */  jal        func_150B6000
    /* E32D0 150B5E20 8FA60098 */   lw        $a2, 0x98($sp)
    /* E32D4 150B5E24 8FBF0014 */  lw         $ra, 0x14($sp)
    /* E32D8 150B5E28 27BD0090 */  addiu      $sp, $sp, 0x90
    /* E32DC 150B5E2C 03E00008 */  jr         $ra
    /* E32E0 150B5E30 00000000 */   nop
endlabel func_150B5C38

nonmatching func_150B5E34, 0x1CC

glabel func_150B5E34
    /* E32E4 150B5E34 27BDFF68 */  addiu      $sp, $sp, -0x98
    /* E32E8 150B5E38 AFBF001C */  sw         $ra, 0x1C($sp)
    /* E32EC 150B5E3C AFA40098 */  sw         $a0, 0x98($sp)
    /* E32F0 150B5E40 AFA5009C */  sw         $a1, 0x9C($sp)
    /* E32F4 150B5E44 AFA600A0 */  sw         $a2, 0xA0($sp)
    /* E32F8 150B5E48 3C180020 */  lui        $t8, (0x200005 >> 16)
    /* E32FC 150B5E4C 240E002B */  addiu      $t6, $zero, 0x2B
    /* E3300 150B5E50 240F4403 */  addiu      $t7, $zero, 0x4403
    /* E3304 150B5E54 37180005 */  ori        $t8, $t8, (0x200005 & 0xFFFF)
    /* E3308 150B5E58 3C190002 */  lui        $t9, (0x20000 >> 16)
    /* E330C 150B5E5C A3AE0045 */  sb         $t6, 0x45($sp)
    /* E3310 150B5E60 A7AF0030 */  sh         $t7, 0x30($sp)
    /* E3314 150B5E64 AFB80028 */  sw         $t8, 0x28($sp)
    /* E3318 150B5E68 0D42B688 */  jal        func_150ADA20
    /* E331C 150B5E6C AFB9002C */   sw        $t9, 0x2C($sp)
    /* E3320 150B5E70 24010007 */  addiu      $at, $zero, 0x7
    /* E3324 150B5E74 0041001B */  divu       $zero, $v0, $at
    /* E3328 150B5E78 00004010 */  mfhi       $t0
    /* E332C 150B5E7C 25090004 */  addiu      $t1, $t0, 0x4
    /* E3330 150B5E80 240A00FF */  addiu      $t2, $zero, 0xFF
    /* E3334 150B5E84 240B00FF */  addiu      $t3, $zero, 0xFF
    /* E3338 150B5E88 240C00FF */  addiu      $t4, $zero, 0xFF
    /* E333C 150B5E8C 240D00FF */  addiu      $t5, $zero, 0xFF
    /* E3340 150B5E90 240E00FF */  addiu      $t6, $zero, 0xFF
    /* E3344 150B5E94 240F00FF */  addiu      $t7, $zero, 0xFF
    /* E3348 150B5E98 241800FF */  addiu      $t8, $zero, 0xFF
    /* E334C 150B5E9C 241900FF */  addiu      $t9, $zero, 0xFF
    /* E3350 150B5EA0 240800FF */  addiu      $t0, $zero, 0xFF
    /* E3354 150B5EA4 A7A90032 */  sh         $t1, 0x32($sp)
    /* E3358 150B5EA8 AFA00034 */  sw         $zero, 0x34($sp)
    /* E335C 150B5EAC AFA00038 */  sw         $zero, 0x38($sp)
    /* E3360 150B5EB0 A3AA003C */  sb         $t2, 0x3C($sp)
    /* E3364 150B5EB4 A3AB003D */  sb         $t3, 0x3D($sp)
    /* E3368 150B5EB8 A3AC003E */  sb         $t4, 0x3E($sp)
    /* E336C 150B5EBC A3AD003F */  sb         $t5, 0x3F($sp)
    /* E3370 150B5EC0 A3AE0040 */  sb         $t6, 0x40($sp)
    /* E3374 150B5EC4 A3AF0041 */  sb         $t7, 0x41($sp)
    /* E3378 150B5EC8 A3B80042 */  sb         $t8, 0x42($sp)
    /* E337C 150B5ECC A3B90043 */  sb         $t9, 0x43($sp)
    /* E3380 150B5ED0 0D42B69A */  jal        func_150ADA68
    /* E3384 150B5ED4 A3A80044 */   sb        $t0, 0x44($sp)
    /* E3388 150B5ED8 3C0143FA */  lui        $at, (0x43FA0000 >> 16)
    /* E338C 150B5EDC 44816000 */  mtc1       $at, $f12
    /* E3390 150B5EE0 8FAA0098 */  lw         $t2, 0x98($sp)
    /* E3394 150B5EE4 27A90058 */  addiu      $t1, $sp, 0x58
    /* E3398 150B5EE8 460C0102 */  mul.s      $f4, $f0, $f12
    /* E339C 150B5EEC 44801000 */  mtc1       $zero, $f2
    /* E33A0 150B5EF0 240E0003 */  addiu      $t6, $zero, 0x3
    /* E33A4 150B5EF4 240F0055 */  addiu      $t7, $zero, 0x55
    /* E33A8 150B5EF8 24180001 */  addiu      $t8, $zero, 0x1
    /* E33AC 150B5EFC 460C2180 */  add.s      $f6, $f4, $f12
    /* E33B0 150B5F00 E7A60054 */  swc1       $f6, 0x54($sp)
    /* E33B4 150B5F04 E7A60050 */  swc1       $f6, 0x50($sp)
    /* E33B8 150B5F08 8D410000 */  lw         $at, 0x0($t2)
    /* E33BC 150B5F0C AD210000 */  sw         $at, 0x0($t1)
    /* E33C0 150B5F10 8D4D0004 */  lw         $t5, 0x4($t2)
    /* E33C4 150B5F14 AD2D0004 */  sw         $t5, 0x4($t1)
    /* E33C8 150B5F18 8D410008 */  lw         $at, 0x8($t2)
    /* E33CC 150B5F1C AD210008 */  sw         $at, 0x8($t1)
    /* E33D0 150B5F20 3C013F80 */  lui        $at, (0x3F800000 >> 16)
    /* E33D4 150B5F24 44814000 */  mtc1       $at, $f8
    /* E33D8 150B5F28 A7AE0046 */  sh         $t6, 0x46($sp)
    /* E33DC 150B5F2C A7AF0048 */  sh         $t7, 0x48($sp)
    /* E33E0 150B5F30 A7B8004A */  sh         $t8, 0x4A($sp)
    /* E33E4 150B5F34 E7A20064 */  swc1       $f2, 0x64($sp)
    /* E33E8 150B5F38 E7A20068 */  swc1       $f2, 0x68($sp)
    /* E33EC 150B5F3C E7A2006C */  swc1       $f2, 0x6C($sp)
    /* E33F0 150B5F40 E7A20070 */  swc1       $f2, 0x70($sp)
    /* E33F4 150B5F44 E7A20074 */  swc1       $f2, 0x74($sp)
    /* E33F8 150B5F48 E7A20078 */  swc1       $f2, 0x78($sp)
    /* E33FC 150B5F4C E7A2007C */  swc1       $f2, 0x7C($sp)
    /* E3400 150B5F50 0D42B688 */  jal        func_150ADA20
    /* E3404 150B5F54 E7A8004C */   swc1      $f8, 0x4C($sp)
    /* E3408 150B5F58 30590001 */  andi       $t9, $v0, 0x1
    /* E340C 150B5F5C 13200003 */  beqz       $t9, .L150B5F6C
    /* E3410 150B5F60 00001825 */   or        $v1, $zero, $zero
    /* E3414 150B5F64 10000001 */  b          .L150B5F6C
    /* E3418 150B5F68 24030040 */   addiu     $v1, $zero, 0x40
  .L150B5F6C:
    /* E341C 150B5F6C 0D42B688 */  jal        func_150ADA20
    /* E3420 150B5F70 AFA30020 */   sw        $v1, 0x20($sp)
    /* E3424 150B5F74 30480001 */  andi       $t0, $v0, 0x1
    /* E3428 150B5F78 11000003 */  beqz       $t0, .L150B5F88
    /* E342C 150B5F7C 8FA30020 */   lw        $v1, 0x20($sp)
    /* E3430 150B5F80 10000002 */  b          .L150B5F8C
    /* E3434 150B5F84 24020080 */   addiu     $v0, $zero, 0x80
  .L150B5F88:
    /* E3438 150B5F88 00001025 */  or         $v0, $zero, $zero
  .L150B5F8C:
    /* E343C 150B5F8C 344C0001 */  ori        $t4, $v0, 0x1
    /* E3440 150B5F90 01835025 */  or         $t2, $t4, $v1
    /* E3444 150B5F94 93AB009F */  lbu        $t3, 0x9F($sp)
    /* E3448 150B5F98 8FA900A0 */  lw         $t1, 0xA0($sp)
    /* E344C 150B5F9C 354DC200 */  ori        $t5, $t2, 0xC200
    /* E3450 150B5FA0 240E0006 */  addiu      $t6, $zero, 0x6
    /* E3454 150B5FA4 240F0006 */  addiu      $t7, $zero, 0x6
    /* E3458 150B5FA8 2418FFFF */  addiu      $t8, $zero, -0x1
    /* E345C 150B5FAC 2419FFFF */  addiu      $t9, $zero, -0x1
    /* E3460 150B5FB0 2408FFFF */  addiu      $t0, $zero, -0x1
    /* E3464 150B5FB4 240C0004 */  addiu      $t4, $zero, 0x4
    /* E3468 150B5FB8 AFAD0080 */  sw         $t5, 0x80($sp)
    /* E346C 150B5FBC A3AE0088 */  sb         $t6, 0x88($sp)
    /* E3470 150B5FC0 A3AF0089 */  sb         $t7, 0x89($sp)
    /* E3474 150B5FC4 A3B8008A */  sb         $t8, 0x8A($sp)
    /* E3478 150B5FC8 A3B9008B */  sb         $t9, 0x8B($sp)
    /* E347C 150B5FCC A3A8008C */  sb         $t0, 0x8C($sp)
    /* E3480 150B5FD0 A3AC008D */  sb         $t4, 0x8D($sp)
    /* E3484 150B5FD4 27A40028 */  addiu      $a0, $sp, 0x28
    /* E3488 150B5FD8 24050001 */  addiu      $a1, $zero, 0x1
    /* E348C 150B5FDC 00003025 */  or         $a2, $zero, $zero
    /* E3490 150B5FE0 00003825 */  or         $a3, $zero, $zero
    /* E3494 150B5FE4 AFAB0010 */  sw         $t3, 0x10($sp)
    /* E3498 150B5FE8 0D44C0A0 */  jal        func_15130280
    /* E349C 150B5FEC AFA90014 */   sw        $t1, 0x14($sp)
    /* E34A0 150B5FF0 8FBF001C */  lw         $ra, 0x1C($sp)
    /* E34A4 150B5FF4 27BD0098 */  addiu      $sp, $sp, 0x98
    /* E34A8 150B5FF8 03E00008 */  jr         $ra
    /* E34AC 150B5FFC 00000000 */   nop
endlabel func_150B5E34

nonmatching func_150B6000, 0xE0

glabel func_150B6000
    /* E34B0 150B6000 27BDFFB0 */  addiu      $sp, $sp, -0x50
    /* E34B4 150B6004 AFBF0034 */  sw         $ra, 0x34($sp)
    /* E34B8 150B6008 AFA50054 */  sw         $a1, 0x54($sp)
    /* E34BC 150B600C AFA60058 */  sw         $a2, 0x58($sp)
    /* E34C0 150B6010 240E0003 */  addiu      $t6, $zero, 0x3
    /* E34C4 150B6014 240FFFFF */  addiu      $t7, $zero, -0x1
    /* E34C8 150B6018 A3AE0048 */  sb         $t6, 0x48($sp)
    /* E34CC 150B601C A3AF0049 */  sb         $t7, 0x49($sp)
    /* E34D0 150B6020 0D42B688 */  jal        func_150ADA20
    /* E34D4 150B6024 AFA40050 */   sw        $a0, 0x50($sp)
    /* E34D8 150B6028 24010009 */  addiu      $at, $zero, 0x9
    /* E34DC 150B602C 0041001B */  divu       $zero, $v0, $at
    /* E34E0 150B6030 8FA40050 */  lw         $a0, 0x50($sp)
    /* E34E4 150B6034 0000C010 */  mfhi       $t8
    /* E34E8 150B6038 27190003 */  addiu      $t9, $t8, 0x3
    /* E34EC 150B603C A7B9004A */  sh         $t9, 0x4A($sp)
    /* E34F0 150B6040 A3A0004C */  sb         $zero, 0x4C($sp)
    /* E34F4 150B6044 C4840000 */  lwc1       $f4, 0x0($a0)
    /* E34F8 150B6048 4600218D */  trunc.w.s  $f6, $f4
    /* E34FC 150B604C 44093000 */  mfc1       $t1, $f6
    /* E3500 150B6050 00000000 */  nop
    /* E3504 150B6054 AFA9003C */  sw         $t1, 0x3C($sp)
    /* E3508 150B6058 C4880004 */  lwc1       $f8, 0x4($a0)
    /* E350C 150B605C 4600428D */  trunc.w.s  $f10, $f8
    /* E3510 150B6060 440B5000 */  mfc1       $t3, $f10
    /* E3514 150B6064 00000000 */  nop
    /* E3518 150B6068 AFAB0040 */  sw         $t3, 0x40($sp)
    /* E351C 150B606C C4900008 */  lwc1       $f16, 0x8($a0)
    /* E3520 150B6070 4600848D */  trunc.w.s  $f18, $f16
    /* E3524 150B6074 440D9000 */  mfc1       $t5, $f18
    /* E3528 150B6078 0D42B688 */  jal        func_150ADA20
    /* E352C 150B607C AFAD0044 */   sw        $t5, 0x44($sp)
    /* E3530 150B6080 240100C9 */  addiu      $at, $zero, 0xC9
    /* E3534 150B6084 0041001B */  divu       $zero, $v0, $at
    /* E3538 150B6088 93B90057 */  lbu        $t9, 0x57($sp)
    /* E353C 150B608C 8FA80058 */  lw         $t0, 0x58($sp)
    /* E3540 150B6090 00003010 */  mfhi       $a2
    /* E3544 150B6094 240E00FF */  addiu      $t6, $zero, 0xFF
    /* E3548 150B6098 240F00FF */  addiu      $t7, $zero, 0xFF
    /* E354C 150B609C 241800FF */  addiu      $t8, $zero, 0xFF
    /* E3550 150B60A0 AFB80018 */  sw         $t8, 0x18($sp)
    /* E3554 150B60A4 AFAF0014 */  sw         $t7, 0x14($sp)
    /* E3558 150B60A8 AFAE0010 */  sw         $t6, 0x10($sp)
    /* E355C 150B60AC 24C60037 */  addiu      $a2, $a2, 0x37
    /* E3560 150B60B0 27A40048 */  addiu      $a0, $sp, 0x48
    /* E3564 150B60B4 27A5003C */  addiu      $a1, $sp, 0x3C
    /* E3568 150B60B8 240700FF */  addiu      $a3, $zero, 0xFF
    /* E356C 150B60BC AFA0001C */  sw         $zero, 0x1C($sp)
    /* E3570 150B60C0 AFA00020 */  sw         $zero, 0x20($sp)
    /* E3574 150B60C4 AFB90024 */  sw         $t9, 0x24($sp)
    /* E3578 150B60C8 0D4580B0 */  jal        func_151602C0
    /* E357C 150B60CC AFA80028 */   sw        $t0, 0x28($sp)
    /* E3580 150B60D0 8FBF0034 */  lw         $ra, 0x34($sp)
    /* E3584 150B60D4 27BD0050 */  addiu      $sp, $sp, 0x50
    /* E3588 150B60D8 03E00008 */  jr         $ra
    /* E358C 150B60DC 00000000 */   nop
endlabel func_150B6000

nonmatching func_150B60E0, 0x30

glabel func_150B60E0
    /* E3590 150B60E0 27BDFFE8 */  addiu      $sp, $sp, -0x18
    /* E3594 150B60E4 AFBF0014 */  sw         $ra, 0x14($sp)
    /* E3598 150B60E8 00803825 */  or         $a3, $a0, $zero
    /* E359C 150B60EC 8CE601D4 */  lw         $a2, 0x1D4($a3)
    /* E35A0 150B60F0 3C04800A */  lui        $a0, %hi(D_8009FC30)
    /* E35A4 150B60F4 2484FC30 */  addiu      $a0, $a0, %lo(D_8009FC30)
    /* E35A8 150B60F8 0D450C4D */  jal        func_15143134
    /* E35AC 150B60FC 24C60140 */   addiu     $a2, $a2, 0x140
    /* E35B0 150B6100 8FBF0014 */  lw         $ra, 0x14($sp)
    /* E35B4 150B6104 27BD0018 */  addiu      $sp, $sp, 0x18
    /* E35B8 150B6108 03E00008 */  jr         $ra
    /* E35BC 150B610C 00000000 */   nop
endlabel func_150B60E0

nonmatching func_150B6110, 0x340

glabel func_150B6110
    /* E35C0 150B6110 27BDFF38 */  addiu      $sp, $sp, -0xC8
    /* E35C4 150B6114 AFB5004C */  sw         $s5, 0x4C($sp)
    /* E35C8 150B6118 0080A825 */  or         $s5, $a0, $zero
    /* E35CC 150B611C AFBF005C */  sw         $ra, 0x5C($sp)
    /* E35D0 150B6120 AFBE0058 */  sw         $fp, 0x58($sp)
    /* E35D4 150B6124 AFB70054 */  sw         $s7, 0x54($sp)
    /* E35D8 150B6128 AFB60050 */  sw         $s6, 0x50($sp)
    /* E35DC 150B612C AFB40048 */  sw         $s4, 0x48($sp)
    /* E35E0 150B6130 AFB30044 */  sw         $s3, 0x44($sp)
    /* E35E4 150B6134 AFB20040 */  sw         $s2, 0x40($sp)
    /* E35E8 150B6138 AFB1003C */  sw         $s1, 0x3C($sp)
    /* E35EC 150B613C AFB00038 */  sw         $s0, 0x38($sp)
    /* E35F0 150B6140 F7B60030 */  sdc1       $f22, 0x30($sp)
    /* E35F4 150B6144 F7B40028 */  sdc1       $f20, 0x28($sp)
    /* E35F8 150B6148 8EB10028 */  lw         $s1, 0x28($s5)
    /* E35FC 150B614C 92A20030 */  lbu        $v0, 0x30($s5)
    /* E3600 150B6150 24010001 */  addiu      $at, $zero, 0x1
    /* E3604 150B6154 922E0014 */  lbu        $t6, 0x14($s1)
    /* E3608 150B6158 A2AE0030 */  sb         $t6, 0x30($s5)
    /* E360C 150B615C 922F0014 */  lbu        $t7, 0x14($s1)
    /* E3610 150B6160 31D800FF */  andi       $t8, $t6, 0xFF
    /* E3614 150B6164 15E10007 */  bne        $t7, $at, .L150B6184
    /* E3618 150B6168 00000000 */   nop
    /* E361C 150B616C 105800AA */  beq        $v0, $t8, .L150B6418
    /* E3620 150B6170 00002025 */   or        $a0, $zero, $zero
    /* E3624 150B6174 0D452538 */  jal        func_151494E0
    /* E3628 150B6178 2405004A */   addiu     $a1, $zero, 0x4A
    /* E362C 150B617C 100000A7 */  b          .L150B641C
    /* E3630 150B6180 8FBF005C */   lw        $ra, 0x5C($sp)
  .L150B6184:
    /* E3634 150B6184 0D42B69A */  jal        func_150ADA68
    /* E3638 150B6188 00000000 */   nop
    /* E363C 150B618C 3C013F80 */  lui        $at, (0x3F800000 >> 16)
    /* E3640 150B6190 4481A000 */  mtc1       $at, $f20
    /* E3644 150B6194 3C01800A */  lui        $at, %hi(D_8009FCBC)
    /* E3648 150B6198 C424FCBC */  lwc1       $f4, %lo(D_8009FCBC)($at)
    /* E364C 150B619C 3C01800A */  lui        $at, %hi(D_8009FCC0)
    /* E3650 150B61A0 C426FCC0 */  lwc1       $f6, %lo(D_8009FCC0)($at)
    /* E3654 150B61A4 3C01800C */  lui        $at, %hi(D_800BE9A4)
    /* E3658 150B61A8 C430E9A4 */  lwc1       $f16, %lo(D_800BE9A4)($at)
    /* E365C 150B61AC 46060202 */  mul.s      $f8, $f0, $f6
    /* E3660 150B61B0 26B20028 */  addiu      $s2, $s5, 0x28
    /* E3664 150B61B4 C6460004 */  lwc1       $f6, 0x4($s2)
    /* E3668 150B61B8 3C01420C */  lui        $at, (0x420C0000 >> 16)
    /* E366C 150B61BC 24190028 */  addiu      $t9, $zero, 0x28
    /* E3670 150B61C0 24080004 */  addiu      $t0, $zero, 0x4
    /* E3674 150B61C4 24090003 */  addiu      $t1, $zero, 0x3
    /* E3678 150B61C8 46082280 */  add.s      $f10, $f4, $f8
    /* E367C 150B61CC 240A0007 */  addiu      $t2, $zero, 0x7
    /* E3680 150B61D0 240B0004 */  addiu      $t3, $zero, 0x4
    /* E3684 150B61D4 240C0003 */  addiu      $t4, $zero, 0x3
    /* E3688 150B61D8 46105482 */  mul.s      $f18, $f10, $f16
    /* E368C 150B61DC 240D007E */  addiu      $t5, $zero, 0x7E
    /* E3690 150B61E0 240E00F9 */  addiu      $t6, $zero, 0xF9
    /* E3694 150B61E4 240F00FF */  addiu      $t7, $zero, 0xFF
    /* E3698 150B61E8 2418007F */  addiu      $t8, $zero, 0x7F
    /* E369C 150B61EC 46123100 */  add.s      $f4, $f6, $f18
    /* E36A0 150B61F0 E6440004 */  swc1       $f4, 0x4($s2)
    /* E36A4 150B61F4 C6480004 */  lwc1       $f8, 0x4($s2)
    /* E36A8 150B61F8 4608A03C */  c.lt.s     $f20, $f8
    /* E36AC 150B61FC 00000000 */  nop
    /* E36B0 150B6200 45020086 */  bc1fl      .L150B641C
    /* E36B4 150B6204 8FBF005C */   lw        $ra, 0x5C($sp)
    /* E36B8 150B6208 44810000 */  mtc1       $at, $f0
    /* E36BC 150B620C 3C014298 */  lui        $at, (0x42980000 >> 16)
    /* E36C0 150B6210 44815000 */  mtc1       $at, $f10
    /* E36C4 150B6214 3C0142CE */  lui        $at, (0x42CE0000 >> 16)
    /* E36C8 150B6218 44818000 */  mtc1       $at, $f16
    /* E36CC 150B621C 3C01800A */  lui        $at, %hi(D_8009FCC4)
    /* E36D0 150B6220 C426FCC4 */  lwc1       $f6, %lo(D_8009FCC4)($at)
    /* E36D4 150B6224 A7B900A0 */  sh         $t9, 0xA0($sp)
    /* E36D8 150B6228 24190080 */  addiu      $t9, $zero, 0x80
    /* E36DC 150B622C E7A0008C */  swc1       $f0, 0x8C($sp)
    /* E36E0 150B6230 E7A00090 */  swc1       $f0, 0x90($sp)
    /* E36E4 150B6234 A7A000A2 */  sh         $zero, 0xA2($sp)
    /* E36E8 150B6238 A7A800A4 */  sh         $t0, 0xA4($sp)
    /* E36EC 150B623C A7A900A6 */  sh         $t1, 0xA6($sp)
    /* E36F0 150B6240 A7AA00A8 */  sh         $t2, 0xA8($sp)
    /* E36F4 150B6244 AFAB00AC */  sw         $t3, 0xAC($sp)
    /* E36F8 150B6248 AFAC00B0 */  sw         $t4, 0xB0($sp)
    /* E36FC 150B624C A3AD00B4 */  sb         $t5, 0xB4($sp)
    /* E3700 150B6250 A3AE00B5 */  sb         $t6, 0xB5($sp)
    /* E3704 150B6254 A3AF00B6 */  sb         $t7, 0xB6($sp)
    /* E3708 150B6258 A3B800B7 */  sb         $t8, 0xB7($sp)
    /* E370C 150B625C A3B900B8 */  sb         $t9, 0xB8($sp)
    /* E3710 150B6260 E7AA0094 */  swc1       $f10, 0x94($sp)
    /* E3714 150B6264 E7B00098 */  swc1       $f16, 0x98($sp)
    /* E3718 150B6268 E7A6009C */  swc1       $f6, 0x9C($sp)
    /* E371C 150B626C 86290008 */  lh         $t1, 0x8($s1)
    /* E3720 150B6270 86280002 */  lh         $t0, 0x2($s1)
    /* E3724 150B6274 3C01800A */  lui        $at, %hi(D_8009FCC8)
    /* E3728 150B6278 C436FCC8 */  lwc1       $f22, %lo(D_8009FCC8)($at)
    /* E372C 150B627C 01095021 */  addu       $t2, $t0, $t1
    /* E3730 150B6280 448A9000 */  mtc1       $t2, $f18
    /* E3734 150B6284 27BE007C */  addiu      $fp, $sp, 0x7C
    /* E3738 150B6288 24170081 */  addiu      $s7, $zero, 0x81
    /* E373C 150B628C 46809120 */  cvt.s.w    $f4, $f18
    /* E3740 150B6290 27B60088 */  addiu      $s6, $sp, 0x88
    /* E3744 150B6294 27B40074 */  addiu      $s4, $sp, 0x74
    /* E3748 150B6298 27B30080 */  addiu      $s3, $sp, 0x80
    /* E374C 150B629C E7A40084 */  swc1       $f4, 0x84($sp)
    /* E3750 150B62A0 862C0008 */  lh         $t4, 0x8($s1)
    /* E3754 150B62A4 862B0002 */  lh         $t3, 0x2($s1)
    /* E3758 150B62A8 016C6821 */  addu       $t5, $t3, $t4
    /* E375C 150B62AC 448D4000 */  mtc1       $t5, $f8
    /* E3760 150B62B0 00000000 */  nop
    /* E3764 150B62B4 468042A0 */  cvt.s.w    $f10, $f8
    /* E3768 150B62B8 E7AA0078 */  swc1       $f10, 0x78($sp)
  .L150B62BC:
    /* E376C 150B62BC 0D42B688 */  jal        func_150ADA20
    /* E3770 150B62C0 00000000 */   nop
    /* E3774 150B62C4 304E00FF */  andi       $t6, $v0, 0xFF
    /* E3778 150B62C8 448E8000 */  mtc1       $t6, $f16
    /* E377C 150B62CC 305000FF */  andi       $s0, $v0, 0xFF
    /* E3780 150B62D0 05C10005 */  bgez       $t6, .L150B62E8
    /* E3784 150B62D4 46808320 */   cvt.s.w   $f12, $f16
    /* E3788 150B62D8 3C014F80 */  lui        $at, (0x4F800000 >> 16)
    /* E378C 150B62DC 44813000 */  mtc1       $at, $f6
    /* E3790 150B62E0 00000000 */  nop
    /* E3794 150B62E4 46066300 */  add.s      $f12, $f12, $f6
  .L150B62E8:
    /* E3798 150B62E8 862F0006 */  lh         $t7, 0x6($s1)
    /* E379C 150B62EC 02603025 */  or         $a2, $s3, $zero
    /* E37A0 150B62F0 02C03825 */  or         $a3, $s6, $zero
    /* E37A4 150B62F4 448F9000 */  mtc1       $t7, $f18
    /* E37A8 150B62F8 0D450DCF */  jal        func_1514373C
    /* E37AC 150B62FC 468093A0 */   cvt.s.w   $f14, $f18
    /* E37B0 150B6300 86380000 */  lh         $t8, 0x0($s1)
    /* E37B4 150B6304 C7A40080 */  lwc1       $f4, 0x80($sp)
    /* E37B8 150B6308 C7A60088 */  lwc1       $f6, 0x88($sp)
    /* E37BC 150B630C 44984000 */  mtc1       $t8, $f8
    /* E37C0 150B6310 00000000 */  nop
    /* E37C4 150B6314 468042A0 */  cvt.s.w    $f10, $f8
    /* E37C8 150B6318 460A2400 */  add.s      $f16, $f4, $f10
    /* E37CC 150B631C E7B00080 */  swc1       $f16, 0x80($sp)
    /* E37D0 150B6320 86390004 */  lh         $t9, 0x4($s1)
    /* E37D4 150B6324 44999000 */  mtc1       $t9, $f18
    /* E37D8 150B6328 00000000 */  nop
    /* E37DC 150B632C 46809220 */  cvt.s.w    $f8, $f18
    /* E37E0 150B6330 46083100 */  add.s      $f4, $f6, $f8
    /* E37E4 150B6334 0D42B688 */  jal        func_150ADA20
    /* E37E8 150B6338 E7A40088 */   swc1      $f4, 0x88($sp)
    /* E37EC 150B633C 0057001B */  divu       $zero, $v0, $s7
    /* E37F0 150B6340 00004010 */  mfhi       $t0
    /* E37F4 150B6344 02088021 */  addu       $s0, $s0, $t0
    /* E37F8 150B6348 26100040 */  addiu      $s0, $s0, 0x40
    /* E37FC 150B634C 320900FF */  andi       $t1, $s0, 0xFF
    /* E3800 150B6350 01208025 */  or         $s0, $t1, $zero
    /* E3804 150B6354 44905000 */  mtc1       $s0, $f10
    /* E3808 150B6358 16E00002 */  bnez       $s7, .L150B6364
    /* E380C 150B635C 00000000 */   nop
    /* E3810 150B6360 0007000D */  break      7
  .L150B6364:
    /* E3814 150B6364 3C014F80 */  lui        $at, (0x4F800000 >> 16)
    /* E3818 150B6368 05210004 */  bgez       $t1, .L150B637C
    /* E381C 150B636C 46805320 */   cvt.s.w   $f12, $f10
    /* E3820 150B6370 44818000 */  mtc1       $at, $f16
    /* E3824 150B6374 00000000 */  nop
    /* E3828 150B6378 46106300 */  add.s      $f12, $f12, $f16
  .L150B637C:
    /* E382C 150B637C 862A0006 */  lh         $t2, 0x6($s1)
    /* E3830 150B6380 02803025 */  or         $a2, $s4, $zero
    /* E3834 150B6384 03C03825 */  or         $a3, $fp, $zero
    /* E3838 150B6388 448A9000 */  mtc1       $t2, $f18
    /* E383C 150B638C 0D450DCF */  jal        func_1514373C
    /* E3840 150B6390 468093A0 */   cvt.s.w   $f14, $f18
    /* E3844 150B6394 862B0000 */  lh         $t3, 0x0($s1)
    /* E3848 150B6398 C7A60074 */  lwc1       $f6, 0x74($sp)
    /* E384C 150B639C C7B0007C */  lwc1       $f16, 0x7C($sp)
    /* E3850 150B63A0 448B4000 */  mtc1       $t3, $f8
    /* E3854 150B63A4 240D0001 */  addiu      $t5, $zero, 0x1
    /* E3858 150B63A8 02602025 */  or         $a0, $s3, $zero
    /* E385C 150B63AC 46804120 */  cvt.s.w    $f4, $f8
    /* E3860 150B63B0 02802825 */  or         $a1, $s4, $zero
    /* E3864 150B63B4 24060004 */  addiu      $a2, $zero, 0x4
    /* E3868 150B63B8 27A7008C */  addiu      $a3, $sp, 0x8C
    /* E386C 150B63BC 46043280 */  add.s      $f10, $f6, $f4
    /* E3870 150B63C0 E7AA0074 */  swc1       $f10, 0x74($sp)
    /* E3874 150B63C4 862C0004 */  lh         $t4, 0x4($s1)
    /* E3878 150B63C8 AFAD0014 */  sw         $t5, 0x14($sp)
    /* E387C 150B63CC E7B60010 */  swc1       $f22, 0x10($sp)
    /* E3880 150B63D0 448C9000 */  mtc1       $t4, $f18
    /* E3884 150B63D4 00000000 */  nop
    /* E3888 150B63D8 46809220 */  cvt.s.w    $f8, $f18
    /* E388C 150B63DC 46088180 */  add.s      $f6, $f16, $f8
    /* E3890 150B63E0 E7A6007C */  swc1       $f6, 0x7C($sp)
    /* E3894 150B63E4 92AE000C */  lbu        $t6, 0xC($s5)
    /* E3898 150B63E8 AFAE0018 */  sw         $t6, 0x18($sp)
    /* E389C 150B63EC 92AF0001 */  lbu        $t7, 0x1($s5)
    /* E38A0 150B63F0 0D441BE6 */  jal        func_15106F98
    /* E38A4 150B63F4 AFAF001C */   sw        $t7, 0x1C($sp)
    /* E38A8 150B63F8 C6440004 */  lwc1       $f4, 0x4($s2)
    /* E38AC 150B63FC 46142281 */  sub.s      $f10, $f4, $f20
    /* E38B0 150B6400 E64A0004 */  swc1       $f10, 0x4($s2)
    /* E38B4 150B6404 C6520004 */  lwc1       $f18, 0x4($s2)
    /* E38B8 150B6408 4612A03C */  c.lt.s     $f20, $f18
    /* E38BC 150B640C 00000000 */  nop
    /* E38C0 150B6410 4501FFAA */  bc1t       .L150B62BC
    /* E38C4 150B6414 00000000 */   nop
  .L150B6418:
    /* E38C8 150B6418 8FBF005C */  lw         $ra, 0x5C($sp)
  .L150B641C:
    /* E38CC 150B641C D7B40028 */  ldc1       $f20, 0x28($sp)
    /* E38D0 150B6420 D7B60030 */  ldc1       $f22, 0x30($sp)
    /* E38D4 150B6424 8FB00038 */  lw         $s0, 0x38($sp)
    /* E38D8 150B6428 8FB1003C */  lw         $s1, 0x3C($sp)
    /* E38DC 150B642C 8FB20040 */  lw         $s2, 0x40($sp)
    /* E38E0 150B6430 8FB30044 */  lw         $s3, 0x44($sp)
    /* E38E4 150B6434 8FB40048 */  lw         $s4, 0x48($sp)
    /* E38E8 150B6438 8FB5004C */  lw         $s5, 0x4C($sp)
    /* E38EC 150B643C 8FB60050 */  lw         $s6, 0x50($sp)
    /* E38F0 150B6440 8FB70054 */  lw         $s7, 0x54($sp)
    /* E38F4 150B6444 8FBE0058 */  lw         $fp, 0x58($sp)
    /* E38F8 150B6448 03E00008 */  jr         $ra
    /* E38FC 150B644C 27BD00C8 */   addiu     $sp, $sp, 0xC8
endlabel func_150B6110

nonmatching func_150B6450, 0x3C

glabel func_150B6450
    /* E3900 150B6450 27BDFFE8 */  addiu      $sp, $sp, -0x18
    /* E3904 150B6454 AFA60020 */  sw         $a2, 0x20($sp)
    /* E3908 150B6458 30CE00FF */  andi       $t6, $a2, 0xFF
    /* E390C 150B645C 01C03025 */  or         $a2, $t6, $zero
    /* E3910 150B6460 AFBF0014 */  sw         $ra, 0x14($sp)
    /* E3914 150B6464 AFA5001C */  sw         $a1, 0x1C($sp)
    /* E3918 150B6468 2401004A */  addiu      $at, $zero, 0x4A
    /* E391C 150B646C 54C10004 */  bnel       $a2, $at, .L150B6480
    /* E3920 150B6470 8FBF0014 */   lw        $ra, 0x14($sp)
    /* E3924 150B6474 0D45A5CB */  jal        func_1516972C
    /* E3928 150B6478 00000000 */   nop
    /* E392C 150B647C 8FBF0014 */  lw         $ra, 0x14($sp)
  .L150B6480:
    /* E3930 150B6480 27BD0018 */  addiu      $sp, $sp, 0x18
    /* E3934 150B6484 03E00008 */  jr         $ra
    /* E3938 150B6488 00000000 */   nop
endlabel func_150B6450

nonmatching func_150B648C, 0x250

glabel func_150B648C
    /* E393C 150B648C 27BDFF90 */  addiu      $sp, $sp, -0x70
    /* E3940 150B6490 AFB00018 */  sw         $s0, 0x18($sp)
    /* E3944 150B6494 309000FF */  andi       $s0, $a0, 0xFF
    /* E3948 150B6498 AFBF001C */  sw         $ra, 0x1C($sp)
    /* E394C 150B649C AFA40070 */  sw         $a0, 0x70($sp)
    /* E3950 150B64A0 16000027 */  bnez       $s0, .L150B6540
    /* E3954 150B64A4 02001025 */   or        $v0, $s0, $zero
    /* E3958 150B64A8 0D4508F6 */  jal        func_151423D8
    /* E395C 150B64AC 240400AA */   addiu     $a0, $zero, 0xAA
    /* E3960 150B64B0 3C014120 */  lui        $at, (0x41200000 >> 16)
    /* E3964 150B64B4 44812000 */  mtc1       $at, $f4
    /* E3968 150B64B8 3C014040 */  lui        $at, (0x40400000 >> 16)
    /* E396C 150B64BC 44814000 */  mtc1       $at, $f8
    /* E3970 150B64C0 46040182 */  mul.s      $f6, $f0, $f4
    /* E3974 150B64C4 240400EA */  addiu      $a0, $zero, 0xEA
    /* E3978 150B64C8 E7A80034 */  swc1       $f8, 0x34($sp)
    /* E397C 150B64CC 0D4508F6 */  jal        func_151423D8
    /* E3980 150B64D0 E7A60030 */   swc1      $f6, 0x30($sp)
    /* E3984 150B64D4 3C014120 */  lui        $at, (0x41200000 >> 16)
    /* E3988 150B64D8 44815000 */  mtc1       $at, $f10
    /* E398C 150B64DC 240400AA */  addiu      $a0, $zero, 0xAA
    /* E3990 150B64E0 460A0402 */  mul.s      $f16, $f0, $f10
    /* E3994 150B64E4 0D4508F6 */  jal        func_151423D8
    /* E3998 150B64E8 E7B00038 */   swc1      $f16, 0x38($sp)
    /* E399C 150B64EC 3C01800A */  lui        $at, %hi(D_8009FCCC)
    /* E39A0 150B64F0 C432FCCC */  lwc1       $f18, %lo(D_8009FCCC)($at)
    /* E39A4 150B64F4 3C014316 */  lui        $at, (0x43160000 >> 16)
    /* E39A8 150B64F8 44812000 */  mtc1       $at, $f4
    /* E39AC 150B64FC 3C01800A */  lui        $at, %hi(D_8009FCD0)
    /* E39B0 150B6500 C42AFCD0 */  lwc1       $f10, %lo(D_8009FCD0)($at)
    /* E39B4 150B6504 46040182 */  mul.s      $f6, $f0, $f4
    /* E39B8 150B6508 240400EA */  addiu      $a0, $zero, 0xEA
    /* E39BC 150B650C E7AA0028 */  swc1       $f10, 0x28($sp)
    /* E39C0 150B6510 46069201 */  sub.s      $f8, $f18, $f6
    /* E39C4 150B6514 0D4508F6 */  jal        func_151423D8
    /* E39C8 150B6518 E7A80024 */   swc1      $f8, 0x24($sp)
    /* E39CC 150B651C 3C01800A */  lui        $at, %hi(D_8009FCD4)
    /* E39D0 150B6520 C430FCD4 */  lwc1       $f16, %lo(D_8009FCD4)($at)
    /* E39D4 150B6524 3C014316 */  lui        $at, (0x43160000 >> 16)
    /* E39D8 150B6528 44812000 */  mtc1       $at, $f4
    /* E39DC 150B652C 00000000 */  nop
    /* E39E0 150B6530 46040482 */  mul.s      $f18, $f0, $f4
    /* E39E4 150B6534 46128181 */  sub.s      $f6, $f16, $f18
    /* E39E8 150B6538 1000002A */  b          .L150B65E4
    /* E39EC 150B653C E7A6002C */   swc1      $f6, 0x2C($sp)
  .L150B6540:
    /* E39F0 150B6540 24010001 */  addiu      $at, $zero, 0x1
    /* E39F4 150B6544 14410015 */  bne        $v0, $at, .L150B659C
    /* E39F8 150B6548 24040018 */   addiu     $a0, $zero, 0x18
    /* E39FC 150B654C 3C064115 */  lui        $a2, (0x41159999 >> 16)
    /* E3A00 150B6550 34C69999 */  ori        $a2, $a2, (0x41159999 & 0xFFFF)
    /* E3A04 150B6554 2404FFBB */  addiu      $a0, $zero, -0x45
    /* E3A08 150B6558 2405001C */  addiu      $a1, $zero, 0x1C
    /* E3A0C 150B655C 0D450DE5 */  jal        func_15143794
    /* E3A10 150B6560 27A70030 */   addiu     $a3, $sp, 0x30
    /* E3A14 150B6564 00107880 */  sll        $t7, $s0, 2
    /* E3A18 150B6568 01F07823 */  subu       $t7, $t7, $s0
    /* E3A1C 150B656C 3C18800A */  lui        $t8, %hi(D_8009FC3C)
    /* E3A20 150B6570 2718FC3C */  addiu      $t8, $t8, %lo(D_8009FC3C)
    /* E3A24 150B6574 000F7880 */  sll        $t7, $t7, 2
    /* E3A28 150B6578 01F8C821 */  addu       $t9, $t7, $t8
    /* E3A2C 150B657C 8F210000 */  lw         $at, 0x0($t9)
    /* E3A30 150B6580 27AE0024 */  addiu      $t6, $sp, 0x24
    /* E3A34 150B6584 ADC10000 */  sw         $at, 0x0($t6)
    /* E3A38 150B6588 8F290004 */  lw         $t1, 0x4($t9)
    /* E3A3C 150B658C ADC90004 */  sw         $t1, 0x4($t6)
    /* E3A40 150B6590 8F210008 */  lw         $at, 0x8($t9)
    /* E3A44 150B6594 10000013 */  b          .L150B65E4
    /* E3A48 150B6598 ADC10008 */   sw        $at, 0x8($t6)
  .L150B659C:
    /* E3A4C 150B659C 3C064115 */  lui        $a2, (0x41159999 >> 16)
    /* E3A50 150B65A0 34C69999 */  ori        $a2, $a2, (0x41159999 & 0xFFFF)
    /* E3A54 150B65A4 2405000F */  addiu      $a1, $zero, 0xF
    /* E3A58 150B65A8 0D450DE5 */  jal        func_15143794
    /* E3A5C 150B65AC 27A70030 */   addiu     $a3, $sp, 0x30
    /* E3A60 150B65B0 00105880 */  sll        $t3, $s0, 2
    /* E3A64 150B65B4 01705823 */  subu       $t3, $t3, $s0
    /* E3A68 150B65B8 3C0C800A */  lui        $t4, %hi(D_8009FC3C)
    /* E3A6C 150B65BC 258CFC3C */  addiu      $t4, $t4, %lo(D_8009FC3C)
    /* E3A70 150B65C0 000B5880 */  sll        $t3, $t3, 2
    /* E3A74 150B65C4 016C6821 */  addu       $t5, $t3, $t4
    /* E3A78 150B65C8 8DA10000 */  lw         $at, 0x0($t5)
    /* E3A7C 150B65CC 27AA0024 */  addiu      $t2, $sp, 0x24
    /* E3A80 150B65D0 AD410000 */  sw         $at, 0x0($t2)
    /* E3A84 150B65D4 8DB80004 */  lw         $t8, 0x4($t5)
    /* E3A88 150B65D8 AD580004 */  sw         $t8, 0x4($t2)
    /* E3A8C 150B65DC 8DA10008 */  lw         $at, 0x8($t5)
    /* E3A90 150B65E0 AD410008 */  sw         $at, 0x8($t2)
  .L150B65E4:
    /* E3A94 150B65E4 00101080 */  sll        $v0, $s0, 2
    /* E3A98 150B65E8 3C01800A */  lui        $at, %hi(D_8009FC60)
    /* E3A9C 150B65EC 00220821 */  addu       $at, $at, $v0
    /* E3AA0 150B65F0 C428FC60 */  lwc1       $f8, %lo(D_8009FC60)($at)
    /* E3AA4 150B65F4 3C01800A */  lui        $at, %hi(D_8009FCD8)
    /* E3AA8 150B65F8 C42AFCD8 */  lwc1       $f10, %lo(D_8009FCD8)($at)
    /* E3AAC 150B65FC 3C01800A */  lui        $at, %hi(D_8009FCDC)
    /* E3AB0 150B6600 C424FCDC */  lwc1       $f4, %lo(D_8009FCDC)($at)
    /* E3AB4 150B6604 3C01800A */  lui        $at, %hi(D_8009FCE0)
    /* E3AB8 150B6608 C430FCE0 */  lwc1       $f16, %lo(D_8009FCE0)($at)
    /* E3ABC 150B660C 3C01800A */  lui        $at, %hi(D_8009FC6C)
    /* E3AC0 150B6610 00220821 */  addu       $at, $at, $v0
    /* E3AC4 150B6614 C432FC6C */  lwc1       $f18, %lo(D_8009FC6C)($at)
    /* E3AC8 150B6618 24080004 */  addiu      $t0, $zero, 0x4
    /* E3ACC 150B661C 240E0006 */  addiu      $t6, $zero, 0x6
    /* E3AD0 150B6620 3C01800A */  lui        $at, %hi(D_8009FC78)
    /* E3AD4 150B6624 A3A80040 */  sb         $t0, 0x40($sp)
    /* E3AD8 150B6628 A3AE004C */  sb         $t6, 0x4C($sp)
    /* E3ADC 150B662C 00220821 */  addu       $at, $at, $v0
    /* E3AE0 150B6630 C426FC78 */  lwc1       $f6, %lo(D_8009FC78)($at)
    /* E3AE4 150B6634 3C0E800A */  lui        $t6, %hi(D_8009FC84)
    /* E3AE8 150B6638 00104040 */  sll        $t0, $s0, 1
    /* E3AEC 150B663C 01C87021 */  addu       $t6, $t6, $t0
    /* E3AF0 150B6640 3C01800A */  lui        $at, %hi(D_8009FCE4)
    /* E3AF4 150B6644 E7A8003C */  swc1       $f8, 0x3C($sp)
    /* E3AF8 150B6648 85CEFC84 */  lh         $t6, %lo(D_8009FC84)($t6)
    /* E3AFC 150B664C C428FCE4 */  lwc1       $f8, %lo(D_8009FCE4)($at)
    /* E3B00 150B6650 3C06800A */  lui        $a2, %hi(D_8009FC8E)
    /* E3B04 150B6654 24190080 */  addiu      $t9, $zero, 0x80
    /* E3B08 150B6658 240900FF */  addiu      $t1, $zero, 0xFF
    /* E3B0C 150B665C 240B0002 */  addiu      $t3, $zero, 0x2
    /* E3B10 150B6660 240C0005 */  addiu      $t4, $zero, 0x5
    /* E3B14 150B6664 240F0005 */  addiu      $t7, $zero, 0x5
    /* E3B18 150B6668 240A0033 */  addiu      $t2, $zero, 0x33
    /* E3B1C 150B666C 240D0003 */  addiu      $t5, $zero, 0x3
    /* E3B20 150B6670 24180055 */  addiu      $t8, $zero, 0x55
    /* E3B24 150B6674 00C23021 */  addu       $a2, $a2, $v0
    /* E3B28 150B6678 A3B90054 */  sb         $t9, 0x54($sp)
    /* E3B2C 150B667C A7A90056 */  sh         $t1, 0x56($sp)
    /* E3B30 150B6680 A3AB0060 */  sb         $t3, 0x60($sp)
    /* E3B34 150B6684 A3AC0061 */  sb         $t4, 0x61($sp)
    /* E3B38 150B6688 A3AF0062 */  sb         $t7, 0x62($sp)
    /* E3B3C 150B668C A3AA0063 */  sb         $t2, 0x63($sp)
    /* E3B40 150B6690 A3AD0064 */  sb         $t5, 0x64($sp)
    /* E3B44 150B6694 A3B80065 */  sb         $t8, 0x65($sp)
    /* E3B48 150B6698 A3A00068 */  sb         $zero, 0x68($sp)
    /* E3B4C 150B669C 84C6FC8E */  lh         $a2, %lo(D_8009FC8E)($a2)
    /* E3B50 150B66A0 27A40030 */  addiu      $a0, $sp, 0x30
    /* E3B54 150B66A4 27A50024 */  addiu      $a1, $sp, 0x24
    /* E3B58 150B66A8 E7AA0044 */  swc1       $f10, 0x44($sp)
    /* E3B5C 150B66AC E7A40048 */  swc1       $f4, 0x48($sp)
    /* E3B60 150B66B0 E7B00050 */  swc1       $f16, 0x50($sp)
    /* E3B64 150B66B4 E7B20058 */  swc1       $f18, 0x58($sp)
    /* E3B68 150B66B8 E7A6005C */  swc1       $f6, 0x5C($sp)
    /* E3B6C 150B66BC A7AE0066 */  sh         $t6, 0x66($sp)
    /* E3B70 150B66C0 0D42CFD7 */  jal        func_150B3F5C
    /* E3B74 150B66C4 E7A8006C */   swc1      $f8, 0x6C($sp)
    /* E3B78 150B66C8 8FBF001C */  lw         $ra, 0x1C($sp)
    /* E3B7C 150B66CC 8FB00018 */  lw         $s0, 0x18($sp)
    /* E3B80 150B66D0 27BD0070 */  addiu      $sp, $sp, 0x70
    /* E3B84 150B66D4 03E00008 */  jr         $ra
    /* E3B88 150B66D8 00000000 */   nop
endlabel func_150B648C

nonmatching func_150B66DC, 0x78

glabel func_150B66DC
    /* E3B8C 150B66DC 8C820018 */  lw         $v0, 0x18($a0)
    /* E3B90 150B66E0 24010001 */  addiu      $at, $zero, 0x1
    /* E3B94 150B66E4 90430068 */  lbu        $v1, 0x68($v0)
    /* E3B98 150B66E8 24020001 */  addiu      $v0, $zero, 0x1
    /* E3B9C 150B66EC 2463FFF1 */  addiu      $v1, $v1, -0xF
    /* E3BA0 150B66F0 50600008 */  beql       $v1, $zero, .L150B6714
    /* E3BA4 150B66F4 8C8F0014 */   lw        $t7, 0x14($a0)
    /* E3BA8 150B66F8 10610009 */  beq        $v1, $at, .L150B6720
    /* E3BAC 150B66FC 24010002 */   addiu     $at, $zero, 0x2
    /* E3BB0 150B6700 5061000E */  beql       $v1, $at, .L150B673C
    /* E3BB4 150B6704 8C890014 */   lw        $t1, 0x14($a0)
    /* E3BB8 150B6708 1000000C */  b          .L150B673C
    /* E3BBC 150B670C 8C890014 */   lw        $t1, 0x14($a0)
    /* E3BC0 150B6710 8C8F0014 */  lw         $t7, 0x14($a0)
  .L150B6714:
    /* E3BC4 150B6714 240E0001 */  addiu      $t6, $zero, 0x1
    /* E3BC8 150B6718 1000000C */  b          .L150B674C
    /* E3BCC 150B671C A1EE0009 */   sb        $t6, 0x9($t7)
  .L150B6720:
    /* E3BD0 150B6720 8C980014 */  lw         $t8, 0x14($a0)
    /* E3BD4 150B6724 24190014 */  addiu      $t9, $zero, 0x14
    /* E3BD8 150B6728 A3000009 */  sb         $zero, 0x9($t8)
    /* E3BDC 150B672C 8C880014 */  lw         $t0, 0x14($a0)
    /* E3BE0 150B6730 10000006 */  b          .L150B674C
    /* E3BE4 150B6734 A119002F */   sb        $t9, 0x2F($t0)
    /* E3BE8 150B6738 8C890014 */  lw         $t1, 0x14($a0)
  .L150B673C:
    /* E3BEC 150B673C 240A0028 */  addiu      $t2, $zero, 0x28
    /* E3BF0 150B6740 A1200009 */  sb         $zero, 0x9($t1)
    /* E3BF4 150B6744 8C8B0014 */  lw         $t3, 0x14($a0)
    /* E3BF8 150B6748 A16A002F */  sb         $t2, 0x2F($t3)
  .L150B674C:
    /* E3BFC 150B674C 03E00008 */  jr         $ra
    /* E3C00 150B6750 00000000 */   nop
endlabel func_150B66DC

nonmatching func_150B6754, 0x84

glabel func_150B6754
    /* E3C04 150B6754 27BDFFD0 */  addiu      $sp, $sp, -0x30
    /* E3C08 150B6758 AFBF0024 */  sw         $ra, 0x24($sp)
    /* E3C0C 150B675C AFA40030 */  sw         $a0, 0x30($sp)
    /* E3C10 150B6760 AFA50034 */  sw         $a1, 0x34($sp)
    /* E3C14 150B6764 0D42B688 */  jal        func_150ADA20
    /* E3C18 150B6768 00000000 */   nop
    /* E3C1C 150B676C 0D42B688 */  jal        func_150ADA20
    /* E3C20 150B6770 AFA20028 */   sw        $v0, 0x28($sp)
    /* E3C24 150B6774 8FA70028 */  lw         $a3, 0x28($sp)
    /* E3C28 150B6778 24010038 */  addiu      $at, $zero, 0x38
    /* E3C2C 150B677C 93A80033 */  lbu        $t0, 0x33($sp)
    /* E3C30 150B6780 00E1001B */  divu       $zero, $a3, $at
    /* E3C34 150B6784 00007010 */  mfhi       $t6
    /* E3C38 150B6788 2401000B */  addiu      $at, $zero, 0xB
    /* E3C3C 150B678C 8FA90034 */  lw         $t1, 0x34($sp)
    /* E3C40 150B6790 0041001B */  divu       $zero, $v0, $at
    /* E3C44 150B6794 0000C010 */  mfhi       $t8
    /* E3C48 150B6798 25C700C8 */  addiu      $a3, $t6, 0xC8
    /* E3C4C 150B679C 30EF00FF */  andi       $t7, $a3, 0xFF
    /* E3C50 150B67A0 2719000F */  addiu      $t9, $t8, 0xF
    /* E3C54 150B67A4 AFB90010 */  sw         $t9, 0x10($sp)
    /* E3C58 150B67A8 01E03825 */  or         $a3, $t7, $zero
    /* E3C5C 150B67AC 240400CC */  addiu      $a0, $zero, 0xCC
    /* E3C60 150B67B0 240500CC */  addiu      $a1, $zero, 0xCC
    /* E3C64 150B67B4 240600FF */  addiu      $a2, $zero, 0xFF
    /* E3C68 150B67B8 AFA00014 */  sw         $zero, 0x14($sp)
    /* E3C6C 150B67BC AFA80018 */  sw         $t0, 0x18($sp)
    /* E3C70 150B67C0 0D46099C */  jal        func_15182670
    /* E3C74 150B67C4 AFA9001C */   sw        $t1, 0x1C($sp)
    /* E3C78 150B67C8 8FBF0024 */  lw         $ra, 0x24($sp)
    /* E3C7C 150B67CC 27BD0030 */  addiu      $sp, $sp, 0x30
    /* E3C80 150B67D0 03E00008 */  jr         $ra
    /* E3C84 150B67D4 00000000 */   nop
endlabel func_150B6754
    /* E3C88 150B67D8 00000000 */  nop
    /* E3C8C 150B67DC 00000000 */  nop
