.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching func_150C5370, 0xC0

glabel func_150C5370
    /* F2820 150C5370 27BDFFD0 */  addiu      $sp, $sp, -0x30
    /* F2824 150C5374 AFBF001C */  sw         $ra, 0x1C($sp)
    /* F2828 150C5378 AFA40030 */  sw         $a0, 0x30($sp)
    /* F282C 150C537C AFA50034 */  sw         $a1, 0x34($sp)
    /* F2830 150C5380 8FA60034 */  lw         $a2, 0x34($sp)
    /* F2834 150C5384 240E00FF */  addiu      $t6, $zero, 0xFF
    /* F2838 150C5388 240F0001 */  addiu      $t7, $zero, 0x1
    /* F283C 150C538C AFAF0014 */  sw         $t7, 0x14($sp)
    /* F2840 150C5390 AFAE0010 */  sw         $t6, 0x10($sp)
    /* F2844 150C5394 24040046 */  addiu      $a0, $zero, 0x46
    /* F2848 150C5398 00002825 */  or         $a1, $zero, $zero
    /* F284C 150C539C 24070001 */  addiu      $a3, $zero, 0x1
    /* F2850 150C53A0 0D459E9A */  jal        func_15167A68
    /* F2854 150C53A4 24C600C8 */   addiu     $a2, $a2, 0xC8
    /* F2858 150C53A8 14400003 */  bnez       $v0, .L150C53B8
    /* F285C 150C53AC 00401825 */   or        $v1, $v0, $zero
    /* F2860 150C53B0 1000001B */  b          .L150C5420
    /* F2864 150C53B4 00001025 */   or        $v0, $zero, $zero
  .L150C53B8:
    /* F2868 150C53B8 24640018 */  addiu      $a0, $v1, 0x18
    /* F286C 150C53BC 8FA50030 */  lw         $a1, 0x30($sp)
    /* F2870 150C53C0 24060024 */  addiu      $a2, $zero, 0x24
    /* F2874 150C53C4 0C008BB0 */  jal        memcpy
    /* F2878 150C53C8 AFA3002C */   sw        $v1, 0x2C($sp)
    /* F287C 150C53CC 8FA3002C */  lw         $v1, 0x2C($sp)
    /* F2880 150C53D0 C4640018 */  lwc1       $f4, 0x18($v1)
    /* F2884 150C53D4 C4660024 */  lwc1       $f6, 0x24($v1)
    /* F2888 150C53D8 27A40020 */  addiu      $a0, $sp, 0x20
    /* F288C 150C53DC 46062201 */  sub.s      $f8, $f4, $f6
    /* F2890 150C53E0 E7A80020 */  swc1       $f8, 0x20($sp)
    /* F2894 150C53E4 C4700028 */  lwc1       $f16, 0x28($v1)
    /* F2898 150C53E8 C46A001C */  lwc1       $f10, 0x1C($v1)
    /* F289C 150C53EC 46105481 */  sub.s      $f18, $f10, $f16
    /* F28A0 150C53F0 E7B20024 */  swc1       $f18, 0x24($sp)
    /* F28A4 150C53F4 C466002C */  lwc1       $f6, 0x2C($v1)
    /* F28A8 150C53F8 C4640020 */  lwc1       $f4, 0x20($v1)
    /* F28AC 150C53FC 46062201 */  sub.s      $f8, $f4, $f6
    /* F28B0 150C5400 0D450F99 */  jal        func_15143E64
    /* F28B4 150C5404 E7A80028 */   swc1      $f8, 0x28($sp)
    /* F28B8 150C5408 8FA3002C */  lw         $v1, 0x2C($sp)
    /* F28BC 150C540C 24180001 */  addiu      $t8, $zero, 0x1
    /* F28C0 150C5410 E46000C0 */  swc1       $f0, 0xC0($v1)
    /* F28C4 150C5414 AC780010 */  sw         $t8, 0x10($v1)
    /* F28C8 150C5418 AC600014 */  sw         $zero, 0x14($v1)
    /* F28CC 150C541C 00601025 */  or         $v0, $v1, $zero
  .L150C5420:
    /* F28D0 150C5420 8FBF001C */  lw         $ra, 0x1C($sp)
    /* F28D4 150C5424 27BD0030 */  addiu      $sp, $sp, 0x30
    /* F28D8 150C5428 03E00008 */  jr         $ra
    /* F28DC 150C542C 00000000 */   nop
endlabel func_150C5370

nonmatching func_150C5430, 0x20

glabel func_150C5430
    /* F28E0 150C5430 27BDFFE8 */  addiu      $sp, $sp, -0x18
    /* F28E4 150C5434 AFBF0014 */  sw         $ra, 0x14($sp)
    /* F28E8 150C5438 0D45A601 */  jal        func_15169804
    /* F28EC 150C543C 00000000 */   nop
    /* F28F0 150C5440 8FBF0014 */  lw         $ra, 0x14($sp)
    /* F28F4 150C5444 27BD0018 */  addiu      $sp, $sp, 0x18
    /* F28F8 150C5448 03E00008 */  jr         $ra
    /* F28FC 150C544C 00000000 */   nop
endlabel func_150C5430

nonmatching func_150C5450, 0x20

glabel func_150C5450
    /* F2900 150C5450 27BDFFE8 */  addiu      $sp, $sp, -0x18
    /* F2904 150C5454 AFBF0014 */  sw         $ra, 0x14($sp)
    /* F2908 150C5458 0D45A609 */  jal        func_15169824
    /* F290C 150C545C 00000000 */   nop
    /* F2910 150C5460 8FBF0014 */  lw         $ra, 0x14($sp)
    /* F2914 150C5464 27BD0018 */  addiu      $sp, $sp, 0x18
    /* F2918 150C5468 03E00008 */  jr         $ra
    /* F291C 150C546C 00000000 */   nop
endlabel func_150C5450

nonmatching func_150C5470, 0x50

glabel func_150C5470
    /* F2920 150C5470 27BDFFE8 */  addiu      $sp, $sp, -0x18
    /* F2924 150C5474 AFBF0014 */  sw         $ra, 0x14($sp)
    /* F2928 150C5478 90820038 */  lbu        $v0, 0x38($a0)
    /* F292C 150C547C 3C198009 */  lui        $t9, %hi(D_800887B8)
    /* F2930 150C5480 04410003 */  bgez       $v0, .L150C5490
    /* F2934 150C5484 28410002 */   slti      $at, $v0, 0x2
    /* F2938 150C5488 10000004 */  b          .L150C549C
    /* F293C 150C548C 00001025 */   or        $v0, $zero, $zero
  .L150C5490:
    /* F2940 150C5490 54200003 */  bnel       $at, $zero, .L150C54A0
    /* F2944 150C5494 00027080 */   sll       $t6, $v0, 2
    /* F2948 150C5498 00001025 */  or         $v0, $zero, $zero
  .L150C549C:
    /* F294C 150C549C 00027080 */  sll        $t6, $v0, 2
  .L150C54A0:
    /* F2950 150C54A0 032EC821 */  addu       $t9, $t9, $t6
    /* F2954 150C54A4 8F3987B8 */  lw         $t9, %lo(D_800887B8)($t9)
    /* F2958 150C54A8 0320F809 */  jalr       $t9
    /* F295C 150C54AC 00000000 */   nop
    /* F2960 150C54B0 8FBF0014 */  lw         $ra, 0x14($sp)
    /* F2964 150C54B4 27BD0018 */  addiu      $sp, $sp, 0x18
    /* F2968 150C54B8 03E00008 */  jr         $ra
    /* F296C 150C54BC 00000000 */   nop
endlabel func_150C5470

nonmatching func_150C54C0, 0x50

glabel func_150C54C0
    /* F2970 150C54C0 27BDFFE8 */  addiu      $sp, $sp, -0x18
    /* F2974 150C54C4 AFBF0014 */  sw         $ra, 0x14($sp)
    /* F2978 150C54C8 90820038 */  lbu        $v0, 0x38($a0)
    /* F297C 150C54CC 3C198009 */  lui        $t9, %hi(D_800887C0)
    /* F2980 150C54D0 04410003 */  bgez       $v0, .L150C54E0
    /* F2984 150C54D4 28410002 */   slti      $at, $v0, 0x2
    /* F2988 150C54D8 10000004 */  b          .L150C54EC
    /* F298C 150C54DC 00001025 */   or        $v0, $zero, $zero
  .L150C54E0:
    /* F2990 150C54E0 54200003 */  bnel       $at, $zero, .L150C54F0
    /* F2994 150C54E4 00027080 */   sll       $t6, $v0, 2
    /* F2998 150C54E8 00001025 */  or         $v0, $zero, $zero
  .L150C54EC:
    /* F299C 150C54EC 00027080 */  sll        $t6, $v0, 2
  .L150C54F0:
    /* F29A0 150C54F0 032EC821 */  addu       $t9, $t9, $t6
    /* F29A4 150C54F4 8F3987C0 */  lw         $t9, %lo(D_800887C0)($t9)
    /* F29A8 150C54F8 0320F809 */  jalr       $t9
    /* F29AC 150C54FC 00000000 */   nop
    /* F29B0 150C5500 8FBF0014 */  lw         $ra, 0x14($sp)
    /* F29B4 150C5504 27BD0018 */  addiu      $sp, $sp, 0x18
    /* F29B8 150C5508 03E00008 */  jr         $ra
    /* F29BC 150C550C 00000000 */   nop
endlabel func_150C54C0

nonmatching func_150C5510, 0x2C

glabel func_150C5510
    /* F29C0 150C5510 27BDFFE8 */  addiu      $sp, $sp, -0x18
    /* F29C4 150C5514 AFBF0014 */  sw         $ra, 0x14($sp)
    /* F29C8 150C5518 8C8500C8 */  lw         $a1, 0xC8($a0)
    /* F29CC 150C551C 0D453B7C */  jal        func_1514EDF0
    /* F29D0 150C5520 AFA40018 */   sw        $a0, 0x18($sp)
    /* F29D4 150C5524 0D43150C */  jal        func_150C5430
    /* F29D8 150C5528 8FA40018 */   lw        $a0, 0x18($sp)
    /* F29DC 150C552C 8FBF0014 */  lw         $ra, 0x14($sp)
    /* F29E0 150C5530 27BD0018 */  addiu      $sp, $sp, 0x18
    /* F29E4 150C5534 03E00008 */  jr         $ra
    /* F29E8 150C5538 00000000 */   nop
endlabel func_150C5510

nonmatching func_150C553C, 0x2C

glabel func_150C553C
    /* F29EC 150C553C 27BDFFE8 */  addiu      $sp, $sp, -0x18
    /* F29F0 150C5540 AFBF0014 */  sw         $ra, 0x14($sp)
    /* F29F4 150C5544 8C8500C8 */  lw         $a1, 0xC8($a0)
    /* F29F8 150C5548 0D453B7C */  jal        func_1514EDF0
    /* F29FC 150C554C AFA40018 */   sw        $a0, 0x18($sp)
    /* F2A00 150C5550 0D431514 */  jal        func_150C5450
    /* F2A04 150C5554 8FA40018 */   lw        $a0, 0x18($sp)
    /* F2A08 150C5558 8FBF0014 */  lw         $ra, 0x14($sp)
    /* F2A0C 150C555C 27BD0018 */  addiu      $sp, $sp, 0x18
    /* F2A10 150C5560 03E00008 */  jr         $ra
    /* F2A14 150C5564 00000000 */   nop
endlabel func_150C553C

nonmatching func_150C5568, 0x13C

glabel func_150C5568
    /* F2A18 150C5568 27BDFFC0 */  addiu      $sp, $sp, -0x40
    /* F2A1C 150C556C AFBF0014 */  sw         $ra, 0x14($sp)
    /* F2A20 150C5570 00802825 */  or         $a1, $a0, $zero
    /* F2A24 150C5574 8CAE0010 */  lw         $t6, 0x10($a1)
    /* F2A28 150C5578 00001825 */  or         $v1, $zero, $zero
    /* F2A2C 150C557C 2401FFFF */  addiu      $at, $zero, -0x1
    /* F2A30 150C5580 31CF0001 */  andi       $t7, $t6, 0x1
    /* F2A34 150C5584 51E00044 */  beql       $t7, $zero, .L150C5698
    /* F2A38 150C5588 8FBF0014 */   lw        $ra, 0x14($sp)
    /* F2A3C 150C558C 80A20030 */  lb         $v0, 0x30($a1)
    /* F2A40 150C5590 C4A40018 */  lwc1       $f4, 0x18($a1)
    /* F2A44 150C5594 C4A60024 */  lwc1       $f6, 0x24($a1)
    /* F2A48 150C5598 C4A8001C */  lwc1       $f8, 0x1C($a1)
    /* F2A4C 150C559C C4AA0028 */  lwc1       $f10, 0x28($a1)
    /* F2A50 150C55A0 C4B00020 */  lwc1       $f16, 0x20($a1)
    /* F2A54 150C55A4 C4B2002C */  lwc1       $f18, 0x2C($a1)
    /* F2A58 150C55A8 46062001 */  sub.s      $f0, $f4, $f6
    /* F2A5C 150C55AC 460A4081 */  sub.s      $f2, $f8, $f10
    /* F2A60 150C55B0 10410013 */  beq        $v0, $at, .L150C5600
    /* F2A64 150C55B4 46128301 */   sub.s     $f12, $f16, $f18
    /* F2A68 150C55B8 0002C080 */  sll        $t8, $v0, 2
    /* F2A6C 150C55BC 3C198009 */  lui        $t9, %hi(D_80088760)
    /* F2A70 150C55C0 0338C821 */  addu       $t9, $t9, $t8
    /* F2A74 150C55C4 8F398760 */  lw         $t9, %lo(D_80088760)($t9)
    /* F2A78 150C55C8 00A02025 */  or         $a0, $a1, $zero
    /* F2A7C 150C55CC A3A0003B */  sb         $zero, 0x3B($sp)
    /* F2A80 150C55D0 AFA50040 */  sw         $a1, 0x40($sp)
    /* F2A84 150C55D4 E7A0002C */  swc1       $f0, 0x2C($sp)
    /* F2A88 150C55D8 E7A20030 */  swc1       $f2, 0x30($sp)
    /* F2A8C 150C55DC 0320F809 */  jalr       $t9
    /* F2A90 150C55E0 E7AC0034 */   swc1      $f12, 0x34($sp)
    /* F2A94 150C55E4 93A3003B */  lbu        $v1, 0x3B($sp)
    /* F2A98 150C55E8 8FA50040 */  lw         $a1, 0x40($sp)
    /* F2A9C 150C55EC C7A0002C */  lwc1       $f0, 0x2C($sp)
    /* F2AA0 150C55F0 C7A20030 */  lwc1       $f2, 0x30($sp)
    /* F2AA4 150C55F4 14400002 */  bnez       $v0, .L150C5600
    /* F2AA8 150C55F8 C7AC0034 */   lwc1      $f12, 0x34($sp)
    /* F2AAC 150C55FC 24030001 */  addiu      $v1, $zero, 0x1
  .L150C5600:
    /* F2AB0 150C5600 14600020 */  bnez       $v1, .L150C5684
    /* F2AB4 150C5604 00000000 */   nop
    /* F2AB8 150C5608 C4A40018 */  lwc1       $f4, 0x18($a1)
    /* F2ABC 150C560C C4A60024 */  lwc1       $f6, 0x24($a1)
    /* F2AC0 150C5610 27A40020 */  addiu      $a0, $sp, 0x20
    /* F2AC4 150C5614 46062201 */  sub.s      $f8, $f4, $f6
    /* F2AC8 150C5618 E7A80020 */  swc1       $f8, 0x20($sp)
    /* F2ACC 150C561C C4B00028 */  lwc1       $f16, 0x28($a1)
    /* F2AD0 150C5620 C4AA001C */  lwc1       $f10, 0x1C($a1)
    /* F2AD4 150C5624 46105481 */  sub.s      $f18, $f10, $f16
    /* F2AD8 150C5628 C7AA0020 */  lwc1       $f10, 0x20($sp)
    /* F2ADC 150C562C E7B20024 */  swc1       $f18, 0x24($sp)
    /* F2AE0 150C5630 C4A6002C */  lwc1       $f6, 0x2C($a1)
    /* F2AE4 150C5634 C4A40020 */  lwc1       $f4, 0x20($a1)
    /* F2AE8 150C5638 46005032 */  c.eq.s     $f10, $f0
    /* F2AEC 150C563C C7B00024 */  lwc1       $f16, 0x24($sp)
    /* F2AF0 150C5640 46062201 */  sub.s      $f8, $f4, $f6
    /* F2AF4 150C5644 45000009 */  bc1f       .L150C566C
    /* F2AF8 150C5648 E7A80028 */   swc1      $f8, 0x28($sp)
    /* F2AFC 150C564C 46028032 */  c.eq.s     $f16, $f2
    /* F2B00 150C5650 C7B20028 */  lwc1       $f18, 0x28($sp)
    /* F2B04 150C5654 45020006 */  bc1fl      .L150C5670
    /* F2B08 150C5658 A3A3003B */   sb        $v1, 0x3B($sp)
    /* F2B0C 150C565C 460C9032 */  c.eq.s     $f18, $f12
    /* F2B10 150C5660 00000000 */  nop
    /* F2B14 150C5664 45010007 */  bc1t       .L150C5684
    /* F2B18 150C5668 00000000 */   nop
  .L150C566C:
    /* F2B1C 150C566C A3A3003B */  sb         $v1, 0x3B($sp)
  .L150C5670:
    /* F2B20 150C5670 0D450F99 */  jal        func_15143E64
    /* F2B24 150C5674 AFA50040 */   sw        $a1, 0x40($sp)
    /* F2B28 150C5678 8FA50040 */  lw         $a1, 0x40($sp)
    /* F2B2C 150C567C 93A3003B */  lbu        $v1, 0x3B($sp)
    /* F2B30 150C5680 E4A000C0 */  swc1       $f0, 0xC0($a1)
  .L150C5684:
    /* F2B34 150C5684 50600004 */  beql       $v1, $zero, .L150C5698
    /* F2B38 150C5688 8FBF0014 */   lw        $ra, 0x14($sp)
    /* F2B3C 150C568C 0D45A5CB */  jal        func_1516972C
    /* F2B40 150C5690 00A02025 */   or        $a0, $a1, $zero
    /* F2B44 150C5694 8FBF0014 */  lw         $ra, 0x14($sp)
  .L150C5698:
    /* F2B48 150C5698 27BD0040 */  addiu      $sp, $sp, 0x40
    /* F2B4C 150C569C 03E00008 */  jr         $ra
    /* F2B50 150C56A0 00000000 */   nop
endlabel func_150C5568

nonmatching func_150C56A4, 0x4E4

glabel func_150C56A4
    /* F2B54 150C56A4 27BDFF50 */  addiu      $sp, $sp, -0xB0
    /* F2B58 150C56A8 AFB1003C */  sw         $s1, 0x3C($sp)
    /* F2B5C 150C56AC 00A08825 */  or         $s1, $a1, $zero
    /* F2B60 150C56B0 AFBF0044 */  sw         $ra, 0x44($sp)
    /* F2B64 150C56B4 AFB20040 */  sw         $s2, 0x40($sp)
    /* F2B68 150C56B8 AFB00038 */  sw         $s0, 0x38($sp)
    /* F2B6C 150C56BC AFA600B8 */  sw         $a2, 0xB8($sp)
    /* F2B70 150C56C0 8E2A0010 */  lw         $t2, 0x10($s1)
    /* F2B74 150C56C4 240C0001 */  addiu      $t4, $zero, 0x1
    /* F2B78 150C56C8 3C0D800C */  lui        $t5, %hi(D_800BE9C0)
    /* F2B7C 150C56CC 314B0001 */  andi       $t3, $t2, 0x1
    /* F2B80 150C56D0 11600126 */  beqz       $t3, .L150C5B6C
    /* F2B84 150C56D4 3C18800E */   lui       $t8, %hi(D_800DBFF0)
    /* F2B88 150C56D8 87A200BA */  lh         $v0, 0xBA($sp)
    /* F2B8C 150C56DC 91ADE9C0 */  lbu        $t5, %lo(D_800BE9C0)($t5)
    /* F2B90 150C56E0 8F18BFF0 */  lw         $t8, %lo(D_800DBFF0)($t8)
    /* F2B94 150C56E4 00027880 */  sll        $t7, $v0, 2
    /* F2B98 150C56E8 01E27821 */  addu       $t7, $t7, $v0
    /* F2B9C 150C56EC 000F7880 */  sll        $t7, $t7, 2
    /* F2BA0 150C56F0 01E27823 */  subu       $t7, $t7, $v0
    /* F2BA4 150C56F4 000F7880 */  sll        $t7, $t7, 2
    /* F2BA8 150C56F8 01E27821 */  addu       $t7, $t7, $v0
    /* F2BAC 150C56FC 000F7940 */  sll        $t7, $t7, 5
    /* F2BB0 150C5700 000D7180 */  sll        $t6, $t5, 6
    /* F2BB4 150C5704 01F8C821 */  addu       $t9, $t7, $t8
    /* F2BB8 150C5708 022E8021 */  addu       $s0, $s1, $t6
    /* F2BBC 150C570C 272902F8 */  addiu      $t1, $t9, 0x2F8
    /* F2BC0 150C5710 A3AC00AB */  sb         $t4, 0xAB($sp)
    /* F2BC4 150C5714 26100040 */  addiu      $s0, $s0, 0x40
    /* F2BC8 150C5718 AFA900A0 */  sw         $t1, 0xA0($sp)
    /* F2BCC 150C571C AFAF0060 */  sw         $t7, 0x60($sp)
    /* F2BD0 150C5720 24050001 */  addiu      $a1, $zero, 0x1
    /* F2BD4 150C5724 0D450ADF */  jal        func_15142B7C
    /* F2BD8 150C5728 24060600 */   addiu     $a2, $zero, 0x600
    /* F2BDC 150C572C 27B200AB */  addiu      $s2, $sp, 0xAB
    /* F2BE0 150C5730 3C058009 */  lui        $a1, %hi(D_80090DE8)
    /* F2BE4 150C5734 240A0036 */  addiu      $t2, $zero, 0x36
    /* F2BE8 150C5738 240B0003 */  addiu      $t3, $zero, 0x3
    /* F2BEC 150C573C AFAB0028 */  sw         $t3, 0x28($sp)
    /* F2BF0 150C5740 AFAA0018 */  sw         $t2, 0x18($sp)
    /* F2BF4 150C5744 24A50DE8 */  addiu      $a1, $a1, %lo(D_80090DE8)
    /* F2BF8 150C5748 AFB20024 */  sw         $s2, 0x24($sp)
    /* F2BFC 150C574C 00402025 */  or         $a0, $v0, $zero
    /* F2C00 150C5750 00003025 */  or         $a2, $zero, $zero
    /* F2C04 150C5754 00003825 */  or         $a3, $zero, $zero
    /* F2C08 150C5758 AFA00010 */  sw         $zero, 0x10($sp)
    /* F2C0C 150C575C AFA00014 */  sw         $zero, 0x14($sp)
    /* F2C10 150C5760 AFA0001C */  sw         $zero, 0x1C($sp)
    /* F2C14 150C5764 0D450B89 */  jal        func_15142E24
    /* F2C18 150C5768 AFA00020 */   sw        $zero, 0x20($sp)
    /* F2C1C 150C576C 3C0C800E */  lui        $t4, %hi(D_800DBFF0)
    /* F2C20 150C5770 8D8CBFF0 */  lw         $t4, %lo(D_800DBFF0)($t4)
    /* F2C24 150C5774 8FAD0060 */  lw         $t5, 0x60($sp)
    /* F2C28 150C5778 00402025 */  or         $a0, $v0, $zero
    /* F2C2C 150C577C 00002825 */  or         $a1, $zero, $zero
    /* F2C30 150C5780 018D7021 */  addu       $t6, $t4, $t5
    /* F2C34 150C5784 8DCF05F0 */  lw         $t7, 0x5F0($t6)
    /* F2C38 150C5788 00003025 */  or         $a2, $zero, $zero
    /* F2C3C 150C578C 00003825 */  or         $a3, $zero, $zero
    /* F2C40 150C5790 31F80001 */  andi       $t8, $t7, 0x1
    /* F2C44 150C5794 53000027 */  beql       $t8, $zero, .L150C5834
    /* F2C48 150C5798 AFA00010 */   sw        $zero, 0x10($sp)
    /* F2C4C 150C579C 87A800BA */  lh         $t0, 0xBA($sp)
    /* F2C50 150C57A0 3C09800E */  lui        $t1, %hi(D_800D9B78)
    /* F2C54 150C57A4 25299B78 */  addiu      $t1, $t1, %lo(D_800D9B78)
    /* F2C58 150C57A8 0008C880 */  sll        $t9, $t0, 2
    /* F2C5C 150C57AC 0328C823 */  subu       $t9, $t9, $t0
    /* F2C60 150C57B0 03291021 */  addu       $v0, $t9, $t1
    /* F2C64 150C57B4 240A00FF */  addiu      $t2, $zero, 0xFF
    /* F2C68 150C57B8 AFAA0010 */  sw         $t2, 0x10($sp)
    /* F2C6C 150C57BC 90450000 */  lbu        $a1, 0x0($v0)
    /* F2C70 150C57C0 90460001 */  lbu        $a2, 0x1($v0)
    /* F2C74 150C57C4 90470002 */  lbu        $a3, 0x2($v0)
    /* F2C78 150C57C8 03204025 */  or         $t0, $t9, $zero
    /* F2C7C 150C57CC AFB90060 */  sw         $t9, 0x60($sp)
    /* F2C80 150C57D0 0D450B04 */  jal        func_15142C10
    /* F2C84 150C57D4 AFB20014 */   sw        $s2, 0x14($sp)
    /* F2C88 150C57D8 8FA80060 */  lw         $t0, 0x60($sp)
    /* F2C8C 150C57DC 3C0B800E */  lui        $t3, %hi(D_800D9B68)
    /* F2C90 150C57E0 256B9B68 */  addiu      $t3, $t3, %lo(D_800D9B68)
    /* F2C94 150C57E4 010B1821 */  addu       $v1, $t0, $t3
    /* F2C98 150C57E8 906C0001 */  lbu        $t4, 0x1($v1)
    /* F2C9C 150C57EC 906D0002 */  lbu        $t5, 0x2($v1)
    /* F2CA0 150C57F0 240E00FF */  addiu      $t6, $zero, 0xFF
    /* F2CA4 150C57F4 AFAE0018 */  sw         $t6, 0x18($sp)
    /* F2CA8 150C57F8 90670000 */  lbu        $a3, 0x0($v1)
    /* F2CAC 150C57FC 00402025 */  or         $a0, $v0, $zero
    /* F2CB0 150C5800 240500F2 */  addiu      $a1, $zero, 0xF2
    /* F2CB4 150C5804 00003025 */  or         $a2, $zero, $zero
    /* F2CB8 150C5808 AFB2001C */  sw         $s2, 0x1C($sp)
    /* F2CBC 150C580C AFAC0010 */  sw         $t4, 0x10($sp)
    /* F2CC0 150C5810 0D450B3C */  jal        func_15142CF0
    /* F2CC4 150C5814 AFAD0014 */   sw        $t5, 0x14($sp)
    /* F2CC8 150C5818 00402025 */  or         $a0, $v0, $zero
    /* F2CCC 150C581C 2405001E */  addiu      $a1, $zero, 0x1E
    /* F2CD0 150C5820 0D44FD39 */  jal        func_1513F4E4
    /* F2CD4 150C5824 02403025 */   or        $a2, $s2, $zero
    /* F2CD8 150C5828 10000012 */  b          .L150C5874
    /* F2CDC 150C582C 00402025 */   or        $a0, $v0, $zero
    /* F2CE0 150C5830 AFA00010 */  sw         $zero, 0x10($sp)
  .L150C5834:
    /* F2CE4 150C5834 0D450B04 */  jal        func_15142C10
    /* F2CE8 150C5838 AFB20014 */   sw        $s2, 0x14($sp)
    /* F2CEC 150C583C 00402025 */  or         $a0, $v0, $zero
    /* F2CF0 150C5840 00002825 */  or         $a1, $zero, $zero
    /* F2CF4 150C5844 00003025 */  or         $a2, $zero, $zero
    /* F2CF8 150C5848 00003825 */  or         $a3, $zero, $zero
    /* F2CFC 150C584C AFA00010 */  sw         $zero, 0x10($sp)
    /* F2D00 150C5850 AFA00014 */  sw         $zero, 0x14($sp)
    /* F2D04 150C5854 AFA00018 */  sw         $zero, 0x18($sp)
    /* F2D08 150C5858 0D450B3C */  jal        func_15142CF0
    /* F2D0C 150C585C AFB2001C */   sw        $s2, 0x1C($sp)
    /* F2D10 150C5860 00402025 */  or         $a0, $v0, $zero
    /* F2D14 150C5864 24050013 */  addiu      $a1, $zero, 0x13
    /* F2D18 150C5868 0D44FD39 */  jal        func_1513F4E4
    /* F2D1C 150C586C 02403025 */   or        $a2, $s2, $zero
    /* F2D20 150C5870 00402025 */  or         $a0, $v0, $zero
  .L150C5874:
    /* F2D24 150C5874 3C02800A */  lui        $v0, %hi(D_800A4AC8)
    /* F2D28 150C5878 3C05800D */  lui        $a1, %hi(D_800D2C9C)
    /* F2D2C 150C587C 8CA52C9C */  lw         $a1, %lo(D_800D2C9C)($a1)
    /* F2D30 150C5880 24424AC8 */  addiu      $v0, $v0, %lo(D_800A4AC8)
    /* F2D34 150C5884 8C4B000C */  lw         $t3, 0xC($v0)
    /* F2D38 150C5888 8C4C0008 */  lw         $t4, 0x8($v0)
    /* F2D3C 150C588C 3C010008 */  lui        $at, (0x80000 >> 16)
    /* F2D40 150C5890 00A14825 */  or         $t1, $a1, $at
    /* F2D44 150C5894 35252CA0 */  ori        $a1, $t1, 0x2CA0
    /* F2D48 150C5898 02403825 */  or         $a3, $s2, $zero
    /* F2D4C 150C589C 0D450BEF */  jal        func_15142FBC
    /* F2D50 150C58A0 016C3025 */   or        $a2, $t3, $t4
    /* F2D54 150C58A4 C62A0024 */  lwc1       $f10, 0x24($s1)
    /* F2D58 150C58A8 8FA300A0 */  lw         $v1, 0xA0($sp)
    /* F2D5C 150C58AC 24440008 */  addiu      $a0, $v0, 0x8
    /* F2D60 150C58B0 E7AA0058 */  swc1       $f10, 0x58($sp)
    /* F2D64 150C58B4 C6260018 */  lwc1       $f6, 0x18($s1)
    /* F2D68 150C58B8 C7A40058 */  lwc1       $f4, 0x58($sp)
    /* F2D6C 150C58BC 00802825 */  or         $a1, $a0, $zero
    /* F2D70 150C58C0 24840008 */  addiu      $a0, $a0, 0x8
    /* F2D74 150C58C4 46062201 */  sub.s      $f8, $f4, $f6
    /* F2D78 150C58C8 00803825 */  or         $a3, $a0, $zero
    /* F2D7C 150C58CC 24840008 */  addiu      $a0, $a0, 0x8
    /* F2D80 150C58D0 E7A80094 */  swc1       $f8, 0x94($sp)
    /* F2D84 150C58D4 C62A001C */  lwc1       $f10, 0x1C($s1)
    /* F2D88 150C58D8 C62E0028 */  lwc1       $f14, 0x28($s1)
    /* F2D8C 150C58DC 460A7181 */  sub.s      $f6, $f14, $f10
    /* F2D90 150C58E0 E7A60098 */  swc1       $f6, 0x98($sp)
    /* F2D94 150C58E4 C62A0020 */  lwc1       $f10, 0x20($s1)
    /* F2D98 150C58E8 C62C002C */  lwc1       $f12, 0x2C($s1)
    /* F2D9C 150C58EC C4660000 */  lwc1       $f6, 0x0($v1)
    /* F2DA0 150C58F0 460A6001 */  sub.s      $f0, $f12, $f10
    /* F2DA4 150C58F4 46062281 */  sub.s      $f10, $f4, $f6
    /* F2DA8 150C58F8 E7AA0088 */  swc1       $f10, 0x88($sp)
    /* F2DAC 150C58FC C4640004 */  lwc1       $f4, 0x4($v1)
    /* F2DB0 150C5900 46047181 */  sub.s      $f6, $f14, $f4
    /* F2DB4 150C5904 44807000 */  mtc1       $zero, $f14
    /* F2DB8 150C5908 E7A6008C */  swc1       $f6, 0x8C($sp)
    /* F2DBC 150C590C C4640008 */  lwc1       $f4, 0x8($v1)
    /* F2DC0 150C5910 C7A60098 */  lwc1       $f6, 0x98($sp)
    /* F2DC4 150C5914 E7A80048 */  swc1       $f8, 0x48($sp)
    /* F2DC8 150C5918 46046081 */  sub.s      $f2, $f12, $f4
    /* F2DCC 150C591C C7A8008C */  lwc1       $f8, 0x8C($sp)
    /* F2DD0 150C5920 E7AA004C */  swc1       $f10, 0x4C($sp)
    /* F2DD4 150C5924 46023102 */  mul.s      $f4, $f6, $f2
    /* F2DD8 150C5928 E7A80050 */  swc1       $f8, 0x50($sp)
    /* F2DDC 150C592C 46004282 */  mul.s      $f10, $f8, $f0
    /* F2DE0 150C5930 C7A80048 */  lwc1       $f8, 0x48($sp)
    /* F2DE4 150C5934 460A2401 */  sub.s      $f16, $f4, $f10
    /* F2DE8 150C5938 C7AA004C */  lwc1       $f10, 0x4C($sp)
    /* F2DEC 150C593C E7A6004C */  swc1       $f6, 0x4C($sp)
    /* F2DF0 150C5940 460A0182 */  mul.s      $f6, $f0, $f10
    /* F2DF4 150C5944 E7B00048 */  swc1       $f16, 0x48($sp)
    /* F2DF8 150C5948 E7B00060 */  swc1       $f16, 0x60($sp)
    /* F2DFC 150C594C 46081102 */  mul.s      $f4, $f2, $f8
    /* F2E00 150C5950 46043481 */  sub.s      $f18, $f6, $f4
    /* F2E04 150C5954 C7A40050 */  lwc1       $f4, 0x50($sp)
    /* F2E08 150C5958 46044202 */  mul.s      $f8, $f8, $f4
    /* F2E0C 150C595C C7A4004C */  lwc1       $f4, 0x4C($sp)
    /* F2E10 150C5960 E7B2005C */  swc1       $f18, 0x5C($sp)
    /* F2E14 150C5964 46045282 */  mul.s      $f10, $f10, $f4
    /* F2E18 150C5968 460A4301 */  sub.s      $f12, $f8, $f10
    /* F2E1C 150C596C 46129102 */  mul.s      $f4, $f18, $f18
    /* F2E20 150C5970 C7A80048 */  lwc1       $f8, 0x48($sp)
    /* F2E24 150C5974 46084282 */  mul.s      $f10, $f8, $f8
    /* F2E28 150C5978 46045180 */  add.s      $f6, $f10, $f4
    /* F2E2C 150C597C 460C6202 */  mul.s      $f8, $f12, $f12
    /* F2E30 150C5980 46083080 */  add.s      $f2, $f6, $f8
    /* F2E34 150C5984 46027032 */  c.eq.s     $f14, $f2
    /* F2E38 150C5988 E7A20078 */  swc1       $f2, 0x78($sp)
    /* F2E3C 150C598C C7A00078 */  lwc1       $f0, 0x78($sp)
    /* F2E40 150C5990 45020006 */  bc1fl      .L150C59AC
    /* F2E44 150C5994 46000004 */   sqrt.s    $f0, $f0
    /* F2E48 150C5998 46007406 */  mov.s      $f16, $f14
    /* F2E4C 150C599C 46007486 */  mov.s      $f18, $f14
    /* F2E50 150C59A0 1000000B */  b          .L150C59D0
    /* F2E54 150C59A4 46007306 */   mov.s     $f12, $f14
    /* F2E58 150C59A8 46000004 */  sqrt.s     $f0, $f0
  .L150C59AC:
    /* F2E5C 150C59AC 3C01800A */  lui        $at, %hi(D_800A0400)
    /* F2E60 150C59B0 C42A0400 */  lwc1       $f10, %lo(D_800A0400)($at)
    /* F2E64 150C59B4 46005083 */  div.s      $f2, $f10, $f0
    /* F2E68 150C59B8 46028402 */  mul.s      $f16, $f16, $f2
    /* F2E6C 150C59BC 00000000 */  nop
    /* F2E70 150C59C0 46029482 */  mul.s      $f18, $f18, $f2
    /* F2E74 150C59C4 00000000 */  nop
    /* F2E78 150C59C8 46026302 */  mul.s      $f12, $f12, $f2
    /* F2E7C 150C59CC 00000000 */  nop
  .L150C59D0:
    /* F2E80 150C59D0 C62400C0 */  lwc1       $f4, 0xC0($s1)
    /* F2E84 150C59D4 C6260034 */  lwc1       $f6, 0x34($s1)
    /* F2E88 150C59D8 3C014280 */  lui        $at, (0x42800000 >> 16)
    /* F2E8C 150C59DC 44815000 */  mtc1       $at, $f10
    /* F2E90 150C59E0 46062202 */  mul.s      $f8, $f4, $f6
    /* F2E94 150C59E4 240303C0 */  addiu      $v1, $zero, 0x3C0
    /* F2E98 150C59E8 26100040 */  addiu      $s0, $s0, 0x40
    /* F2E9C 150C59EC 460A4102 */  mul.s      $f4, $f8, $f10
    /* F2EA0 150C59F0 C7A80058 */  lwc1       $f8, 0x58($sp)
    /* F2EA4 150C59F4 46104280 */  add.s      $f10, $f8, $f16
    /* F2EA8 150C59F8 4600218D */  trunc.w.s  $f6, $f4
    /* F2EAC 150C59FC 4600510D */  trunc.w.s  $f4, $f10
    /* F2EB0 150C5A00 44063000 */  mfc1       $a2, $f6
    /* F2EB4 150C5A04 440F2000 */  mfc1       $t7, $f4
    /* F2EB8 150C5A08 00000000 */  nop
    /* F2EBC 150C5A0C A60FFFC0 */  sh         $t7, -0x40($s0)
    /* F2EC0 150C5A10 C6260028 */  lwc1       $f6, 0x28($s1)
    /* F2EC4 150C5A14 46123200 */  add.s      $f8, $f6, $f18
    /* F2EC8 150C5A18 4600428D */  trunc.w.s  $f10, $f8
    /* F2ECC 150C5A1C 44195000 */  mfc1       $t9, $f10
    /* F2ED0 150C5A20 00000000 */  nop
    /* F2ED4 150C5A24 A619FFC2 */  sh         $t9, -0x3E($s0)
    /* F2ED8 150C5A28 C624002C */  lwc1       $f4, 0x2C($s1)
    /* F2EDC 150C5A2C A600FFC8 */  sh         $zero, -0x38($s0)
    /* F2EE0 150C5A30 A600FFCA */  sh         $zero, -0x36($s0)
    /* F2EE4 150C5A34 460C2180 */  add.s      $f6, $f4, $f12
    /* F2EE8 150C5A38 4600320D */  trunc.w.s  $f8, $f6
    /* F2EEC 150C5A3C 440A4000 */  mfc1       $t2, $f8
    /* F2EF0 150C5A40 00000000 */  nop
    /* F2EF4 150C5A44 A60AFFC4 */  sh         $t2, -0x3C($s0)
    /* F2EF8 150C5A48 C62A0024 */  lwc1       $f10, 0x24($s1)
    /* F2EFC 150C5A4C 46105101 */  sub.s      $f4, $f10, $f16
    /* F2F00 150C5A50 4600218D */  trunc.w.s  $f6, $f4
    /* F2F04 150C5A54 440C3000 */  mfc1       $t4, $f6
    /* F2F08 150C5A58 00000000 */  nop
    /* F2F0C 150C5A5C A60CFFD0 */  sh         $t4, -0x30($s0)
    /* F2F10 150C5A60 C6280028 */  lwc1       $f8, 0x28($s1)
    /* F2F14 150C5A64 260CFFC0 */  addiu      $t4, $s0, -0x40
    /* F2F18 150C5A68 46124281 */  sub.s      $f10, $f8, $f18
    /* F2F1C 150C5A6C 4600510D */  trunc.w.s  $f4, $f10
    /* F2F20 150C5A70 440E2000 */  mfc1       $t6, $f4
    /* F2F24 150C5A74 00000000 */  nop
    /* F2F28 150C5A78 A60EFFD2 */  sh         $t6, -0x2E($s0)
    /* F2F2C 150C5A7C C626002C */  lwc1       $f6, 0x2C($s1)
    /* F2F30 150C5A80 A603FFD8 */  sh         $v1, -0x28($s0)
    /* F2F34 150C5A84 A600FFDA */  sh         $zero, -0x26($s0)
    /* F2F38 150C5A88 460C3201 */  sub.s      $f8, $f6, $f12
    /* F2F3C 150C5A8C 3C0E0500 */  lui        $t6, (0x5000406 >> 16)
    /* F2F40 150C5A90 35CE0406 */  ori        $t6, $t6, (0x5000406 & 0xFFFF)
    /* F2F44 150C5A94 4600428D */  trunc.w.s  $f10, $f8
    /* F2F48 150C5A98 44185000 */  mfc1       $t8, $f10
    /* F2F4C 150C5A9C 00000000 */  nop
    /* F2F50 150C5AA0 A618FFD4 */  sh         $t8, -0x2C($s0)
    /* F2F54 150C5AA4 C6240018 */  lwc1       $f4, 0x18($s1)
    /* F2F58 150C5AA8 46102181 */  sub.s      $f6, $f4, $f16
    /* F2F5C 150C5AAC 4600320D */  trunc.w.s  $f8, $f6
    /* F2F60 150C5AB0 44094000 */  mfc1       $t1, $f8
    /* F2F64 150C5AB4 00000000 */  nop
    /* F2F68 150C5AB8 A609FFE0 */  sh         $t1, -0x20($s0)
    /* F2F6C 150C5ABC C62A001C */  lwc1       $f10, 0x1C($s1)
    /* F2F70 150C5AC0 46125101 */  sub.s      $f4, $f10, $f18
    /* F2F74 150C5AC4 4600218D */  trunc.w.s  $f6, $f4
    /* F2F78 150C5AC8 440B3000 */  mfc1       $t3, $f6
    /* F2F7C 150C5ACC 00000000 */  nop
    /* F2F80 150C5AD0 A60BFFE2 */  sh         $t3, -0x1E($s0)
    /* F2F84 150C5AD4 C6280020 */  lwc1       $f8, 0x20($s1)
    /* F2F88 150C5AD8 A603FFE8 */  sh         $v1, -0x18($s0)
    /* F2F8C 150C5ADC A606FFEA */  sh         $a2, -0x16($s0)
    /* F2F90 150C5AE0 460C4281 */  sub.s      $f10, $f8, $f12
    /* F2F94 150C5AE4 3C0B0100 */  lui        $t3, (0x1004008 >> 16)
    /* F2F98 150C5AE8 356B4008 */  ori        $t3, $t3, (0x1004008 & 0xFFFF)
    /* F2F9C 150C5AEC 4600510D */  trunc.w.s  $f4, $f10
    /* F2FA0 150C5AF0 440D2000 */  mfc1       $t5, $f4
    /* F2FA4 150C5AF4 00000000 */  nop
    /* F2FA8 150C5AF8 A60DFFE4 */  sh         $t5, -0x1C($s0)
    /* F2FAC 150C5AFC C6260018 */  lwc1       $f6, 0x18($s1)
    /* F2FB0 150C5B00 3C0D0500 */  lui        $t5, (0x5000204 >> 16)
    /* F2FB4 150C5B04 35AD0204 */  ori        $t5, $t5, (0x5000204 & 0xFFFF)
    /* F2FB8 150C5B08 46103200 */  add.s      $f8, $f6, $f16
    /* F2FBC 150C5B0C 4600428D */  trunc.w.s  $f10, $f8
    /* F2FC0 150C5B10 440F5000 */  mfc1       $t7, $f10
    /* F2FC4 150C5B14 00000000 */  nop
    /* F2FC8 150C5B18 A60FFFF0 */  sh         $t7, -0x10($s0)
    /* F2FCC 150C5B1C C624001C */  lwc1       $f4, 0x1C($s1)
    /* F2FD0 150C5B20 46122180 */  add.s      $f6, $f4, $f18
    /* F2FD4 150C5B24 4600320D */  trunc.w.s  $f8, $f6
    /* F2FD8 150C5B28 44194000 */  mfc1       $t9, $f8
    /* F2FDC 150C5B2C 00000000 */  nop
    /* F2FE0 150C5B30 A619FFF2 */  sh         $t9, -0xE($s0)
    /* F2FE4 150C5B34 C62A0020 */  lwc1       $f10, 0x20($s1)
    /* F2FE8 150C5B38 A600FFF8 */  sh         $zero, -0x8($s0)
    /* F2FEC 150C5B3C A606FFFA */  sh         $a2, -0x6($s0)
    /* F2FF0 150C5B40 460C5100 */  add.s      $f4, $f10, $f12
    /* F2FF4 150C5B44 4600218D */  trunc.w.s  $f6, $f4
    /* F2FF8 150C5B48 440A3000 */  mfc1       $t2, $f6
    /* F2FFC 150C5B4C 00000000 */  nop
    /* F3000 150C5B50 A60AFFF4 */  sh         $t2, -0xC($s0)
    /* F3004 150C5B54 AC4B0000 */  sw         $t3, 0x0($v0)
    /* F3008 150C5B58 AC4C0004 */  sw         $t4, 0x4($v0)
    /* F300C 150C5B5C ACAD0000 */  sw         $t5, 0x0($a1)
    /* F3010 150C5B60 ACA00004 */  sw         $zero, 0x4($a1)
    /* F3014 150C5B64 ACEE0000 */  sw         $t6, 0x0($a3)
    /* F3018 150C5B68 ACE00004 */  sw         $zero, 0x4($a3)
  .L150C5B6C:
    /* F301C 150C5B6C 00801025 */  or         $v0, $a0, $zero
    /* F3020 150C5B70 8FBF0044 */  lw         $ra, 0x44($sp)
    /* F3024 150C5B74 8FB00038 */  lw         $s0, 0x38($sp)
    /* F3028 150C5B78 8FB1003C */  lw         $s1, 0x3C($sp)
    /* F302C 150C5B7C 8FB20040 */  lw         $s2, 0x40($sp)
    /* F3030 150C5B80 03E00008 */  jr         $ra
    /* F3034 150C5B84 27BD00B0 */   addiu     $sp, $sp, 0xB0
endlabel func_150C56A4

nonmatching func_150C5B88, 0x4C

glabel func_150C5B88
    /* F3038 150C5B88 8C8E00C8 */  lw         $t6, 0xC8($a0)
    /* F303C 150C5B8C 248300C8 */  addiu      $v1, $a0, 0xC8
    /* F3040 150C5B90 8DCF0000 */  lw         $t7, 0x0($t6)
    /* F3044 150C5B94 55E00004 */  bnel       $t7, $zero, .L150C5BA8
    /* F3048 150C5B98 8C780000 */   lw        $t8, 0x0($v1)
    /* F304C 150C5B9C 03E00008 */  jr         $ra
    /* F3050 150C5BA0 00001025 */   or        $v0, $zero, $zero
    /* F3054 150C5BA4 8C780000 */  lw         $t8, 0x0($v1)
  .L150C5BA8:
    /* F3058 150C5BA8 24020001 */  addiu      $v0, $zero, 0x1
    /* F305C 150C5BAC C7040014 */  lwc1       $f4, 0x14($t8)
    /* F3060 150C5BB0 E4840024 */  swc1       $f4, 0x24($a0)
    /* F3064 150C5BB4 8C790000 */  lw         $t9, 0x0($v1)
    /* F3068 150C5BB8 C7260018 */  lwc1       $f6, 0x18($t9)
    /* F306C 150C5BBC E4860028 */  swc1       $f6, 0x28($a0)
    /* F3070 150C5BC0 8C680000 */  lw         $t0, 0x0($v1)
    /* F3074 150C5BC4 C508001C */  lwc1       $f8, 0x1C($t0)
    /* F3078 150C5BC8 E488002C */  swc1       $f8, 0x2C($a0)
    /* F307C 150C5BCC 03E00008 */  jr         $ra
    /* F3080 150C5BD0 00000000 */   nop
endlabel func_150C5B88

nonmatching func_150C5BD4, 0xA0

glabel func_150C5BD4
    /* F3084 150C5BD4 27BDFFE8 */  addiu      $sp, $sp, -0x18
    /* F3088 150C5BD8 AFBF0014 */  sw         $ra, 0x14($sp)
    /* F308C 150C5BDC 00803825 */  or         $a3, $a0, $zero
    /* F3090 150C5BE0 8CEE00C8 */  lw         $t6, 0xC8($a3)
    /* F3094 150C5BE4 24E200C8 */  addiu      $v0, $a3, 0xC8
    /* F3098 150C5BE8 8DCF0000 */  lw         $t7, 0x0($t6)
    /* F309C 150C5BEC 55E00004 */  bnel       $t7, $zero, .L150C5C00
    /* F30A0 150C5BF0 8C430000 */   lw        $v1, 0x0($v0)
    /* F30A4 150C5BF4 1000001B */  b          .L150C5C64
    /* F30A8 150C5BF8 00001025 */   or        $v0, $zero, $zero
    /* F30AC 150C5BFC 8C430000 */  lw         $v1, 0x0($v0)
  .L150C5C00:
    /* F30B0 150C5C00 90580004 */  lbu        $t8, 0x4($v0)
    /* F30B4 150C5C04 9079003B */  lbu        $t9, 0x3B($v1)
    /* F30B8 150C5C08 53190004 */  beql       $t8, $t9, .L150C5C1C
    /* F30BC 150C5C0C 8C6801D4 */   lw        $t0, 0x1D4($v1)
    /* F30C0 150C5C10 10000014 */  b          .L150C5C64
    /* F30C4 150C5C14 00001025 */   or        $v0, $zero, $zero
    /* F30C8 150C5C18 8C6801D4 */  lw         $t0, 0x1D4($v1)
  .L150C5C1C:
    /* F30CC 150C5C1C 5500000B */  bnel       $t0, $zero, .L150C5C4C
    /* F30D0 150C5C20 904B0005 */   lbu       $t3, 0x5($v0)
    /* F30D4 150C5C24 C4640014 */  lwc1       $f4, 0x14($v1)
    /* F30D8 150C5C28 E4E40024 */  swc1       $f4, 0x24($a3)
    /* F30DC 150C5C2C 8C490000 */  lw         $t1, 0x0($v0)
    /* F30E0 150C5C30 C5260018 */  lwc1       $f6, 0x18($t1)
    /* F30E4 150C5C34 E4E60028 */  swc1       $f6, 0x28($a3)
    /* F30E8 150C5C38 8C4A0000 */  lw         $t2, 0x0($v0)
    /* F30EC 150C5C3C C548001C */  lwc1       $f8, 0x1C($t2)
    /* F30F0 150C5C40 10000007 */  b          .L150C5C60
    /* F30F4 150C5C44 E4E8002C */   swc1      $f8, 0x2C($a3)
    /* F30F8 150C5C48 904B0005 */  lbu        $t3, 0x5($v0)
  .L150C5C4C:
    /* F30FC 150C5C4C 24440008 */  addiu      $a0, $v0, 0x8
    /* F3100 150C5C50 24E50024 */  addiu      $a1, $a3, 0x24
    /* F3104 150C5C54 000B6180 */  sll        $t4, $t3, 6
    /* F3108 150C5C58 0D450C4D */  jal        func_15143134
    /* F310C 150C5C5C 010C3021 */   addu      $a2, $t0, $t4
  .L150C5C60:
    /* F3110 150C5C60 24020001 */  addiu      $v0, $zero, 0x1
  .L150C5C64:
    /* F3114 150C5C64 8FBF0014 */  lw         $ra, 0x14($sp)
    /* F3118 150C5C68 27BD0018 */  addiu      $sp, $sp, 0x18
    /* F311C 150C5C6C 03E00008 */  jr         $ra
    /* F3120 150C5C70 00000000 */   nop
endlabel func_150C5BD4

nonmatching func_150C5C74, 0x28

glabel func_150C5C74
    /* F3124 150C5C74 27BDFFE8 */  addiu      $sp, $sp, -0x18
    /* F3128 150C5C78 AFBF0014 */  sw         $ra, 0x14($sp)
    /* F312C 150C5C7C 24050015 */  addiu      $a1, $zero, 0x15
    /* F3130 150C5C80 24060001 */  addiu      $a2, $zero, 0x1
    /* F3134 150C5C84 0D4534EC */  jal        func_1514D3B0
    /* F3138 150C5C88 00003825 */   or        $a3, $zero, $zero
    /* F313C 150C5C8C 8FBF0014 */  lw         $ra, 0x14($sp)
    /* F3140 150C5C90 27BD0018 */  addiu      $sp, $sp, 0x18
    /* F3144 150C5C94 03E00008 */  jr         $ra
    /* F3148 150C5C98 00000000 */   nop
endlabel func_150C5C74

nonmatching func_150C5C9C, 0x28

glabel func_150C5C9C
    /* F314C 150C5C9C 27BDFFE8 */  addiu      $sp, $sp, -0x18
    /* F3150 150C5CA0 AFBF0014 */  sw         $ra, 0x14($sp)
    /* F3154 150C5CA4 24050015 */  addiu      $a1, $zero, 0x15
    /* F3158 150C5CA8 24060002 */  addiu      $a2, $zero, 0x2
    /* F315C 150C5CAC 0D4534EC */  jal        func_1514D3B0
    /* F3160 150C5CB0 00003825 */   or        $a3, $zero, $zero
    /* F3164 150C5CB4 8FBF0014 */  lw         $ra, 0x14($sp)
    /* F3168 150C5CB8 27BD0018 */  addiu      $sp, $sp, 0x18
    /* F316C 150C5CBC 03E00008 */  jr         $ra
    /* F3170 150C5CC0 00000000 */   nop
endlabel func_150C5C9C

nonmatching func_150C5CC4, 0x48

glabel func_150C5CC4
    /* F3174 150C5CC4 27BDFFE8 */  addiu      $sp, $sp, -0x18
    /* F3178 150C5CC8 AFA60020 */  sw         $a2, 0x20($sp)
    /* F317C 150C5CCC 30CE00FF */  andi       $t6, $a2, 0xFF
    /* F3180 150C5CD0 01C03025 */  or         $a2, $t6, $zero
    /* F3184 150C5CD4 AFBF0014 */  sw         $ra, 0x14($sp)
    /* F3188 150C5CD8 908F0038 */  lbu        $t7, 0x38($a0)
    /* F318C 150C5CDC 3C028009 */  lui        $v0, %hi(D_800887C8)
    /* F3190 150C5CE0 000FC080 */  sll        $t8, $t7, 2
    /* F3194 150C5CE4 00581021 */  addu       $v0, $v0, $t8
    /* F3198 150C5CE8 8C4287C8 */  lw         $v0, %lo(D_800887C8)($v0)
    /* F319C 150C5CEC 50400004 */  beql       $v0, $zero, .L150C5D00
    /* F31A0 150C5CF0 8FBF0014 */   lw        $ra, 0x14($sp)
    /* F31A4 150C5CF4 0040F809 */  jalr       $v0
    /* F31A8 150C5CF8 00000000 */   nop
    /* F31AC 150C5CFC 8FBF0014 */  lw         $ra, 0x14($sp)
  .L150C5D00:
    /* F31B0 150C5D00 27BD0018 */  addiu      $sp, $sp, 0x18
    /* F31B4 150C5D04 03E00008 */  jr         $ra
    /* F31B8 150C5D08 00000000 */   nop
endlabel func_150C5CC4

nonmatching func_150C5D0C, 0xAC

glabel func_150C5D0C
    /* F31BC 150C5D0C 27BDFFE8 */  addiu      $sp, $sp, -0x18
    /* F31C0 150C5D10 AFA60020 */  sw         $a2, 0x20($sp)
    /* F31C4 150C5D14 30CE00FF */  andi       $t6, $a2, 0xFF
    /* F31C8 150C5D18 01C03025 */  or         $a2, $t6, $zero
    /* F31CC 150C5D1C AFBF0014 */  sw         $ra, 0x14($sp)
    /* F31D0 150C5D20 00803825 */  or         $a3, $a0, $zero
    /* F31D4 150C5D24 14C0000E */  bnez       $a2, .L150C5D60
    /* F31D8 150C5D28 00C01025 */   or        $v0, $a2, $zero
    /* F31DC 150C5D2C 24E200C8 */  addiu      $v0, $a3, 0xC8
    /* F31E0 150C5D30 8C4F0000 */  lw         $t7, 0x0($v0)
    /* F31E4 150C5D34 8CB80000 */  lw         $t8, 0x0($a1)
    /* F31E8 150C5D38 11F80005 */  beq        $t7, $t8, .L150C5D50
    /* F31EC 150C5D3C 00000000 */   nop
    /* F31F0 150C5D40 90590004 */  lbu        $t9, 0x4($v0)
    /* F31F4 150C5D44 90A80004 */  lbu        $t0, 0x4($a1)
    /* F31F8 150C5D48 57280018 */  bnel       $t9, $t0, .L150C5DAC
    /* F31FC 150C5D4C 8FBF0014 */   lw        $ra, 0x14($sp)
  .L150C5D50:
    /* F3200 150C5D50 0D45A5CB */  jal        func_1516972C
    /* F3204 150C5D54 00E02025 */   or        $a0, $a3, $zero
    /* F3208 150C5D58 10000014 */  b          .L150C5DAC
    /* F320C 150C5D5C 8FBF0014 */   lw        $ra, 0x14($sp)
  .L150C5D60:
    /* F3210 150C5D60 2401002D */  addiu      $at, $zero, 0x2D
    /* F3214 150C5D64 14410010 */  bne        $v0, $at, .L150C5DA8
    /* F3218 150C5D68 24E200C8 */   addiu     $v0, $a3, 0xC8
    /* F321C 150C5D6C 8C440000 */  lw         $a0, 0x0($v0)
    /* F3220 150C5D70 8CA30000 */  lw         $v1, 0x0($a1)
    /* F3224 150C5D74 54640007 */  bnel       $v1, $a0, .L150C5D94
    /* F3228 150C5D78 8CAB0004 */   lw        $t3, 0x4($a1)
    /* F322C 150C5D7C 8CA90004 */  lw         $t1, 0x4($a1)
    /* F3230 150C5D80 AC490000 */  sw         $t1, 0x0($v0)
    /* F3234 150C5D84 90AA0009 */  lbu        $t2, 0x9($a1)
    /* F3238 150C5D88 10000007 */  b          .L150C5DA8
    /* F323C 150C5D8C A04A0004 */   sb        $t2, 0x4($v0)
    /* F3240 150C5D90 8CAB0004 */  lw         $t3, 0x4($a1)
  .L150C5D94:
    /* F3244 150C5D94 55640005 */  bnel       $t3, $a0, .L150C5DAC
    /* F3248 150C5D98 8FBF0014 */   lw        $ra, 0x14($sp)
    /* F324C 150C5D9C AC430000 */  sw         $v1, 0x0($v0)
    /* F3250 150C5DA0 90AC0008 */  lbu        $t4, 0x8($a1)
    /* F3254 150C5DA4 A04C0004 */  sb         $t4, 0x4($v0)
  .L150C5DA8:
    /* F3258 150C5DA8 8FBF0014 */  lw         $ra, 0x14($sp)
  .L150C5DAC:
    /* F325C 150C5DAC 27BD0018 */  addiu      $sp, $sp, 0x18
    /* F3260 150C5DB0 03E00008 */  jr         $ra
    /* F3264 150C5DB4 00000000 */   nop
endlabel func_150C5D0C
    /* F3268 150C5DB8 00000000 */  nop
    /* F326C 150C5DBC 00000000 */  nop
