.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching func_150C7670, 0xCC

glabel func_150C7670
    /* F4B20 150C7670 8C8E0170 */  lw         $t6, 0x170($a0)
    /* F4B24 150C7674 3C014F80 */  lui        $at, (0x4F800000 >> 16)
    /* F4B28 150C7678 24020001 */  addiu      $v0, $zero, 0x1
    /* F4B2C 150C767C 8DCF0014 */  lw         $t7, 0x14($t6)
    /* F4B30 150C7680 91F8002F */  lbu        $t8, 0x2F($t7)
    /* F4B34 150C7684 44982000 */  mtc1       $t8, $f4
    /* F4B38 150C7688 07010004 */  bgez       $t8, .L150C769C
    /* F4B3C 150C768C 46802020 */   cvt.s.w   $f0, $f4
    /* F4B40 150C7690 44813000 */  mtc1       $at, $f6
    /* F4B44 150C7694 00000000 */  nop
    /* F4B48 150C7698 46060000 */  add.s      $f0, $f0, $f6
  .L150C769C:
    /* F4B4C 150C769C 3C01800A */  lui        $at, %hi(D_800A04C0)
    /* F4B50 150C76A0 C42804C0 */  lwc1       $f8, %lo(D_800A04C0)($at)
    /* F4B54 150C76A4 24080001 */  addiu      $t0, $zero, 0x1
    /* F4B58 150C76A8 3C014F00 */  lui        $at, (0x4F000000 >> 16)
    /* F4B5C 150C76AC 46080282 */  mul.s      $f10, $f0, $f8
    /* F4B60 150C76B0 4459F800 */  cfc1       $t9, $31
    /* F4B64 150C76B4 44C8F800 */  ctc1       $t0, $31
    /* F4B68 150C76B8 00000000 */  nop
    /* F4B6C 150C76BC 46005424 */  cvt.w.s    $f16, $f10
    /* F4B70 150C76C0 4448F800 */  cfc1       $t0, $31
    /* F4B74 150C76C4 00000000 */  nop
    /* F4B78 150C76C8 31080078 */  andi       $t0, $t0, 0x78
    /* F4B7C 150C76CC 51000013 */  beql       $t0, $zero, .L150C771C
    /* F4B80 150C76D0 44088000 */   mfc1      $t0, $f16
    /* F4B84 150C76D4 44818000 */  mtc1       $at, $f16
    /* F4B88 150C76D8 24080001 */  addiu      $t0, $zero, 0x1
    /* F4B8C 150C76DC 46105401 */  sub.s      $f16, $f10, $f16
    /* F4B90 150C76E0 44C8F800 */  ctc1       $t0, $31
    /* F4B94 150C76E4 00000000 */  nop
    /* F4B98 150C76E8 46008424 */  cvt.w.s    $f16, $f16
    /* F4B9C 150C76EC 4448F800 */  cfc1       $t0, $31
    /* F4BA0 150C76F0 00000000 */  nop
    /* F4BA4 150C76F4 31080078 */  andi       $t0, $t0, 0x78
    /* F4BA8 150C76F8 15000005 */  bnez       $t0, .L150C7710
    /* F4BAC 150C76FC 00000000 */   nop
    /* F4BB0 150C7700 44088000 */  mfc1       $t0, $f16
    /* F4BB4 150C7704 3C018000 */  lui        $at, (0x80000000 >> 16)
    /* F4BB8 150C7708 10000007 */  b          .L150C7728
    /* F4BBC 150C770C 01014025 */   or        $t0, $t0, $at
  .L150C7710:
    /* F4BC0 150C7710 10000005 */  b          .L150C7728
    /* F4BC4 150C7714 2408FFFF */   addiu     $t0, $zero, -0x1
    /* F4BC8 150C7718 44088000 */  mfc1       $t0, $f16
  .L150C771C:
    /* F4BCC 150C771C 00000000 */  nop
    /* F4BD0 150C7720 0500FFFB */  bltz       $t0, .L150C7710
    /* F4BD4 150C7724 00000000 */   nop
  .L150C7728:
    /* F4BD8 150C7728 44D9F800 */  ctc1       $t9, $31
    /* F4BDC 150C772C A0880070 */  sb         $t0, 0x70($a0)
    /* F4BE0 150C7730 00000000 */  nop
    /* F4BE4 150C7734 03E00008 */  jr         $ra
    /* F4BE8 150C7738 00000000 */   nop
endlabel func_150C7670

nonmatching func_150C773C, 0x30

glabel func_150C773C
    /* F4BEC 150C773C 27BDFFE8 */  addiu      $sp, $sp, -0x18
    /* F4BF0 150C7740 AFBF0014 */  sw         $ra, 0x14($sp)
    /* F4BF4 150C7744 AFA5001C */  sw         $a1, 0x1C($sp)
    /* F4BF8 150C7748 3C058009 */  lui        $a1, %hi(D_80089470)
    /* F4BFC 150C774C 24A59470 */  addiu      $a1, $a1, %lo(D_80089470)
    /* F4C00 150C7750 0C008BB0 */  jal        memcpy
    /* F4C04 150C7754 24060040 */   addiu     $a2, $zero, 0x40
    /* F4C08 150C7758 24020001 */  addiu      $v0, $zero, 0x1
    /* F4C0C 150C775C 8FBF0014 */  lw         $ra, 0x14($sp)
    /* F4C10 150C7760 27BD0018 */  addiu      $sp, $sp, 0x18
    /* F4C14 150C7764 03E00008 */  jr         $ra
    /* F4C18 150C7768 00000000 */   nop
endlabel func_150C773C
    /* F4C1C 150C776C 00000000 */  nop
