.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching osSetThreadPri, 0xE0

glabel osSetThreadPri
    /* 22BB0 10022BB0 27BDFFD8 */  addiu      $sp, $sp, -0x28
    /* 22BB4 10022BB4 AFBF001C */  sw         $ra, 0x1C($sp)
    /* 22BB8 10022BB8 AFA40028 */  sw         $a0, 0x28($sp)
    /* 22BBC 10022BBC AFA5002C */  sw         $a1, 0x2C($sp)
    /* 22BC0 10022BC0 0C008B70 */  jal        __osDisableInt
    /* 22BC4 10022BC4 AFB00018 */   sw        $s0, 0x18($sp)
    /* 22BC8 10022BC8 8FAE0028 */  lw         $t6, 0x28($sp)
    /* 22BCC 10022BCC 00408025 */  or         $s0, $v0, $zero
    /* 22BD0 10022BD0 15C00004 */  bnez       $t6, .L10022BE4
    /* 22BD4 10022BD4 00000000 */   nop
    /* 22BD8 10022BD8 3C0F8003 */  lui        $t7, %hi(__osRunningThread)
    /* 22BDC 10022BDC 8DEFBE00 */  lw         $t7, %lo(__osRunningThread)($t7)
    /* 22BE0 10022BE0 AFAF0028 */  sw         $t7, 0x28($sp)
  .L10022BE4:
    /* 22BE4 10022BE4 8FB80028 */  lw         $t8, 0x28($sp)
    /* 22BE8 10022BE8 8FA8002C */  lw         $t0, 0x2C($sp)
    /* 22BEC 10022BEC 8F190004 */  lw         $t9, 0x4($t8)
    /* 22BF0 10022BF0 13280020 */  beq        $t9, $t0, .L10022C74
    /* 22BF4 10022BF4 00000000 */   nop
    /* 22BF8 10022BF8 AF080004 */  sw         $t0, 0x4($t8)
    /* 22BFC 10022BFC 3C0A8003 */  lui        $t2, %hi(__osRunningThread)
    /* 22C00 10022C00 8D4ABE00 */  lw         $t2, %lo(__osRunningThread)($t2)
    /* 22C04 10022C04 8FA90028 */  lw         $t1, 0x28($sp)
    /* 22C08 10022C08 112A000C */  beq        $t1, $t2, .L10022C3C
    /* 22C0C 10022C0C 00000000 */   nop
    /* 22C10 10022C10 952B0010 */  lhu        $t3, 0x10($t1)
    /* 22C14 10022C14 24010001 */  addiu      $at, $zero, 0x1
    /* 22C18 10022C18 11610008 */  beq        $t3, $at, .L10022C3C
    /* 22C1C 10022C1C 00000000 */   nop
    /* 22C20 10022C20 8D240008 */  lw         $a0, 0x8($t1)
    /* 22C24 10022C24 0C0091E0 */  jal        __osDequeueThread
    /* 22C28 10022C28 01202825 */   or        $a1, $t1, $zero
    /* 22C2C 10022C2C 8FAC0028 */  lw         $t4, 0x28($sp)
    /* 22C30 10022C30 8D840008 */  lw         $a0, 0x8($t4)
    /* 22C34 10022C34 0C001E76 */  jal        func_100079D8
    /* 22C38 10022C38 01802825 */   or        $a1, $t4, $zero
  .L10022C3C:
    /* 22C3C 10022C3C 3C0D8003 */  lui        $t5, %hi(__osRunningThread)
    /* 22C40 10022C40 3C0F8003 */  lui        $t7, %hi(D_8002BDF8)
    /* 22C44 10022C44 8DEFBDF8 */  lw         $t7, %lo(D_8002BDF8)($t7)
    /* 22C48 10022C48 8DADBE00 */  lw         $t5, %lo(__osRunningThread)($t5)
    /* 22C4C 10022C4C 8DF90004 */  lw         $t9, 0x4($t7)
    /* 22C50 10022C50 8DAE0004 */  lw         $t6, 0x4($t5)
    /* 22C54 10022C54 01D9082A */  slt        $at, $t6, $t9
    /* 22C58 10022C58 10200006 */  beqz       $at, .L10022C74
    /* 22C5C 10022C5C 00000000 */   nop
    /* 22C60 10022C60 24080002 */  addiu      $t0, $zero, 0x2
    /* 22C64 10022C64 3C048003 */  lui        $a0, %hi(D_8002BDF8)
    /* 22C68 10022C68 A5A80010 */  sh         $t0, 0x10($t5)
    /* 22C6C 10022C6C 0C001E2D */  jal        func_100078B4
    /* 22C70 10022C70 2484BDF8 */   addiu     $a0, $a0, %lo(D_8002BDF8)
  .L10022C74:
    /* 22C74 10022C74 0C008B78 */  jal        __osRestoreInt
    /* 22C78 10022C78 02002025 */   or        $a0, $s0, $zero
    /* 22C7C 10022C7C 8FBF001C */  lw         $ra, 0x1C($sp)
    /* 22C80 10022C80 8FB00018 */  lw         $s0, 0x18($sp)
    /* 22C84 10022C84 27BD0028 */  addiu      $sp, $sp, 0x28
    /* 22C88 10022C88 03E00008 */  jr         $ra
    /* 22C8C 10022C8C 00000000 */   nop
endlabel osSetThreadPri
