.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching osStopThread, 0xC0

glabel osStopThread
    /* 22E00 10022E00 27BDFFC8 */  addiu      $sp, $sp, -0x38
    /* 22E04 10022E04 AFBF0024 */  sw         $ra, 0x24($sp)
    /* 22E08 10022E08 AFA40038 */  sw         $a0, 0x38($sp)
    /* 22E0C 10022E0C AFB20020 */  sw         $s2, 0x20($sp)
    /* 22E10 10022E10 AFB1001C */  sw         $s1, 0x1C($sp)
    /* 22E14 10022E14 0C008B70 */  jal        __osDisableInt
    /* 22E18 10022E18 AFB00018 */   sw        $s0, 0x18($sp)
    /* 22E1C 10022E1C 8FAE0038 */  lw         $t6, 0x38($sp)
    /* 22E20 10022E20 00408025 */  or         $s0, $v0, $zero
    /* 22E24 10022E24 15C00003 */  bnez       $t6, .L10022E34
    /* 22E28 10022E28 00000000 */   nop
    /* 22E2C 10022E2C 10000003 */  b          .L10022E3C
    /* 22E30 10022E30 24110004 */   addiu     $s1, $zero, 0x4
  .L10022E34:
    /* 22E34 10022E34 8FAF0038 */  lw         $t7, 0x38($sp)
    /* 22E38 10022E38 95F10010 */  lhu        $s1, 0x10($t7)
  .L10022E3C:
    /* 22E3C 10022E3C 02209025 */  or         $s2, $s1, $zero
    /* 22E40 10022E40 24010002 */  addiu      $at, $zero, 0x2
    /* 22E44 10022E44 1241000F */  beq        $s2, $at, .L10022E84
    /* 22E48 10022E48 24010004 */   addiu     $at, $zero, 0x4
    /* 22E4C 10022E4C 12410005 */  beq        $s2, $at, .L10022E64
    /* 22E50 10022E50 24010008 */   addiu     $at, $zero, 0x8
    /* 22E54 10022E54 1241000B */  beq        $s2, $at, .L10022E84
    /* 22E58 10022E58 00000000 */   nop
    /* 22E5C 10022E5C 10000010 */  b          .L10022EA0
    /* 22E60 10022E60 00000000 */   nop
  .L10022E64:
    /* 22E64 10022E64 3C198003 */  lui        $t9, %hi(__osRunningThread)
    /* 22E68 10022E68 8F39BE00 */  lw         $t9, %lo(__osRunningThread)($t9)
    /* 22E6C 10022E6C 24180001 */  addiu      $t8, $zero, 0x1
    /* 22E70 10022E70 00002025 */  or         $a0, $zero, $zero
    /* 22E74 10022E74 0C001E2D */  jal        func_100078B4
    /* 22E78 10022E78 A7380010 */   sh        $t8, 0x10($t9)
    /* 22E7C 10022E7C 10000008 */  b          .L10022EA0
    /* 22E80 10022E80 00000000 */   nop
  .L10022E84:
    /* 22E84 10022E84 8FA90038 */  lw         $t1, 0x38($sp)
    /* 22E88 10022E88 24080001 */  addiu      $t0, $zero, 0x1
    /* 22E8C 10022E8C A5280010 */  sh         $t0, 0x10($t1)
    /* 22E90 10022E90 8FAA0038 */  lw         $t2, 0x38($sp)
    /* 22E94 10022E94 8D440008 */  lw         $a0, 0x8($t2)
    /* 22E98 10022E98 0C0091E0 */  jal        __osDequeueThread
    /* 22E9C 10022E9C 01402825 */   or        $a1, $t2, $zero
  .L10022EA0:
    /* 22EA0 10022EA0 0C008B78 */  jal        __osRestoreInt
    /* 22EA4 10022EA4 02002025 */   or        $a0, $s0, $zero
    /* 22EA8 10022EA8 8FBF0024 */  lw         $ra, 0x24($sp)
    /* 22EAC 10022EAC 8FB00018 */  lw         $s0, 0x18($sp)
    /* 22EB0 10022EB0 8FB1001C */  lw         $s1, 0x1C($sp)
    /* 22EB4 10022EB4 8FB20020 */  lw         $s2, 0x20($sp)
    /* 22EB8 10022EB8 03E00008 */  jr         $ra
    /* 22EBC 10022EBC 27BD0038 */   addiu     $sp, $sp, 0x38
endlabel osStopThread
