.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching osContStartReadData, 0xC4

glabel osContStartReadData
    /* 24BC0 10024BC0 27BDFFE0 */  addiu      $sp, $sp, -0x20
    /* 24BC4 10024BC4 AFBF0014 */  sw         $ra, 0x14($sp)
    /* 24BC8 10024BC8 AFA40020 */  sw         $a0, 0x20($sp)
    /* 24BCC 10024BCC 0C0095D4 */  jal        __osSiGetAccess
    /* 24BD0 10024BD0 AFA0001C */   sw        $zero, 0x1C($sp)
    /* 24BD4 10024BD4 3C0E8004 */  lui        $t6, %hi(__osContLastCmd)
    /* 24BD8 10024BD8 91CE2A50 */  lbu        $t6, %lo(__osContLastCmd)($t6)
    /* 24BDC 10024BDC 24010001 */  addiu      $at, $zero, 0x1
    /* 24BE0 10024BE0 11C1000C */  beq        $t6, $at, .L10024C14
    /* 24BE4 10024BE4 00000000 */   nop
    /* 24BE8 10024BE8 0C00934B */  jal        __osPackReadData
    /* 24BEC 10024BEC 00000000 */   nop
    /* 24BF0 10024BF0 3C058004 */  lui        $a1, %hi(__osContPifRam)
    /* 24BF4 10024BF4 24A52A10 */  addiu      $a1, $a1, %lo(__osContPifRam)
    /* 24BF8 10024BF8 0C0095F0 */  jal        __osSiRawStartDma
    /* 24BFC 10024BFC 24040001 */   addiu     $a0, $zero, 0x1
    /* 24C00 10024C00 AFA2001C */  sw         $v0, 0x1C($sp)
    /* 24C04 10024C04 8FA40020 */  lw         $a0, 0x20($sp)
    /* 24C08 10024C08 00002825 */  or         $a1, $zero, $zero
    /* 24C0C 10024C0C 0C008D10 */  jal        osRecvMesg
    /* 24C10 10024C10 24060001 */   addiu     $a2, $zero, 0x1
  .L10024C14:
    /* 24C14 10024C14 AFA00018 */  sw         $zero, 0x18($sp)
  .L10024C18:
    /* 24C18 10024C18 8FB80018 */  lw         $t8, 0x18($sp)
    /* 24C1C 10024C1C 8FA80018 */  lw         $t0, 0x18($sp)
    /* 24C20 10024C20 3C018004 */  lui        $at, %hi(__osContPifRam)
    /* 24C24 10024C24 0018C880 */  sll        $t9, $t8, 2
    /* 24C28 10024C28 00390821 */  addu       $at, $at, $t9
    /* 24C2C 10024C2C 240F00FF */  addiu      $t7, $zero, 0xFF
    /* 24C30 10024C30 AC2F2A10 */  sw         $t7, %lo(__osContPifRam)($at)
    /* 24C34 10024C34 25090001 */  addiu      $t1, $t0, 0x1
    /* 24C38 10024C38 29210010 */  slti       $at, $t1, 0x10
    /* 24C3C 10024C3C 1420FFF6 */  bnez       $at, .L10024C18
    /* 24C40 10024C40 AFA90018 */   sw        $t1, 0x18($sp)
    /* 24C44 10024C44 3C018004 */  lui        $at, %hi(D_80042A4C)
    /* 24C48 10024C48 3C058004 */  lui        $a1, %hi(__osContPifRam)
    /* 24C4C 10024C4C AC202A4C */  sw         $zero, %lo(D_80042A4C)($at)
    /* 24C50 10024C50 24A52A10 */  addiu      $a1, $a1, %lo(__osContPifRam)
    /* 24C54 10024C54 0C0095F0 */  jal        __osSiRawStartDma
    /* 24C58 10024C58 00002025 */   or        $a0, $zero, $zero
    /* 24C5C 10024C5C 240A0001 */  addiu      $t2, $zero, 0x1
    /* 24C60 10024C60 3C018004 */  lui        $at, %hi(__osContLastCmd)
    /* 24C64 10024C64 AFA2001C */  sw         $v0, 0x1C($sp)
    /* 24C68 10024C68 0C0095E5 */  jal        __osSiRelAccess
    /* 24C6C 10024C6C A02A2A50 */   sb        $t2, %lo(__osContLastCmd)($at)
    /* 24C70 10024C70 8FBF0014 */  lw         $ra, 0x14($sp)
    /* 24C74 10024C74 8FA2001C */  lw         $v0, 0x1C($sp)
    /* 24C78 10024C78 27BD0020 */  addiu      $sp, $sp, 0x20
    /* 24C7C 10024C7C 03E00008 */  jr         $ra
    /* 24C80 10024C80 00000000 */   nop
endlabel osContStartReadData

nonmatching osContGetReadData, 0xA8

glabel osContGetReadData
    /* 24C84 10024C84 3C0F8004 */  lui        $t7, %hi(__osMaxControllers)
    /* 24C88 10024C88 91EF2A51 */  lbu        $t7, %lo(__osMaxControllers)($t7)
    /* 24C8C 10024C8C 3C0E8004 */  lui        $t6, %hi(__osContPifRam)
    /* 24C90 10024C90 27BDFFF0 */  addiu      $sp, $sp, -0x10
    /* 24C94 10024C94 25CE2A10 */  addiu      $t6, $t6, %lo(__osContPifRam)
    /* 24C98 10024C98 AFAE000C */  sw         $t6, 0xC($sp)
    /* 24C9C 10024C9C 19E00021 */  blez       $t7, .L10024D24
    /* 24CA0 10024CA0 AFA00000 */   sw        $zero, 0x0($sp)
  .L10024CA4:
    /* 24CA4 10024CA4 8FB9000C */  lw         $t9, 0xC($sp)
    /* 24CA8 10024CA8 27B80004 */  addiu      $t8, $sp, 0x4
    /* 24CAC 10024CAC 8B210000 */  lwl        $at, 0x0($t9)
    /* 24CB0 10024CB0 9B210003 */  lwr        $at, 0x3($t9)
    /* 24CB4 10024CB4 AF010000 */  sw         $at, 0x0($t8)
    /* 24CB8 10024CB8 8B290004 */  lwl        $t1, 0x4($t9)
    /* 24CBC 10024CBC 9B290007 */  lwr        $t1, 0x7($t9)
    /* 24CC0 10024CC0 AF090004 */  sw         $t1, 0x4($t8)
    /* 24CC4 10024CC4 93AA0006 */  lbu        $t2, 0x6($sp)
    /* 24CC8 10024CC8 314B00C0 */  andi       $t3, $t2, 0xC0
    /* 24CCC 10024CCC 000B6103 */  sra        $t4, $t3, 4
    /* 24CD0 10024CD0 A08C0004 */  sb         $t4, 0x4($a0)
    /* 24CD4 10024CD4 908D0004 */  lbu        $t5, 0x4($a0)
    /* 24CD8 10024CD8 15A00007 */  bnez       $t5, .L10024CF8
    /* 24CDC 10024CDC 00000000 */   nop
    /* 24CE0 10024CE0 97AE0008 */  lhu        $t6, 0x8($sp)
    /* 24CE4 10024CE4 A48E0000 */  sh         $t6, 0x0($a0)
    /* 24CE8 10024CE8 83AF000A */  lb         $t7, 0xA($sp)
    /* 24CEC 10024CEC A08F0002 */  sb         $t7, 0x2($a0)
    /* 24CF0 10024CF0 83A8000B */  lb         $t0, 0xB($sp)
    /* 24CF4 10024CF4 A0880003 */  sb         $t0, 0x3($a0)
  .L10024CF8:
    /* 24CF8 10024CF8 8FB80000 */  lw         $t8, 0x0($sp)
    /* 24CFC 10024CFC 3C0B8004 */  lui        $t3, %hi(__osMaxControllers)
    /* 24D00 10024D00 916B2A51 */  lbu        $t3, %lo(__osMaxControllers)($t3)
    /* 24D04 10024D04 8FA9000C */  lw         $t1, 0xC($sp)
    /* 24D08 10024D08 27190001 */  addiu      $t9, $t8, 0x1
    /* 24D0C 10024D0C 032B082A */  slt        $at, $t9, $t3
    /* 24D10 10024D10 252A0008 */  addiu      $t2, $t1, 0x8
    /* 24D14 10024D14 AFAA000C */  sw         $t2, 0xC($sp)
    /* 24D18 10024D18 AFB90000 */  sw         $t9, 0x0($sp)
    /* 24D1C 10024D1C 1420FFE1 */  bnez       $at, .L10024CA4
    /* 24D20 10024D20 24840006 */   addiu     $a0, $a0, 0x6
  .L10024D24:
    /* 24D24 10024D24 03E00008 */  jr         $ra
    /* 24D28 10024D28 27BD0010 */   addiu     $sp, $sp, 0x10
endlabel osContGetReadData

nonmatching __osPackReadData, 0xEC

glabel __osPackReadData
    /* 24D2C 10024D2C 27BDFFF0 */  addiu      $sp, $sp, -0x10
    /* 24D30 10024D30 3C0E8004 */  lui        $t6, %hi(__osContPifRam)
    /* 24D34 10024D34 25CE2A10 */  addiu      $t6, $t6, %lo(__osContPifRam)
    /* 24D38 10024D38 AFAE000C */  sw         $t6, 0xC($sp)
    /* 24D3C 10024D3C AFA00000 */  sw         $zero, 0x0($sp)
  .L10024D40:
    /* 24D40 10024D40 8FAF0000 */  lw         $t7, 0x0($sp)
    /* 24D44 10024D44 8FB90000 */  lw         $t9, 0x0($sp)
    /* 24D48 10024D48 3C018004 */  lui        $at, %hi(__osContPifRam)
    /* 24D4C 10024D4C 000FC080 */  sll        $t8, $t7, 2
    /* 24D50 10024D50 00380821 */  addu       $at, $at, $t8
    /* 24D54 10024D54 AC202A10 */  sw         $zero, %lo(__osContPifRam)($at)
    /* 24D58 10024D58 27280001 */  addiu      $t0, $t9, 0x1
    /* 24D5C 10024D5C 29010010 */  slti       $at, $t0, 0x10
    /* 24D60 10024D60 1420FFF7 */  bnez       $at, .L10024D40
    /* 24D64 10024D64 AFA80000 */   sw        $t0, 0x0($sp)
    /* 24D68 10024D68 3C198004 */  lui        $t9, %hi(__osMaxControllers)
    /* 24D6C 10024D6C 93392A51 */  lbu        $t9, %lo(__osMaxControllers)($t9)
    /* 24D70 10024D70 24090001 */  addiu      $t1, $zero, 0x1
    /* 24D74 10024D74 3C018004 */  lui        $at, %hi(D_80042A4C)
    /* 24D78 10024D78 240A00FF */  addiu      $t2, $zero, 0xFF
    /* 24D7C 10024D7C 240B0001 */  addiu      $t3, $zero, 0x1
    /* 24D80 10024D80 240C0004 */  addiu      $t4, $zero, 0x4
    /* 24D84 10024D84 240D0001 */  addiu      $t5, $zero, 0x1
    /* 24D88 10024D88 340EFFFF */  ori        $t6, $zero, 0xFFFF
    /* 24D8C 10024D8C 240FFFFF */  addiu      $t7, $zero, -0x1
    /* 24D90 10024D90 2418FFFF */  addiu      $t8, $zero, -0x1
    /* 24D94 10024D94 AC292A4C */  sw         $t1, %lo(D_80042A4C)($at)
    /* 24D98 10024D98 A3AA0004 */  sb         $t2, 0x4($sp)
    /* 24D9C 10024D9C A3AB0005 */  sb         $t3, 0x5($sp)
    /* 24DA0 10024DA0 A3AC0006 */  sb         $t4, 0x6($sp)
    /* 24DA4 10024DA4 A3AD0007 */  sb         $t5, 0x7($sp)
    /* 24DA8 10024DA8 A7AE0008 */  sh         $t6, 0x8($sp)
    /* 24DAC 10024DAC A3AF000A */  sb         $t7, 0xA($sp)
    /* 24DB0 10024DB0 A3B8000B */  sb         $t8, 0xB($sp)
    /* 24DB4 10024DB4 1B200013 */  blez       $t9, .L10024E04
    /* 24DB8 10024DB8 AFA00000 */   sw        $zero, 0x0($sp)
  .L10024DBC:
    /* 24DBC 10024DBC 27A90004 */  addiu      $t1, $sp, 0x4
    /* 24DC0 10024DC0 8D210000 */  lw         $at, 0x0($t1)
    /* 24DC4 10024DC4 8FA8000C */  lw         $t0, 0xC($sp)
    /* 24DC8 10024DC8 3C188004 */  lui        $t8, %hi(__osMaxControllers)
    /* 24DCC 10024DCC A9010000 */  swl        $at, 0x0($t0)
    /* 24DD0 10024DD0 B9010003 */  swr        $at, 0x3($t0)
    /* 24DD4 10024DD4 8D2B0004 */  lw         $t3, 0x4($t1)
    /* 24DD8 10024DD8 A90B0004 */  swl        $t3, 0x4($t0)
    /* 24DDC 10024DDC B90B0007 */  swr        $t3, 0x7($t0)
    /* 24DE0 10024DE0 8FAE0000 */  lw         $t6, 0x0($sp)
    /* 24DE4 10024DE4 93182A51 */  lbu        $t8, %lo(__osMaxControllers)($t8)
    /* 24DE8 10024DE8 8FAC000C */  lw         $t4, 0xC($sp)
    /* 24DEC 10024DEC 25CF0001 */  addiu      $t7, $t6, 0x1
    /* 24DF0 10024DF0 01F8082A */  slt        $at, $t7, $t8
    /* 24DF4 10024DF4 258D0008 */  addiu      $t5, $t4, 0x8
    /* 24DF8 10024DF8 AFAF0000 */  sw         $t7, 0x0($sp)
    /* 24DFC 10024DFC 1420FFEF */  bnez       $at, .L10024DBC
    /* 24E00 10024E00 AFAD000C */   sw        $t5, 0xC($sp)
  .L10024E04:
    /* 24E04 10024E04 8FAA000C */  lw         $t2, 0xC($sp)
    /* 24E08 10024E08 241900FE */  addiu      $t9, $zero, 0xFE
    /* 24E0C 10024E0C 27BD0010 */  addiu      $sp, $sp, 0x10
    /* 24E10 10024E10 03E00008 */  jr         $ra
    /* 24E14 10024E14 A1590000 */   sb        $t9, 0x0($t2)
endlabel __osPackReadData
    /* 24E18 10024E18 00000000 */  nop
    /* 24E1C 10024E1C 00000000 */  nop
