.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching __osSpGetStatus, 0xC

glabel __osSpGetStatus
    /* 27620 10027620 3C0EA404 */  lui        $t6, %hi(D_A4040010)
    /* 27624 10027624 03E00008 */  jr         $ra
    /* 27628 10027628 8DC20010 */   lw        $v0, %lo(D_A4040010)($t6)
endlabel __osSpGetStatus
    /* 2762C 1002762C 00000000 */  nop
