.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching osSpTaskYield, 0x20

glabel osSpTaskYield
    /* 24BA0 10024BA0 27BDFFE8 */  addiu      $sp, $sp, -0x18
    /* 24BA4 10024BA4 AFBF0014 */  sw         $ra, 0x14($sp)
    /* 24BA8 10024BA8 0C008F68 */  jal        __osSpSetStatus
    /* 24BAC 10024BAC 24040400 */   addiu     $a0, $zero, 0x400
    /* 24BB0 10024BB0 8FBF0014 */  lw         $ra, 0x14($sp)
    /* 24BB4 10024BB4 27BD0018 */  addiu      $sp, $sp, 0x18
    /* 24BB8 10024BB8 03E00008 */  jr         $ra
    /* 24BBC 10024BBC 00000000 */   nop
endlabel osSpTaskYield
